### ISSUE TITLE
Custom event props break if filtered by e.g. device, browser or exit-page

### ISSUE THREAD

**Issue by ukutaht** [plausible/analytics#1003]
Created from this discussion: https://github.com/plausible/analytics/discussions/1002

Doesn't seem to be an issue on prod but there's a case with a self-hosted installation. Maybe Clickhouse changed something? Need to investigate

**Comment by metmarkosaric** [comment]
closing as seems to be fixed according to the comment in the original thread but feel free to reopen if it's not
