### ISSUE TITLE
Accurate location - city level data

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/analytics#102]
"It would be great to get a little more info about the location. Not too much to invade privacy but I’m part of a small business and it’s hard to get valuable info when page visits come just out of Switzerland and Germany.

Agreed, I don’t think capturing the user city is a privacy issue and it would be useful to see.

I totally agree with this feature. To get more information as it now is like country. It should give information about country, state and city.That is important to make some better and more precise Settings when you use google ads.

I’d assume the IPv4 and IPv6 IP addresses are anonymized though it doesn’t provide anonymity to some companies companies due to their IP address ranges."

([imported from the old roadmap](https://plausible.nolt.io/33))

**Comment by rhysperry111** [comment]
if this feature does get implemented, would it be possible to turn it off? I do not need data that specific (although I understand that others might) so in the best interests of privacy I don't want to collect more data than I need

**Comment by flatroof** [comment]
Small businesses/local would need far less geo than country. For US, state and city minimal.

**Comment by erikjoling** [comment]
I would also like to see more specific location data. This would make Plausible much more interesting for small businesses whose audiences are more more local, regional or national. And it would make it easier for me to convince them to not use Google Analytics :)
