### ISSUE TITLE
[SOLVED] Proxy with Netlify : Error 500 for some _redirects (POST) 

### ISSUE THREAD

**Issue by divinerites** [plausible/analytics#1085]
## Prerequisites
- [X] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report
**Describe the bug**

Following [this discussion](https://github.com/plausible/analytics/discussions/610) and especially [this comment](https://github.com/plausible/analytics/discussions/610#discussioncomment-785911), and after [this response from a Netlify engineer](https://answers.netlify.com/t/error-500-for-some-redirects-post/38312/2?u=divinerites) to my question, I open an issue because all of this is too deeply inside the discussion I guess.

I'll put all the relevant informations here.

- I use proxy thru `_redirects` on Netlify.
- Seems to mainly works, but I have a regular amount of error 500.
- I also opened a [post on Netlify](https://answers.netlify.com/t/random-error-500-for-some-redirects/38312) and got a response from their engineer.

This is my `_redirects`

```
/misc/js/script.js https://plausible.io/js/plausible.outbound-links.js 200
/misc/api/event https://plausible.io/api/event 200
```

<img width="922" alt="Capture d’écran 2021-05-26 à 13 56 42" src="https://user-images.githubusercontent.com/32342823/119655975-7376c700-be2a-11eb-88b7-85f68977152e.png">

<img width="918" alt="Capture d’écran 2021-05-26 à 14 09 39" src="https://user-images.githubusercontent.com/32342823/119657437-314e8500-be2c-11eb-866a-e86895d27d45.png">

After reading [some posts](https://answers.netlify.com/t/redirect-returns-500-internal-server-error-for-only-put-and-delete-requests/12280/9) I made some tests.

```sh
$ curl -I https://www.camping-arolla.com/misc/api/event
HTTP/2 500 
server: Netlify
age: 0
x-nf-request-id: 3016a1f8-d520-4f57-874b-ceadfac73d00
date: Wed, 26 May 2021 12:23:14 GMT

$ curl -I https://www.camping-arolla.com/misc/js/script.js
HTTP/2 200 
age: 0
cache-control: max-age=3600,public
content-length: 1830
content-type: application/javascript
cross-origin-resource-policy: cross-origin
date: Wed, 26 May 2021 12:23:42 GMT
server: Netlify
x-nf-request-id: 396518f1-e04a-41e9-b78f-be514dafd0cb
```

And got a response from Netlify engineer :

```
Hey! I’m cURLing the URL now and seeing a 404 which makes sense,
as raw requests to the path also return a 404.
The 500 error is/was likely returned by the proxied path itself!
```

**Expected behavior**
We never do expect regular error 500.

**Screenshots (If applicable)**
See above.

And on this one you can clearly see the 28 sec waiting for the event

<img width="925" alt="Capture d’écran 2021-05-27 à 10 47 33" src="https://user-images.githubusercontent.com/32342823/119796072-564d0180-bed9-11eb-9cab-d3f15de6384c.png">

**Environment (If applicable):**

The plausible part in my html head:

```
<script async defer data-domain=camping-arolla.com src=/misc/js/script.js data-api=/misc/api/event>
</script>

<script>window.plausible=window.plausible||function(){(window.plausible.q=window.plausible.q||[]).push(arguments)
</script>
```

 - OS: Mac OSX v10.14.6
 - Browser : Brave Version 1.24.86 Chromium: 90.0.4430.212 (Build officiel) (x86_64)
 - Browser : All extensions removed

**Comment by divinerites** [comment]
I see this commit : https://github.com/plausible/docs/commit/c9f30a062984bb2ed096e0d47b45adebf8d50769

You changed `200` for `202` 2 days ago. 
Is this the possible cause ??

**Comment by ukutaht** [comment]
I will look into this issue in more depth soon. Meanwhile, I'm wondering that maybe this is a problem from [Netlify's docs](https://docs.netlify.com/routing/redirects/rewrites-proxies/):

> For security reasons, rewrites between Netlify sites belonging to different teams are not allowed.

`plausible.io` is actually on Netlify, so the proxy chain is: Netlify -> Netlify -> Our backend. Sounds like it's a problem.

I will investigate more. Haven't heard of any reports of 500s from other users.

**Comment by divinerites** [comment]
I also see a difference:

- Your general advice with `async` : `<script async defer data-domain="yourdomain.com" ...`
- Your advice for proxing without `async`. Is this normal ?

**Comment by ukutaht** [comment]
Yeah I'm intending to change everything to suggest just `defer` without `async`. See https://github.com/plausible/analytics/discussions/602

**Comment by divinerites** [comment]
> You changed `200` for `202` in the event line, 2 days ago.
> Is this the possible cause ??

Just modify my setup with 202, but no change.

**Comment by divinerites** [comment]
> Haven't heard of any reports of 500s from other users.

May be because as there are still some stats coming, they are not looking into it ? And that I'm verifying everything every week :-)

Also, I tested once this morning with Safari and got a valid event. Strange.

**Comment by mikktrix** [comment]
Got the same console logs with POST 500 for my site. Using Chrome. Edge doesn't get the error.

Also, these are from plausible.io with Chrome:
![image](https://user-images.githubusercontent.com/34936671/119807259-a8971e00-beeb-11eb-8a63-ecca282971df.png)
![image](https://user-images.githubusercontent.com/34936671/119806746-29a1e580-beeb-11eb-8142-491a583d77de.png)

**Comment by divinerites** [comment]
I think you are "doing things" right now, so it could be the reason, but just in case ... I now have a immediate 404 instead of 500

<img width="911" alt="Capture d’écran 2021-05-27 à 12 09 46" src="https://user-images.githubusercontent.com/32342823/119808595-8fd73a00-bee4-11eb-9ad7-7d440eaea4cf.png">

**Comment by divinerites** [comment]
> Also, these are from plausible.io with Chrome:

I can confirm this too.

FYI the test "Request URL: https://testing-plausible-io-proxy.uku-taht.workers.dev/api/event" is OK 202 for me :-)

**Comment by ukutaht** [comment]
Thank you for all the help in diagnosing the issue. Here's what I've found:

This issue does not seem related to the proxy settings to me. When requesting `plausible.io` itself, sometimes it fails even with curl. The request hangs forever and after 28 seconds you get a 500 timeout from the proxy.

Here's how it looks when the request hangs with curl in verbose mode:
```
➜  analytics git:(master) curl -v https://plausible.io/js/plausible.outbound-links.js
*   Trying 206.189.52.23...
* TCP_NODELAY set
*   Trying 2a05:d014:275:cb02:66df:50b:6e56:a6bf...
* TCP_NODELAY set
* Immediate connect fail for 2a05:d014:275:cb02:66df:50b:6e56:a6bf: Network is unreachable
*   Trying 2a05:d014:275:cb01:1f85:932b:b797:22f9...
* TCP_NODELAY set
* Immediate connect fail for 2a05:d014:275:cb01:1f85:932b:b797:22f9: Network is unreachable
*   Trying 2a05:d014:275:cb02:66df:50b:6e56:a6bf...
* TCP_NODELAY set
* Immediate connect fail for 2a05:d014:275:cb02:66df:50b:6e56:a6bf: Network is unreachable
*   Trying 2a05:d014:275:cb01:1f85:932b:b797:22f9...
* TCP_NODELAY set
* Immediate connect fail for 2a05:d014:275:cb01:1f85:932b:b797:22f9: Network is unreachable
*   Trying 2a05:d014:275:cb02:66df:50b:6e56:a6bf...
* TCP_NODELAY set
* Immediate connect fail for 2a05:d014:275:cb02:66df:50b:6e56:a6bf: Network is unreachable
*   Trying 2a05:d014:275:cb01:1f85:932b:b797:22f9...
* TCP_NODELAY set
```

etc. etc.

When the DNS query resolves to `206.189.50.215` the request seems to hang at the TCP connection phase. When the DNS query resolves to a different IP address, everything works fine. I will contact Netlify and try to get to the bottom of why this IP address is being returned from their DNS queries.

**Comment by divinerites** [comment]
OK Thanks a lot. 
Will post this analyse on my netlify ticket too.

**Comment by ukutaht** [comment]
> OK Thanks a lot.
> Will post this analyse on my netlify ticket too.

OK Let's see what they say. I'll hold off on creating another ticket for now

**Comment by divinerites** [comment]
> OK Let's see what they say. I'll hold off on creating another ticket for now

Done here : https://answers.netlify.com/t/error-500-for-some-redirects-post/38312/4?u=divinerites

**Comment by divinerites** [comment]
I post your response, but may be you can directly interact with them if is better.

https://answers.netlify.com/t/error-500-for-some-redirects-post/38312/2

**Comment by divinerites** [comment]
Got a response from netlify. They find the culprit.

Hey there,

I did some digging. I could see cache invalidation on the https://plausible.io/ site (we’re serving content from different deploys) likely because they are defeating our caching headers.

Our default is: Cache-Control: public, max-age=0, must-revalidate

On /js/plausible.outbound-links.js for example, they’re using: Cache-Control: max-age=3600,public

And here’s why that’s important.

I’ve managed to purge the CDN cache for your site, and the plausible site, and I’m no longer returning 500 responses on any node. However, this will almost certainly arise again with the cache-busting header in place.

**Comment by ukutaht** [comment]
Thanks @divinerites. That's interesting, I'll take a look at our caching strategy.

**Comment by divinerites** [comment]
OK. Cool. From my experience with Netlify caches, we have to have strong arguments to go against their default.

I only overwrite theirs for fonts & **fingerprinted** css/images/js.

All other tests lead me to trouble in the past.

**Comment by divinerites** [comment]
> Thanks @divinerites. That's interesting, I'll take a look at our caching strategy.

I don't know if you saw it but "Request URL: https://testing-plausible-io-proxy.uku-taht.workers.dev/api/event" is OK 202 for me

**Comment by divinerites** [comment]
Hello @ukutaht 

Did you succeeded to have a 0 cache strategy for Netlify as pointed by them ?
Nothing seems to have changed for us for all those error 500.

**Comment by divinerites** [comment]
I also have some 404 now.
<img width="978" alt="Capture d’écran 2021-06-02 à 11 14 41" src="https://user-images.githubusercontent.com/32342823/120453953-c1904b00-c393-11eb-8227-8f936d3f4cf2.png">

**Comment by ukutaht** [comment]
Sorry it took me longer than expected to change the cache header. I deployed the change yesterday and I'll nudge Netlify to purge their cache again as well.

**Comment by divinerites** [comment]
> I deployed the change yesterday and I'll nudge Netlify to purge their cache again as well.

OK. Cool.

- For the cache my understanding is they have to do it for all our sites. Do you need my site list ?
- Do you think the 404 I get is related and will vanish ?

**Comment by ukutaht** [comment]
> For the cache my understanding is they have to do it for all our sites. Do you need my site list ?
Yeah if you have other sites with the proxy setup you can add them in the netlify thread.

> Do you think the 404 I get is related and will vanish ?
I hope so but let's see

**Comment by divinerites** [comment]
That's weird. Was 99,99% sure to have given feedback here.
Anyway it was (not ?) this :

Thanks a lot @ukutaht 
All my sites are now 200/202 whatever I do.
Thanks a lot for debug and the solution.
