### ISSUE TITLE
Average session length

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/analytics#110]
"Measure average session length. Breakdown by referrer."

([imported from the old roadmap](https://plausible.nolt.io/54))

**Comment by metmarkosaric** [comment]
Session length is now live on your Plausible Analytics dashboard! You can see the average visit duration for your site on the top chart and you can dig into the "Top Referrers" report to check visit duration split by the different referral sources. Enjoy!

**Comment by juliansthl** [comment]
just started testing plausible and was wondering if there's a way to see the average visit duration on a per page basis?

**Comment by metmarkosaric** [comment]
> just started testing plausible and was wondering if there's a way to see the average visit duration on a per page basis?

It's not possible at this point but it has been requested before so we've put it on our roadmap. See #111
