### ISSUE TITLE
Time on page

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/analytics#111]
"Show how much time people spend on average on specific pages

The biggest problem of time on page is in case of bounce and exit pages. They are not captured . How do u solve it

The plan is to use the Navigator.sendBeacon() API to solve this specific issue (more info: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/sendBeacon)

Happy to share how we built time-on-site tracking features that overlay with conversion rates. One issue that comes into play is users minimizing screen and coming back hours or days later.

Here is how ackee ( an open source analytics tool) does track the time on page: https://github.com/electerious/ackee-tracker/blob/master/src/scripts/main.js#L182"

([imported from the old roadmap](https://plausible.nolt.io/55))

**Comment by oliverpool** [comment]
#190 is related to this (however the problem there is the delay for outbound links)

**Comment by bendrick92** [comment]
Adding my two cents of support for this feature...

Since blogs (where I'm running Plausible) traditionally have high bounce rates, defaulting single page visits to a duration of 0:00 is throwing off the averages I see in my dashboard.

It would be great to see how long even single page viewers spend on my site/which pages have the most time spent!

**Comment by metmarkosaric** [comment]
Thanks @bendrick92! Got some similar feedback via email yesterday so we'll have to see how to calculate time on page (and whether we continue to follow industry standards like we do now or we should introduce some more elaborate definition):

"In Plausible, my average visitor duration is 24 seconds but in Clicky, it's almost 3 minutes. I think Clicky pings the visitor every 30 seconds to get an accurate time. I

In Clicky, a "bounce" is registered only if a visitor stays on the first page less than 30 seconds. I think this is a good way to measure what a true bounce is because some visitors might spend 5 minutes on the first page (reading content, possibly signing up for email updates and/or purchasing products). Is this something you would consider useful for Plausible?"

**Comment by oliverpool** [comment]
Using https://www.igvita.com/2015/11/20/dont-lose-user-and-app-state-use-page-visibility/ one should be able to make only 2 requests: one on pageload (for the "live-hit") and one on page leave (for the duration).

How can this event be deduplicated to prevent being it counted as 2 hits?

I can try to craft a PR if you tell me which Payload must be sent by the JS script (and you are willing to review it :)
