### ISSUE TITLE
Enable upgrade to OTP 24

### ISSUE THREAD

**Issue by happysalada** [plausible/analytics#1116]
I'm just putting this here so we can gather information.
OTP 24 has been released. Elixir 12 enables the upgrade.
A quick check on the repo generates some compile error when upgrading.
One of the error is from the sleeplocks dependency.
I've opened an issue upstream
https://github.com/whitfin/sleeplocks/issues/6

**Comment by ukutaht** [comment]
Wonderful, thanks for helping with this

**Comment by happysalada** [comment]
The error was related to hexpm giving an old version of rebar3
I tested today and it compilation works.
Here is the related PR
https://github.com/plausible/analytics/pull/1119

**Comment by ACPK** [comment]
@ukutaht Will this PR be merged in as I'm unable to install Plausible locally?

**Comment by cwaj400** [comment]
Hi! I am keen to help fix issues with this project as I think it's a great project. Is it an open source one, and how can I help?

**Comment by ukutaht** [comment]
https://github.com/plausible/analytics/pull/1313 is now merged. Master is running OTP24
