### ISSUE TITLE
Exclude visitors by IP address

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/analytics#112]
"It would be great to have an ignore list for IP addresses. Currently, my and my team’s manual testing shows up as visits.

Dunno if this is any help but if you’re testing on any environments that aren’t “production” then wrapping the Plausible script tag inside a simple IF statement does the trick. EG I’m rarely on production but I’m messing about in LOCAL all the time so my Plausible script is inside

if (environment == “Production”)
// script tag
}

so nothing from local, dev or staging gets counted.

This would only be for client-side events but we use Google server-side for event tracking. Additionally, the method above would require getting your employees to install it on their phones and computers which seems a bit unrealistic.

Many start also need to block the tracking of brower testing software (ex: Browerstack - https://www.browserstack.com/question/585) and security scanners."

([imported from the old roadmap](https://plausible.nolt.io/58))

**Comment by admkx** [comment]
Temporary workaround: [](https://docs.plausible.io/excluding/)
