### ISSUE TITLE
plausible.io is down?

### ISSUE THREAD

**Issue by OmgImAlexis** [plausible/analytics#1135]
All the links you have to contact you goto this domain which is down.

**Comment by metmarkosaric** [comment]
Everything is running fine. We haven't had any downtime in a while. You can check [our status page](https://plausible.instatus.com/). Perhaps you're running an adblocker that blocks our whole domain?

**Comment by OmgImAlexis** [comment]
> Everything is running fine. We haven't had any downtime in a while. You can check [our status page](https://plausible.instatus.com/). Perhaps you're running an adblocker that blocks our whole domain?

It might be worth adding this to the readme? Since I’m sure a lot of people wanting to use this are self hosting. It didn’t even cross my mind since most projects like this purposely have a second domain for this reason.
