### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/analytics#115]
"Save our eyes!"

([imported from the old roadmap](https://plausible.nolt.io/61))

**Comment by cassidyjames** [comment]
I have quite a bit of experience implementing dark styles on sites and in software, having tackled the [elementary blog](https://blog.elementary.io), my [personal website](https://cassidyjames.com), the [AppCenter website](https://appcenter.elementary.io), the [elementary releases](https://releases.elementary.io) site, and elementary OS itself. I'd love to contribute to this. :eyes:

**Comment by ukutaht** [comment]
That's great. Dark mode hasn't been on the top of my priority list but I'd be super happy to merge a PR for this! :)

**Comment by NuroDev** [comment]
Of course not the most pressing feature, but would be a nice to have that could be toggled easily.
I went ahead and tweaked some CSS to give a quick mockup of how nice it could look using Tailwind's color palette 🙂
<img width="1312" alt="Screenshot 2020-10-11 at 9 52 09 pm" src="https://user-images.githubusercontent.com/4991309/95689965-6646f800-0c0c-11eb-9865-d8f26d1d3697.png">

**Comment by ukutaht** [comment]
@NuroDev Uuh that looks really nice :)
