### ISSUE TITLE
Nginx reverse proxy sending X-forward-for but plausible seems to ignore it

### ISSUE THREAD

**Issue by gtmadev** [plausible/analytics#1166]
## Prerequisites
- [ x] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report
**Describe the bug**
I use an nginx reverse proxy and added the proper lines in the location directive so it will send the real ip of the user. However, this seems to be ignored. All traffic is showing as coming from the load balancer.

` 
 location = /api/pl/event {

        proxy_pass https://plausible.io/api/event;
        proxy_buffering on;
        proxy_http_version 1.1;
	proxy_set_header   X-Real-IP  $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header X-Forwarded-Host  $host;

 }
`

The nginx settings above are the same ones I use for Matomo, and I know they do work.

Does Plausible expect to see the "X-Forwarded" headers and properly utilize them?

**Expected behavior**
I was expecting the plausible api endpoint to see the X-Forwarded-For header and use that value to determine the user ip.

**Screenshots (If applicable)**
NA

**Environment (If applicable):**
 - OS: Linux
 - Browser  Brave/Chrome
 - Version 91

**Comment by gtmadev** [comment]
Closing... looks like it's my config.

**Comment by ukutaht** [comment]
All good. Just for information, if `X-Forwarded-For` is set we do read the real IP address from that header.

**Comment by gtmadev** [comment]
Thanks. And in case anyone else is curious... the config problem was upstream in my nginx config. I was specifying some old (removed) load balancer IP addresses for the source of the client IP. Thus, it was just handing over the IP of whichever load balancer handled the request. Fixing those IPs solved the problem.
