### ISSUE TITLE
Toggle between different metrics in the main graph

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/analytics#117]
"The main graph should be able to show both unique visitors and pageviews, depending on what the user selects."

([imported from the old roadmap](https://plausible.nolt.io/64))

**Comment by kevquirk** [comment]
+1 for this.

**Comment by Cdingram** [comment]
+1 would really love to see page views instead of unique visitors

**Comment by inouire** [comment]
+1 , both metrics are veey relevant (and I think that they are the only one I use :)
