### ISSUE TITLE
Student Discount

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/analytics#118]
"It would be great if Plausible has special rate for student."

([imported from the old roadmap](https://plausible.nolt.io/66))

**Comment by yagarea** [comment]
[This organization](https://www.isic.org/) offering partnership and API.

https://www.isic.org/

**Comment by Kulcanhez** [comment]
Be part of Github Students would be very nice https://education.github.com/pack/offers I find great software there 😄

**Comment by metmarkosaric** [comment]
> Be part of Github Students would be very nice https://education.github.com/pack/offers I find great software there smile

Thanks! How do we join this?

**Comment by Kulcanhez** [comment]
> > Be part of Github Students would be very nice https://education.github.com/pack/offers I find great software there smile
> 
> 
> 
> Thanks! How do we join this?

[Here](https://education.github.com/pack/partners) 🙂

**Comment by haula1122** [comment]
Please , I applied for GitHub student pack but unfortunately I was rejected for not using school issued email, and the fact is our school don't issues email to us, I have submitted my ID card as proof of my studentship... 
Thanks
