### ISSUE TITLE
Goal counter incorrect when filtering

### ISSUE THREAD

**Issue by JacoBriers** [plausible/analytics#1188]
## Prerequisites
- [x] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report
**Describe the bug**
When filtering the dashboard on dimensions other than `Completed Goal`(for instance `Country`) the goal counters are a multiple of the true values. 

**Expected behavior**
Goal counters are identical when filtering on any combination of dimensions.

**Screenshots**
No filter:
![image](https://user-images.githubusercontent.com/1818218/125789530-a930cbf1-82ad-483c-878c-b5904ba48a57.png)

Filter on `Country`:
![image](https://user-images.githubusercontent.com/1818218/125789559-1e7c8c65-ebf8-47c1-86b3-ce9ca8003b37.png)

**Environment**
 - MacOS
 - Chrome
 - 90.0.4430.212

**Comment by metmarkosaric** [comment]
thanks @JacoBriers! i cannot replicate this anywhere. please share your dashboard (or a full screenshot) or send us an email with your account details and we can take a look for you.

**Comment by JacoBriers** [comment]
Sure thing, here is a full screenshot:

Without filter:
![image](https://user-images.githubusercontent.com/1818218/125912970-a9636d0b-9491-45b8-a1e7-cb4ff71a743d.png)

With filter:
![image](https://user-images.githubusercontent.com/1818218/125913055-b40b0cdf-4ae1-434f-8d40-3b5dc86cdbfa.png)

I can share the dashboard as well, which email address should I send the link to?

**Comment by metmarkosaric** [comment]
thanks for the details @JacoBriers! looks very weird! @ukutaht will take a look at the db to see if he can figure out what's going on. thanks for your patience!

**Comment by JacoBriers** [comment]
Looking at the dashboard again today - issue seems to have disappeared

**Comment by ukutaht** [comment]
I was just looking at this and I cannot reproduce either. Thanks for reporting anyways and please do let us know if any other issues come up.
