### ISSUE TITLE
API metrics property doesn't work

### ISSUE THREAD

**Issue by Schotsl** [plausible/analytics#1197]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Describe the bug

When I query the `timeseries` endpoint, the metrics property doesn't seem to do anything

https://plausible.io/api/v1/stats/timeseries?period=12mo&metrics=bounce_rate%2Cpageviews&site_id=%SITE%

https://plausible.io/api/v1/stats/timeseries?period=12mo&metrics=pageviews&site_id=%SITE%

Both return the exact same result:

Settings `bounce_rate` as property returns: 
```
[
  { date: "2020-08-01", visitors: 0 },
  { date: "2020-09-01", visitors: 0 },
  { date: "2020-10-01", visitors: 0 },
  { date: "2020-11-01", visitors: 0 },
  { date: "2020-12-01", visitors: 0 },
  { date: "2021-01-01", visitors: 1031 },
  { date: "2021-02-01", visitors: 1284 },
  { date: "2021-03-01", visitors: 2110 },
  { date: "2021-04-01", visitors: 1776 },
  { date: "2021-05-01", visitors: 1860 },
  { date: "2021-06-01", visitors: 1893 },
  { date: "2021-07-01", visitors: 1467 }
]
```

While setting `pageviews` as property returns:
```
[
  { date: "2020-08-01", visitors: 0 },
  { date: "2020-09-01", visitors: 0 },
  { date: "2020-10-01", visitors: 0 },
  { date: "2020-11-01", visitors: 0 },
  { date: "2020-12-01", visitors: 0 },
  { date: "2021-01-01", visitors: 1031 },
  { date: "2021-02-01", visitors: 1284 },
  { date: "2021-03-01", visitors: 2110 },
  { date: "2021-04-01", visitors: 1776 },
  { date: "2021-05-01", visitors: 1860 },
  { date: "2021-06-01", visitors: 1893 },
  { date: "2021-07-01", visitors: 1467 }
]
```

### Expected behavior

The query with `bounce_rate` as `metrics` property should return the bounce rate

### Environment

```markdown
- OS: MacOS
- Browser: Firefox
- Browser Version: 89.0.2
```

**Comment by ukutaht** [comment]
Works fine for me on current live. Are you on self-hosted by any chance?

**Comment by Schotsl** [comment]
I just updated my self hosted Plausible instance and it seems to be fixed! :)
