### ISSUE TITLE
Applying filter in new tab doesn't work for Top Sources and Devices

### ISSUE THREAD

**Issue by FlorianRaediker** [plausible/analytics#1198]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Describe the bug

Opening a filter-link on the dashboard in a new tab doesn't always work because the domain is missing in the URL.
E.g. if I middle-click on "Google" under "Top Sources", plausible.io opens because the URL is https://plausible.io/?source=Google and not https://plausible.io/plausible.io?source=Google.

It works correctly for "Top Pages" and "Goal Conversions", but not for "Top Sources", "Devices", and "Countries" (countries have no link at all).

Thank you for creating an awesome analytics tool!

### Expected behavior

I would expect the link to include the domain so that filters can be applied in a new tab.

### Screenshots

Not working:
![image](https://user-images.githubusercontent.com/38762910/126461623-55c9ee5f-08db-4321-b55a-bc0357caa8cf.png)

Correct:
![image](https://user-images.githubusercontent.com/38762910/126461698-e8221804-42f2-4e9f-ab71-5fb475ca469b.png)

### Environment

```markdown
- OS: Linux
- Browser: Chromium-based
- Browser Version: 91.0.4472.164
```

**Comment by ukutaht** [comment]
Thanks for reporting! I'll take a look.
