### ISSUE TITLE
Breakdown API with custom property filter: unexpected values returned

### ISSUE THREAD

**Issue by seeARMS** [plausible/analytics#1203]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Describe the bug

I'm using the `/api/v1/stats/breakdown` API on a self-hosted installation.

I'm grouping by `event:page`, and filtering by a custom property.

If I include `metrics=visitors`, everything works as intended and the proper values are returned:

![image](https://user-images.githubusercontent.com/3957773/126740554-25b25549-c3da-4d74-9bcb-12261bba7585.png)

However, if I include `metrics=visitors,bounce_rate` (or, any metric which has a null value on entries which do not match the custom property), then many rows are returned, including ones which do not have the custom property logged:

![image](https://user-images.githubusercontent.com/3957773/126740602-900ba73b-c749-4546-b8b5-d514d4028bf5.png)

Full JSON output of this example is here:

```
{
    "results": [
        {
            "bounce_rate": null,
            "page": "/@PapyrusBlog/welcome-to-papyrus!",
            "visitors": 1
        },
        {
            "bounce_rate": null,
            "page": "/@PapyrusBlog/z8icYc3WDYsigHDhRgs2",
            "visitors": 1
        },
        {
            "bounce_rate": 88.0,
            "page": "/@colinarms/personal-automation-with-huginn-using-slack-docker-and-gcp",
            "visitors": null
        },
        {
            "bounce_rate": 38.0,
            "page": "/",
            "visitors": null
        },
        {
            "bounce_rate": 100.0,
            "page": "/notes",
            "visitors": null
        },
        {
            "bounce_rate": 0.0,
            "page": "/settings/blog",
            "visitors": null
        }
    ]
}
```

The first two entries are what was expected, but all the remaining entries did not have the custom property logged and was thus unexpected.

The documentation says `Custom prop filters and breakdowns cannot be combined arbitrarily.`, but I assumed that meant we cannot both break down and filter by custom props, and not the issue that is encountered here?

### Expected behavior

I was surprised to see the entries included that did not have the custom property logged. 

### Screenshots

Screenshots are above

### Environment

```markdown
- OS: Mac OSX
- Browser: Chrome
- Browser Version: 91
```

**Comment by RobertJoonas** [comment]
The intended response for this query would be:
```
Session metric `bounce_rate` cannot be queried when using a filter on `event:props:blogId`.
```
This was actually fixed with [this commit](https://github.com/plausible/analytics/commit/7d1b1214e201107da1fe386a0a88f6bee847ab03#diff-a490614dd2b9fcf4867d0e456686fb707b32103d63b73a5c808df1deb4c94cef) 10 months ago and should also be working in self-hosted from version 1.4. So, closing this issue. Feel free to reopen if you encounter this again. Thanks!
