### ISSUE TITLE
Docs for Cloudfront proxy behaviour are incorrect

### ISSUE THREAD

**Issue by espen** [plausible/analytics#1204]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Describe the bug

https://plausible.io/docs/proxy/guides/cloudfront

1. Docs state to use `script.outbound-links.js` but the correct path is `plausible.outbound-links.js`
2. Docs to not mention required option origin request policy: "The parameter Origin request policy cannot be attached without a cache policy."

I thought `script.js` was used to avoid issues with blocking. If `plausible.js` is used, wouldn't it risk these request being blocked? If so perhaps the docs are correct and the server is not able to correctly serve flexible script configuration like `script.outbound-links.js`?

### Expected behavior

To document correctly.

### Environment

```markdown
- OS:
- Browser:
- Browser Version:
```

**Comment by espen** [comment]
Also see related discussion at https://github.com/plausible/analytics/discussions/1201

**Comment by ukutaht** [comment]
Thanks, the instructions need to be fixed indeed. More info here: https://github.com/plausible/analytics/discussions/610#discussioncomment-1040940

**Comment by ukutaht** [comment]
I'm building a fix that will make the docs work as advertised with regard to `script.js`. However, I don't fully understand this:

> Docs to not mention required option origin request policy: "The parameter Origin request policy cannot be attached without a cache policy."

Does something need to be added to the docs for this?

**Comment by espen** [comment]
A cache policy is required for adding a new behaviour. Could be worth explaining it and giving a sensible default as AWS sometimes can be a bit confusing to configure for new users.
<img width="694" alt="CleanShot 2021-09-23 at 13 16 51@2x" src="https://user-images.githubusercontent.com/32258/134498121-090a14e7-2d34-4899-b052-9b075a9c804a.png">

**Comment by ukutaht** [comment]
I see. Would adding this line to the docs help?

```
Cache policy: CachingOptimized <--
Origin Request Policy: Managed-UserAgentRefererHeaders
```
