### ISSUE TITLE
Feature request: Add stats granularity control (days, weeks, months)

### ISSUE THREAD

**Issue by anmipo** [plausible/analytics#1208]
Currently, the "mid-term" time window options are limited to:

- Last 30 days (by day)
- Last 6 months (by month)

The gap between them is quite wide... 

Normally, I check my stats over the last 90 days, by week. I can quickly select the nearest option (6 month) but it shows monthly values — which is too coarse. So I have to fallback to the custom range — but it shows daily values. 
So every time I have to 1) click many times to pick the 90-day window, and 2) guestimate weekly values by scientifically squinting my eyes :raised_eyebrow:

It would be great to have a quick selector for daily/weekly/monthly stats...

**Comment by Vigasaurus** [comment]
This probably ought to be a discussion given it is a feature request and not a bug, but either way, I am working on this as part of my major changes to the main graph (including new tooltips, comparisons, metric selection, and this option to choose granularity).
