### ISSUE TITLE
Sudden jump in visitor numbers on my site without a source

### ISSUE THREAD

**Issue by kasbah** [plausible/analytics#1212]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Describe the bug

There's a sudden jump in visitor numbers on my site. The visitor numbers seem suspicious and there is no source reported. 

https://plausible.io/kitspace.org?period=custom&from=2021-07-21&to=2021-07-28

### Expected behavior

No jump in visitor numbers, or at least a reported source, even if it's "direct entry".

**Comment by metmarkosaric** [comment]
seems like a normal traffic spike to me. there are clicks from hacker news, lobsters, reddit, twitter etc going to this post over the last 48 hours or so https://kitspace.org/boards/github.com/ottercast/ottercastaudiov2/

see this https://plausible.io/kitspace.org?period=custom&from=2021-07-27&to=2021-07-28&page=%2Fboards%2Fgithub.com%2Fottercast%2Fottercastaudiov2%2F

if you haven't shared this yourself in these sites/forums then someone else has shared it for you. for instance there's some likes and comments on Linux subreddit https://old.reddit.com/r/linux/comments/osn1tr/ottercast_an_opensource_audio_streaming_device/

many of these sites are heavy on mobile traffic which explains the direct referral sources. for instance reddit mobile app wouldn't show the referral source but would show direct

**Comment by kasbah** [comment]
Ok, thanks, the amount of "direct" entries is really throwing me off here.

**Comment by metmarkosaric** [comment]
no problem! yeah, it's pretty typical for the spikes coming from emails/social media and other sources that are heavily used on mobile phones. this is why people increasingly use [utm tags](https://plausible.io/blog/utm-tracking-tags) when sharing links
