### ISSUE TITLE
Release tracker as stand-alone NPM package

### ISSUE THREAD

**Issue by tmaier** [plausible/analytics#1216]
There might be an alternative to the proxy setup, where I wonder why it is mot being provided by default.

prove the tracker as stand-alone npm package, which I can add to my application.
I can use dependabot to keep it up-to-date.

**Comment by ukutaht** [comment]
Thanks for the suggestion. We've already released a standalone NPM package here: https://github.com/plausible/plausible-tracker. It supports Typescript as well if that's your thing.
