### ISSUE TITLE
window.localStorage causes plusible.js to crash

### ISSUE THREAD

**Issue by andrejj** [plausible/analytics#1225]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Describe the bug

Chrome, Incognito, in iframe.

Using `window.localStorage` is not available. Tracker script crashes.

Location of problem: https://github.com/plausible/analytics/blob/f179b253b43dc199871609b4eaebe7bbacf3237a/tracker/src/plausible.js#L13

You already solves similar issues in this PR: https://github.com/plausible/analytics/pull/971/files

### Expected behavior

`window.localStorage` not being available should not cause the tracker script to crash.

### Screenshots

![image](https://user-images.githubusercontent.com/9829/128072490-b79162fe-cefe-4abd-a424-7478c6d51322.png)

### Environment

```markdown
- OS: Linux, Windows
- Browser: Chrome - Incognito, in Iframe
- Browser Version: 92.0.4515.107 (Official Build) (64-bit)
```

**Comment by ukutaht** [comment]
Thanks for reporting. Wasn't aware of this issue.

**Comment by RAlfoeldi** [comment]
This is still current behaviour on the hosted version as of today (28.12.2021).
![Screenshot 2021-12-28 at 07 47 31](https://user-images.githubusercontent.com/7020711/147536883-19e8f00e-4457-4c10-a2bd-f0d3a887e296.jpg)

I really would like to subscribe, but for my use case this is a showstopper.

**Comment by RAlfoeldi** [comment]
Just to follow up on my above comment: This issue was fixed and the team reacted very promptly. I'm now paying customer :-)

**Comment by metmarkosaric** [comment]
thanks for the update @RAlfoeldi! enjoy Plausible!
