### ISSUE TITLE
Queries fail after updating clickhouse

### ISSUE THREAD

**Issue by ItalyPaleAle** [plausible/analytics#1228]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Describe the bug

I'm self-hosting Plausible (using Docker, I tried tags :v1 and :stable) and after updating Clickhouse today (still running on Docker, with tag :latest) the Plausible dashboards stopped working. All charts don't load, and I see in the inspector errors like:

```
GET | https://***/api/stats/***/pages?period=day&date=2021-08-04&filters={}
** (Clickhousex.Error) Code: 8, e.displayText() = DB::Exception: Cannot find column `equals(domain, '****')` in source stream (version 21.7.5.29 (official build))
```

### Expected behavior

Dashboards should load

### Environment

```markdown
Server-side error
```

**Comment by ukutaht** [comment]
Hey @ItalyPaleAle.

Pin your Clickhouse version to `yandex/clickhouse-server:21.3.2.5` as shown in the [hosting repo](https://github.com/plausible/hosting/blob/master/docker-compose.yml#L15). That's the highest version Plausible is currently compatible with. I don't recommend using `latest` because they can introduce breaking changes so better to pin a specific version.

**Comment by ItalyPaleAle** [comment]
Thanks, when I created the Docker Compose file, it was a long time ago :) Do you know what would happen if I downgraded now?

**Comment by ukutaht** [comment]
Ah yeah I made the mistake of specifying `latest` in the docker-compose.yml early on but I have changed it now to pin the version down.

>  Do you know what would happen if I downgraded now?

It should work fine. Try spinning the database back up with `21.3.2.5` version.

**Comment by ItalyPaleAle** [comment]
> It should work fine. Try spinning the database back up with 21.3.2.5 version.

It worked. Phew :) Thanks for letting me know
