### ISSUE TITLE
Daily visitors and current visitors for sites on landing

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/analytics#123]
"It would be nice to have a little column added to https://plausible.io/sites so that I can see an overview of my daily traffic, for each website, without having to click through to each one."

([imported from the old roadmap](https://plausible.nolt.io/73))

"Would love to see current visitors count on the My Websites listing page. At high level, this could be useful to see across all sites in the list."

([imported from the old roadmap](https://plausible.nolt.io/80))

**Comment by dewey** [comment]
I just came here to open that issue but found this one. This would be really neat to have. The current analytics platform I use just has a simple "xx views by xx people" under each website name which would already be good enough I think.

**Comment by ArsalaBangash** [comment]
I'd like this feature too!

**Comment by metmarkosaric** [comment]
New design to the /sites page is now live, the sites are in alphabetical order and we've added "unique visitors in last 24 hours" metric to each site for easy overview. Hope you like it!
