### ISSUE TITLE
Favo icon not change

### ISSUE THREAD

**Issue by RobbyTown** [plausible/analytics#1233]
I checkt the very great documentation nothing found.

If you add the website it take also the favo icon from the website (if there is) nice and easy to see the difference.

Now i have update 3 days ago my favo icon from 2 websites. On plausible i still see the old (if visit the website you see the new favo icon). 

To 'force' the favo icon update I delete the website and re add the website in plausible still the old favo icon.

Also change from .png to .svg it show the old.

When will the favo icon get update/how long is it cached?

**Comment by metmarkosaric** [comment]
thanks @RobbyTown! We get all the favicons (your site favicon and the favicons of all the referral sources) directly from the DuckDuckGo API. We display the same icon that DuckDuckGo shows in their search results. Sometimes they might not have your favicon or they show the outdated one but they normally refresh their database within a few days. Plausible will automatically show the new favicon as soon as they show it, we don't cache it. Let's hope they update your favicon to the correct one soon.
