### ISSUE TITLE
Self-hosted weekly report links to plausible.io

### ISSUE THREAD

**Issue by smilingpeanut** [plausible/analytics#1235]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Describe the bug

When installed as a self-hosted instance, the purple "Login to view your dashboard" button links to https://plausible.io/login.

### Expected behavior

The button should link to the instance from which it was generated, ie. "https://self-hosted-domain.tld/login".

### Screenshots

[https://cloudup.com/cLdxt6JxPwN](url)

### Environment

```markdown
- OS: macOS
- Browser: Chrome
- Browser Version: 92
```

**Comment by immunity20** [comment]
have you add `BASE_URL` env variable equals to your https://self-hosted-domain.tld  inside `/plausible-conf.env` file?

**Comment by ukutaht** [comment]
Fixed in 88c2666

Will be part of the next self-hosted release.

Thanks for reporting @smilingpeanut !
