### ISSUE TITLE
Different Elixir Versions

### ISSUE THREAD

**Issue by ACPK** [plausible/analytics#1238]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Describe the bug

I noticed that mix.exe has ```elixir: "~> 1.10"``` while the Dockerfile has ```elixir:1.11.3```.

Shouldn't these be the same versions? When developing a PR, should we be using Docker? 

### Expected behavior

Same versions of Elixir

### Environment

```markdown
- OS: Mac
- Browser: Safari
- Browser Version: 14.1
```

**Comment by Vigasaurus** [comment]
They both reference compatible versions, see [version docs](https://hexdocs.pm/elixir/Version.html#module-requirements). `~> 1.10` means any version from 1.10 up to 2.0, and as such, 1.11.x falls into this criteria.
