### ISSUE TITLE
Potential license inconsistency

### ISSUE THREAD

**Issue by MiWeiss** [plausible/analytics#1261]
### Past Issues Searched

- [x] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [x] This is a bug report and not a feature request, nor asking for self-hosted support

### Describe the bug

Since ~10 months, this project is AGPL licensed. However, the official docker image still refers to the MIT license:

> License
> Plausible is open-source under the most permissive Massachusetts Institute of Technology (MIT) license. This means that there are no restrictions on redistributing, modifying or using Plausible software for any reason. You can take it and use it any way that you wish.

Found [here](https://hub.docker.com/r/plausible/analytics)

### Expected behavior

The licenses should be consistent, or it should be explained why it's not.

### Screenshots

n.a.

### Environment

```markdown
n.a.
```

**Comment by ukutaht** [comment]
Thanks for pointing that out @MiWeiss! I've changed the README on Docker to reflect the license change.
