### ISSUE TITLE
Mobile issues (realtime dashboard, favicon etc)

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/analytics#1272]
* A way for anonymous/logged-out viewers to see domain name on the embed/public mobile version. right now they only see the favicon and would be nice by tapping the favicon they can see the full domain name too

* if i'm logged in and tap on the favicon to display the full domain / other sites i have, i cannot tap the favicon again to close that little menu. i must tap on another site or somewhere else on the display to close the menu. would be nice if i can tap the favicon again

* The text headings for unique visitors and pageviews in "realtime" view overflow

![index4](https://user-images.githubusercontent.com/34340819/131127126-1a6cb65a-d636-4747-b79f-3ad2af365ef6.jpg)

* footer menus need to be aligned properly

![index3](https://user-images.githubusercontent.com/34340819/131127172-4e3a3b56-73f9-4f96-b532-c1dd57486081.jpg)

* top pages:

![top-pages](https://user-images.githubusercontent.com/34340819/131127061-bb3be0c7-67c6-48aa-ba58-ad48054cf7e3.png)

**Comment by Vigasaurus** [comment]
The issues with the top stat headers I have fixed in my graph overhaul, should be coming soonish.

**Comment by metmarkosaric** [comment]
Another little issue is on the home page for non-logged in users. the "2 months free" overflows so should be placed either above or below "yearly billing"

![Screenshot_20210901-141848_Firefox.jpg](https://user-images.githubusercontent.com/34340819/131670154-6b14e7ab-1f4e-49ce-9ce5-3a2c7fe9763a.jpg)

**Comment by hirusi** [comment]
@metmarkosaric - got it. think I'll start tackling this new stuff this weekend/early next week.

**Comment by hirusi** [comment]
Also:

https://user-images.githubusercontent.com/3974019/133571822-6e448428-fd28-4cba-9624-bc962dd66f40.mp4

Not a "mobile issue" though.

**Comment by hirusi** [comment]
> Another little issue is on the home page for non-logged in users. the "2 months free" overflows so should be placed either above or below "yearly billing"

Does this look good?

![Screen Shot 2021-09-28 at 11 20 39](https://user-images.githubusercontent.com/3974019/135030730-e591df85-8825-4c0b-8fdc-5d18f5df403c.png)

If so, I'll finish this tomorrow (tablet+desktop adjustments) and open a PR.

**Comment by hirusi** [comment]
> The text headings for unique visitors and pageviews in "realtime" view overflow

To confirm, this has been tackled by @Vigasaurus?

**Comment by hirusi** [comment]
> if i'm logged in and tap on the favicon to display the full domain / other sites i have, i cannot tap the favicon again to close that little menu. i must tap on another site or somewhere else on the display to close the menu. would be nice if i can tap the favicon again

50-50 on this, but I doubt this functionality was available before? I'm looking into it either way. Might be a simple JavaScript fix/enhancement.

**Comment by hirusi** [comment]
> if i'm logged in and tap on the favicon to display the full domain / other sites i have, i cannot tap the favicon again to close that little menu. i must tap on another site or somewhere else on the display to close the menu. would be nice if i can tap the favicon again

@ukutaht - I see two conflicting handlers for this one:

https://github.com/plausible/analytics/blob/5f6553c8d83c616f19d3b68ff7f5d905c0261dff/assets/js/dashboard/site-switcher.js#L18-L22

https://github.com/plausible/analytics/blob/5f6553c8d83c616f19d3b68ff7f5d905c0261dff/assets/js/dashboard/site-switcher.js#L41-L46

...and, this:

https://github.com/plausible/analytics/blob/5f6553c8d83c616f19d3b68ff7f5d905c0261dff/assets/js/dashboard/site-switcher.js#L141

https://github.com/plausible/analytics/blob/5f6553c8d83c616f19d3b68ff7f5d905c0261dff/assets/js/dashboard/site-switcher.js#L63-L71

---

I would favor the `toggle` method -- as adding event listeners is generally not very React-y.

**Comment by hirusi** [comment]
I have a PR open for this now, but let me know if you need this changed please.

**Comment by hirusi** [comment]
> A way for anonymous/logged-out viewers to see domain name on the embed/public mobile version. right now they only see the favicon and would be nice by tapping the favicon they can see the full domain name too

![Peek 2021-11-28 21-38](https://user-images.githubusercontent.com/3974019/143776235-1f43ecd7-ce16-498b-9463-8c6c8306f5d6.gif)

I have an early peek here. I'm not sure how well this fits into all use cases for the site switcher -- maybe @ukutaht has input here?

The idea is to show the site switcher even for guests (as is the case for embeds), but remove the hotkey keyboard hint (1, 2, 3).

This also means I'll have to update the site switcher to show an arrow (or another element) so guests have an idea by looking at the area that this is something that can be toggled for additional info.

**Comment by hirusi** [comment]
I believe fixes to all the listed issues here have been merged?

**Comment by metmarkosaric** [comment]
> I believe fixes to all the listed issues here have been merged?

hi @hirusi! i think the only one left is the text headings for unique visitors and pageviews in "realtime" view where they overflow

**Comment by metmarkosaric** [comment]
also the one where non-logged-in only see the favicon and cannot know the full domain name of the site... but probably not important if there's no simple way to showcase the domain on tap. adding the site switcher seems unnecessary just to showcase the domain

**Comment by hirusi** [comment]
> > I believe fixes to all the listed issues here have been merged?
> 
> hi @hirusi! i think the only one left is the text headings for unique visitors and pageviews in "realtime" view where they overflow

Has that not been fixed by @Vigasaurus?

**Comment by metmarkosaric** [comment]
> Has that not been fixed by @Vigasaurus?

There are a couple PRs waiting so could be part of that but at least it's not live yet. 

> Let me see if I can come up with something. Perhaps a tooltip on tap?

Yeah, if it's not possible to have the design we have for logged in users (but without the whole site switcher), then something simple could work too. Thanks!

**Comment by Vigasaurus** [comment]
> > Has that not been fixed by @Vigasaurus?

> There are a couple PRs waiting so could be part of that but at least it's not live yet.

Yeah - it's part of #1364 if I recall correctly.

**Comment by metmarkosaric** [comment]
closing as the realtime design issues have now been fixed so nothing remaining here

**Comment by MaybeThisIsRu** [comment]
I left a message on our Element group a few days ago re: https://github.com/plausible/analytics/issues/1272#issuecomment-1014750675. Probably should have commented here too...

Is that not of interest anymore?

**Comment by metmarkosaric** [comment]
ah sorry! we switched to Basecamp for internal comms few months ago so haven't been on Element. the other ideas we discussed are more important than this one (email reports on mobile, icons for os/browser...) but if there's a way to fix this one too at the same time, sure let's do it
