### ISSUE TITLE
Hash mode for SPAs

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/analytics#129]
"Some SPAs use hash-based routing. We should have an option to pick that up with the Plausible script"

([imported from the old roadmap](https://plausible.nolt.io/84))

**Comment by ukutaht** [comment]
@ivanbacher I'm working on this now. Would you be open to testing the feature for us? I'm not running any hash-based websites myself.

**Comment by ivanbacher** [comment]
Sure thing 😊

**Comment by ukutaht** [comment]
@ivanbacher Thanks! I've deployed an initial test. Hash-based tracker will have a different file name from the default one. Could you try out this new script:

```
<script async defer data-domain="<your-domain.com>" src="https://plausible.io/js/plausible.hash.js"></script>
```

Note the `hash` in the filename.

This new tracker will do 2 things:
1. Trigger pageviews on the `hashchange` event
2. Keeps the hash in the URL in your stats

Unfortunately this does not apply backwards so the hashes will be collected going forward only.

**Comment by ivanbacher** [comment]
Yup as far as I can tell it's working.

![Screenshot 2020-08-24 at 20 21 03](https://user-images.githubusercontent.com/5493114/91081442-70ef0300-e647-11ea-8e15-dc7a4f6d4318.png)

**Comment by ukutaht** [comment]
Great!

I'll go live with this and we can adjust things based on feedback.
