### ISSUE TITLE
Self hosted -Weekly Email links to plausible.io

### ISSUE THREAD

**Issue by appinteractive** [plausible/analytics#1301]
When I get the weekly (and monthly) stats mail, the link to the dashboard leads me to the plausible.io login instead to my self hosted. 

I saw that there is a variable in the Mails (I hope it's that) but somehow it does not work. Or is the var not part of the latest 1.3.0 April release?

**Comment by ukutaht** [comment]
Yes this has been fixed but not released yet. See https://github.com/plausible/analytics/issues/1235

**Comment by appinteractive** [comment]
Thaks @ukutaht I only searched for `email` but not for `report` 🙄 any schedule for releasing the next version?

**Comment by ukutaht** [comment]
Probably October. We release twice a year
