### ISSUE TITLE
Empty country code - No country data reported

### ISSUE THREAD

**Issue by vitobotta** [plausible/analytics#1322]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Describe the bug

HI, I originally started a discussion but I think this belongs here because I suspect it's some sort of bug.
I have Plausible installed in a Kubernetes cluster behind a Cloudflare worker as suggested in the docs to avoid ad blockers. No country data is reported at all. I have tried both with and without the maxmind container since the last version should not require that container anymore. I have many apps in the same cluster and all of them see the correct IP of the client, plus Nginx ingress is configured to use the forwarded headers, and the ingress for Plausible is also configured to set the real IP from the CF-Connecting-IP header set by Cloudflare. 
I've also tried removing Cloudflare from the equation with the same result. There is no load balancer involved; I mean there is Cloudflare's load balancing but configured in DNS mode only, so it's as if requests go straight to the servers or via the worker if enabled. Either way no country data is reported. 

### Expected behavior

I would expect Plausible to detect countries, but no countries are reported and when I look at the logs, I can see that the country code field is left empty. 

### Environment

```markdown
I don't think it's relevant, but anyway
- OS: MacOS
- Browser: Any browser
- Browser Version:
```

**Comment by metmarkosaric** [comment]
have you tried without the cloudflare worker? those instructions are more meant for the cloud version. for self-hosted, you have some options to avoid adblockers here https://github.com/plausible/analytics/discussions/387

**Comment by vitobotta** [comment]
Thanks! It worked that way. The super weird thing is that that deployment uses the latest tag while I was using the 1.3.0 tag. Shouldn't they be the same? There was a difference when setting the account up, because this time it asked me to verify my account with a code, which didn't happen with the previous deployment, suggesting that the two versions are perhaps different. Anyway, it works now! Thanks :)

**Comment by metmarkosaric** [comment]
Great, glad that it worked! Thanks for the update!
