### ISSUE TITLE
Direct / None referrer is not filterable

### ISSUE THREAD

**Issue by TkDodo** [plausible/analytics#1325]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Describe the bug

At the moment, you cannot filter for the "Direct / None" referrer via the "filter by source" filter (see screenshot)

There is a workaround to make it work:

- Filter for the realtime view
- Direct / None is now shown. Click it.
- Filter for Direct / None is added.
- Now go back to any view you'd like

You can also add source=Direct+%2F+None into the url, but it's not visible in the Fiilter dialog.

This is likely because the referrer itself is filtered out for the main view (see https://github.com/plausible/analytics/issues/187)

### Expected behavior

The referrer "Direct / None" should be filterable, just like all the other referrers.

### Screenshots

<img width="451" alt="Screenshot 2021-09-12 at 08 14 43" src="https://user-images.githubusercontent.com/1021430/133114991-0bd2f64c-7a66-4a0b-bd6b-1c982997a662.png">

### Environment

```markdown
- OS:MacOS
- Browser: Brave
- Browser Version: Version 1.29.77 Chromium: 93.0.4577.63 (Official Build) (x86_64)
```

**Comment by metmarkosaric** [comment]
thanks for reporting @TkDodo - this is more like a feature request rather than a bug. 

by the way - you can also click on the "details" in Top Sources and direct/none will be listed there. clicking on it, would filter the dashboard by it

**Comment by TkDodo** [comment]
right, I discussed this originally with @ukutaht over here: https://github.com/plausible/analytics/issues/187#issuecomment-918267565, where it was suggested to open a new issue :)

I didn't know that clicking on the various values in the Dialog will also filter. There are a couple of workarounds for this, so feel free to close this as it's really minor 👍

**Comment by metmarkosaric** [comment]
yeah our original filtering was done with the "click on anything in the dashboard" way. the "custom filter" is a recent introduction to add extra functionality such as search, exclude, group... filtering by clicking on a metric is still the most effective way at least to me

**Comment by ukutaht** [comment]
Thanks @TkDodo, will close for now
