### ISSUE TITLE
email server without authentication

### ISSUE THREAD

**Issue by emilburzo** [plausible/analytics#133]
Hi, thank you for creating/open-sourcing plausible.io!

It's just what I wanted for personal/hobby projects and very easy to setup / migrate to it (I think it took me less than 1 hour to set it up and migrate all my personal projects from google analytics)

Some questions popped up, most of them already have issues with the `self-hosted ` label, but one I couldn't find is: how do I have to set the environment variables if my email server doesn't require auth?

I noticed in [the config](https://github.com/plausible/analytics/blob/master/config/config.exs#L146) auth is set to `:always`. It appears there's also a `:if_available` setting [documented in bamboo_smtp](https://github.com/fewlinesco/bamboo_smtp/blob/39a27e7f9879aa4f494abba2d3275b82e93f59d1/lib/bamboo/adapters/smtp_adapter.ex#L27) -- assuming it does what I think, would it be possible to use that or, probably even better, make the option configurable?

Not sure how easy it is, but including a "send me a test email" button would be very helpful

**Comment by tckb** [comment]
@emilburzo  thanks for reporting this. Though I wouldn't recommend to turn off SMTP auth, I think it is fair request. I will address this #89
