### ISSUE TITLE
Z-index bug

### ISSUE THREAD

**Issue by albertwalicki** [plausible/analytics#1346]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Describe the bug

There is a small overlay bug with the list of all sites. 

### Expected behavior

Bigger z-index on `.sticky` class resolving the problem

### Screenshots

![Screenshot 2021-09-21 at 09 46 33](https://user-images.githubusercontent.com/23482023/134132711-c800a491-538e-413b-a1dc-b16d27eca1be.png)

### Environment

```markdown
- OS: MacOS
- Browser: Chrome
- Browser Version: 93.0.4577
```

**Comment by ukutaht** [comment]
Thanks for reporting! The fix will go live on plausible.io soon
