### ISSUE TITLE
Optional MaxMind geolocation database is required to fix errors on POST /api/event

### ISSUE THREAD

**Issue by vorotech** [plausible/analytics#1351]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Describe the bug

Hello team!
There is a discussion related to fixing 500 error response when POST data to /api/event endpoint
https://github.com/plausible/analytics/discussions/638

From the discussion I understood that logged error `BadMapError expected a map, got: nil` is related to missed `GEOLITE2_COUNTRY_DB` option which is set when integrating with MaxMind GeoIP.

But isn't the `dbip` that Plausible uses by default already enriching analytics data with visitor countries.

### Expected behavior

Assuming the `dbip` doesn't provide details in format or amount that MaxMind GeoIP solution can do, still expected the application to work without error out of the box. 

### Screenshots

```
plausible_1            | 07:53:43.562 [error] #PID<0.8387.0> running PlausibleWeb.Endpoint (connection #PID<0.7597.0>, stream id 31) terminated
plausible_1            | Server: analytics.example.com:80 (http)
plausible_1            | Request: POST /api/event
plausible_1            | ** (exit) an exception was raised:
plausible_1            |     ** (BadMapError) expected a map, got: nil
plausible_1            |         (elixir 1.11.3) lib/map.ex:469: Map.get(nil, :country, nil)
plausible_1            |         (plausible 0.0.1) lib/plausible_web/controllers/api/external_controller.ex:158: PlausibleWeb.Api.ExternalController.visitor_country/1
plausible_1            |         (plausible 0.0.1) lib/plausible_web/controllers/api/external_controller.ex:80: PlausibleWeb.Api.ExternalController.create_event/2
plausible_1            |         (plausible 0.0.1) lib/plausible_web/controllers/api/external_controller.ex:9: PlausibleWeb.Api.ExternalController.event/2
plausible_1            |         (plausible 0.0.1) lib/plausible_web/controllers/api/external_controller.ex:1: PlausibleWeb.Api.ExternalController.action/2
plausible_1            |         (plausible 0.0.1) lib/plausible_web/controllers/api/external_controller.ex:1: PlausibleWeb.Api.ExternalController.phoenix_controller_pipeline/2
plausible_1            |         (phoenix 1.5.8) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
plausible_1            |         (plausible 0.0.1) lib/plausible_web/endpoint.ex:1: PlausibleWeb.Endpoint.plug_builder_call/2
```

### Environment

```markdown
# docker-compose.yml
version: "3.3"
services:
  mail:
    image: bytemark/smtp
    restart: always

  plausible_db:
    image: postgres:12
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres

  plausible_events_db:
    image: yandex/clickhouse-server:21.3.2.5
    restart: always
    volumes:
      - event-data:/var/lib/clickhouse
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  plausible:
    image: plausible/analytics:latest
    restart: always
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh db init-admin && /entrypoint.sh run"
    depends_on:
      - plausible_db
      - plausible_events_db
      - mail
    ports:
      - 8000:8000
    env_file:
      - plausible-conf.env

volumes:
  db-data:
    external: true
  event-data:
    external: true
  geoip:
    external: true
```

**Comment by ukutaht** [comment]
I cannot test this right now but:

1. The `latest` tag should use db-ip if you don't configure `GEOLITE2_COUNTRY_DB`
2. In the next version (coming October or November) we will probably have city level data which db-ip does not support for free. So I'll probably remove support for db-ip and go back to this option being required for any location data.

**Comment by vorotech** [comment]
Thanks @ukutaht for quick response
Your second point makes sense. It still would be cool to opt-in only region level data with `db-ip`
But even if development effort doesn't let you make it configurable, would be nice to have documentation updated as well to reflect the new requirements.
Thanks.

**Comment by vorotech** [comment]
@ukutaht JFYI
it seems that image with a `latest` tag has some regression issues, since event with correct setup of the MaxMind GeoIP the problem didn't go away.
Once I've switched to `stable` image it works without any reported error logs.

**Comment by ukutaht** [comment]
Thanks for letting me know. I'll take a look when I can
