### ISSUE TITLE
Filter Page URLs

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/analytics#136]
"I have some pages that contain UUIDs that are specific to users. I don't care which date or UUID is called and want to aggregate them.

Example:
Before: /account/550e8400-e29b-11d4-a716-446655440000
After: /account/{uuid}

A simple search and replace functionality with regex would be great!"

([imported from the old roadmap](https://plausible.nolt.io/95))

**Comment by pelme** [comment]
This would be helpful from a privacy *and* analytics perspective for us.

**Comment by marcobusemann** [comment]
Same here. Would be nice to specify multiple patterns to aggregate page URLs. Currently having dynamic URL parts creates a mess in the statistic.

**Comment by tlghnb** [comment]
It is indeed creating a mess and completely unnecessary to show stats for those URLs. Would love to see this feature added anytime soon!
