### ISSUE TITLE
site settings: left-hand sidebar is empty

### ISSUE THREAD

**Issue by MarkusAtEnreach** [plausible/analytics#1361]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Describe the bug

When I go into the site settings of the website, the left-hand sidebar is empty.
Same behavior for all our 16 website 

### Expected behavior

Should be like documented in the online help: https://plausible.io/docs/users-roles.
This has always worked like this so far.

### Screenshots

![image](https://user-images.githubusercontent.com/86395489/135029145-51fd65ab-acac-478f-8d1c-1c9db1c9fb99.png)

### Environment

```markdown
- OS: Windows 10
- Browser: Microsoft Edge 
- Browser Version: Version 94.0.992.31 (Official build) (64-bit)
```

**Comment by metmarkosaric** [comment]
thanks for reporting @MarkusAtEnreach! looks very weird! we haven't got this issue reported before and i cannot replicate it on other chromium based browsers. could it be that you have some extension or something else installed that is blocking it?

**Comment by MarkusAtEnreach** [comment]
Firefox is working fine.
In Edge also buttons on your homepage are missing:
![image](https://user-images.githubusercontent.com/86395489/135059218-39c1dbe4-5d5f-4769-8f64-bb4b847228fb.png)

**Comment by MarkusAtEnreach** [comment]
I have only a few extensions. Disabled them. No change.

**Comment by metmarkosaric** [comment]
weird. i just installed Edge Version 94.0.992.31 to try it and it all works and looks all fine here. edge is based on chromium and the fact that we haven't heard this from any of the thousands of people that visit us daily from chromium browsers makes me think it's something to do with your Edge. but what i'm not sure. perhaps you can try in incognito mode (can see Edge calls it InPrivate) as that disables any plugins or changes you might have?

**Comment by MarkusAtEnreach** [comment]
Found the root cause. It is the keeper extension:

https://microsoftedge.microsoft.com/addons/detail/keeper%C2%AE-password-manager-/lfochlioelphaglamdcakfjemolpichk

If I disable it, the homepage is displayed correctly

**Comment by metmarkosaric** [comment]
great! thanks for the update and glad you found a cause of this!
