### ISSUE TITLE
Use Udger for bot detection

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/analytics#137]
"I see many Crawler and Bots in my page views. Is it possible to exclude those?

Yes, bot detection can be improved significantly. Currently I use an open source solution that only looks at the User-Agent header. I’m planning to add detection based on known bot/crawler IP addresses and referrer spammers."

([imported from the old roadmap](https://plausible.nolt.io/96))

**Comment by julianrubisch** [comment]
fwiw, you could look into how https://github.com/ankane/ahoy does it... I think they defer to JS bot detection a lot

**Comment by metmarkosaric** [comment]
https://udger.com/resources/ip-list
