### ISSUE TITLE
Update the Google Search Console API discovery document

### ISSUE THREAD

**Issue by Heziode** [plausible/analytics#1371]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Describe the bug

I just received a mail from Google, regarding the following subject: Update the Google Search Console API discovery document.

## Content

Hello Google Search Console API Customer,

In [August](https://notifications.google.com/g/p/AD-FnEwxC7asW3P-RYbLlogvCHCf-nE8hUFIL7VFbWHBwl_sX2CIl1NcouuIqUBgDz-4VeEu8_Gik8U-7PiegjJ8UERvIOB0yq0kdivb3xggciUsu8oVTS-svLkeUuMFifFjlvScIPh6erJfDoBw5XUEh6b5f8xNA_Ka) and [December](https://notifications.google.com/g/p/AD-FnEzJwbGde64djbidITINbtzyClwMiDXHnJSRBy0oEA824dj94hMbOsRuJfGvnqC060UUmf_gzwFXDFjQtncYu3T6xwQDqkklu6rSk0lnLpzMJJlCI3_X9Qe9arcAJmzDWuotM9MHdd_Vk3xHq79GTir0) 2020, we announced that we would be removing support for the Webmasters discovery document.

Today we are writing to let you know that starting November 1, 2021, **projects which have not updated their discovery document will no longer be supported and will stop working.**

If you're querying the Search Console API using an external API library, or querying the Webmasters API discovery document directly, **you will need to update your API calls to include the changes described in** [**these step-by-step instructions**](https://notifications.google.com/g/p/AD-FnExnJaNWwsMxdlXPR_UKxTML71_ghjNXjpA2y-Ndp9FAfwsLwkM_FvnCmDjaxeNsvxXJAXyVkN4gfiGnAe03irdZl8_GjfirMYXvel0eTQ2FFMmNb58hhXRI3lQor1dIG2-aa_BQcY7vUjHI8vmkDbBzc-eNR9dJP9-lTW964fGZv8WwxUNqeHoE).

Your projects listed below have used the Search Console API in the last 90 days and may be affected by this change:

*   Plausible (plausible-123456)

If you have any questions or require assistance, please refer to the [Google Search help page](https://notifications.google.com/g/p/AD-FnEwVRqcnndXs0b18YoliMBz7euAzE2UF91Gpd7Uo1J9l_MUoBPix9oVTm4LdYKV3zFfhHIYeCxQXa6efD25-Z2T3BmwT5_x5aOYbWjPIcg).

Thanks for using the Google Search Console API.

Sincerely,

The Google Search Console team

### Expected behavior

Update API call on the code.

### Environment

```markdown
Not relevant here.
```

**Comment by paskal** [comment]
I think this is the code that should be updated:

https://github.com/plausible/analytics/blob/c68b88c24b5de1b257b8ee9ffc9fc06bbaae7911/lib/plausible/google/api.ex#L2

https://github.com/plausible/analytics/blob/c68b88c24b5de1b257b8ee9ffc9fc06bbaae7911/lib/plausible/google/api.ex#L27

**Comment by paskal** [comment]
Preferably someone like me or you should update that locally, verify that it works and then prepare the PR with the update to this repo so that it will be fixed for everyone.

**Comment by ukutaht** [comment]
Looks like things are working fine. Closing this issue.
