### ISSUE TITLE
Custom events with the JavaScript API

### ISSUE THREAD

**Issue by resynth1943** [plausible/analytics#140]
Hello,

Is there an official method for sending custom data via the JS API?

I have seen users use `window.plausible('eventName', ...)` How would the Plausible API react to an object as the second parameter? Would it serialise it?

So many questions... 😝

Many thanks,
Synth

**Comment by metmarkosaric** [comment]
Sharing the link to the code we use on our own website to track trial signups: https://docs.plausible.io/custom-event-goals

We discussed this via email too so closing this for now. Do reopen if there's anything else, thanks!

**Comment by resynth1943** [comment]
Oh damn, sorry. Forgot to close this... 😝

**Comment by metmarkosaric** [comment]
No problem :smiley:
