### ISSUE TITLE
Phantom Wallet (crypto wallet) blocks sending page views

### ISSUE THREAD

**Issue by wandrzejczak** [plausible/analytics#1403]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Describe the bug

Using crypto wallet Phantom for Solana blockchain (https://phantom.app/) is blocking Plausible Analytics tracking script to send Page View events.
Phantom Wallet is represented in JavaScript with the `window.phantom` object, and as I can see in the code of the tracking script in line 39 if this object is available, then stop processing sending page view event.

` if (window.phantom || window._phantom || window.__nightmare || window.navigator.webdriver || window.Cypress) return;`

Besides, if you wish to block sending analytics for bots using popular Web Drivers like Selenium you should add a mapping list like this:
  ```

  var documentDetectionKeys = [
          "__webdriver_evaluate",
          "__selenium_evaluate",
          "__webdriver_script_function",
          "__webdriver_script_func",
          "__webdriver_script_fn",
          "__fxdriver_evaluate",
          "__driver_unwrapped",
          "__webdriver_unwrapped",
          "__driver_evaluate",
          "__selenium_unwrapped",
          "__fxdriver_unwrapped",
      ];
  
  var windowDetectionKeys = [
      "_phantom",
      "__nightmare",
      "_selenium",
      "callPhantom",
      "callSelenium",
      "_Selenium_IDE_Recorder",
  ]; 
```

As far I know `window.phantom` was never a correct object to detect phantom, it should be `window._phantom`, but I might be wrong.

Wojtek.

### Expected behavior

Having the Phantom Wallet extension installed in the browser should not block sending page view events.

### Environment

```markdown
- OS: Windows 10 / OS X
- Browser: Chrome
- Browser Version: 94
```

**Comment by wandrzejczak** [comment]
Thank you, @cannikin, for the quick reply.

I've already made a temporary bypass solution. But I'm looking forward for a final solution :)

**Comment by ukutaht** [comment]
Thanks everyone! `window.phantom` detection will be removed next time I deploy live. Probably late this week.
