### ISSUE TITLE
Database connection error is misleading

### ISSUE THREAD

**Issue by viraptor** [plausible/analytics#1405]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Describe the bug

When setting up the initial database all errors seem to result in the same exception:
```
plausible_1           | create Plausible.ClickhouseRepo database if it doesn't exist
plausible_1           | 01:16:05.185 [error] Task #PID<0.198.0> started from #PID<0.94.0> terminating
plausible_1           | ** (DBConnection.ConnectionError) connection not available and request was dropped from queue after 2997ms. This means requests are coming in and your connection pool cannot serve them fast enough. You can address this by:
plausible_1           | 
plausible_1           |   1. By tracking down slow queries and making sure they are running fast enough
plausible_1           |   2. Increasing the pool_size (albeit it increases resource consumption)
plausible_1           |   3. Allow requests to wait longer by increasing :queue_target and :queue_interval
```

This is not correct and misleading. There is some connection issue in my environment, but the real reason for the failure is not passed on / displayed.

### Expected behavior

The actual error from ecto or socket should be displayed so the issue can be debugged.

### Environment

```markdown
- OS:
- Browser:
- Browser Version:
```

**Comment by ukutaht** [comment]
Thanks for reporting.

We show the exact error we get from [clickhouse-elixir](https://github.com/clickhouse-elixir/clickhousex). If the error message is not correct, it needs to be fixed upstream. There is nothing we can do in this project to show a better error message.
