### ISSUE TITLE
Import from Google Analytics

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/analytics#142]
"Let’s make it easier to stop using GA"

([imported from the old roadmap](https://plausible.nolt.io/101))

**Comment by rebelchris** [comment]
Def would be keen to convert, but don't want to miss out on existing stats.

**Comment by metmarkosaric** [comment]
Definitely something we want to do. Closing this in favour of #211 as it has a larger discussion with more details.

**Comment by metmarkosaric** [comment]
**Update:** You can now import your historical Google Analytics (Universal Analytics) stats into your Plausible dashboard. [See more here](https://plausible.io/docs/google-analytics-import).

**Comment by oliverbutler** [comment]
@metmarkosaric Any update on this being disabled? https://github.com/plausible/docs/commit/74f69bf19c74492ef2021276b4eb8ee8035753ce

I just migrated two of my projects to Plausible cloud and I'd __love__ to get this data imported.

**Comment by metmarkosaric** [comment]
hi @oliverbutler! we're putting the finishing touches as we speak so should be back online pretty soon. stay tuned!

**Comment by metmarkosaric** [comment]
Google Analytics import is now back!

https://plausible.io/docs/google-analytics-import

**Comment by sylvaingable** [comment]
Hi @metmarkosaric it seems the Google Analytics import is not back into the self-hosted version yet. Any idea when the docker images will be updated?

Thanks.

**Comment by davidngrc** [comment]
Hi @metmarkosaric  I install the self host, and in the UI, it said importing data from google analytics.
but due to my data is from 2011, is there a way that I can track the progress of the import?
