### ISSUE TITLE
Stats API doesn't allow getting data for outbound click event

### ISSUE THREAD

**Issue by TimDaub** [plausible/analytics#1429]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Describe the bug

One can visit a site's goal conversion aka "events" tracking page and find a graph on top with which events happened at what time: https://plausible.io/rugpullindex.com?period=day&goal=Outbound+Link%3A+Click&date=2021-10-28

Overview:

<img width="1032" alt="Screen Shot 2021-10-30 at 22 01 45" src="https://user-images.githubusercontent.com/2758453/139556960-154a51b7-9484-4087-962e-faf41f730aa7.png">

But, we can also click on one of the links and find when those conversions for a link happened: https://plausible.io/rugpullindex.com?period=day&goal=Outbound+Link%3A+Click&date=2021-10-28&props=%7B%22url%22%3A%22https%3A%2F%2Fcoinmarketcap.com%2Falexandria%2Farticle%2Fwhat-are-automated-market-makers%22%7D

<img width="1016" alt="Screen Shot 2021-10-30 at 22 02 10" src="https://user-images.githubusercontent.com/2758453/139556966-61b2acd5-bfa7-4a53-8e55-a837dc2cdad7.png">

Hence we can conclude that someone clicked that link at 10pm.

### Expected behavior

The stats API allows a user to download data based on custom events too: https://plausible.io/docs/stats-api#breakdown-custom-event-by-custom-props. We've implemented it here: https://github.com/rugpullindex/plausible-crawler/tree/fc11527f7e404547a023e86220b4557ca3522b8d

However, the results do now include dates:

<img width="606" alt="Screen Shot 2021-10-30 at 22 04 03" src="https://user-images.githubusercontent.com/2758453/139557011-83fb14a2-2950-4060-b72a-c4ee2e708a62.png">

But I need to exactly know when a certain click happened on an hourly resolution.

### Environment

```markdown
all environments
```

**Comment by ukutaht** [comment]
Thanks for reporting.

If I understand your use-case correctly, you'd want to use the `/api/v1/timeseries` endpoint with `hourly` interval and a filter on `event:name==Outbound Link: Click;event:props:url==<your-url>`

Unfortunately the `hourly` interval is not supported but the filter is. So really this will be covered by https://github.com/plausible/analytics/discussions/1434

Closing this for now as this is more of a feature request for the API than a bug
