### ISSUE TITLE
Heatmap support

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/analytics#143]
"I’m not quite sure whether this is manageable with privacy restrictions but _if_ it is, it would be nice to have support for heatmaps."

([imported from the old roadmap](https://plausible.nolt.io/102))

**Comment by yagarea** [comment]
If you implement this, please make it on optional. It is heavy weight feature and from some points of view privacy intrusive.

**Comment by metmarkosaric** [comment]
Closing this as we do not have the intention to add heatmaps in the current scope of the project.

**Comment by GermanJablo** [comment]
Since it's been almost 3 years of this, can it be reconsidered?

**Comment by metmarkosaric** [comment]
hey @johannbuscail! no short term plans to work on this but I've now added a note on it on our new feedback board so we can see what the demand is like https://feedback.plausible.io/308

**Comment by R70YNS** [comment]
+1 for heatmaps, would love to see this implemented in a privacy-focused manner.

**Comment by ADTC** [comment]
> no short term plans to work on this

@metmarkosaric I'm assuming this is still the case?
