### ISSUE TITLE
Regional pricing based on Purchasing Power Parity

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/analytics#144]
"I’m a developer from a non-US country. I find it difficult to subscribe to an array of serivces when each one of them charges the same from a US-based employee as they do from those based in countries like India, Brazil, South Africa, Indonesia and so on.

Some privacy-friendly way to verify and offer a cheaper price to residents of not so well off countries, unlike the US, would be very much appreciated."

([imported from the old roadmap](https://plausible.nolt.io/103))

**Comment by metmarkosaric** [comment]
Does anyone have any good examples of how this is done in real life by other startups? Cannot find any examples and seems something that's difficult to organize looking at our current setup, website and how we deal with payments and subscriptions. Thanks!

**Comment by jerodsanto** [comment]
I agree this is a big challenge and, sadly, I don't know of any obvious/public examples off the top of my head. We plan on tackling this as well when we move Changelog++ (our community membership) onsite, so I'm very interested in how y'all go about it.

There was some conversation around this on JS Party when discussing online conferences, which have similar desires.

Here it is: https://changelog.com/jsparty/124#transcript-31

**Comment by metmarkosaric** [comment]
Thanks @jerodsanto!

**Comment by ravivyas84** [comment]
https://stripe.com/docs/api/prices, Check if this works. i.e Setting up a different price for different currencies. 

I have never used Stripe, but I am guessing they are the ones to handle it via the defined currency.

**Comment by jerodsanto** [comment]
This is really cool! Here are their supported currencies:

https://stripe.com/docs/currencies

I haven't yet found in the docs if and where they will detect the user's currency for display and charging purposes...

**Comment by metmarkosaric** [comment]
Thanks @ravivyas84! Will explore how Stripe does it and what Paddle can do too.

**Comment by hirusi** [comment]
I had recently paid via Paddle but the workflow used in that scenario was:

1. Site detects IP (probably?)
2. Site offers a discount code specific to my country
3. I start the payment via Paddle for the full amount (say, USD 40)
4. I enter the generic discount coupon code given to me
5. I get the discount but pay in USD at the end of the day

**If** this is how it was done, this is ripe for abuse, but the author offered her best in good faith regardless. **If** this is the only workflow for Paddle, it might be best to stick to Stripe for intl. customers.
