### ISSUE TITLE
User flows

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/analytics#149]
"One of the main reasons for me to want Analytics is to see the users flow inside the Website itself, so that I can tailor it to the way the users are actually using it. The way I did it previously (when I had Google Analytics) was to have a Sankey Diagram which showed me how many users were flowing from one page to another. Is this something supported by Plausible or planned to be supported at some point?

Details:
For this to be useful for larger websites, I will describe how I would imagine it for a Blog (The web’s standard Hello World of websites :P )

The user would define custom page types. In this case, it would be:
HomePage: Has it’s own type
About: Has it’s own type
Posts: All posts share this type.

Then the Analytics allows me to select a page type (Say HomePage) and see how users flow from there (maybe 90% go to a Posts type page, and 10% to the About page).

Does this make sense?"

![ldud4xldqpwft8kfaovh](https://user-images.githubusercontent.com/34340819/85281041-9f0a6800-b489-11ea-960e-6fd25c00b748.png)

([imported from the old roadmap](https://plausible.nolt.io/109))

**Comment by bradonomics** [comment]
This type of user flow data would be a prerequisite for moving people off Google Analytics who wanted to use predictive prefetching libraries like [Guess.js](https://guess-js.github.io/).
