### ISSUE TITLE
Plausible doesn't capture subdomains

### ISSUE THREAD

**Issue by vixalien** [plausible/analytics#1496]
I added tracking to rabbet.me, but when I visit a page at https://vixalien.rabbet.me/test, in the dashboard it shows `/test` only. When I click on it it takes me to https://rabbet.me/test

Very annoying bug.

**Comment by metmarkosaric** [comment]
If you would like to track a subdomain then please include the subdomain when adding a site to Plausible. Plausible essentially sees different subdomains as different sites. See https://plausible.io/docs/add-website#do-you-want-to-track-a-subdomain

**Comment by vixalien** [comment]
I know I can do that but I want to track a site with a dynamic number of
subdomains. I think Google analytics does that. Why not here?

**Comment by metmarkosaric** [comment]
There are many things that Google Analytics does that we don't do. We're looking into enabling this functionality in the future though. You can follow this thread for updates on our progress: #160
