### ISSUE TITLE
Browser and OS Versions

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/analytics#151]
"Would it possible to display the browser version?
For example it would be useful to know if users are using Safari 8 vs Safari 13."

([imported from the old roadmap](https://plausible.nolt.io/112))

**Comment by peterkarrer** [comment]
I am currently evaluating plausible and this is the only missing feature that's a must-have for me. Besides that it's an awesome project!

**Comment by metmarkosaric** [comment]
Browser versions and OS versions are now live! We started tracking them few minutes ago so the data will gradually start filling in on your dashboard.

**Comment by jerodsanto** [comment]
Nice! 👏

**Comment by benbro** [comment]
Is it possible to view the full browser version (e.g. Chrome 89.0.4389.90)?
Sometimes there is a bug in a specific browser version and knowing the number of users on this version can help.

**Comment by ukutaht** [comment]
Browsers have such weird versioning schemes. I think the major version is most useful for figuring out which features you can/cannot support (although for that we can still do much better as well). We don't store the specific version at the moment. It would require reworking the data schema quite a bit. I think we'll get there eventually but don't hold your breath :)
