### ISSUE TITLE
Countries list shows wrong stats

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/analytics#1512]
When clicking on the "details" button in the "Locations" report the stats are weird. Here's a screenshot from our live demo:

![Screenshot from 2021-12-06 12-54-27](https://user-images.githubusercontent.com/34340819/144841690-f7317a08-ee7b-44bd-ac37-1d0202c798f5.png)

**Comment by ukutaht** [comment]
Fixed

**Comment by metmarkosaric** [comment]
great, thanks!
