### ISSUE TITLE
All Top Pages, Entry Pages and Exit Pages links are broken

### ISSUE THREAD

**Issue by simonplend** [plausible/analytics#1515]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Describe the bug

When I click on any link under Top Pages, Entry Pages or Exit Pages, they are all broken.

All the links under Top Pages point to `https://plausible.io/?page=undefined`, and the URLs are similar under Entry Pages and Exit Pages.

### Expected behavior

Clicking on a page link under Top Pages, Entry Pages or Exit Pages will take me through to detailed stats for that specific page.

### Screenshots

![image](https://user-images.githubusercontent.com/2773428/144920443-eddd5299-a859-4e14-93ef-da51ee4dda1f.png)

### Environment

```markdown
- OS: Pop!_OS
- Browser: Firefox
- Browser Version: 89.0.2 (64-bit)
```

**Comment by metmarkosaric** [comment]
thanks for reporting! i cannot replicate this on any dashboard i tried. what is the site dashboard that this happens on?

**Comment by simonplend** [comment]
@metmarkosaric simonplend.com

**Comment by flaming-codes** [comment]
I can report that it happens to me as well. The last time it was working for me was probably around 04-12-2021.

| Description | Image |
| --- | --- |
| DevTools | <img width="646" alt="Screenshot 2021-12-06 at 23 29 41" src="https://user-images.githubusercontent.com/11635736/144933413-ba30aa3e-011a-4bda-824c-c8834bf12ee6.png"> |
| Selected link | <img width="1170" alt="Screenshot 2021-12-06 at 23 29 56" src="https://user-images.githubusercontent.com/11635736/144933421-1026b1ec-5337-46ca-ab6f-27ae74986985.png"> |

**Comment by nicwortel** [comment]
Have the same issue, tested with both Firefox (94.0) and Chrome (96.0.4664.45) on Ubuntu.

I think it still worked for me earlier today.

**Comment by mupkoo** [comment]
We have the same problem as well. (Safari Version 15.1 (16612.2.9.1.30, 16612)). Site ID: app.livecasts.eu, although we have the problem on all the sites

<img width="890" alt="Screenshot 2021-12-07 at 8 55 47" src="https://user-images.githubusercontent.com/1788571/144981453-f93e6fe1-7077-4aa9-90fd-e7c275282b63.png">

**Comment by nekits** [comment]
We have the same problem with all our dashboards. 
The problem is only with links on dashboard (as previously described by other users), in manual mode filter per page works fine

**Comment by simonplend** [comment]
This still seems to be broken on my hosted Plausible account (site: simonplend.com). Is the fix still waiting to be deployed there?

**Comment by metmarkosaric** [comment]
Yes, sorry. The fix hasn't been deployed yet unfortunately. Thanks for your patience!

**Comment by simonplend** [comment]
No problem, just wanted to check that it wasn't a recurring bug 🙂

**Comment by metmarkosaric** [comment]
The fix is now live on site! Thanks again for reporting and sorry for the inconvenience!

**Comment by simonplend** [comment]
@metmarkosaric Brilliant, thank you — those links are all working again.
