### ISSUE TITLE
Whitelabel Dashboard

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/analytics#152]
"Could dashboards be whitelabelled? Or perhaps just the dashboard shown via share links? It could be useful for freelancers and agencies sharing a dashboard link with clients.

I think something that allows logo and branding colors would be cool, so clients can login and get their own view of their reports!"

([imported from the old roadmap](https://plausible.nolt.io/113))

**Comment by MoryCorp** [comment]
Something like this ?

![image](https://user-images.githubusercontent.com/26336203/97233935-1fe2c300-17e0-11eb-8770-6e31668c35aa.png)
And if custom image is uploaded then disable footer/docs button ?
