### ISSUE TITLE
Call event goal callback when ignored due to localhost

### ISSUE THREAD

**Issue by ronnyhaase** [plausible/analytics#1548]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Describe the bug

Hi!

When implement tracking of an event goal, locally, I noticed something that disturbed me:

I noticed that the event does not get tracked because it's localhost - that is great of course!
But also the callback I pass does not get called in that case, which prevents me from properly testing my code.
While I can indeed take measures to make sure it will very likely work this still means I need to put it to production to be 100% sure it works.

### Expected behavior

When ignoring an event due to localhost, still call the provided callback function.

### Environment

```markdown
- OS: MacOS
- Browser: Firefox
- Browser Version: 95
```

**Comment by metmarkosaric** [comment]
thanks for reporting @ronnyhaase! you can use our localhost script extension if you want to track localhost. see https://plausible.io/docs/script-extensions

**Comment by ukutaht** [comment]
Hey, thanks for reporting.

One shouldn't rely on the `callback` being called. There are a number of reasons why it may not fire and we cannot guarantee that it will always be called. So instead of relying on the callback, it's a good practice to implement a timeout on your side so that your application can always move on, even if the `callback` is never called.

Here's an example of our registration form where we implement a timeout for the callback: https://github.com/plausible/analytics/blob/0c8de55c444e09a40c4937161d0dfba47e095ab2/assets/js/app.js#L40

**Comment by ronnyhaase** [comment]
@metmarkosaric I do not wish to track on localhost, I want it to behave as in production.

@ukutaht Hm, not sure I like it - what is an appropriate timeout? Wouldn't it be better if callback is guaranteed to be called once the event was sent or so, no matter if it actually arrived, etc. (I don't know the internals)

Also it adds unnecessary defensive  complexity to the code ("In case the callback never gets called add a timeout of 1sec to call it just as safeguard" - sounds wrong).

No matter what you think about my thinking, may I'd suggest you highlight that fact a little more in the docs? While the examples use the technique you shared, it did not become obvious to me that it's a godo practice because callback is not guaranteed to be called.

**Comment by ronnyhaase** [comment]
As an idea maybe your plausible.js, could simply take care of that fallback to guarantee callback to be called?

**Comment by ronnyhaase** [comment]
For comparison:
Before:
https://github.com/ronnyhaase/ronnyhaase.com/blob/f33d130fcb6f98c3afe323eb28027bb982e6bdc5/src/_scripts.pug
Now:
https://github.com/ronnyhaase/ronnyhaase.com/blob/master/src/_scripts.pug

Don't get me wrong it's not a show stopper at all, but it also would make Uncle Bob much more happy if the fallback could be removed.
While moving the tracking to a separate function seems a good idea anyway and reduces the potential for complexity due to reusability, I still have this seemingly useless LOC requiring a comment to explain it.
What's the meaning of a callback not getting called?

In your code it's the same and also you need to keep track of the form submit state. you wouldn't need to do that if you could rely on callback.

**Comment by ukutaht** [comment]
Thanks for the feedback. It would be a lot cleaner if you could rely on the callback but this requires a bunch of extra code, both in the SDK and the snippet that you copy. This would increase the weight of the script.

It's a tradeoff and for now I think I'm leaning on the side of keeping it the way it is. In the future I'm planning to build a much richer SDK that would work similarly to your `[data-analytics]` stuff.

**Comment by ronnyhaase** [comment]
@ukutaht Thanks for getting back!

Fair enough, but may I still advise to highlight this in the docs. 1) Don't rely on callback and 2) take care your callbacks are not getting called twice.

**Comment by ukutaht** [comment]
Yeah sure, documenting it makes sense :)
