### ISSUE TITLE
Feature request: Login with SAML/SSO

### ISSUE THREAD

**Issue by rmens** [plausible/analytics#1554]
I'm evaluating some Google Analytics alternatives for enterprise use and Plausible is by far favorite. What makes it complicated is user management. Matomo has a SAML plug-in that can be used to authenticate with Azure AD/Google Accounts. Plausible lacks this.

This is probably not high on the wishlist for the average Plausible user, which I guess is not too enterprisy. But nevertheless wanted to log this as feature request.

**Comment by metmarkosaric** [comment]
thanks @rmens! there's already a thread for this idea: https://github.com/plausible/analytics/discussions/383
