### ISSUE TITLE
iframe counted as mobile user?

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/analytics#157]
"I noticed a suspiciously high percentage of “mobile” users shown on my Plausible dashboard. I suspect the majority of these are false positives caused by the fact that my site is often loaded in an narrow iframe which Plausible is treating as “mobile” based on the width of the viewport.

Can “mobile” users be qualified by user agent as well? e.g. if view width <= 576 and user agent contains "foo" then..."

([imported from the old roadmap](https://plausible.nolt.io/121))

**Comment by unformatt** [comment]
I contributed this originally. Any chance of this getting fixed? Thank you :)
