### ISSUE TITLE
Add custom goal properties to breakdown endpoint

### ISSUE THREAD

**Issue by waldhacker1** [plausible/analytics#1577]
### Discussed in https://github.com/plausible/analytics/discussions/1541

<div type='discussions-op-text'>

<sup>Originally posted by **waldhacker-joerg** December 15, 2021</sup>
Hi, I'm trying to get the available Custom Properties of the Goals via the Stats API. Unfortunately, I have not found a way. Does anyone know a possibility?

<img width="1202" alt="custom-property-breakdown" src="https://user-images.githubusercontent.com/92523446/146267670-f3e6f300-5bbd-4379-8e14-fa748f79d0c1.png">
</div>

To find out which custom properties can be queried in general (https://plausible.io/docs/stats-api#custom-props) it would be useful if an endpoint would return the user defined event properties.

**Comment by kelynch** [comment]
My organization very interested in using this feature as well.
