### ISSUE TITLE
Petition AdBlock for "Non-Invasive" Status?

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/analytics#158]
"I’m not sure if this is even a thing, but I heard that AdBlock was allowing some non-intrusive advertisements. The same kind of thing might be true of tracker blockers.

I didn’t know about Acceptable Ads. I’ll definitely think about this. Being exempt from these blockers would be huge"

([imported from the old roadmap](https://plausible.nolt.io/122))

**Comment by metmarkosaric** [comment]
There seems to be a complete blanket coverage on all forms of analytics even those that are privacy friendly so there is no way to get "non-invasive" status from the blocklists we are on.

**Comment by MoryCorp** [comment]
That's really weird, the current tool I am using : https://ghostboard.io/ isn't detected by Ublock Origin.
It seems that plausible.io domain is blocked by "easyprivacy" only.
Do you know if self-hosted is also being blocked as none of requests are calling plausible.io domain ?

**Comment by ukutaht** [comment]
Self-hosted installations are not blocked as they live on a different domain from `plausible.io`

**Comment by metmarkosaric** [comment]
I assume they haven't been "discovered" by the blocklist maintainers yet :) There's also this possibility if you'd like to go around the adblockers with the Cloud version: https://docs.plausible.io/custom-domain/

**Comment by MoryCorp** [comment]
> I assume they haven't been "discovered" by the blocklist maintainers yet :) There's also this possibility if you'd like to go around the adblockers with the Cloud version: https://docs.plausible.io/custom-domain/

Well that's what I tried.
I am currently using my 30 days trial, and added a custom domain as you can see here.

uBlock Origin still blocks it as it recognizes the redirection to the original domain :

![image](https://user-images.githubusercontent.com/26336203/95861123-4e34bd00-0d61-11eb-88eb-2ab4d3aec27c.png)

Thanks for the fast reply, sorry to reply to a closed issue.

**Comment by metmarkosaric** [comment]
Yes, uBlock Origin on Firefox can still block it. But it cannot block it on any other browsers such as Chrome, Safari and Brave.

**Comment by thatshumbug** [comment]
Would it be possible to selfhost the JS file? That way there is no redirect

**Comment by MoryCorp** [comment]
> Would it be possible to selfhost the JS file? That way there is no redirect

https://github.com/plausible/hosting

**Comment by thatshumbug** [comment]
> > Would it be possible to selfhost the JS file? That way there is no redirect
> 
> https://github.com/plausible/hosting

Well, I know that you can selfhost plausible. But I was talking about just the JS file. So I could you the hosted plausible instance and put the JS file on my webspace.

**Comment by MoryCorp** [comment]
Ah I understand my bad.
This way you could use plausible.io databases but avoid adblockers ?

Never tried something similar before.
Not sure if it van works this way.

Wouldn't it be easier to selfhost the whole thing?

**Comment by thatshumbug** [comment]
If it is just an upload of the JS file it's not easier to selfhost.

I do want to try to selfhost though.

**Comment by ukutaht** [comment]
It's possible but I doubt it's effective to just self-host the JS file. Adblockers can still block the API call to `https://plausible.io/api/event` after the JS is loaded.

To completely circumvent all blockers you need to self-host plausible itself or use a proxy.
