### ISSUE TITLE
Hash-based script fails to load on Firefox

### ISSUE THREAD

**Issue by ste163** [plausible/analytics#1581]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Describe the bug

Following the documentation for two different Vue 3 SPAs I'm managing, I changed the script tag from the normal script to the hash-based one (https://plausible.io/docs/hash-based-routing) after I realized my pages were not showing on the dashboard.

When I load the websites on Chrome, the script loads properly. However, when I load it on Firefox, the script tag fails to load.

### Expected behavior

The Plausible Analytics script should load properly on all major browsers.

### Screenshots

![Screenshot_2022-01-02_18-52-21](https://user-images.githubusercontent.com/62910490/147892612-b3aa1221-0555-4821-98c2-94c21ee714a0.png)
This link was copied directly from the Docs. This image was taken from Firefox. No error shows in the console on Chrome, and Plausible's dashboard shows that I'm actively viewing the page when I'm on a Chrome browser.

### Environment

```markdown
- OS: Linux Mint 20.2
- Browser: Firefox
- Browser Version: 95.0.1 (64-bit)
```

**Comment by metmarkosaric** [comment]
thanks for reporting @ste163! loads all fine for me (also on firefox on linux) and we haven't had any other reports of this. i see firefox visitors on other hash based dashboards. perhaps you're using an adblocker or something? 

see our proxy for adblockers: https://plausible.io/docs/proxy/introduction

**Comment by ste163** [comment]
Ah! An adblocker would do the trick as I have one running on firefox but not Chrome. Thank you for the quick response, and I apologize for not reading the docs more thoroughly on this!

**Comment by metmarkosaric** [comment]
no worries, thanks for the update!
