### ISSUE TITLE
Feedback for cities and regions

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/analytics#1582]
Cities and regions are now finally live on Plausible following a great demand! 

We've been testing a few different geolocation databases over the last few months and settled on https://db-ip.com. It's closest to what we want to achieve but we're still not happy with the way they display some cities in some countries. In some cases, they go to the district/borough level and we'd prefer all visits to be on the city level only (for instance by default DB-IP would display Soho or King's Cross rather than London on the city level).

We've done some manual overrides ourselves for some cities and plan to do more as we discover them. If you find these situations for the cities you're familiar with, please add them in this thread and we'll take a look in order to manually override them. Thanks!

**Comment by metmarkosaric** [comment]
"I have Bratislava twice, with ids 3060972 and 3343955."

([feedback via twitter](https://twitter.com/ptrlaszlo/status/1478350696957235204))

**Comment by vstollen** [comment]
Thanks for the great work! I still found a few inconsistencies:

# Unrealistic Data
As a local (German) website, a unrealistically high portion of our traffic is from Berlin (it's by far our top source), even though we should be mostly irrelevant in that region. Is there an explanation for this?

# Districts
Apart from that, here are a few districts I have found:
- "Bezirk Tempelhof-Schönberg" as part of Berlin
- "Köln-Lindenthal" as part of Köln
- "Köln-Ehrenfeld" as part of Köln
- "Stadtbezirk 04" (this translates to "District 04". No clue what city this belongs to)
- "Gemeindebezirk Leopoldstadt" as part of Wien, Austria

# Localization
Lastly, as a German, it is weird to read the English names of our German states. Albeit this is not a priority, it would be nice to see localized state names.

**Comment by metmarkosaric** [comment]
"The names of the cities in Israel are wrong. For example:
Tall Abib -> Tel Aviv
Hefa -> Haifa"

![Screen Shot 2022-01-05 at 23 33 35](https://user-images.githubusercontent.com/34340819/148298783-9660ec83-19bf-4034-95cf-47de700ec94f.png)

(via email)

**Comment by metmarkosaric** [comment]
I've submitted the fix for Bratislava and some merges of city districts into the main cities for Denmark: https://github.com/plausible/analytics/pull/1587/commits/9dd94445e381808b4a256a8048fddd80bb97410e

Don't seem to find the file that has the actual city names in order to change the Israel cases above. Searching doesn't find anything. @ukutaht would you be able to link to the actual file?

**Comment by n194** [comment]
One issue I noticed is that many Japanese regions are missing names.
![screenshot](https://user-images.githubusercontent.com/67550725/148644853-16223c52-8c5f-4e57-8da5-03be0a0e241e.png)
https://plausible.io/plausible.io/regions?country=JP&country_name=Japan

It looks like the data source is [ISO 3166-2](https://en.wikipedia.org/wiki/ISO_3166-2:JP) in which those regions don't have a unique English translation. In that case it should fall back to the romaji (Latin alphabet) name.

**Comment by ConnorOnTheWeb** [comment]
Hello, I just spun up a plausible instance. Set up the MaxMind credentials and ran:

docker-compose -f docker-compose.yml -f geoip/docker-compose.geoip.yml up --detach --force-recreate
(found in another thread)

I'm still only seeing country level, is there something else I need to do to record city level?

![Screenshot_20220110_210538](https://user-images.githubusercontent.com/28314904/148884481-dcbfdc62-f5dc-4098-8fa7-144b0db0e3e0.png)

**Comment by ukutaht** [comment]
Thanks @n194! I'll take a look as soon as I can.

**Comment by urbantrout** [comment]
I found another issue:

<img width="319" alt="Screenshot 2022-01-14 at 15 42 16" src="https://user-images.githubusercontent.com/10465787/149534017-1650bd3c-2bdb-4165-ba1f-c783d208955a.png">

*Gemeindebezirk* means district and these particular ones should just be merged into Vienna.

**Comment by tctree333** [comment]
Are there any plans for adding the region/city information to the map? It's probably more of a novelty and a lower priority, but it would be helpful to visualize where precisely these locations are. It would also help when multiple cities have the same name to identify which city specifically (though this could also be added in the text format by adding the region).

**Comment by metmarkosaric** [comment]
> Are there any plans for adding the region/city information to the map? It's probably more of a novelty and a lower priority, but it would be helpful to visualize where precisely these locations are.

thanks @tctree333! no plans for this yet but i've now added it as a feature request to https://github.com/plausible/analytics/discussions/1613

> It would also help when multiple cities have the same name to identify which city specifically (though this could also be added in the text format by adding the region).

you can do this now. click to filter by any city and then go into the Regions or Countries tabs to see where that city is located.

**Comment by ukutaht** [comment]
I've finished a round of updates to cities and regions.

1. Israel region names are updated to use international English names rather than Hebrew
2. Added missing Japanese regions
3. Merged @metmarkosaric's pull requests to improve city tracking in the Netherlands, Austria, Norway and Switzerland. These will unfortunately only apply going forward, no effect on historical data

**Comment by metmarkosaric** [comment]
nice one! i think all the major stuff has been fixed so i'll close this for now.

**Comment by mquandalle** [comment]
I see a problem with the city “Saint-Denis-lès-Bourg” in France. The city is a [small village](https://en.wikipedia.org/wiki/Saint-Denis-l%C3%A8s-Bourg) of about 5000 inhabitants but ranks as high as big French cities like Nantes, Marseille, etc.

I suspect the traffic comes from either [big city of “Saint-Denis”](https://en.wikipedia.org/wiki/Saint-Denis,_Seine-Saint-Denis) near Paris or the [capital city of La Réunion](https://en.wikipedia.org/wiki/Saint-Denis,_R%C3%A9union).

**Comment by metmarkosaric** [comment]
thanks for reporting @mquandalle! i reached out to [db-ip](https://db-ip.com/) who we use for the location database about this. here's what they say: it appears that we could not find an issue regarding the city of Saint-Denis-lès-Bourg in France in our current data set, the latest IP to Location database has ~20 records for this location totaling about 700 unique IPv4 addresses

**Comment by mquandalle** [comment]
Here is an example from a public stats page of mine where the village ranks suspectingly high : https://plausible.io/mesaidesvelo.fr?period=month

**Comment by metmarkosaric** [comment]
after some more testing of different geolocation databases, we have now gone live with a switch of the database provider. we now use the maxmind database instead. no database is 100% accurate unfortunately but this change should provide some more accuracy in terms of cities. details https://plausible.io/docs/countries#how-it-works
