### ISSUE TITLE
Realtime top pages & top sources don't update

### ISSUE THREAD

**Issue by christophelimpalair** [plausible/analytics#1589]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Describe the bug

For about 1 month (maybe 2), I've noticed that the top pages & top sources don't update as frequently anymore in the real-time view.

For example:

- User will visit the website
- Source & pages will populate
- User leaves
- Source & pages are still populated with the same information

I think it does eventually go away, but it's a significant and noticeable delay. Otherwise refreshing also gets rid of it.

It's not a major issue, just slightly annoying when looking at real-time traffic data. 

Thanks!

### Expected behavior

Real-time top pages and top sources should update more quickly after someone leaves/goes idle instead of sticking around for a long time.

### Screenshots

![Screenshot 2022-01-06 213103](https://user-images.githubusercontent.com/6696921/148491980-57d36210-d99e-41a1-bdd3-e8ef816b8915.jpg)

### Environment

```markdown
- OS: Windows
- Browser: Chrome
- Browser Version: 96.0.4664.110
```

**Comment by rdyar** [comment]
I'm new to plausible and used to GA real-time which I am addicted to. In the screenshot above, I like that the top pages are still listed, the timeframe for real-time looks to really be 30 minutes, so any page views in that 30 minutes to me should be listed. In GA they break it down a little more clearly - `Active Users` and `Pageviews (Last 30 min)` which I like, I switch that back and forth fairly often.

I've noticed that the views don't always update though unless I refresh or go back and forth from Today to Realtime. I like having this tab open all the time and look at it frequently. Maybe that is not expected?

I check real-time info often as I have a new ordering system (not a lot of traffic) and I like to see the user flow and see if they complete an order or if they leave - if they leave I like to see if they only hit a page or two or if they looked to be trying to order and gave up for some reason - and did they go to the help page. The ordering process could easily take 15 minutes so seeing 30 minutes as real-time is what I like. It is handy though to see what is actually active right this second and I'm not sure how to do that.

**Comment by ukutaht** [comment]
Hey, thanks for the feedback.

Indeed, some reports are not updating automatically anymore. I'll get that fixed.

To add to the general discussion:

Current visitors in Plausible are defined as visitors who triggered an event in the last 5 minutes. I understand it makes intuitive sense that when the user leaves, their data should be removed from the realtime dashboard. However, there's no '_'user left'_ event that we can use to trigger that update. We only track pageviews and events. So the only way to define a 'current visitor' is by setting some sort of time interval after an event that a user is still considered 'active'.

The realtime dashboard itself automatically updates every 30 seconds. This is partly broken at the moment but I'll fix it.

One way to improve the situation would be to show a message in the realtime dashboard like

> _Last updated XX seconds ago_ 

along with a manual refresh button. I think that would make the behaviour more clear.

**Comment by rdyar** [comment]
thanks for the info, and yes those 2 things would help.

So if a user has been on for the last 20 minutes and is still actively clicking around, is the intention that all of those page views would still show up on the Top pages list? thus why the graph goes out 30 minutes?

If so that works for my use case more or less, though generally I would prefer the Top pages to show the last 30 minutes as it gives me more of a chance to see what happened.

As I get more used to this I like it!

**Comment by ukutaht** [comment]
The 'Top pages' report shows only pages that have been visited in the last 5 minutes.

Mixing 30 minutes and 5 minutes in the realtime is probably unclear. I should play around with making it either one or the other in a consistent way

**Comment by rdyar** [comment]
right - I would prefer more than 5 minutes as it gives you a chance to see a trail of what a current user is doing. Once it gets into the Today realm maybe you can still do it by their geo location though but you would need to go back and forth.

Any chance for that to be user configurable?

**Comment by metmarkosaric** [comment]
> Any chance for that to be user configurable?

we focus on being simple and easy to use so prefer to make choices where it makes sense for the best of the majority. if something is not good enough to be the default choice for the majority, then in most cases we prefer not to offer that option at all. if we start giving multiple settings and choices for each small possible feature that most people are not interested in, pretty soon we'll end up some kind of a confusing monster like GA is today

**Comment by rdyar** [comment]
no problem, this is simpler and like a breath of fresh air, I can actually tell what is happening better. 

I can live with it as is I think but my vote is to extend the top pages report to something more than 5 minutes - 30 isn't really needed, but 5 is awful short.

**Comment by RobertJoonas** [comment]
The [fix](https://github.com/plausible/analytics/pull/2445) for this is now live. Closing the issue.
