### ISSUE TITLE
WordPress plugin

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/analytics#159]
"WordPress is the largest CMS in the world with some 35% of all sites being on it. Could be nice with a simple WordPress integration: Plausible stats directly in the WordPress dashboard."

([imported from the old roadmap](https://plausible.nolt.io/123))

**Comment by binaryfire** [comment]
+1. This would be huge!

**Comment by boogah** [comment]
Yes please!

**Comment by danyork** [comment]
+1 to this request. My most critical requirement is an easy way to add the Plausible script into the headers of a WordPress site. I'd like to try out Plausible on a couple of my organization's smaller sites, but we use "default" WordPress themes on those sites that we do not modify. I therefore need a plugin to inject the the script into the header of the site. (We do something similar with GA right now, using a plugin to insert the GA javascript tracking script.)

I actually don't care as much about seeing the Plausible stats in the WordPress dashboard. I mean, that's cool and useful, but I can also just login to the Plausible website to get it.

If you do go ahead with this work, I'd be glad to help with testing.

**Comment by metmarkosaric** [comment]
Thanks for your feedback! It's something we'd definitely like to support. I use WordPress myself and add Plausible by editing my theme file currently.

If you need an immediate solution and don't need Plausible stats displayed in your WordPress dashboard, there are well supported plugins such as [this one](https://wordpress.org/plugins/insert-headers-and-footers/) with more than 1 million active users. It allows you to easily insert any code into your header without editing theme files. You could use this plugin to insert GA, Plausible and any other script.

Hope that helps, thanks!

**Comment by danyork** [comment]
@metmarkosaric - Aha! **Of course** there would be a WordPress plugin for inserting headers! Thanks for pointing that one out. I've got that installed now on two very small sites that are now sending stats to your service. Thanks!

**Comment by metmarkosaric** [comment]
Nice! There's a WordPress plugin for anything :smiley: 

Looking forward to hearing what you think @danyork!

**Comment by metmarkosaric** [comment]
Just published the instructions to our Docs in case someone else wants to insert Plausible Analytics code into their WordPress site either by [using a plugin or by modifying a theme file](https://docs.plausible.io/wordpress-integration/).

**Comment by binaryfire** [comment]
@metmarkosaric This is cool but I think it should be tracked in a separate issue? This issue is about a plugin for displaying stats in the dashboard (eg. via a REST API)

**Comment by metmarkosaric** [comment]
Thanks @binaryfire. Yeah, I just added it here for information as several people found this thread when looking for a simple WordPress integration. The thread will now focus on the plugin option that displays all stats within the WP dashboard.
