### ISSUE TITLE
Props for custom events aren't showing on the dashboard

### ISSUE THREAD

**Issue by markcellus** [plausible/analytics#1596]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Describe the bug

Custom props that I'm passing with my custom events via [the Events API](https://plausible.io/docs/events-api#post-apievent) aren't showing up in the dashboard as filters. The custom event shows up --but not the prop filters.

### Expected behavior

The [custom event docs](https://plausible.io/docs/custom-event-goals#using-custom-props) say 

> filter and sort your goals by custom event properties in your Plausible dashboard

So I'm expecting the custom props that I'm passing with my custom event to show up in the dashboard.

### Environment

```markdown
- OS:
- Browser:
- Browser Version:
```

**Comment by markcellus** [comment]
Actually nvm. It appears I was spreading the `props` in the Event API call instead of assigning them to a `props` key :laughing: my bad.

**Comment by ukutaht** [comment]
No worries, let us know if you need help with anything else!
