### ISSUE TITLE
Domain and subdomain data aggregation

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/analytics#160]
"A nice feature would be if you can set a domain and subdomains for tracking and see a link between them and/or aggregating of data tab?"

([imported from the old roadmap](https://plausible.nolt.io/124))

**Comment by mehulkar** [comment]
From #205, my use case is the _same_ site deployed on multiple domains, and wanting to see which one is used more.

**Comment by vermorel** [comment]
I operate multiple websites on the same domain: `www.lokad.com`, `blog.lokad.com`, `docs.lokad.com`. I would really like to have some control on the originating subdomain, as least to filter.

**Comment by shaunchurch** [comment]
I run one app that serves different content on many domains and would really like to be able to get a global overview of traffic across all the domains, as well as filter by a single domain.

**Comment by divinerites** [comment]
> I operate multiple websites on the same domain: `www.lokad.com`, `blog.lokad.com`, `docs.lokad.com`. I would really like to have some control on the originating subdomain, as least to filter.

In fact when you give the *domain name* in Plausible, it is just an ID or tracking.

So in your use case (tracking separate subdomains), i would just create 3 different ids, and use each of them in their respective pages form this suddomain..

**Comment by ltalirz** [comment]
Would be very useful for running PaaS instances like [dokku](http://dokku.viewdocs.io/dokku/)

**Comment by shafy** [comment]
I have different subdomains for different languages of my website (e.g. yeticheese.com and de.yeticheese.com) - would be cool to see aggregate data. A related issue I'm having is that my auto language switcher redirects based on browser language, so people who go on yeticheese.com with a German browser are redireted to de.yeticheese.com and I then use the origin referrer. I know that I can do a workaround with the ref URL param, but still :-)
