### ISSUE TITLE
Support for the web-vitals framework

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/analytics#161]
"Not sure if it’s something that fits in with Plausible but it would be a nice addition to have a Web Vitals card in the dashboard that shows you stats (maybe over time?) about your web-vitality stats.

Link to framework: https://github.com/GoogleChrome/web-vitals/"

([imported from the old roadmap](https://plausible.nolt.io/125))

**Comment by danyork** [comment]
Given Google's direct that "Core Web Vitals" will be part of calculating search engine result rank "sometime in 2021", it would be great if Plausible could help web site operators with more info:  https://webmasters.googleblog.com/2020/05/evaluating-page-experience.html

(It's not 100% clear to me that any of these new "page experience" ranking factors are measurable **without** the long term data Google may be collecting from users.)

**Comment by websocket98765** [comment]
Another link that may be helpful: https://nextjs.org/blog/next-9-4#integrated-web-vitals-reporting 

You could NextJS to set up a demo quickly and generate vitals to send to Plausible.
