### ISSUE TITLE
Half a visit

### ISSUE THREAD

**Issue by hvitis** [plausible/analytics#1636]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Describe the bug

Maybe it's a tiny thing, I just set your service for one of my websites and I can see on the y axis of the graph 0.5 values. I think either we have a visit or not, there is no place for Schroedinger here :D

### Expected behavior

Graph should have full integer values on number of visits axis.

### Screenshots

<img width="498" alt="Screenshot 2022-01-26 at 07 59 50" src="https://user-images.githubusercontent.com/17104239/151117961-2f772152-eadd-4e12-891c-6b29a22d5850.png">

### Environment

```markdown
Everywhere
```

**Comment by ukutaht** [comment]
Hey, thanks for your feedback.

This behaviour is coming from the graphing library we use. We specify the number of ticks to show and we don't have control over integer vs float values. I agree with your report but to fix it we would have to reimplement a part of the Chart.js library which I would really like to avoid.

My judgement call is that the work needed to fix it is not worth the improvement to the app when we have so many more important things to work on. I will close this issue with no plans to fix, sorry :/
