### ISSUE TITLE
Stats API does not allow regex/glob patterns

### ISSUE THREAD

**Issue by asgarth** [plausible/analytics#1647]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Describe the bug

The Stats API does not allow to use the same wildcard characters available in dashboard filters. 

Also not sure why but it seems the dashboard is using a different API call to fetch the top viewed pages:

`/api/stats/$SITE_ID/pages?period=6mo&date=2022-01-28&filters=%7B%7D&limit=100&page=1&detailed=true`

Instead of the API described in the doc:

`/api/v1/stats/breakdown?site_id=$SITE_ID&period=6mo&property=event:page&limit=5`

### Expected behavior

Be able to filter using `*` and `**` as explained here:

https://plausible.io/docs/filters-segments#group-your-pages

### Environment

```markdown
- OS:
- Browser:
- Browser Version:
```

**Comment by metmarkosaric** [comment]
Thanks! This is more like a feature request rather than an issue. There's already a thread about it here https://github.com/plausible/analytics/discussions/1282
