### ISSUE TITLE
See which unique visitors generate page views

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/analytics#165]
"I just added plausible to a sub-page on my site and am seeing hundreds of page views but only 9 unique visitors. This seems odd to me and I want to look into it, but as far as I can tell there’s no way to see which unique visitors are generating the page views."

([imported from the old roadmap](https://plausible.nolt.io/130))

**Comment by ukutaht** [comment]
If this is a request to single out visitors then I don't think Plausible should ever support something like this for privacy reasons.

If it's a request to show the number of unique visitors per page then it's a duplicate. Closing this in favour of #162.
