### ISSUE TITLE
Not possible to add subfolder in website details

### ISSUE THREAD

**Issue by sebastian-raubach** [plausible/analytics#1655]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Describe the bug

I'm trying to track a subfolder on my domain, because it's an independent application.
The documentation (https://plausible.io/docs/add-website) says this should be possible and I'm able to create the site, however, when trying to select it from the site overview, I get a "Not found" page.

Here's the section in the documentation that claims it should work:

> If you'd like to track a specific subfolder only, you can also add a subfolder (yourdomain.com/subfolder).

The property I'm trying to add has the form `https://sub.domain.com/something` and I've put `sub.domain.com/something` into the domain field.

### Expected behavior

Show the site dashboard for the subfolder.

### Environment

```markdown
- OS: Windows 10
- Browser: Chrome
- Browser Version: 97.0.4692.99
```

**Comment by metmarkosaric** [comment]
thanks for reporting @sebastian-raubach! i just tested it and it works all fine for me with this format: sub.domain.com/something

can you please try again and if you have issues adding a site, please [contact our customer support](https://plausible.io/contact) so we can help you. thanks!
