### ISSUE TITLE
Full UTM tags support

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/analytics#166]
"Currently Plausible supports ref, source and utm_source parameters but would be great with the full UTM tags support too (utm_medium, utm_campaign).

* Many services support UTMs (with some sort of “automatic tagging” feature), notably emailing and marketing automation tools.
 
* Some people have taken the habit to add UTMs on their outbound links. Would make adoption easier.

* You can’t always control how your partners (or team mates, especially in large and heterogeneous company) will make up their links, but, again, it is very very likely that they would set UTMs “by default”."

([imported from the old roadmap](https://plausible.nolt.io/131))

**Comment by metmarkosaric** [comment]
Feedback on UTM via email:

"we use three dimensions of url params — by default they are called “utm_source”, “utm_medium” and “utm_campaign”. It allows us to filter visitors by three dimensions. we tag links like this:

* domain.com/?utm_source=instagram&utm_medium=ads&utm_campaign=video_story
* domain.com/?utm_source=facebook&utm_medium=ads&utm_campaign=video_story
* domain.com/?utm_source=facebook&utm_medium=social&utm_campaign=welcome_post

So with ability to track three url parameters we are able to count: 

* all visitors from Instagram or Facebook
* we can count all visitors from ads (by filtering by utm_medium)
* we can count all visitors with “video_story” tag"

**Comment by metmarkosaric** [comment]
One solution could be to display all UTM parameters that have had clicks directly in the Top Sources list. Then you can click on the individual parameter to drill-down. Looking at the above example this means that all of these would be part of the Top Sources where they would be listed with the number of unique visitors, bounce rate and visit duration:

* Instagram
* Facebook
* Ads
* Social
* Video_story
* Welcome_post

Then you could click on any of them for deeper insights:

* Click on Facebook and the total traffic from Facebook would be split into Ads, Social, Video_story and Welcome_post with individual stats for each
* Click on Ads and the total traffic from Ads would be split into Instagram, Facebook, Video_story with individual stats for each
* Click on Video_story and the total traffic from Video_story would be split into Ads, Instagram, Facebook with individual stats for each

Seems to cover all use-causes from the above example.

**Comment by ukutaht** [comment]
Thanks for putting this together, Marko.

I would suggest something like option 4 but instead of a general `UTM` tab we could have three tabs: `medium, source, campaign` with `source` pre-selected when you open it.

Should there also be a toggle to include/exclude only tagged links? I think the default view should mix both auto-detected referrer sources as well as manually tagged ones. But I can see why people would want to only inspect links that were tagged specifically.

**Comment by metmarkosaric** [comment]
UTM tags support is now live!
