### ISSUE TITLE
More pageviews in the dashboard with a region filter than no filters. 

### ISSUE THREAD

**Issue by whscienceteacher** [plausible/analytics#1666]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Describe the bug

In my current online dashboard, I see more pageviews when I choose a country or region filter than with no filters. I cannot think of a reason why this should be the case. 

[Example with filter](http://whscience.org/bugreports/plausible2022-02-11093710.png) 357 pageviews

[Without filter](https://whscience.org/bugreports/plausible2022-02-11093720.png) 139 pageviews

### Expected behavior

Adding filters should only decrease the number of pageviews. 

### Screenshots

![plausible2022-02-11093710](https://user-images.githubusercontent.com/69084880/153624153-cd56f243-b76b-41b6-b6da-f81d5fcef67a.png)
![plausible2022-02-11093720](https://user-images.githubusercontent.com/69084880/153624165-4da61698-1b25-4a3c-876e-8c37716c8945.png)

### Environment

```markdown
- OS: Windows
- Browser: Edge
- Browser Version: 98.0.1108.43
```

**Comment by ukutaht** [comment]
Thanks for the report. Clearly a bug.

**Comment by metmarkosaric** [comment]
thanks @whscienceteacher! do you still experience this issue?

**Comment by metmarkosaric** [comment]
closing this as cannot replicate the issue but please do share more details if this happens again. thanks!

**Comment by sptv2reg** [comment]
I'm also seeing this bug on our trial:

![image](https://user-images.githubusercontent.com/103186488/213391494-e1dd92fb-247e-47ce-9362-2420fe6916fb.png)

With country filter:

![image](https://user-images.githubusercontent.com/103186488/213391554-ea6f64e6-3486-4e73-a020-a85a743b640f.png)

**Comment by metmarkosaric** [comment]
thanks for reporting this! our developers were able to identify the issue. it seems to be happening on the reports for "today" and "realtime". we're working on a fix and will update here when it's live

**Comment by metmarkosaric** [comment]
Just a quick update that this fix is now online. You might notice a faster loading dashboard after this change too. Thanks again for reporting it and for helping us make Plausible better for everyone!
