### ISSUE TITLE
Change the world map according to top visitor location

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/analytics#168]
"This is not necessary for all sites but would be a useful personalized feature for sites which for instance get most of their visitors from a single country or from a single region. Focus the map on that top country, state, region, or continent instead of the whole world.

This could work especially well when we implement the accurate location feature request and start displaying cities/states in addition to countries."

([imported from the old roadmap](https://plausible.nolt.io/133))

**Comment by sahilsk11** [comment]
Hi, noticed "when we implement the accurate location feature request and start displaying cities/states"! Was just about to make a feature request for this. Do you have any more info related to this?

**Comment by metmarkosaric** [comment]
See [this](https://github.com/plausible/analytics/issues/102)

**Comment by metmarkosaric** [comment]
Closing this.
