### ISSUE TITLE
Sign-in using Github + Google Auth + Other OpenID

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/analytics#169]
"It would be great if we could sign in using some of the popular authentication providers.

Benefits:

    Convenience for users
    Security for those that use it, as many providers (Github, google) use 2FA. 2FA is so far not supported by Plausible."

([imported from the old roadmap](https://plausible.nolt.io/137))

**Comment by metmarkosaric** [comment]
We have no intention to add any third-party logins. Closing this in favour of #156

**Comment by alexanderadam** [comment]
Maybe the intended reference was [issue 383](https://github.com/plausible/analytics/discussions/383).
I would even say that this issue here is a direct duplicate of it.
