### ISSUE TITLE
'Follow System Theme' isn't working in Chromium

### ISSUE THREAD

**Issue by winux1** [plausible/analytics#1696]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Describe the bug

The 'Follow System Theme' option at the Dashboard Appearance section isn't changing the site's theme to dark when using Chromium on a dark-themed OS but it work perfectly using firefox.

### Expected behavior

The 'Follow System Theme' option at the Dashboard Appearance section is changing the site's theme to dark in Chromium when used on a dark-themed OS.

### Environment

```markdown
- OS: Arch Linux
- Browser: Chromium
- Browser Version: 98.0.4758.102
```

**Comment by metmarkosaric** [comment]
thanks for reporting @winux1! this could be a bug with Linux. i see other websites that support "Follow System Theme" also don't show dark theme on Chrome/Chromium on Linux while for instance Chrome on Android shows dark theme all fine both with Plausible and other sites.

**Comment by metmarkosaric** [comment]
closing this as i've confirmed that it is a bug on chromium linux and not something we can do something about unfortunately. there are several threads on different forums about it and a 3 year old or so bug report on chromium repo itself. one of the links here: https://bugs.chromium.org/p/chromium/issues/detail?id=998903
