### ISSUE TITLE
Invites don't work when registration is disabled

### ISSUE THREAD

**Issue by sergioisidoro** [plausible/analytics#1706]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Describe the bug

When registration is disabled, it's not possible to invite people to Plausible. To invite someone to the platform we need to change the environment variable, invite people, and then re-enable the flag to prevent unauthorised people from creating accounts.

### Expected behavior

While the behaviour is understandable, if a user has a valid invite it should still be possible to register to plausible instance.

The feature for disabling registration (https://github.com/plausible/analytics/issues/86), I thought, was just to prevent random people from creating accounts in the landing page.

Alternatively, we could just add a note in the docs, mentioning that this also applies to valid invites :)

**Comment by metmarkosaric** [comment]
thanks for reporting @sergioisidoro! this is expected behavior when registrations are disabled.

**Comment by jesperordrup** [comment]
@ukutaht could you reopen this? 

Is it possible to sponsor fixing this to get it out there to self hosting?

**Comment by ukutaht** [comment]
> @ukutaht could you reopen this?

We keep the issue tracker for unambiguous bugs only. I think this one is on the line between a feature request and a bug report - the system works as designed but the design is too inflexible. Based on this I'll keep this issue closed and treat it as a feature request.

> Is it possible to sponsor fixing this to get it out there to self hosting?

Not with the core team but we might find contributors who would be willing to work for a bounty. @Vigasaurus interested?

**Comment by jesperordrup** [comment]
> > @ukutaht could you reopen this?
> 
> We keep the issue tracker for unambiguous bugs only. I think this one is on the line between a feature request and a bug report - the system works as designed but the design is too inflexible. Based on this I'll keep this issue closed and treat it as a feature request.
> 
> > Is it possible to sponsor fixing this to get it out there to self hosting?
> 
> Not with the core team but we might find contributors who would be willing to work for a bounty. @Vigasaurus interested?

Ok, I've emailed @Vigasaurus and hopefully we get it done. It only makes sense if you're willing to make a release just after test success?

Also this is what I believe is required in high level description:

* Environment option, change.from true false to
switch between: no reg, allow, invite only.

* Update logic to allow register when invite only.

**Comment by genox** [comment]
Sorry for bumping this. :) Has there been any progress on this front? I just ended up in the same situation - trying to invite someone to a project with general registration being closed. IMHO it makes a lot of sense to have the option of an invite-only instance. We want to invite team members but not allow anybody to register and add sites at random.

**Comment by ruslandoga** [comment]
@genox 👋

Yes, it has been implemented and released in v1.5. You configure it by setting `DISABLE_REGISTRATION=invite_only`.

**Comment by genox** [comment]
Wonderful, thanks so much!

**Comment by stefanv** [comment]
Should this be added to the README?

**Comment by ruslandoga** [comment]
@stefanv 👋

It'd probably won't make it to the README since it's not about self-hosting, but I'll open a PR to update https://plausible.io/docs/self-hosting-configuration#server tomorrow.

**Comment by stefanv** [comment]
Thanks @ruslandoga!

**Comment by melker** [comment]
To me, as a new user testing plausible I think that invite_only should be the default option, as this is how I expect it to behave.

**Comment by ruslandoga** [comment]
👋 @melker 

Good point! I'll open a PR to update the default.
