### ISSUE TITLE
Is there any way to breakdown an event prop and filter by another event prop?

### ISSUE THREAD

**Issue by margox** [plausible/analytics#1709]
I am building a simple CMS, and I want all my analytic stuffs could be done by plausible, in my project, I need to know the most frequent visitors of an article, and when someone view an article, an event will be trigged like below:
```javascript
window.plausible('viewArticle', {
  props: {
    userId: 'user_1',
    articldId: 'article_1'
  }
})
``` 
I can breakdown the `viewArticle` event by `props.userId` and filter by `props.userId`, or  breakdown by `props.articldId` and filter by `props.articldId` , but cannot breakdown by one prop but filter by another prop,  seems that the filters only applied to the breakdown result?

I just want to know if there is any other solution for my problem, if no, I will change my project design to avoid this problem.

Thanks :)

**Comment by metmarkosaric** [comment]
thanks for the feedback @margox! this is not currently possible unfortunately. there's a thread on this topic where you can find more info: https://github.com/plausible/analytics/discussions/846
