### ISSUE TITLE
** (ArithmeticError) bad argument in arithmetic expression

### ISSUE THREAD

**Issue by ukutaht** [plausible/analytics#1729]
### Discussed in https://github.com/plausible/analytics/discussions/1714

This should work

<div type='discussions-op-text'>

<sup>Originally posted by **kumfo** February 25, 2022</sup>
when I request the API path to stats goal, it response error:

* API path: `/api/stats/:site/pages`
* payload: 
```
period: 30d
date: 2022-02-25
filters: {"goal":"viewed","props":{"user_id":"1111"}}
```

* response:
```json
{"error":"** (ArithmeticError) bad argument in arithmetic expression"}
```

deploy with docker by latest tag

Thanks</div>

**Comment by kumfo** [comment]
When I post custom event, I also submitted the `pageview` event. I found it work. but now, I have a new problem, it can't load next page😂，I don't know what it happen.
