### ISSUE TITLE
Support client-side routing (for SPAs)

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/analytics#173]
"It would be awesome if Plausible supported tracking client-driven routing for my single-page application.

Right now it only seems to track the root (/) URL, which is fine for general traffic, but it would be nice if Plausible was able to track when a user was at /#/about (or something like that).

Plausible does automatically trigger pageviews based on pushState and popState events. What is missing however is support for hash-based routing.

My guess is that new pageviews are triggered each time you navigate on your site. Just they all get counted as / because we don’t consider the hash part of the url as being part of the pathname. Can you confirm by navigating around and seeing if pageviews are triggered in the network tab?

So I can confirm that the pageview events are being sent on each navigation, but it sends the url as the bare /, which is probably why all my page views are on that page and not my hash-based router.

Eventually I will move away from hash-based routing on my site, but for now I’m sort of tied to it."

([imported from the old roadmap](https://plausible.nolt.io/141))

**Comment by himynameisdave** [comment]
Hey just wanted to note that I was the original poster of this issue on the roadmap, and I'd be happy to provide any additional details about my routing setup if that helps us debug this. 

Thanks!

**Comment by ukutaht** [comment]
Hey, thanks for the request :)

I think it's pretty clear but I found an older request for hash-based routing. Closing in favor of #129
