### ISSUE TITLE
Cannot read properties of null (reading 'getAttribute')

### ISSUE THREAD

**Issue by koraniar** [plausible/analytics#1741]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Describe the bug

I am just implementing the script in the `<head>` tag
```
<script defer data-domain="myDomain.com" src="https://plausible.io/js/plausible.outbound-links.compat.js"></script>
```
But it does not report information and throws an error in the console:
```
plausible.outbound-links.compat.js:1 Uncaught TypeError: Cannot read properties of null (reading 'getAttribute')
    at plausible.outbound-links.compat.js:1:108
    at plausible.outbound-links.compat.js:1:1855
```

### Expected behavior

It should work

### Screenshots

<img width="561" alt="Screen Shot 2022-03-08 at 21 08 06" src="https://user-images.githubusercontent.com/17574419/157358929-8edcc649-ab22-4eb5-b655-56a576071b72.png">
<img width="1243" alt="Screen Shot 2022-03-08 at 21 08 38" src="https://user-images.githubusercontent.com/17574419/157358935-d6ed822b-a173-4ee4-a135-0493f6e6ed1e.png">

### Environment

```markdown
- OS: MacOS
- Browser: Chrome
- Browser Version: 99.0.4844.51
```

**Comment by RobertJoonas** [comment]
Hi @koraniar!

Using the `compat` script extension, you should also add `id="plausible"` to your snippet. This is also stated in the docs: https://plausible.io/docs/script-extensions#plausiblecompatjs

**Comment by koraniar** [comment]
Hello @metmarkosaric,

Thanks!, I though it was only for Internet Explorer, it is working now.

**Comment by metmarkosaric** [comment]
thanks for the update @koraniar!
