### ISSUE TITLE
[bug] calculate_cr has error

### ISSUE THREAD

**Issue by kumfo** [plausible/analytics#1748]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Describe the bug

FilePath: `/lib/plausible_web/controllers/api/stats_controller.ex`

```elixir
  defp calculate_cr(unique_visitors, converted_visitors) do
    if unique_visitors > 0,
      do: Float.round(converted_visitors / unique_visitors * 100, 1),
      else: 0.0
  end
```
I'm not good at elixir development language, So, I don't known what happen. But I found  `converted_visitors` is `nil` when I request API with page > 1.

Example:

```elixir
calculate_cr(1,nil)
```

And it will be throw error:
```
** (ArithmeticError) bad argument in arithmetic expression
```

I found this problem because I requested the `/api/stats/:domain/pages`  interface to get the next page with goal and breakdown by my custom props.

Here is error log:
```shell
** (exit) an exception was raised:

** (ArithmeticError) bad argument in arithmetic expression

(plausible 0.0.1) lib/plausible_web/controllers/api/stats_controller.ex:494: PlausibleWeb.Api.StatsController.calculate_cr/2

(plausible 0.0.1) lib/plausible_web/controllers/api/stats_controller.ex:615: anonymous fn/3 in PlausibleWeb.Api.StatsController.add_cr/3

(elixir 1.12.2) lib/enum.ex:1582: Enum."-map/2-lists^map/1-0-"/2

(plausible 0.0.1) lib/plausible_web/controllers/api/stats_controller.ex:344: PlausibleWeb.Api.StatsController.pages/2

(plausible 0.0.1) lib/plausible_web/controllers/api/stats_controller.ex:1: PlausibleWeb.Api.StatsController.action/2

(plausible 0.0.1) lib/plausible_web/controllers/api/stats_controller.ex:1: PlausibleWeb.Api.StatsController.phoenix_controller_pipeline/2

(plausible 0.0.1) lib/plug/error_handler.ex:65: PlausibleWeb.Api.StatsController.call/2

(phoenix 1.5.13) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
```

### Expected behavior

I want it work correctly。

I think it can be
```elixir
def calculate_cr(unique_visitors, converted_visitors) do
      if unique_visitors !== nil && converted_visitors !== nil && unique_visitors > 0,
         do: Float.round(converted_visitors / unique_visitors * 100, 1),
         else: 0.0
    end
```

### Environment

```markdown
- OS:
- Browser:
- Browser Version:
```

**Comment by kumfo** [comment]
I found it at 1.4.4, I review the newest code I it fixed

**Comment by metmarkosaric** [comment]
thanks for the update @kumfo!

**Comment by kumfo** [comment]
> thanks for the update @kumfo!

you are welcome，Cound you publish a new version to docker?😂The version of 1.4.4 is to old. 

And I use custom gold to realize some business statistics. I find that if too many gold are saved, there seems to be a performance problem.

Example, I created an event like `viewed`, and I use `user_id` field to record everyone's article views, the statistics will be slowly, sometimes Clickhouse will report the error of connection timeout.

**Comment by metmarkosaric** [comment]
self-hosted is a long term release and it's published approximately twice per year so latest features won't be immediately available as they're battled-tested in the cloud first. there should be a new self-hosted release over the next couple of months hopefully

**Comment by kumfo** [comment]
Thank you
