### ISSUE TITLE
Diplay the day of the week on chart x-axis labels

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/analytics#175]
"It’s nice to know at a glance that, for example, “14 June” was a Sunday. So when I see a dip in traffic I can quickly realize that everyone was AFK and it’s nothing to be worried about. 😎"

([imported from the old roadmap](https://plausible.nolt.io/147))

**Comment by chadwhitacre** [comment]
Why @jerodsanto, fancy meeting you here. :)
