### ISSUE TITLE
Multiple users and roles for the same account

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/analytics#176]
"As a company, giving out the username and password to every employee which needs to access the data is not very friendly, also we don’t want all employees to see all properties, plus if someone leaves, we have to reset the password and update everyone with the new passport… Please give the option of multiple users 😍"

([imported from the old roadmap](https://plausible.nolt.io/148))

**Comment by metmarkosaric** [comment]
From #327 :

Two roles would be sufficient:

* Admin, everything is allowed (including removing another admin)
* Viewer, a read-only access to the account

**Comment by Eptis** [comment]
I'm interested in contributing to this feature. If I understand correctly, this feature is about allowing multiple accounts under a site with different permission settings based on a Role model. This feature would involve:

- [ ] Adding a `role` property to the `membership` model/table which could contain either "ADMIN" or "VIEWER"
- [ ] Add an endpoint to allow the invitation of users to a site with a given Role. Calling this multiple times for the same user should send a re-invite.
- [ ] Add an endpoint to allow the updating of user roles of a site. It should only be allowed by an ADMIN.
- [ ] Add an endpoint to remove a user from a site.It should only be allowed by an ADMIN.
- [ ] Update the UI to allow the invitation of users to a site, with a given Role
- [ ] Update the UI to allow the editing of users of a site. It should allow an ADMIN to change the roles of certain accounts
- [ ] Update the UI to allow the removal of users of a site. It should only be allowed by an ADMIN.

I based this on a quick glance through the codebase so not sure if this list is comprehensive.

**Comment by ukutaht** [comment]
@Eptis That looks good to me.

I could see some sort of support for teams/organizations as well but that can be added on top later on.

We also need to think about how this feature interacts with the billing system on Plausible Cloud. When there are multiple admins on a site, who gets billed for it? I'm thinking that we need an 'OWNER' role with a rule being that every site has one and only one owner.

**Comment by Eptis** [comment]
Good point. I think using 'OWNER' as a role might be problematic in terms of ensuring only 1 account is used for billing, but I could be mistaken. Would a new relation similar to membership be an option? 'Ownership' could be introduced in a separate table. What do you think?

**Comment by Eptis** [comment]
A different option would be to store the Account ID that Owns the site itself but that might mix concerns

**Comment by Eptis** [comment]
Also, what is the best way to run all the databases required 😬 ?

**Comment by ukutaht** [comment]
@Eptis You're right, I like your idea of adding a `owner_id` to the site record so we can enforce the constraint on the db level.

We would need the app then to make sure that the owner is never deleted from the list of members.

> Also, what is the best way to run all the databases required 😬 ?

I run postgres on my MacOs natively via homebrew and Clickhouse via Docker: https://hub.docker.com/r/yandex/clickhouse-server/

If you're going to get set up on your machine, would it be too much to ask to also document the process? I'd love to offer a `CONTRIBUTING.md` doc to new contributors like yourself. Don't feel obligated to write the doc but it would be a great help :)

**Comment by Eptis** [comment]
Ok owner_id it is!

I'll document the process and maybe add a makefile to hide-away some of the docker commands to run it.

**Comment by Eptis** [comment]
I think I missed something in the TODO list above. I believe it should also allow the invitation of users and allow them to register a new account. Is there already something in place for this?

**Comment by metmarkosaric** [comment]
True, as an admin you would need to be able to invite people to the account. We don't have that functionality at this stage.

**Comment by Eptis** [comment]
I made a first attempt as this feature but the size and impact of it are becoming larger and larger. Also I don't have time until next year to work on this. Maybe this is useful for you and you (or someone else) could continue the effort. I made a draft PR here: https://github.com/plausible/analytics/pull/432
