### ISSUE TITLE
[Bug on plausible website] Error showing custom event goal

### ISSUE THREAD

**Issue by bencresty** [plausible/analytics#1789]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Describe the bug

Yesterday I opened this issue, but today I was unhappily surprised that somebody without even asking just closed this issue and converted this to a discussion while it's clearly a bug. It seems like the issue is not even read, because it's also suddenly placed in the 'selfhosting' category while it's obviously not about that, but a bug on the plausible website where we view the analytics and was working before.

Please fix this issue. We pay for Plausible every month and expect things to keep working, not suddenly break what was working for at least a year.

--

When clicking on a custom event an endless wait cursor appears and the data never shows. This was working fine in previous versions of Plausible. The code on our website didn't change and is not sending other data so something on the Plausible website did change.

### Expected behavior

Plausible to keep working as before, not suddenly crash on a feature that worked in all previous versions for at least a year.

### Screenshots

![screenshot-issue](https://user-images.githubusercontent.com/69322733/159875643-b73e46e5-55cd-42b2-9aaf-b83cca632516.png)

### Environment

```markdown
- OS: windows
- Browser: ms edge chromium for instance
- Browser Version: latest (99.0.1150.46 (Official build) (64-bit))
```

**Comment by metmarkosaric** [comment]
thanks for sharing @bencresty! if this is an issue with your Plausible account, then it's best to [contact our customer support](https://plausible.io/contact) directly so we can take a look. if you prefer that we deal with it here on GitHub, please do share the website, goal name and account that this happens for and we will take a look. thanks!

**Comment by metmarkosaric** [comment]
hi @bencresty! do you still experience this issue?

**Comment by metmarkosaric** [comment]
closing this as cannot replicate the issue but please do share more details if this happens again. thanks!
