### ISSUE TITLE
404 when trying to delete sites via API

### ISSUE THREAD

**Issue by theprometeus** [plausible/analytics#1792]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Describe the bug

When I try to do a `DELETE` request to `/api/v1/sites/website.domain`, Plausible returns 404 instead of attempting to delete the site.

### Expected behavior

For the site to be deleted.

### Screenshots

![image](https://user-images.githubusercontent.com/3390576/159963277-9479ca03-0d12-4daf-9e46-b9a9573fefcb.png)

### Environment

```markdown
- OS: Ubuntu
```

**Comment by ukutaht** [comment]
Are you on self-hosted? I'm asking because this feature is not released there yet.

**Comment by theprometeus** [comment]
> Are you on self-hosted? I'm asking because this feature is not released there yet.

Yes, I'm using the self-hosted version.

**Comment by theprometeus** [comment]
I didn't get why it was closed since I can create a website using the API but can't delete it and the documentation says I can actually delete it.

If it's not available for everyone at the moment(only for the cloud version), it should be clear in the documentation, but there's nothing saying about it.

![image](https://user-images.githubusercontent.com/3390576/160007128-761f2f0c-ee55-42bd-90e4-e93acf31bed3.png)

**Comment by metmarkosaric** [comment]
hi @theprometeus! it was closed because the feature to delete sites via API is not available in the latest self-hosted release which is why you get the error message. self-hosted is a long term release and it's released twice per year or so which means that latest features may take months before they get there. our docs are based on the Plausible Analytics cloud which has all the latest features. [there are release notes for self-hosted](https://github.com/plausible/analytics/releases) which tell you what features are available. anything not mentioned there means that it is not available

**Comment by ukutaht** [comment]
> If it's not available for everyone at the moment, but only for the cloud version, it should be clear in the documentation, and there's nothing saying about it.

Sorry about that @theprometeus. We are discussing how we could version the docs so it's clear which feature is available in which version. For now you can check the [changelog](https://github.com/plausible/analytics/blob/master/CHANGELOG.md) which shows new stuff that isn't in a numbered release yet.

**Comment by theprometeus** [comment]
> self-hosted is a long term release and it's released twice per year or so which means that latest features may take months before they get there.

Oh okay,, now I got it.


> We are discussing how we could version the docs so it's clear which feature is available in which version.

Maybe just a tag with every endpoint could be nice.
