### ISSUE TITLE
Daily timeline chart fail to load: FunctionClauseError

### ISSUE THREAD

**Issue by mef** [plausible/analytics#1803]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Self-hosting

### Describe the bug

The following error sometimes happens when looking at the daily view of a low-traffic website.

* The timeline chart data is not shown. Spinners keep being displayed.
* No error message is shown in the page.
* Error 500 returned by the API call to `https://[redacted].com/api/stats/my.site/main-graph?period=day&date=2022-03-28&filters={}` Error log shown below:

```
** (FunctionClauseError) no function clause matching in String.replace/4

Uncaught (in promise) ApiError: ** (FunctionClauseError) no function clause matching in String.replace/4
    an https://[redacted]/js/dashboard-30df7c8f675d52883013f6b10c56c737.js?vsn=d:2
    r https://[redacted]/js/dashboard-30df7c8f675d52883013f6b10c56c737.js?vsn=d:2
    r https://[redacted]/js/dashboard-30df7c8f675d52883013f6b10c56c737.js?vsn=d:2
    o https://[redacted]/js/dashboard-30df7c8f675d52883013f6b10c56c737.js?vsn=d:2
    gn https://[redacted]/js/dashboard-30df7c8f675d52883013f6b10c56c737.js?vsn=d:2
    promise callback*gn/< https://[redacted]/js/dashboard-30df7c8f675d52883013f6b10c56c737.js?vsn=d:2
    promise callback*gn https://[redacted]/js/dashboard-30df7c8f675d52883013f6b10c56c737.js?vsn=d:2
    value https://[redacted]/js/dashboard-30df7c8f675d52883013f6b10c56c737.js?vsn=d:2
    value https://[redacted]/js/dashboard-30df7c8f675d52883013f6b10c56c737.js?vsn=d:2
    observer https://[redacted]/js/dashboard-30df7c8f675d52883013f6b10c56c737.js?vsn=d:2
    value https://[redacted]/js/dashboard-30df7c8f675d52883013f6b10c56c737.js?vsn=d:2
    ul https://[redacted]/js/dashboard-30df7c8f675d52883013f6b10c56c737.js?vsn=d:2
    ws https://[redacted]/js/dashboard-30df7c8f675d52883013f6b10c56c737.js?vsn=d:2
    unstable_runWithPriority https://[redacted]/js/dashboard-30df7c8f675d52883013f6b10c56c737.js?vsn=d:2
    Ko https://[redacted]/js/dashboard-30df7c8f675d52883013f6b10c56c737.js?vsn=d:2
    xs https://[redacted]/js/dashboard-30df7c8f675d52883013f6b10c56c737.js?vsn=d:2
    ls https://[redacted]/js/dashboard-30df7c8f675d52883013f6b10c56c737.js?vsn=d:2
    ns https://[redacted]/js/dashboard-30df7c8f675d52883013f6b10c56c737.js?vsn=d:2
    Hs https://[redacted]/js/dashboard-30df7c8f675d52883013f6b10c56c737.js?vsn=d:2
    Xs https://[redacted]/js/dashboard-30df7c8f675d52883013f6b10c56c737.js?vsn=d:2
    us https://[redacted]/js/dashboard-30df7c8f675d52883013f6b10c56c737.js?vsn=d:2
    Xs https://[redacted]/js/dashboard-30df7c8f675d52883013f6b10c56c737.js?vsn=d:2
    render https://[redacted]/js/dashboard-30df7c8f675d52883013f6b10c56c737.js?vsn=d:2
    <anonymous> https://[redacted]/js/dashboard-30df7c8f675d52883013f6b10c56c737.js?vsn=d:2
    n https://[redacted]/js/dashboard-30df7c8f675d52883013f6b10c56c737.js?vsn=d:2
    <anonymous> https://[redacted]/js/dashboard-30df7c8f675d52883013f6b10c56c737.js?vsn=d:2
    n https://[redacted]/js/dashboard-30df7c8f675d52883013f6b10c56c737.js?vsn=d:2
    <anonymous> https://[redacted]/js/dashboard-30df7c8f675d52883013f6b10c56c737.js?vsn=d:2
    <anonymous> https://[redacted]/js/dashboard-30df7c8f675d52883013f6b10c56c737.js?vsn=d:2
dashboard-30df7c8f675d52883013f6b10c56c737.js:2:736540
```

This keeps happening throughout the whole day, from any device trying to access to the page.

This looks very much like #797.

### Expected behavior

* The daily traffic statistics are displayed.
* No error message pops up in the developer console.
* Whenever something goes wrong during an API call, a user friendly error message is shown in the page (nice to have)

### Environment

```markdown
- OS: Linux and Android
- Browser: Firefox
- Browser Version: Latest
```

**Comment by ukutaht** [comment]
Hey, thanks for reporting. What version are you running?

**Comment by mef** [comment]
Where can the version number be found? I do not see it neither in the web interface, nor in the files in plausible directory

Plausible was installed in October 2021, using the latest released version at that time.

`git log` shows that the following commit is the latest:

> commit dcd6f5d7376ed23e77cea8e9a922df707da7186a
> Merge: 70a5eb1 0b66365
> Author: Uku Taht <Uku.taht@gmail.com>
> Date:   Mon Aug 23 11:53:46 2021 +0300
> 
>     Merge pull request #38 from navjotjsingh/restart
>     
>     Add Restart Ability to all the Containers

**Comment by mef** [comment]
Thanks.

Where can the version number be found? I do not see it neither in the web interface, nor in the files in plausible directory

Plausible was installed in October 2021, using the latest released version at that time.

`git log` shows that the following commit is the latest:

> commit dcd6f5d7376ed23e77cea8e9a922df707da7186a
> Merge: 70a5eb1 0b66365
> Author: Uku Taht <Uku.taht@gmail.com>
> Date:   Mon Aug 23 11:53:46 2021 +0300
> 
>     Merge pull request #38 from navjotjsingh/restart
>     
>     Add Restart Ability to all the Containers

**Comment by metmarkosaric** [comment]
thanks for reporting! we cannot replicate this issue unfortunately. please do update to the latest version [v1.4.4](https://github.com/plausible/analytics/releases/tag/v1.4.4) that was released in January 2022 as the October 2021 version is now outdated and let us know if you still get this issue.

**Comment by mef** [comment]
Thanks. I just updated plausible, let's see how it goes :)
