### ISSUE TITLE
IP Geolocation by DB-IP will be always shown even if geoip enabled?

### ISSUE THREAD

**Issue by Showfom** [plausible/analytics#1804]
https://github.com/plausible/analytics/blob/383bba947eade19fbb05c326041b369cf7b8eca2/assets/js/dashboard/stats/locations/map.js#L133

Seems the text `IP Geolocation by DB-IP` will be always shown on Countries Map section, even if we have enabled maxmind geoip2?

Is there any way to check if geoip2 is working or not?

**Comment by ukutaht** [comment]
Sorry yes. It will always show the notice even if you've changed the database. It's a bit silly, I'll try to improve it for the next release

**Comment by ruslandoga** [comment]
@Showfom 👋

I think the issue should be resolved in [`v1.5.0-rc.0`](https://github.com/plausible/analytics/discussions/2324):

- [database type is checked before rendering the page, and whether it's dbip](https://github.com/plausible/analytics/blob/2c2f710d249d140515bd95d765cd3a96b6fb85d4/lib/plausible_web/controllers/stats_controller.ex#L313-L323)
- [`is_dbip` is passed to the template as a `data-is-dbip` attribute](https://github.com/plausible/analytics/search?q=is_dbip)
- [`dataset.isDbip` is then used in JS to decide whether to render the notice](https://github.com/plausible/analytics/search?q=isDbip)
