### ISSUE TITLE
The curl sample in https://plausible.io/docs/events-api returns 400 status code.

### ISSUE THREAD

**Issue by andyj2022** [plausible/analytics#1805]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

The curl sample in https://plausible.io/docs/events-api returns 400 status code.

`curl -i -X POST https://plausible.io/api/event -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36 OPR/71.0.3770.284' -H 'X-Forwarded-For: 127.0.0.1' -H 'Content-Type: application/json' --data '{"name":"pageview","url":"https://plausible.io","domain":"plausible.io","screen_width":1666}'`

Returns 400 error "Bad Request".

Making any POST /api/event test from any browser (Chrome, Firefox), it always return CORS error, and it seems to be produced because "access-control-allow-headers" from "plausible.io" does not allow sending "X-Forwarded-For":

`access-control-allow-headers: Authorization,Content-Type,Accept,Origin,User-Agent,DNT,Cache-Control,X-Mx-ReqToken,Keep-Alive,X-Requested-With,If-Modified-Since,X-CSRF-Token`

### Expected behavior

Return ok status code.

### Environment

```markdown
- OS: Ubuntu 20.04
- Browser: Firefox, Chrome
- Browser Version: Latest.
```

**Comment by ukutaht** [comment]
Not for me. Any idea how I could replicate your problem?

```
➜  analytics git:(master) curl -i -X POST https://plausible.io/api/event -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36 OPR/71.0.3770.284' -H 'X-Forwarded-For: 127.0.0.1' -H 'Content-Type: application/json' --data '{"name":"pageview","url":"https://plausible.io","domain":"plausible.io","screen_width":1666}'
HTTP/2 202 
date: Tue, 29 Mar 2022 10:08:31 GMT
content-type: text/plain; charset=utf-8
content-length: 2
server: BunnyCDN-SE1-725
cdn-pullzone: 682664
cdn-uid: 153cb5b1-399a-48ef-b5bf-098c03770254
cdn-requestcountrycode: EE
access-control-allow-credentials: true
access-control-allow-origin: *
cache-control: must-revalidate, max-age=0, private
permissions-policy: interest-cohort=()
x-request-id: FuDSIw9tTU50Gq2xJPkD
cdn-proxyver: 1.02
cdn-requestpullsuccess: True
cdn-requestpullcode: 202
cdn-cachedat: 03/29/2022 10:08:31
cdn-edgestorageid: 725
cdn-status: 202
cdn-requestid: 2d91c3c7d381ce25ac4bc59a241e870b

ok% 
```

**Comment by andyj2022** [comment]
Sorry. I was using the wrong version of 'curl' on an Ubuntu virtual machine. To top it off, in the browser tests I was manually setting 'User-Agent' and 'X-Forwarded-For', which is prohibited.

**Comment by ukutaht** [comment]
No worries :)

**Comment by ukutaht** [comment]
Isn't flutter a framework for mobile apps? I haven't heard of flutter apps running in browsers.

What `Content-type` does the flutter plugin send?

**Comment by ukutaht** [comment]
> Content-Type to application/json; charset=utf-8

Try changing the content-type to `text/plain`. That's what we do in the official client to avoid OPTIONS request.
