### ISSUE TITLE
Feature Request: Be able to see the breakdown by prop type

### ISSUE THREAD

**Issue by christianlmc** [plausible/analytics#1808]
I want to be able to click on 'HTTP' and see the OS tab breakdown for that selection

![image](https://user-images.githubusercontent.com/24314863/161141263-fac48fb2-acd8-4d87-bd47-6cb8b768e925.png)

What happens instead is that all fields fields unrelated to that disappear, just like the following picture:

![image](https://user-images.githubusercontent.com/24314863/161142134-c0ccbdd2-c102-4de9-9c3f-884633d88bbd.png)

**Comment by metmarkosaric** [comment]
thanks @christianlmc! there's already a thread for this idea. take a look at https://github.com/plausible/analytics/discussions/846. i'll close this one so please do follow the other thread
