### ISSUE TITLE
Make installable as a PWA

### ISSUE THREAD

**Issue by cassidyjames** [plausible/analytics#181]
It would be awesome if Plausible was installable as a progressive web app (PWA); this would make it easier to check analytics on Android, Windows, etc. by giving us a dedicated icon on the home screen.

**Comment by cassidyjames** [comment]
Ah, there is probably some overlap with #93 here as well; one of my complaints with the current setup is that there is no icon when adding to my home screen with both Chrome and Firefox Preview on Android. The title was also the entire title tag from HTML instead of a shorter one like “Plausible”.

For a PWA at least, you can provide a bunch of great info in a JSON manifest: https://developer.mozilla.org/en-US/docs/Web/Manifest

I'm not sure if iOS will also use any of that or not.

**Comment by Kulcanhez** [comment]
iOS doesn't like manifest but it will use the icon 🚀
