### ISSUE TITLE
Getting occasional 502 errors when proxying the script

### ISSUE THREAD

**Issue by kristjanmar** [plausible/analytics#1815]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

I'm using the proxy method to serve the script on my site, but my host is reporting a 502 error every few minutes.

```
2 events matched your Error alert in the past 5 minutes.

502 stockanalysis.com/proxy/api/event/
ROUTER_EXTERNAL_TARGET_CONNECTION_ERROR: An error occurred with this application.
502 stockanalysis.com/proxy/api/event/
ROUTER_EXTERNAL_TARGET_HANDSHAKE_ERROR: An error occurred with this application.
```

There appears to be some kind of connection error between my host (Vercel) and Plausible.

This does not happen on every request, but I get a lot of page requests every minute so enough of these are showing up to be quite noticeably in my logs.

I'm using the next-plausible package to implement the proxy, but I don't think this issue is related to that. It seems to be a server error on Plausible's end.

### Expected behavior

There should not be a 502 error.

### Screenshots

![Screenshot_51](https://user-images.githubusercontent.com/22234692/161908359-ded21d5d-8b8a-41a6-b3f5-d201a808e502.png)

### Environment

```markdown
NextJS on Vercel, using next-plausible.
```

**Comment by metmarkosaric** [comment]
thanks for reporting @kristjanmar! we introduced something new last night so this might have been caused by that. we just did some tweaks to optimize it and it's all looking fine now. could you please check how it looks on your side? thanks again!

**Comment by kristjanmar** [comment]
Thanks for looking into it, I am now getting much fewer errors than before. It's my first time proxying a script through Vercel so maybe occasional errors are expected.

**Comment by kristjanmar** [comment]
Actually I spoke too soon, the issue is still ongoing even though it may have decreased a bit.

![Screenshot_53](https://user-images.githubusercontent.com/22234692/162401544-fde79ac2-0f72-4259-a22a-84cbaa7adf23.png)

**Comment by kristjanmar** [comment]
I've stopped getting these 502 errors in my logs.

However, now I've started to get 431 errors showing up in the browser console.

These errors appear to be preventing any events from being tracked by Plausible.

<img width="809" alt="Screenshot 2022-04-11 at 14 48 50" src="https://user-images.githubusercontent.com/22234692/162689709-e55ca38b-ee1c-442d-b287-972b80e8030f.png">

**Comment by ukutaht** [comment]
The events sends fine for me with a 202 status code on stockanalysis.com

**Comment by metmarkosaric** [comment]
hi @kristjanmar! we've made few more tweaks now. how does it look like now from your side?

**Comment by kristjanmar** [comment]
Yes, it does seem like the errors have disappeared! Thanks for fixing this, I will definitely be continuing with a paid subscription once my trial runs out.

**Comment by metmarkosaric** [comment]
that's nice to hear, thanks for the update @kristjanmar!
