### ISSUE TITLE
Export with goals/filters

### ISSUE THREAD

**Issue by julestran** [plausible/analytics#1823]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Self-hosting

### Describe the bug

I put goals and filters in my dashboard and I want to export this view.

But in my csv file it's stats without filters/goals.

### Expected behavior

When I put filters/goals in my dashboard when I export I must see stats related to those filters/goals.

### Environment

```markdown
- OS: MacOs
- Browser: Chrome
- Browser Version: 100
```

**Comment by metmarkosaric** [comment]
thanks for reporting @julestran! could you please explain what exactly happens? what filter do you have on the dashboard? what do you see in the dashboard with that filter on? what files do you get in the download? did you filter by the goal specifically as you need to do that to get the props data to be downloaded? i just tested it and everything works all fine in the cloud version

**Comment by julestran** [comment]
I put filters and goals in my dashboard like pages or goal pageviews and I want to export those stats.

But in the exports, numbers aren't the same as viewed in the dashboard, it's numbers without filters or goals.

**Comment by metmarkosaric** [comment]
Thanks! This feature is not yet available on the self hosted version, it's only available on the cloud. Self hosted is a long term release and doesn't get all the new features automatically. You can find the changelog here https://github.com/plausible/analytics/blob/master/CHANGELOG.md
