### ISSUE TITLE
Onboarding emails are linking to staging environment

### ISSUE THREAD

**Issue by jeppeliisberg** [plausible/analytics#1830]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

Hi, just signed up and so far I'm impressed by the simplicity and ease of getting started.

The emails I'm getting through the onboarding process have some bugs though - links are pointing to staging.plausible.io instead of plausible.io - here's an example (screenshot): https://share.myphoner.help/qGu7O2px.

### Expected behavior

Links in onboarding emails point to plausible.io

### Screenshots

![image](https://user-images.githubusercontent.com/13498/162783346-b1cde209-bda7-4cf2-899a-34db3e5a1e93.png)

![image](https://user-images.githubusercontent.com/13498/162783551-2d1c37ca-70fb-470a-8baf-1bb3ac4f4721.png)

### Environment

```markdown
- OS: MacOS
- Browser: Firefox
- Browser Version: 98
```

**Comment by metmarkosaric** [comment]
thanks for the kind words @jeppeliisberg and for reporting these bugs! we're getting the GA import finalized for the public launch later this week and these will be fixed alongside it

**Comment by ukutaht** [comment]
Thanks for reporting @jeppeliisberg! It should already be fixed.
