### ISSUE TITLE
Error in the Google Analytics import completed email

### ISSUE THREAD

**Issue by rajbos** [plausible/analytics#1836]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

There is an issue with the "import completed" email after importing Google Analytics stats. 
The @link here should be expanded into a link to my dashboard page I expect?

![image](https://user-images.githubusercontent.com/6085745/163482758-7ac3928e-3504-4a5b-953d-e2a709441f9e.png)

### Expected behavior

No text `@link`, but an actual link for this domain's dashboard.

### Screenshots

Added it in the bug describtion... :-D

### Environment

```markdown
- OS: Not relevant
- Browser: Not relevant
- Browser Version: Not relevant
```

**Comment by ukutaht** [comment]
Hey, thanks for reportint! When did you receive this email? We already fixed this issue

**Comment by rajbos** [comment]
I received this yesterday: 14/04/2022 21:18, UTC +02:00

**Comment by ukutaht** [comment]
Thanks! We had some issues but it's fixed now.
