### ISSUE TITLE
Show site settings on that site's dashboard

### ISSUE THREAD

**Issue by cassidyjames** [plausible/analytics#185]
Unless I'm mistaken, right now you have to go back to the top-level `/sites` page to get to a site's settings, whereas you can always get to your account settings from any site dashboard. It would be handy to be able to get to a site's settings from its dashboard.

**Comment by ukutaht** [comment]
Thanks @cassidyjames. Agreed, this navigation option is sorely missing.

I found an earlier request for this so closing this one in favor of #103
