### ISSUE TITLE
Tring to reach a custom dimension behaviour with props parameter

### ISSUE THREAD

**Issue by kaerer** [plausible/analytics#1869]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Self-hosting

### Describe the bug

Hello, i am tring to reach a behaviour like custom dimensions and calling a custom `plausible` method with the parameters below. The custom method is much simple to just send information.

`
plausible('pageview', {
    props: {
        test: 12345,
        actives: ['test-323790-15826', 'test-323789-15824'],
        tools: [
            {id: '323790', v: '15826', t: 'test'},
            {id: '323789', v: '15824', t: 'test'}
        ]
    },
    callback: function(){console.log('ok')}
});
`
- i notice a meta index but not quite sure its purpose
- my custom plausible method also using `JSON.stringify` for the props

`/api/stats/dummy-page.example.com/property/test`
`/api/stats/dummy-page.example.com/property/actives`
`/api/stats/dummy-page.example.com/property/tools`

so far all the above requests returns same results from browser api which i believe total results.

also tested `?props=%7B"test"%3A"12345"%7D` parameter from panel ui and got 0 results.

### Expected behavior

My aim is actually dividing users with the parameters that i will provide and track their goal conversions. I want to sign the visitors session with those multiple parameters.
In this example if there are 2 active tests are running with the given parameters, i would like to receive the goal conversions `ab-323790-15826` and/or `ab-323789-15824` separately 

### Environment

```markdown
- OS: docker inside centos
- Browser: -
- Browser Version: -
```

**Comment by ukutaht** [comment]
The `props` field is intended to be used with custom event goals. It wasn't designed to work the way you're using it.

We are working on this currently so in the future you'll be able to use custom dimensions as you explained here.

> actives: ['test-323790-15826', 'test-323789-15824']

Unfortunately the `props` value can only be a simple key-value mapping. Complex nested data like lists are not allowed.

**Comment by jdevalk** [comment]
@ukutaht any news on that custom dimensions feature? Could kinda use that to track post types and taxonomies :)

**Comment by ukutaht** [comment]
Sorry no, we are currently focused on system stability and performance.
