### ISSUE TITLE
"No Referrer"

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/analytics#187]
Got questions about the discrepancy between unique visitors and total visitors in the top referrer report via email. It's caused by the direct / dark traffic ([more details in our docs](https://docs.plausible.io/top-referrers#traffic-without-a-referrer-source)).

We asked the community "Would you prefer that we show "No Referrer" in the "Top Referrer" list too?"

[70% on Twitter](https://twitter.com/PlausibleHQ/status/1263141632209235969) and [100% on Mastodon](https://fosstodon.org/@markosaric/104201706283475035) said yes to show No Referrer in the Referrers list.

There are couple of interesting points of view to consider:

It might skew the comparison between all the other sources as "no referrer" will be top for most sites and stand for a lot of traffic while all the other ones might look similar on the bar we show:

1: "I could see something without a bar for comparison with the rest, but just a note somewhere in that view saying: "x number of visitors had no referrer""

It is not an actionable metric:

2: "I just don't find that extra info to be useful or actionable, whereas everything else on-screen is. If I see a certain amount of traffic coming from Google, from Pinterest, and from Cool-Site dot xyz, I can do something with that. I don't know what to do with no referrer numbers"

One interesting option could be not to show it in the main dashboard but to list it when you click on "More" to get the full list of referrers.

**Comment by tckb** [comment]
I actually like the 2nd option: now that I’m test driving plausible, I’d really like to see all referrals including dark traffic.

**Comment by tckb** [comment]
@ukutaht  / @metmarkosaric  I think this is still a valuable insight to know that visitors are arriving to site directly and / or  something wrong the configuration. I have quite low traffic most of the time and these stats makes sense to me so I have WIP fix for this:


case#1  

Click "More" to find "Direct Traffic (no referrer)" 
<img width="779" alt="image" src="https://user-images.githubusercontent.com/939542/87095727-8ea40c80-c241-11ea-8d74-df428a23a197.png">


case#2
Show "Direct Traffic (no referrer)"  when that is the only stat available:

<img width="1140" alt="image" src="https://user-images.githubusercontent.com/939542/87095582-4553bd00-c241-11ea-8776-237d65436cc8.png">

**Comment by ukutaht** [comment]
@tckb 

Thanks for the efforts! I'm testing the PR on our dev server. One thing I wanted to discuss before closing this issue.

Did you intentionally send the 'Direct Traffic' row to the end of the results in the referrers modal? It's a bit difficult to find it when you have a long list of referrers. Example: https://staging.plausible.io/plausible.io/referrers

I'm thinking it might make sense to just include it where it should be in the list, ordered by unique visitors. For almost all websites it means direct traffic would be the 1st referrer.


In the modal it would also be good to see bounce rate and visit duration for direct traffic.

What do you think? I can make those changes unless you think it's a bad idea.

**Comment by tckb** [comment]
@ukutaht Yes this was intentional, pushing the "direct traffic" at the end.  As @metmarkosaric  pointed out that  direct traffic is not an actionable metric, I concur on his opinion too. But for low traffic sites like of mine, I still would like to see it.

Most often this is really large, possibly due to Search engines stripping away the referrer header or for various other reasons and showing this on the very top didn't made a lot of sense, because as the model says **Top Referrers** and direct traffic doesn't fit that bill. This is why I made conscious decision to append this at the end.  


>In the modal it would also be good to see bounce rate and visit duration for direct traffic. 
Yes, I think this was added after I made the changes so yes,  lets add it to make it consistent.  👍

**Comment by metmarkosaric** [comment]
Thanks @tckb! I think the best way to do it would be like this:

1. Don't include "no referrer" on the main dashboard as it is not actionable and by being the largest source for majority of sites it would skew the data and comparison with the other referrers.

2. Include "no referrer" when people click on "more" in the "Top Referrer" chart.

3. List the "no referrer" entry where it naturally fits in the list when ranked by number of visitors.

3. Include all the other stats for the "no referrer" entry such as visitors, bounce rate and visit duration.

4. Include "no referrer" on the main realtime view (without needing to click on "more") as most of the times the majority of realtime visitors would be from "no referrer" and in this case it helps actually understand what's happening on your site right now.

How does that sound?

**Comment by tckb** [comment]
- 1  ✅ 
- 1  ✅ 
- 1  ✅ 
- 1  ✅

**Comment by tckb** [comment]
- 1  ✅ 
- 2  ✅ 
Agreed, but I called it "Direct Traffic" instead of "No referrer" (Either one will work)

- 3  ❓
I am bit differed with this although, placing it naturally in the visitors would make it consistent but, the expectation is to view the referrers, direct traffic/ no referrer wouldn't fit per my understanding. 

- 4  ✅ 
- 5  ✅ 
- 6  ✅ 
Agreed.

**Comment by metmarkosaric** [comment]
2. Perhaps something like "(direct) / (none)" that GA uses could work for us too? Some traffic without referrer is direct (typing into browser, bookmark etc) but majority of it comes from links within apps, emails and other sources without a referrer header.

3. I see what you mean. We're keeping it simple so we don't have traffic split by channels kind of like in GA where they have direct, search, social, referrer separate. We put it all into one list so I wouldn't be too worried that the expectations are to view "referrers" only. We already show different sources such as Google search in the list.

**Comment by tckb** [comment]
2. I prefer _Direct_ that sounds more reasonable. 
3. Sure!

**Comment by TkDodo** [comment]
hey, I just searched for issues on why the direct referrer doesn't show up on the normal view, and I get the rationale behind it. However, I also cannot add a filter to "Direct / None", which would still be a use-case I think.

There is a workaround to make it work:
- Filter for the realtime view
- Direct / None is now shown. Click it.
- Filter for Direct / None is added.
- Now go back to any view you'd like

You can also add `source=Direct+%2F+None` into the url, but it's not visible in the Fiilter dialog:

<img width="451" alt="Screenshot 2021-09-12 at 08 14 43" src="https://user-images.githubusercontent.com/1021430/132974288-5c0981f5-294a-477c-92cd-d746548c5036.png">


Let me know if I should open a new issue instead.

**Comment by ukutaht** [comment]
Ah yes, it should show up in the filter view. Also I can see some dark mode issues on the screenshot :)

Feel free to open a new issue for this. More likely it will get fixed in that case
