### ISSUE TITLE
Docker build fails executor failed 137 error

### ISSUE THREAD

**Issue by madanyang** [plausible/analytics#1870]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Self-hosting

### Describe the bug

I have been using plausible with self compiled docker based on git source on Ubuntu 20.4 arm64 oracle platform.

After the latest git pull which the HEAD is now at 02abbda06 docker file is not building anymore with an error code 
 
**'executor failed running [/bin/sh -c mix release plausible]: exit code: 137'**

I have been using the DOCKER_BUILDKIT=1 option but without it also doesn't build anymore.Previously the build was succesfull and the resulting dockerfile was working fine.

Thanks

### Expected behavior

Docker file should compile successfully

### Screenshots

`=> [buildcontainer 11/20] RUN npm install --prefix ./assets &&     npm install --prefix ./tracker                                                                                     38.5s
=> [buildcontainer 12/20] COPY assets ./assets                                                                                                                                         0.3s
=> [buildcontainer 13/20] COPY tracker ./tracker                                                                                                                                       0.1s
=> [buildcontainer 14/20] COPY config ./config                                                                                                                                         0.1s
=> [buildcontainer 15/20] COPY priv ./priv                                                                                                                                             0.4s
=> [buildcontainer 16/20] COPY lib ./lib                                                                                                                                               0.2s
=> [buildcontainer 17/20] RUN npm run deploy --prefix ./assets &&     npm run deploy --prefix ./tracker &&     mix phx.digest priv/static &&     mix download_country_database &&    133.5s
=> [buildcontainer 18/20] WORKDIR /app                                                                                                                                                 0.4s
=> [buildcontainer 19/20] COPY rel rel                                                                                                                                                 0.2s
=> ERROR [buildcontainer 20/20] RUN mix release plausible                                                                                                                             60.7s
------
> [buildcontainer 20/20] RUN mix release plausible:
#30 2.579 Compiling 127 files (.ex)
#30 20.37 Compiling lib/plausible_web/plugs/tracker.ex (it's taking more than 10s)
------
executor failed running [/bin/sh -c mix release plausible]: exit code: 137`

### Environment

```markdown
- OS: "20.04.4 LTS (Focal Fossa)" 5.13.0-1027-oracle aarch64 GNU/Linux
```

**Comment by metmarkosaric** [comment]
thanks for reporting @madanyang! the latest releases such as the one you tried to install are meant for our managed hosting in the cloud and are not meant for self-hosting. please only use the latest self-hosted release when self-hosting as these types of issues are expected to happen when using non-supported releases. see the latest self-hosted release here: https://github.com/plausible/analytics/releases
