### ISSUE TITLE
Wrong City "Innenstadt I"

### ISSUE THREAD

**Issue by vstollen** [plausible/analytics#1875]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

Today, we had a visitor from City "Innenstadt I" (ID 6946225), which is German for "inner city 1". I'd guess this might be related to the [district/borough level data](https://github.com/plausible/analytics/issues/1582#issue-1092383145). 

### Expected behavior

Instead the actual city name should be shown.

### Environment

```markdown
- OS: Manjaro Linux 21.2.6 Qonos, Kernel: 5.10.109-1-MANJARO
- Browser: Firefox
- Browser Version: 99.0.1
```

**Comment by ukutaht** [comment]
Yes this is the issue with district level data. Thanks for reporting!
