### ISSUE TITLE
Check the mobile overflow on the home page

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/analytics#1879]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

On our home page on the mobile, you can scroll right. 

Most of the times easily solvable with

`body { overflow-x: hidden; }`

([reported on twitter](https://twitter.com/wolfgegenlicht/status/1521067195928924160))

### Expected behavior

should not be able to view the empty area on the right

### Environment

```markdown
- OS:
- Browser:
- Browser Version:
```

**Comment by hooch** [comment]
It is the pricing table that overflows the x-axis.

<img width="1114" alt="Screen Shot 2022-05-20 at 8 38 39 pm" src="https://user-images.githubusercontent.com/987814/169511929-beb06f66-0571-4a00-9bce-b3ac0efc65cd.png">
