### ISSUE TITLE
Clickhouse issues: never used it an not sure if its configured correctly?

### ISSUE THREAD

**Issue by mannp** [plausible/analytics#188]
Firstly, excellent job, thanks for creating plausible.

I am trialing your hosted version for my new website, but wanted to have a test with the self hosted version too :)

I am trying to get it securely configured, so added a password using the env variable CLICKHOUSE_DATABASE_PASSWORD and the intial setup created the db, but now it gives me the following error;

> 18:32:28.550 [error] Clickhousex.Protocol (#PID<0.4623.0>) failed to connect: ** (ErlangError) Erlang error: :connect_timeout

Should this env be used on the plausible or clickhouse docker?

Also, the docs mention increasing the CLICKHOUSE_DATABASE_POOLSIZE for production but I am unclear the basis to calc the increase?

I upped it to 20 but have since had this error and not sure whether its related to these new env variables.

Finally, can I set the env variables in a /env file? If so, where should it be placed? Is there a **prod.secret.exs**, like some other apps use?

Thanks for any pointers and again thanks for creating plausible.

**Comment by ukutaht** [comment]
Hey, happy to help as much as I can.

Did you get it to work first without a password? That would be a good first step to make sure there aren't any other connectivity problems.

To secure the Clickhouse database with a password, you need to add the password to its configuration file. The `CLICKHOUSE_DATABASE_PASSWORD` is only intended for the plausible docker process to use when connecting to CH.

To set a password on Clickhouse, see the 'Configuration' section and linked documentation here: https://hub.docker.com/r/yandex/clickhouse-server/. Basically, you need to create a user profile configuration as an XML file and add the password there ([example](https://clickhouse.tech/docs/en/operations/configuration-files/#example)). Then mount that file on the CH docker image so it can read the config.

> I upped it to 20 but have since had this error and not sure whether its related to these new env variables.

I don't have a good way to set a 'correct' pool size either. I use 20 myself and it seems to work OK.

> Finally, can I set the env variables in a /env file? If so, where should it be placed? Is there a prod.secret.exs, like some other apps use?

Yes, in my deployment I have a file in $HOME/.env which I use as follows:
```
$ docker run -d --name plausible --env-file .env plausible/analytics
```

Hope this helps. Let me know how it goes!

**Comment by tckb** [comment]
To add what uku has commented -- 

> I am trying to get it securely configured, so added a password using the env variable CLICKHOUSE_DATABASE_PASSWORD and the intial setup created the db, but now it gives me the following error;
> 
> > 18:32:28.550 [error] Clickhousex.Protocol (#PID<0.4623.0>) failed to connect: ** (ErlangError) Erlang error: :connect_timeout

Lets get the basics right first, Is your ch server running locally? If you so, did yo configure `CLICKHOUSE_DATABASE_HOST` ? It would help if you share your env variables (of course, mask what is not needed) 

> Should this env be used on the plausible or clickhouse docker?
the env variables are used by Plausible to connect to the database. Configure CH as needed and set the appropriate variables in Plausible. 


> Also, the docs mention increasing the CLICKHOUSE_DATABASE_POOLSIZE for production but I am unclear the basis to calc the increase?
> 
> I upped it to 20 but have since had this error and not sure whether its related to these new env variables.

As mentioned in the doku, higher number is only needed for production servers where you have heavy traffic. For normal cases, 10 is more than sufficient.  This is mostly empirical, choose what makes sense to you. If you don't know what it is, leave it as it. 

> Finally, can I set the env variables in a /env file? If so, where should it be placed? Is there a **prod.secret.exs**, like some other apps use?
**prod.secret.exs**  wouldn't be required, the secrets are configured based on the environment variables. For docker-based deployments, you can use the "env" file as @ukutaht  mentioned.

**Comment by mannp** [comment]
Hi @ukutaht and @tckb thanks for your replies.

Okay so first thing missing from my post was I have it running with bare minimum env variables and traefik 2, sorry reading back that was an oversight :)

I was reading here -> https://github.com/tckb/plausible/blob/master/HOSTING.md and noting there were more env variables available than I was using and wanted to secure things as much as i could, before exposing it.

@ukutaht I was expecting a password in clickhouse and then somewhere to reference it in plausible, so your explanation is very helpful, thanks, as too the env file, as i was thinking it was more complex that it was.

@tckb as I said, should have stated all working fine, but I was trying to harden before exposing.

Okay I didn't see the reference to 'heavy traffic' in the docu, just production, which this is, so hence the reason to query the 'correct' setting here, but @ukutaht helped with the 20....

**Comment by mannp** [comment]
@ukutaht clickhouse user and password seems to work fine, so all in all i think this can be close.

Cheers.

**Comment by ukutaht** [comment]
Great! Do let me know if you have any other questions or suggestions :)
