### ISSUE TITLE
Account registration form issue with comma in the name

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/analytics#1885]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

We've had couple of cases where Spanish people tried to register for a trial account and everything seemingly goes well but no email gets sent and the account is not actually registered in our database. In the Sentry errors, it seems like our registration form doesn't accept names with a comma (both of these cases had a comma in their names and removing the comma fixed the issue). I'm not sure if perhaps some other special characters are not supported either?

Would be nice if we either have a way to support these characters in the name field or perhaps easier that we give an error message for people so they know that the registration is not completed and that they can try entering their name without the comma.

### Expected behavior

Names with special characters should work too

### Environment

```markdown
- OS:
- Browser:
- Browser Version:
```

**Comment by metmarkosaric** [comment]
just looked up a couple of names reported to cause this issue and i can reproduce it. sentry error shows up. can you try with a name like `João Random Name, Second` and `Sr. First Second, OCD`

**Comment by ukutaht** [comment]
Gotcha, the issue is caused by Postmark parsing the comma in a special way. More information here: https://github.com/symfony/symfony/issues/39416
