### ISSUE TITLE
(none) Event when adding props dynamically

### ISSUE THREAD

**Issue by guttermouth99** [plausible/analytics#1888]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

I am trying to create event props dynamically. The props are also getting tracked however I also get the event (none) always in my stats. I have tried multiple ways now to add a new key to the props object. However, I always get the (none) event. Everything works fine when I use hardcoded values instead of dynamic prop keys. 

I also read the (none) event happens when passing undefined or null as a value. As you can see in my function below I do a null and undefined check before executing.

I use next-plausible for next.js and react.

```
const trackClick = (from, value) => {
    if (from && value) {
        plausible('MyEvent', {
          props: {
            [from]: value
          }
        })
     }
 } 
```

Thanks for your help.

### Expected behavior

Track all dynamic keys in events without adding (none) as a value.

### Environment

```markdown
- OS: macOs 10.15.7
- Browser: Google Chrome
- Browser Version: 100.0.4896.12
```

**Comment by RobertJoonas** [comment]
Hi @guttermouth99!

The none values will also hop in when you send different sets of property keys with different events. For example these two events:

 1. `plausible('Purchase')`
 2. `plausible('Purchase', props: {amount: 100})`

will create a (none) value in the report. It represents the first event that did not have the property `amount`.

So basically, you should make sure you're "always sending something" as the values of properties that you want to be presented with.

**Comment by guttermouth99** [comment]
Thanks for the clarification. The stats make more sense to me now :) Thanks for your  great work!
