### ISSUE TITLE
It's difficult to distinguish long URLs with a similar structure

### ISSUE THREAD

**Issue by ayoisaiah** [plausible/analytics#1894]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

When viewing the top pages, it can be difficult to distinguish between pages until one hovers on them if they have a similar structure, especially since they are cut off

### Expected behavior

I think it would be nice if the option to switch to the page title (instead of the URL) was present in the UI. 

Another option would be to expand the dialog so that it covers more of the screen.

![Screenshot from 2022-05-09 12-55-36](https://user-images.githubusercontent.com/13372163/167405356-3f98f898-7d3b-46aa-987f-0b887620bfca.png)

### Screenshots

![Screenshot from 2022-05-09 12-48-56](https://user-images.githubusercontent.com/13372163/167404602-ef8bf3bb-1d0a-47e8-80ac-2aec9f9603eb.png)

### Environment

```markdown
- OS: Linux
- Browser: Firefox
- Browser Version: 99
```

**Comment by metmarkosaric** [comment]
thanks for the feedback @ayoisaiah! this is more of a feature request rather than a bug. we keep this issues list to bugs only. you can find a thread discussing this specific feature idea already here: https://github.com/plausible/analytics/discussions/1448

**Comment by ayoisaiah** [comment]
Alright, we can continue the discussion there, thanks!

**Comment by metmarkosaric** [comment]
thanks!
