### ISSUE TITLE
Documentation Gap - tracker data-api attribute

### ISSUE THREAD

**Issue by AxelTheGerman** [plausible/analytics#1899]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Self-hosting

### Describe the bug

I'm using a CDN to proxy the plausible script from my self-hosted instance. Fetching the script works fine, however when it tries to make the `/api/events` call back to Plausible it fails.

Instead of using `https://myhost.com/api/events` it is using `https://mycdn.com/api/events`.

By digging into the code I found https://github.com/plausible/analytics/blob/948de2b4c9850d7dd990d6f6b456496b99cec9ac/tracker/src/plausible.js#L12

So I figured out that I need to add `data-api="https://myhost.com/api/events` to the script tag. I'm using the [manual script extension](https://plausible.io/docs/script-extensions#scriptmanualjs) so I'm not quite sure which script tag needs the attribute. Probably only the one calling the `plausible` function but just in case I added it to all 3.

### Expected behavior

Maybe I missed it, but there should be a "proxy" or "CDN" doc somewhere that mentions this attribute and where to add it.

I'm happy to add it I just don't know where to start - in the Github repo here, the docs website (and where there). If someone has a pointer I'm happy to contribute a PR.

### Environment

```markdown
- OS: all
- Browser: all
- Browser Version: all
```

Thank you for this amazing project!

**Comment by metmarkosaric** [comment]
thanks for the feedback @AxelTheGerman! we have instructions on how to proxy the script here https://plausible.io/docs/proxy/introduction

**Comment by AxelTheGerman** [comment]
Oh sweet, I don't think I came across that one.

I see there are a bunch of docs on specific set ups and all of them (that I checked) instruct to actually proxy both endpoints (fetching the script and posting the event).

As long as the `data-api` attribute is considered a "public API" I'd love to add a comment on the main page that this is an option.

Funny side note: I'm not doing this primarily for ad blockers (as I'm self hosting) but just to offload script serving to my CDN 🙃

**Comment by metmarkosaric** [comment]
i see, thanks! what would be the reason to mention it? we try to keep the docs straightforward and as simple as possible without adding too much stuff that most people don't need. adding too much extra stuff makes everything else more complicated

**Comment by metmarkosaric** [comment]
closing this as we keep this list of issues to actual bugs in the product only. our docs are public too so if you think there's some improvements to be made, please do share there: https://github.com/plausible/docs. thanks!

**Comment by AxelTheGerman** [comment]
Yes that's fair, sorry should have opened an issue there. Will look through the docs if I find a good place to add it.

I agree that the guides should be simple - but having to find options in the code is maybe a bit far the other extreme

**Comment by metmarkosaric** [comment]
yeah, i understand. the data-api attribute is there because of the proxy so it's documented in the proxy section of the docs but perhaps you can find a natural way to mention int in the self hosting docs section too for those that may find it useful for self-hosted without considering a proxy

**Comment by ukutaht** [comment]
I think the 'how-to' guides we have are great and as @AxelTheGerman said I think it would be even better if we also had a reference documentation for the script with all the possible options. Maybe we could expand [this doc page](https://plausible.io/docs/script-extensions) to include all technical information and possibilities with the script, with links back to how-to guides... just a thought.
