### ISSUE TITLE
use beacon api?

### ISSUE THREAD

**Issue by scottjg** [plausible/analytics#190]
i love how small the plausible script is, so i'm a little hesistant to suggest more stuff in it, but it would be nice to use the beacon api instead of xhr. that way, you can shoot off events "in the background", as opposed to having them block the page nav. browser support for this is ok but not supported on IE11 which maybe is a dealbreaker for some of your users. in our case, it isn't though.

i guess in theory you could have different scripts served based on the user agent, though i can see why that would be a hassle to maintain.

**Comment by oliverpool** [comment]
> i'm a little hesistant to suggest more stuff in it

I think that the addition can be quite small, and restricted to the `registerOutboundLinkEvents` mode.


> not supported on IE11

One can make a simple `if(window.navigator.sendBeacon)` to detect its support and fallback to the current "delay method".

---

I would be willing to make a PR for the tracking script if the maintainers are ok with it.

_One thing to be aware, is that `sendBeacon` sends a POST request and I don't know if the backend supports it yet._
