### ISSUE TITLE
Publish tracking code in a npm package

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/analytics#191]
"Could you publish your tracking code in a npm package? It would be great to bundle it in our regular JS bundle to avoid an extra JS bundle download. It avoids a extra http request and it just looks and feels nicer to be in control of the scripts running on the site.

We use Sentry, and Sentry does this. We just install it from npm and import/configure it from JS:
https://docs.sentry.io/platforms/javascript/"

**Comment by Maronato** [comment]
I've published a [tracker package](https://github.com/Maronato/plausible-tracker) to NPM. It supports all of the features from the official script and weights [~700 bytes](https://bundlephobia.com/result?p=plausible-tracker@0.1.11).

- https://github.com/Maronato/plausible-tracker
- https://github.com/Maronato/plausible-tracker

```bash
npm install plausible-tracker
yarn add plausible-tracker
```

**Comment by metmarkosaric** [comment]
Thank you @Maronato! Added this to our list of community integrations so closing the thread: https://docs.plausible.io/community-integrations/

**Comment by metmarkosaric** [comment]
@Maronato what do you think about transferring this to the Plausible repo?

**Comment by Maronato** [comment]
@metmarkosaric that would be great! Do you guys want me to change something about the API before doing so?

**Comment by ukutaht** [comment]
I think it looks great as is! Based on reading the README, I only have two comments:

1. In our code, we treat pageview as one word, so instead of `pageView` or `page_view` it is `pageview`

2. I'm not sure about providing the `url,referrer,deviceWidth` options during initialization. They seem like something that should be specified for each event separately.

**Comment by Maronato** [comment]
@ukutaht good points. I've updated it. Let me know if there is anything else you want me to change.

Also, how do you wanna go about the transfer? I *think* I need write access to the org to properly transfer to it, but you can also republish it if you rather not give me permissions.

**Comment by ukutaht** [comment]
@Maronato Thanks! Very cool

Pretty sure you can start the process of transferring the repository on you end by going to Settings -> Danger Zone -> Transfer repo

**Comment by Maronato** [comment]
@ukutaht I just tried transferring but got:
<img width="521" alt="CleanShot 2020-10-16 at 12 05 48@2x" src="https://user-images.githubusercontent.com/19658460/96275325-f936b800-0fa7-11eb-873f-bb0887b7fe8b.png">

**Comment by metmarkosaric** [comment]
Thanks Gustavo! You could try and transfer it to one of us two and we'll transfer it to Plausible?

**Comment by Maronato** [comment]
Done @metmarkosaric 
I've requested the transfer to you

**Comment by Maronato** [comment]
I should also add one of you as a maintainer of the [NPM package](https://www.npmjs.com/package/plausible-tracker). What are your usernames?

**Comment by metmarkosaric** [comment]
Thanks @Maronato, it has been transferred now!

Just created my account at npmjs.com. My username is: markosaric
