### ISSUE TITLE
Only the country is displayed in the metrics

### ISSUE THREAD

**Issue by teol** [plausible/analytics#1912]
Hi,

I just installed Plausible on one of my servers. Everything works except that unlike in the demo, I can't see from what city my users are coming.
I have the Country, but no region or city.

Is that normal? Do I have something extra to configure to enable it?

Thanks !

**Comment by metmarkosaric** [comment]
Hi @teol! Yes, that's expected. Self-hosted version is not updated as frequently as the hosted version which changes daily so latest features won’t be immediately available. Think of it as a long term release. We stack all the new features and fixes that have been battle tested on the hosted version and release a new self-hosted version twice a year or so. You can check out the features that self-hosted is missing at the moment here: https://github.com/plausible/analytics/blob/master/CHANGELOG.md.
