### ISSUE TITLE
top sources and countries sections not working

### ISSUE THREAD

**Issue by Janevski** [plausible/analytics#1919]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Self-hosting

### Describe the bug

I am using the :latest docker tag image of plausible and i don't know how to check for a version number.
I am not using maxmind, just db-ip as it comes by default.

Top Sources and Countries sections state no data yet, when there is data present.
Countries map also does not work.

### Expected behavior

Countries map should work.
Top Sources should show something as well.

### Screenshots

![Screenshot from 2022-05-22 10-51-02](https://user-images.githubusercontent.com/5252703/169686679-b2a92e64-8f88-41e2-b9c4-7e94e59306dd.png)

### Environment

```markdown
- OS:Ubuntu 20.04 via docker image
- Browser: Chrome 
- Browser Version: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36
```

**Comment by metmarkosaric** [comment]
Thanks @Janevski! We keep "issues" to the actual bugs in the product. Please do post your question in our self hosted forum where we keep all the support questions: https://github.com/plausible/analytics/discussions/categories/self-hosted-support

**Comment by Janevski** [comment]
@metmarkosaric Thank you i shall. Seemed like a bug to me - doesn't work as expected.

**Comment by Janevski** [comment]
.
