### ISSUE TITLE
can't start the application built with Dockerfile

### ISSUE THREAD

**Issue by nakoo** [plausible/analytics#1923]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Self-hosting

### Describe the bug

When I tried to run plausible built with `Dockerfile`, it always give below error and couldn't start the application.

```bash
[warning] OTLP exporter failed to initialize with exception :throw:{:application_either_not_started_or_not_ready, :tls_certificate_check}
{"Kernel pid terminated",application_controller,"{application_start_failure,plausible,{bad_return,{{'Elixir.Plausible.Application',start,[normal,[]]},{'EXIT',{timeout,{'Elixir.Task',await,[#{'__struct__' => 'Elixir.Task',owner => <0.2770.0>,pid => <0.2774.0>,ref => #Ref<0.1430843497.2027225089.189815>},30000]}}}}}}"}

Kernel pid terminated (application_controller) ({application_start_failure,plausible,{bad_return,{{'Elixir.Plausible.Application',start,[normal,[]]},{'EXIT',{timeout,{'Elixir.Task',await,[#{'__struct__' => 'Elixir.Task',owner => <0.2770.0>,pid => <0.2774.0>,ref => #Ref<0.1430843497.2027225089.189815>},30000]}}}}}})

Crash dump is being written to: erl_crash.dump...
```
It says that `erl_crash.dump` was written but I couldn't find the file either.

```bash
# id
uid=0(root) gid=0(root) groups=0(root),1(bin),2(daemon),3(sys),4(adm),6(disk),10(wheel),11(floppy),20(dialout),26(tape),27(video)
# find / -type f -iname 'erl_crash.dump'
#

```

### Expected behavior

Shoud be run without error.

### Environment

```markdown
- OS: NixOS (21.11)
- Browser: Chromium
- Browser Version: 101.0.4951.64
```

**Comment by metmarkosaric** [comment]
Thanks @nakoo! We keep the "Issues" to actual bugs in the product only. For help with your self-hosted installation please post in our self-hosted community forum and hopefully a community member who's had the same problem can help you out: https://github.com/plausible/analytics/discussions/categories/self-hosted-support.

**Comment by nakoo** [comment]
> Thanks @nakoo! We keep the "Issues" to actual bugs in the product only. For help with your self-hosted installation please post in our self-hosted community forum and hopefully a community member who's had the same problem can help you out: https://github.com/plausible/analytics/discussions/categories/self-hosted-support.

Yeah, I wrote this in this bug section since I thought it's more like a bug rather than configuration or management issue. I haven't faced any issue when using latest version.

**Comment by nakoo** [comment]
> The latest version is the only one that we support. We don't support any other versions. What version is this report for?

I cloned master branch of the repository and built myself using `Dockerfile`.

**Comment by metmarkosaric** [comment]
Only the latest version is meant for self-hosting. You can find the latest version here: https://github.com/plausible/analytics/releases. These errors are expected if you're trying to use a version that we use for our cloud as those versions are not built for nor meant for self-hosting.

**Comment by metmarkosaric** [comment]
No problem! There are many tweaks that need to be done to release a self-hosted build and it's time consuming which is why we don't release them all the time. Think of it as a long term release. We stack all the new features and fixes that have been battle tested on the hosted version and release a new self-hosted version twice a year or so.
