### ISSUE TITLE
Link to site assumes HTTPS (and so fails with HTTP sites)

### ISSUE THREAD

**Issue by danyork** [plausible/analytics#194]
In the analytics page on the Plausible website, when you click on the name of the site it will take you over to the website. But the page **assumes** that the site will be over HTTPS and begin with "https://":

<img width="297" alt="site-assumes-https" src="https://user-images.githubusercontent.com/41662/86038890-a5f82400-ba0f-11ea-8bc2-d32624bc7b52.png">

If a site is still only HTTP, then the connection will fail.

Given the continued push to get all sites working over HTTPS, I'm not sure how much attention to give to this issue. You might just flag this as "WON'T FIX" and so it goes.  The reality is that MOST people today will have their sites working over HTTPS.

I'm just pointing out that this behavior happens in your site.

**Comment by ukutaht** [comment]
This was a super quick fix and I was touching that part of the codebase today anyways :)

Just linking to http now. A proper HTTPS setup should redirect from http -> https.
