### ISSUE TITLE
Is plausible script modifying the page ??

### ISSUE THREAD

**Issue by ghk-arolla** [plausible/analytics#1951]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

My reservation hotel provider refuses to add my 1 line plausible script on my reservation page because he says that this script "is modifying the page".

I don't think so but I prefer to have an official statement from you before I get back to them and I sits on having my script added.

Not really belonging to an other section than bug ...

Thanks

### Expected behavior

My reservation hotel provider refuses to add my 1 line plausible script on my reservation page because he says that this script "is modifying the page".

I don't think so but I prefer to have an official statement from you before I get back to them and I sits on having my script added.

Thanks

### Environment

```markdown
- OS:?
- Browser:?
- Browser Version:?
```

**Comment by metmarkosaric** [comment]
thanks for the feedback @ghk-arolla! our script is not doing anything nor modifying anything on your site. it works the same way as the Google Analytics script and any other analytics script. you can insert it and test it

**Comment by ghk-arolla** [comment]
Thanks a lot. I knew it but those smucks are so lame ... anyway. Thanks for confirming.

**Comment by metmarkosaric** [comment]
you're welcome! i'll close this for now. hope you figure it out with them. and do let us know if you need anything else
