### ISSUE TITLE
City-filter doesn't work

### ISSUE THREAD

**Issue by bencresty** [plausible/analytics#1957]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

When on plausible.io and clicking a city the city-tag appears in the filter list, but the results aren't filtered on that city (Filtering on Country or Region does (still) work tho)

### Expected behavior

Same as filtering on Country or Region

### Environment

```markdown
- OS: Windows 10
- Browser: Edge (Chromium)
- Browser Version: -
```

**Comment by metmarkosaric** [comment]
thanks for reporting @bencresty! could you please share an example of where this happens? if you don't want to share the site/URL publicly, please [contact our customer support](https://plausible.io/contact)

**Comment by bencresty** [comment]
@metmarkosaric  It's on https://plausible.io/. If you try it you'll see it.

**Comment by metmarkosaric** [comment]
thanks! city filtering seems to work all fine for me. we do still display other cities in the cities list so that we should fix but the actual stats in all the other charts show the specific city stats only.

**Comment by ukutaht** [comment]
@bencresty Here's a link with a working city filter: https://plausible.io/plausible.io?city=2643743&city_name=London

Could you send a link with one where it's not working?

**Comment by metmarkosaric** [comment]
Our team needed some more info to get to the bottom of this, however we've not heard back from you. We're going to close this for now, but let us know if you manage to dig up some more info and we'll reopen. Thanks!

**Comment by bencresty** [comment]
15 days ago, customer reports:

City-filter doesn't work

You 13 days ago:

> we do still display other cities in the cities list so that we should fix but the actual stats in all the other charts show the specific city stats only.

Acknoledging the exact issue that was reported AND you see it yourself.

now:

> We're going to close this for now, but let us know if you manage to dig up some more info and we'll reopen. Thanks!

You now just close an issue report without fixing the reported issue that you've seen yourself and is just on your own website. You have every info there is.

Perhaps you could act a little more responsible?

Very professional.

**Comment by metmarkosaric** [comment]
Thanks for the feedback @bencresty! City filter works as intended as mentioned previously. Click on any city and the dashboard will be filtered by that city so all the stats you see in the top chart, sources, pages, devices and goals will be for that city only. We don't see any bug in this and asked you to share more details so we can identify what you see. There were no details shared and after 10 days we closed the issue. Happy to reopen if you share more details. Thanks!

**Comment by bencresty** [comment]
First you litereally state **we should fix**

> we do still display other cities in the cities list so that **we should fix** but the actual stats in all the other charts show the specific city stats only.

Now, you act like there's nothing wrong:

> City filter works as intended

Again, very professional way of handling things by moving your responsibility to the client, having bugs and refuse to fix them.
