### ISSUE TITLE
plugin for Hugo

### ISSUE THREAD

**Issue by tckb** [plausible/analytics#196]
I am big fan of Hugo. my personal blog runs on Hugo and I would like to have plausible component/plugin for hugo to integrate once my hosting of plausible is completed. There's already a [component](https://github.com/holehan/hugo-component-matomo) of Matamo, we can adapt to it or get tips from there.

It would be a huge +1 for me if this is taken up. If I have more time, I will try to write it, in the mean time. 

Since we have a more and more requests for plugin support for different providers, would it make sense label them?  I like how this is [listed](https://matomo.org/integrate) here.

**Comment by metmarkosaric** [comment]
Makes sense, thanks @tckb! Just published [this list](https://docs.plausible.io/community-integrations) of current community integrations today (Gatsby and React for now) so would be great to build on top of that.

**Comment by tckb** [comment]
@metmarkosaric  just saw this one: https://ghost.org/integrations/plausible/

**Comment by metmarkosaric** [comment]
Thanks @tckb, will add this to the list!

**Comment by mroach** [comment]
Hugo's support for analytics is just their shipping some templates which themes may or may not include as part of their template. For example, for Google Analytics, Hugo includes this template: https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/google_analytics_async.html

Then themes may include it in the head: https://github.com/Vimux/Mainroad/blob/master/layouts/_default/baseof.html#L32

So for my site I just created a file `layouts/_internal/google_analytics_async.html`. Having a file with a matching path like that automatically overrides the one shipped with Hugo.

My file contents there is then just the necessary snippet.

```html
<script async defer data-domain="mroach.com" src="//ax.mroach.com/js/plausible.js"></script>
```

That's all to say: even if you added a template to the Hugo base for Plausible, themes would still need to include it or you'd have to override/customise them somehow to include it. So if you want to get going now, just shoe-horn the script in there based on what options are available in your theme.

**Comment by tckb** [comment]
@mroach  thanks for tip! At the moment, I have  heavily customized the theme with more or less the same settings. I removed the  GA internal template and created a plausible analytics template and used in my header partials.  Just as a reference,  my base theme is [hugo-vitae](https://github.com/dataCobra/hugo-vitae) as this has better support for GDPR. 

I will keep this issue open so that I can publish either a modified theme or blog instructions on adding this to Hugo on my [blog](https://tckb.tgrthi.me)

**Comment by mroach** [comment]
I want to help refine the objective of this issue so it's actionable. I think the main objective should be opening up a PR to Hugo that adds a template for Plausible, default configuration, and related documentation.

Once that's part of Hugo, themes would be able to add support for it the same way they add support for Google Analytics: including the template.

Otherwise, there's nothing that Plausible can do to help integration. It's a similar story to Ghost: it's just code injection or templating.

**Comment by tckb** [comment]
>. I think the main objective should be opening up a PR to Hugo that adds a template for Plausible, default configuration, and related documentation.

That makes sense and is in my pipeline. Unless, I have more definitive and clean template ready I wouldn't be able to do it with my available bandwidth.  Indeed integrating it into Hugo would make integration more simple.

**Comment by metmarkosaric** [comment]
There's a theme component to add Plausible Analytics & custom goals to your Hugo site now. It allows you to ignore tracking on certain pages. For Saas or self-hosting. Can be used as Hugo Module. Built and maintained by @divinerites

See https://github.com/divinerites/plausible-hugo

**Comment by metmarkosaric** [comment]
Closing this now as there's the Hugo plugin made by @divinerites https://github.com/divinerites/plausible-hugo
