### ISSUE TITLE
N/A instead of city names on All Time view with imported GA data

### ISSUE THREAD

**Issue by jpomykala** [plausible/analytics#1960]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

City names are not showing

### Expected behavior

Should see city names

### Screenshots

![Screenshot 2022-06-16 at 17 27 10](https://user-images.githubusercontent.com/1548104/174105881-cf4428b9-4d3e-4c94-8744-c106c3536b80.png)

### Environment

```markdown
- OS: MacOS
- Browser: Safari
- Browser Version: 15.5
```

**Comment by metmarkosaric** [comment]
Thanks for reporting this @jpomykala! 

I tried to reproduce this issue but with no success. Everything seems to be working fine for me. Please do share more details on how we can reproduce this and/or the exact dashboard URL for the error so we can better help out. 

As you're having an issue with Plausible Analytics managed hosting, if you want to keep your site details private, please drop us an email and we'll be more than happy to help out: https://plausible.io/contact

**Comment by metmarkosaric** [comment]
After discussing this with @jpomykala via email, we've located the issue:

It happens on the dashboard views that include imported data from GA. all N/A shows in the cities tab but if you actually click to filter by any of the N/A cities, then the correct list of top cities shows up as it should have been in the first place
