### ISSUE TITLE
Bug in user management / ownership transfer

### ISSUE THREAD

**Issue by bircha** [plausible/analytics#1966]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

Created a discussion about this https://github.com/plausible/analytics/discussions/1965

Hi! There's a bug in user management / ownership transfer which currently prevents me transferring the ownership to different user. It seems that the system does not recognise me as an owner anymore. Possible steps to reproduce:

1. Create an account and website(s) to it.
2. Invite a user to a website with the role of an admin.
3. Change the account settings email address and name to be the same email address you sent the invitation to before the user has accepted the invitation.
4. The invited user accepts the invitations.
5. Log out.
6. Log in.
7. Your name in the UI has changed to that of the invited user.
8. Change the account settings email address and name back to what they were before step 3.
9. The name of the invited user changes to that what you just added to account settings.
10. Neither the invited user not you can change the ownership anymore.

### Expected behavior

I expect that the account email address would a separate thing that the user account used to login to the service. Or that you set the owner of an account in cleared way.

### Environment

```markdown
- OS: OSX
- Browser: Chrome
- Browser Version: Latest
```

**Comment by metmarkosaric** [comment]
Closing this after discussing/solving via email as our invites are based on email addresses.
