### ISSUE TITLE
Plausible proxy (next.js) causing issues with unique visitor statistic

### ISSUE THREAD

**Issue by guttermouth99** [plausible/analytics#1969]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

I recently implemented a proxy for plausible in order to improve tracking. I am using next-plausible with next.js and react. 

However after integrating (https://plausible.io/docs/proxy/guides/nextjs) the proxy as described in the guidline I started realising that my unique visitor count is decreasing and my site counts and visit duration are increasing. It looks to me that the is something wrong with the tracking, otherwise I cannot explain the massive drop in unique visitors.

Is there the possibility that returning users have the old script under plausible.io cached and this is causing some kind of issue getting the proxied version?

Thanks for your help

### Expected behavior

I was expecting to improve my statistics with implementing a proxy, however I am expieriencing a big drop in unique visitor counts.

### Environment

```markdown
- OS: MacOs
- Browser: Chrome
- Browser Version: 102.0.5005.115 (Official Build) (x86_64)
```

**Comment by metmarkosaric** [comment]
thanks for reaching out @guttermouth99! 

could you please share your domain name? and also the exact details of how you've set up the proxy?

this type of question is best sent to [our customer support directly](https://plausible.io/contact) as we keep the issues list to actual bugs with the product only and not for support questions. thanks!

**Comment by guttermouth99** [comment]
Okay thanks, I sent an email to your hello@ support to discuss the issue.
