### ISSUE TITLE
Total page view discrepancy for one date range run over 2 separate days

### ISSUE THREAD

**Issue by pronick55** [plausible/analytics#1970]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

We are running a total page view report for a date range between June 8 and June 22. We ran the report June 22 and saw a total 377. We ran the same report on June 23 and see 8 fewer page views stated at 369. Why is there a discrepancy? Why would it change to fewer page views one day later?

### Expected behavior

The total page views for a single date range should not have decreased one day later for the same date range. 

### Environment

```markdown
- OS: Windows 10
- Browser: Chrome
- Browser Version:Current
```

**Comment by metmarkosaric** [comment]
thanks for reporting @pronick55! i've never noticed something like it. perhaps @ukutaht has an idea on why it may happen?

**Comment by metmarkosaric** [comment]
closing this for now according to the details above but we'll reopen if it can be replicated
