### ISSUE TITLE
Setting db poolsizes for postgres and clickhouse gives me a kernel dum

### ISSUE THREAD

**Issue by mannp** [plausible/analytics#198]
Setting db poolsizes for postgres and clickhouse gives me a kernel dump;

I am not sure why its DATABASE_POOL_SIZE instead of DATABASE_POOLSIZE for postgres, but either way the kernel hiccups.

DATABASE_POOL_SIZE=20
CLICKHOUSE_DATABASE_POOLSIZE=20

> {"Kernel pid terminated",application_controller,"{application_start_failure,plausible,{{shutdown,{failed_to_start_child,'Elixir.DBConnection.ConnectionPool',{{badmatch,{error,{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<\"ranges (first..last) expect both sides to be integers, got: 1..\\"20\\"\">>},[{'Elixir.Range',new,2,[{file,\"lib/range.ex\"},{line,63}]},{'Elixir.DBConnection.ConnectionPool.Pool',init,1,[{file,\"lib/db_connection/connection_pool/pool.ex\"},{line,18}]},{supervisor,init,1,[{file,\"supervisor.erl\"},{line,295}]},{gen_server,init_it,2,[{file,\"gen_server.erl\"},{line,374}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,342}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,249}]}]}}},[{'Elixir.DBConnection.ConnectionPool',init,1,[{file,\"lib/db_connection/connection_pool.ex\"},{line,22}]},{gen_server,init_it,2,[{file,\"gen_server.erl\"},{line,374}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,342}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,249}]}]}}},{'Elixir.Plausible.Application',start,[normal,[]]}}}"}
> Kernel pid terminated (application_controller) ({application_start_failure,plausible,{{shutdown,{failed_to_start_child,'Elixir.DBConnection.ConnectionPool',{{badmatch,{error,{#{'__exception__' => true

**Comment by tckb** [comment]
@mannp ah! the naming inconsistency might just be an overlook; I think the issue seems to be a mismatched type issue. The issue seems to be in clickhouse pool size setting. IRL, the pool size settings in postgres shouldn't throw you this issue  let mw know otherwise. 

I can fix this in #89 may this can be addressed faster in #197  by @ukutaht

**Comment by mannp** [comment]
Hi @tckb so I've deleted and started again and yes the DATABASE_POOL_SIZE=20 works for postgres albeit it could be good to change to DATABASE_POOLSIZE for consistency when anyone has a chance, but it works.

Yes it looks like a type issue with the clickhouse pools, so have left it off and am back work again.

Lol, I have been watching each day for #89 to be merged, so personally don't mind if this goes in later, rather than adding to that :) but wanted to highlight the issue at least.

**Comment by tckb** [comment]
@mannp apologies for  the delay. I’ve haven’t been having too much lately( I have a full 40 hour work week 😉)  The Final changes are ready I’m still doing some testing. The PR could be merged by this weekend.

**Comment by mannp** [comment]
> @mannp apologies for the delay. I’ve haven’t been having too much time lately( I have a full 40 hour work week wink) The Final changes are ready I’m still doing some testing. The PR could be merged by this weekend.

No need to apologise @tckb  it wasn't intended to be a chaser :+1:  its done when its done :+1:

**Comment by mannp** [comment]
Thanks for the update, I can confirm it works now with both pools :+1:
