### ISSUE TITLE
Cities list features other cities too even when filtered by a city

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/analytics#1982]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

When filtering by a city, everything works fine and all stats are filtered correctly. The only thing is that we still display the other top cities in the cities list itself. On countries and regions, we isolate only the country and region that the dashboard is filtered by and we do not include any other names so we should follow that for cities too. 

### Expected behavior

Cities list should only show the city that the dashboard is filtered by kind of like it works for countries and regions

### Environment

```markdown
- OS:
- Browser:
- Browser Version:
```

**Comment by bencresty** [comment]
Really? Now you're going to open the exact same issue I already opened and you ignored and wrongly closed?

https://github.com/plausible/analytics/issues/1982
