### ISSUE TITLE
When clicking on Source Google Plausible website hangs on API

### ISSUE THREAD

**Issue by bencresty** [plausible/analytics#1986]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

When Source is 'Google' (with capital) and clicking on that data is not collected. When looking in DevTools software is hanging in an API Error 'Invalid Grant'. This was working before.

![image](https://user-images.githubusercontent.com/69322733/177037165-efc4f26c-e9af-48b7-8eee-10fa96c5e338.png)

![image](https://user-images.githubusercontent.com/69322733/177037171-fc95a7e3-6324-442f-8720-05eb4c6ad51b.png)

### Expected behavior

Working website/analytics

### Screenshots

See above

### Environment

```markdown
- Browser: Chromium based (Ms Edge/Chrome)
```

**Comment by metmarkosaric** [comment]
thanks for reporting @bencresty! "Invalid grant" is the error that Google sends us in connection to the Search Console integration. we've listed the different causes for it in our docs: https://plausible.io/docs/google-search-console-integration#i-get-the-invalid-grant-error. please check the status of your site in the Search Console. if everything is fine then simply connecting your Search Console again to Plausible solves the error
