### ISSUE TITLE
google integration not showing any properties

### ISSUE THREAD

**Issue by emilburzo** [plausible/analytics#202]
Hi,

I'm using the self-hosted version, I've setup a google project and configured `GOOGLE_CLIENT_ID` and `GOOGLE_CLIENT_SECRET`.

The account connection/authorization worked without any errors, but when I try to enable the google integration, the property drop-down is empty:

![image](https://user-images.githubusercontent.com/6228327/86319961-64998b80-bc3e-11ea-902d-b1379e2c5184.png)

What am I missing?

**Comment by kpsuperplane** [comment]
You need to enable the search console API for your credentials
https://console.developers.google.com/apis/library/webmasters.googleapis.com

**Comment by emilburzo** [comment]
Ugh, I knew I was missing something obvious :facepalm: 

It's working now, thank you for your help!
