### ISSUE TITLE
Search Console not showing terms

### ISSUE THREAD

**Issue by jummeking** [plausible/analytics#203]
On my little hobby site for a online game Football Manager Game that shows [Vmaninfo](https://vmanstats.com/) I cannot make it shows the queries from GSC, that people have searched to reach the site. Yesterday there was 1 but It won't show:
<img width="1099" alt="Skærmbillede 2020-07-02 kl  11 27 29" src="https://user-images.githubusercontent.com/31508471/86341768-06c56d80-bc57-11ea-9d88-daf164ed3cfc.png">

Can there be an issue if I use a Domain property rather than a URL property?

**Comment by metmarkosaric** [comment]
Search query data is not live. It is delayed by approximately 24-36 hours even on Google Search Console itself. We get the search query data directly from Google Search Console so as soon as they show up there they show up in Plausible Analytics too. Can you check a date few days back in time and compare that with what you see on Google Search Console?

See a bit more details on this in our docs: https://docs.plausible.io/google-search-console-integration#i-dont-see-google-search-query-data-in-my-dashboard
