### ISSUE TITLE
Event not tracked unless button contains text.

### ISSUE THREAD

**Issue by lightson** [plausible/analytics#2031]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

I am using event goals to track clicks on an audio playback button on the mobile view of my website, for example on [this page](https://soundcarrot.com/shows/radio-one-mini-mix/blondish-one-life-stand-mini-mix/).

On the **mobile device** view of this page (not desktop viewport), the play button and code looks like the below, the button contains an SVG, which when clicked plays the mp3. Clicking it does not trigger the capture of custom event goal data.

<img width="1463" alt="image" src="https://user-images.githubusercontent.com/951483/179622807-92beba0d-edc1-4a00-9d44-9443e29df488.png">

When clicking this SVG play button I see no network activity to https://plausible.io/api/event

If I remove the SVG and use text instead that says 'play', I do see network activity to https://plausible.io/api/event, for example: 

![image](https://user-images.githubusercontent.com/951483/179624383-0919b492-3de6-4041-a116-ca1cf7b6c25a.png)

I have the relevant scripts in my header/footer as described on https://plausible.io/docs/custom-event-goals. As mentioned the event tracks fine when the button click is on text. It is only when something other than text is present that the click is ignored by plausible.

### Expected behavior

I would expect clicking the SVG to trigger the same network activity and event tracking as clicking a text link.

### Environment

```markdown
- OS: MacOS
- Browser: Safari, Brave
- Browser Version: Safari 15.5, Brave 1.41.96
```

**Comment by RobertJoonas** [comment]
Hi @lightson!

The code you've used is specifically meant for form submit tracking. You should use a different code if you're only tracking simple button clicks.

Usually it's redirection that makes it hard to track button clicks because you have to give the script enough time to finish the request, before navigating to the next page. In your case though, I think you're not using any redirection with these button clicks? If that's the case, then you can use this code:

```HTML
<script>
    function handleButtonClick(event) {
        var btn = event.target
        while (btn && (typeof btn.tagName === 'undefined' || btn.tagName.toLowerCase() !== 'button')) {
            btn = btn.parentNode
        }

        var attrString = btn && btn.getAttribute('data-analytics')

        if (attrString) {
            var attributes = attrString.split(/,(.+)/)
            var events = [JSON.parse(attributes[0]), JSON.parse(attributes[1] || '{}')]
            plausible(...events)
        }
    }

    document.addEventListener('click', handleButtonClick)
</script>
```

This also accounts for the situation when a child element of the button is clicked (in your case the SVG).

Hope this helps!

**Comment by metmarkosaric** [comment]
thanks @RobertJoonas! closing this as we keep the issues list to actual bugs with the product only. @lightson feel free to contact [our support](https://plausible.io/contact) if you need more help with this, thanks!

**Comment by lightson** [comment]
Oh gosh, that's embarrassing! Thanks so much @[RobertJoonas](https://github.com/RobertJoonas), will do @metmarkosaric :)
