### ISSUE TITLE
Regions are not being collected since July 14th

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/analytics#2033]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

"I noticed when filtering by “Today” the regions don’t show. Is there a reason for that? Going to Map, Countries, and Cities shows data. If I go to “Last 7 days” it shows Regions."

[via twitter](https://twitter.com/ThisIsSingleton/status/1549137152906145792)

### Expected behavior

regions should show

### Environment

```markdown
- OS:
- Browser:
- Browser Version:
```

**Comment by abstractcoder** [comment]
I am also experiencing this issue. When looking at today, or any single day in the past, I can no longer see region information.

**Comment by metmarkosaric** [comment]
This just started happening very recently. Was working all fine few days ago but not sure what could have caused it. It still works all fine for any other period other than a single day.

**Comment by metmarkosaric** [comment]
This seems to be something different now as there's no regions data since July 14th so regions no longer display on other views either and not only today.

**Comment by vinibrsl** [comment]
Does plausible.io use the same geolocation database defined in https://github.com/plausible/analytics/blob/master/lib/mix/tasks/download_country_database.ex?

I'm trying to reproduce it locally and it would be easier if I had the same database.

**Comment by metmarkosaric** [comment]
we use [db-ip](https://db-ip.com/) for the cloud

**Comment by metmarkosaric** [comment]
Just a quick update that our developers have now fixed this bug. The regions data is now being collected again. Sorry again for the inconvenience and thanks for understanding!
