### ISSUE TITLE
Qu: Is DISABLE_AUTH only on initial setup or a selectable env on each boot of the docker?

### ISSUE THREAD

**Issue by mannp** [plausible/analytics#204]
Thanks for the other selfhost changes.

After deleting and reinitialising everything with DISABLE_AUTH=false I tried to enable DISABLE_AUTH=true on a subsequent docker restart.

The login page was still visible, so i wondered how this was intended to work.

Thanks

**Comment by tckb** [comment]
Can you tell me exactly what you are trying to do ? and what you did

**Comment by mannp** [comment]
Trying to test ... so while I had to reset everything for your recent updates (thank you btw) I tried the disable auth option.

I logged out, which i guess should clear the cookies but i did not explicitly delete them.

I deleted all databases and ran the migration scripts on your new version, with DISABLE_AUTH=false

After everything was done and confirmed working I set DISABLE_AUTH=true, logged out and restarted docker.

The login screen appeared after the docker had rebooted.

**Comment by tckb** [comment]
>I logged out, which i guess should clear the cookies but i did not explicitly delete them.
Yes or may be you can try it in incognito mode?

>I deleted all databases and ran the migration scripts on your new version,
I don't think deleting db would have been necessary.  the new changes would only "bypass" the auth by automatically signing in with your admin credentials 

Okay, lets get the basics first: 

How are you pulling docker images? 
- If you are building locally, you need to delete the existing container and run this.

**Comment by mannp** [comment]
> I don't think deleting db would have been necessary. the new changes would only "bypass" the auth by automatically signing in with your admin credentials

Well yes, I was recreating those as I was starting a fresh with both database pools now being able to be setup correctly, nothing to do with trying disable auth.

The question was if I disable auth can be set after initial setup, as I don't intend to use it but found it not to work in the limited case I tried.

If it works for others I will close this..... not needing to go into docker etc, I don't use docker compose so have configured via .env

**Comment by tckb** [comment]
@mannp disabling authentication is never recommended regardless if you are using for hobby.  But, someone requested it and it seemed reasonable. If you are running docker w/o docker-compose then I can only recommend that you check if the container is running the latest and clearing the cache. -- I will verify it again. 

Yes - `DISABLE_AUTH`  is a bypass to login. Internally, it is _signing_ you in as "admin" the "[auto_auth_plug](https://github.com/plausible/analytics/blob/master/lib/plausible_web/plugs/auto_auth_plug.ex) does this for you. But, it also does some additional by-passes.  This auto "sign-in" happens in `/`

**Comment by mannp** [comment]
@tckb Okay thanks for the explanation....I was confused as another project just disables the login page, so you cannot login at all.

Now I know how it works, I will close this, as my question is answered.

Thanks.

**Comment by tckb** [comment]
With the current architecture, you can’t disable auth module completely.  Hence a bypass. 

@mannp feel free to open if problem persists

**Comment by maxemann96** [comment]
> @mannp disabling authentication is never recommended regardless if you are using for hobby. But, someone requested it and it seemed reasonable. If you are running docker w/o docker-compose then I can only recommend that you check if the container is running the latest docker image and clearing the cache -- I will also verify it again.
> 
> Yes - `DISABLE_AUTH` is a bypass to login. Internally, it is _signing_ you in as "admin" the [auto_auth_plug](https://github.com/plausible/analytics/blob/master/lib/plausible_web/plugs/auto_auth_plug.ex) does this for you. This auto "sign-in" happens in `/`

Just wanted to drop that we are using this in production with oauth2-proxy as a gatekepper

**Comment by mannp** [comment]
> oauth2-proxy

Thanks @maxemann96, have it working with cloudflare teams and a self hosted keycloak 👍🏻
