### ISSUE TITLE
Region and City data missing on self-hosted instance

### ISSUE THREAD

**Issue by NathanC** [plausible/analytics#2044]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Self-hosting

### Describe the bug

I just integrated with Plausible, self hosting it. It's really cool so far, but location data is only showing Countries, not Regions or Cities. I'm not sure if this is because of the feature being lacking while self hosting, lack of volume of data on my end, or some other reason.

![image](https://user-images.githubusercontent.com/6182419/180115983-215755df-4b75-4a6d-a438-229d778f96e4.png)

### Expected behavior

I expected location data to be broken up be regions and cities, like in the live demo:

![image](https://user-images.githubusercontent.com/6182419/180115715-0872d6b0-ffd0-4c3c-addb-6e5f9c256f82.png)

### Environment

```markdown
- OS: Windows
- Browser: Firefox
```

**Comment by NathanC** [comment]
I just found another issue about this: https://github.com/plausible/analytics/discussions/1601. From that issue back in Jan, it said that self hosting did not support city level data. 

That's a bit disappointing since [this page](https://plausible.io/open-source-website-analytics#can-plausible-analytics-be-self-hosted) says 
> Plausible Analytics Self-Hosted is our free as in beer and free as in speech version. It’s exactly the same product as our Plausible Analytics Cloud solution, only the self-hosted version you have to install, host and manage yourself.

However, issues with licensing fees and delayed updates to self-hosting make sense, so that's understandable 😄 But it would be good to have that documented somewhere.

Anyhow, what is the timeline for getting this functionality in self-hosted? Is there some way I could workaround or use my own database to get it now?

Thanks in advance!

**Comment by metmarkosaric** [comment]
Thanks for the feedback @NathanC! This is expected as our self-hosted version is not updated as frequently as the Plausible managed hosting in the cloud, which changes daily. It's just unrealistic for us to release a new self-hosted release so frequently. This means that the latest features won't be immediately available.

Think of self-hosted as a long-term release. We stack all the new features and fixes that have been battle-tested on the hosted version and release a new self-hosted version twice a year or so. We don't have any more specific timelines than this as we have limited resources, and the self-hosted release depends on the free capacity of our developers. 

You can check out the features that self-hosted is missing at the moment here: https://github.com/plausible/analytics/blob/master/CHANGELOG.md.

**Comment by pcho** [comment]
@NathanC you can have it sooner by changing `latest` to `master` in [docker-compose.yml](https://github.com/plausible/hosting/blob/f7682057104671b42e3fff3a106f93a32ea14775/docker-compose.yml#L28) file. Then go through this [step in docs](https://plausible.io/docs/self-hosting#1-maxmind-geolocation-database) and everything should work.

Remember to pull master version before running `compose up`.

**Comment by NathanC** [comment]
@pcho does the method linked in those docs require paying for a database? It's not clear. It mentions the [MaxMind](https://www.maxmind.com/) service. Is there a particular paid or free plan associated with this that I should use?

If it's paid, is there any plan for having city-level data be available for self-hosted without being paid? It would be reasonable if the answer is no, but if so, the language about feature parity should be updated.

**Comment by pcho** [comment]
> @pcho does the method linked in those docs require paying for a database? It's not clear. It mentions the [MaxMind](https://www.maxmind.com/) service. Is there a particular paid or free plan associated with this that I should use?
> 
> 
> 
> If it's paid, is there any plan for having city-level data be available for self-hosted without being paid? It would be reasonable if the answer is no, but if so, the language about feature parity should be updated.

Now I would advise to use default option: https://github.com/plausible/analytics/releases/tag/v1.5.0-rc.0 :)

**Comment by NathanC** [comment]
@pcho very cool! I really appreciate your response here. I'll follow that guide-- looks like it's still a bit in flux, but that's to be expected, and I'm very happy to see it's being included.

qq: would `latest` pull this is, or would it not because it's a release candidate?

**Comment by pcho** [comment]
> @pcho very cool! I really appreciate your response here. I'll follow that guide-- looks like it's still a bit in flux, but that's to be expected, and I'm very happy to see it's being included.
> 
> 
> 
> qq: would `latest` pull this is, or would it not because it's a release candidate? 

You need to change it to: 1.5.0-rc.0 and it will work.

**Comment by DocKDE** [comment]
I have the very same problem although I'm running version 2 and this feature was merged in 1.5, as far as I can see. I used the supplied `docker-compose.yaml` without changing anything, really. Could anyone tell me whether I'm missing something here?

**Comment by ruslandoga** [comment]
@DocKDE 👋

Yes, you need to set `MAXMIND_LICENSE_KEY` to get MMDB with both geoname ids and city-level data which are required for this feature.

**Comment by knockkk** [comment]
@ruslandoga Could you please explain how to proceed in more detail?

**Comment by ruslandoga** [comment]
👋 @knockkk Sure! Which part are you interested in, getting the license key or configuring Plausible? Here's the short overview:

- to get `MAXMIND_LICENSE_KEY` please see https://support.maxmind.com/hc/en-us/articles/4407111582235-Generate-a-License-Key
- to make Plausible "see" your `MAXMIND_LICENSE_KEY` you need to set it in [`plausible-conf.env`](https://github.com/plausible/hosting/blob/master/plausible-conf.env) and recreate the container

**Comment by knockkk** [comment]
@ruslandoga Thanks, i just need to know how to get `MAXMIND_LICENSE_KEY` and how to config it. It helps a lot.

**Comment by knockkk** [comment]
> 👋 @knockkk Sure! Which part are you interested in, getting the license key or configuring Plausible? Here's the short overview for both:
> 
> * to get `MAXMIND_LICENSE_KEY` please see https://support.maxmind.com/hc/en-us/articles/4407111582235-Generate-a-License-Key
> * to make Plausible "see" your `MAXMIND_LICENSE_KEY` you need to set it in your [`plausible-conf.env`](https://github.com/plausible/hosting/blob/master/plausible-conf.env) and recreate the container

I have set MAXMIND_LICENSE_KEY in plausible-conf.env and recreate the container, but get the error:
<img width="1129" alt="image" src="https://github.com/plausible/analytics/assets/34182411/580cbd14-359b-451d-af7e-1f72b64f001b">
Is there something wrong with my "MAXMIND_LICENSE_KEY"?

**Comment by ruslandoga** [comment]
It seems like the key you are using is not recognised by MaxMind.
