### ISSUE TITLE
Show data by domain

### ISSUE THREAD

**Issue by mehulkar** [plausible/analytics#205]
I am serving a site on two different domains: foo.com and something.netlify.app. I would like to know which one is being used more. At this point, I'm not even sure if data is being collected from foo.com, since  the domain I added to the plausible dashboard is the netlify one. I did not see any documentation about this.

**Comment by mehulkar** [comment]
> I'm not even sure if data is being collected from foo.com,

Looking at the code a bit more and the events, data _is_ being collected from foo.com and the entire current URL is being reported, the plausible dashboard just doesn't show it, it only shows the pathname.

**Comment by metmarkosaric** [comment]
Yes, that's correct. The data is collected from both sites into one dashboard but we don't show the pathname. We'll work on adding that feature. There's an issue on this already #160 so I'll close this one and you can follow the other thread for updated. Thank you!
