### ISSUE TITLE
Parameters for embed mode don't seem to work

### ISSUE THREAD

**Issue by NathanC** [plausible/analytics#2050]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Self-hosting

### Describe the bug

Embed mode doesn't seem to respect the url paramaters. I'm using the embed link it provided me (converted to React JSX syntax), as follows:

```jsx
<>
    <iframe 
      plausible-embed
      src="https://mydomain/mysite?embed=true&theme=light&background=transparent"
      scrolling="no"
      frameBorder="0"
      loading="lazy"
      style={{
        width: "1px",
        minWidth: "100%",
        height: "1600px"
      }}
    />
      <div
        style={{fontSize: "14px", paddingBottom: "14px"}}
      >
        Stats powered by <a
            target="_blank"
            style={{color: "#4F46E5", textDecoration: "underline"}}
            href="https://plausible.io"
           >Plausible Analytics</a></div>
      <script async src="https://mydomain/js/embed.host.js"></script>
    </>
 ```

I'm not sure if the params `?embed=true&theme=light&background=transparent` are having any effect at all. The theme is dark, not light, and the background is not transparent. It also isn't a simplified view at all (it still shows the Login button for example), although I don't have any reference to compare it to so I'm not sure what it's supposed to look like.

I also had to manually strip the `X-Frame-Options` header at the reverse proxy layer, if that helps diagnosing this at all (as I'd expect that header not to be there for embed mode)

### Expected behavior

I'm expecting the background to be transparent, the theme to be light, and the login button to be hidden.

### Environment

```markdown
- OS: Windows
- Browser: Firefox

Thanks in advance!
```

**Comment by metmarkosaric** [comment]
thanks for reporting @NathanC! the embed seems to work all fine. you can see a test version here: https://markosaric.com/stats/. the issue might be related to the changes you've done to the embed code. please try and use the official code that we provide as that's the only one that has been tested and that is officially supported

**Comment by NathanC** [comment]
@metmarkosaric  Thanks for your quick response! It was useful to see the test version you provided.

I figured out that I needed to generate a share link and use that, I couldn't just use the main public view like I was trying to. It works now 👍
