### ISSUE TITLE
Events from *.vercel.app preview URLs show up in dashboard

### ISSUE THREAD

**Issue by gabalafou** [plausible/analytics#2064]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

We use Vercel to manage the building and deployment of our website.

Vercel puts staging versions of the website at URLs like: our-website-someSHA-company.vercel.app. 

I noticed that when I visited a preview of our website at the vercel.app website, [the visit got recorded by Plausible](https://github.com/Quansight/Quansight-website/pull/337#discussion_r918868406).

I would like to create a minimal reproduction of this bug but I don't think I will have the time for it and I didn't want to delay this bug report indefinitely. 

Because given that there are other website services, like Netlify, that behave similarly, it seems that Plausible ought to exclude such preview URLs by default, or add to the documentation how Plausible behaves on such Vercel and Netlify preview URLs and if it doesn't opt them out by default, how to opt them out.

### Expected behavior

Visits and other events from preview or staging websites on a completely different, third-party domain (such as vercel.app) should not get recorded. Or this should be clearly documented in the docs.

### Screenshots

See [screenshot of Plausible dashboard](https://github.com/Quansight/Quansight-website/pull/337#discussion_r918868406) in this GitHub comment.

### Environment

```markdown
Shouldn't be relevant to this bug report, but just in case it is:

- OS: macOS
- Browser: Brave
- Browser Version: Version 1.41.96 Chromium: 103.0.5060.114 (Official Build) (x86_64)
```

**Comment by gabalafou** [comment]
Creating a minimal reproduction should be easy. 

1. Create a new Plausible project/account. 
2. Create a new Vercel project. 
3. Add Plausible to the new Vercel site.
4. Visit the preview URL that Vercel creates (*.vercel.app) for the commit or PR that adds Plausible.
5. Observe that the Plausible project records the page visit from the Vercel preview URL.

**Comment by metmarkosaric** [comment]
thanks for reporting @gabalafou! do you know what user agent Vercel uses for this?

**Comment by gabalafou** [comment]
Do you mean something like the `x-powered-by` or `server` HTTP headers?

If you visit [this Vercel preview URL for example](https://quansight-consulting-live-git-moving-scipy-to-meson-quansight.vercel.app/), you'll get the following HTTP response headers from Vercel:

```
access-control-allow-methods: POST
access-control-allow-origin: https://zapier.com/
age: 18077
cache-control: public, max-age=0, must-revalidate
content-disposition: inline
content-encoding: br
content-type: text/html; charset=utf-8
date: Thu, 28 Jul 2022 10:08:13 GMT
etag: W/"0f15e326bb802acf0f39d25ceb389eba"
server: Vercel
strict-transport-security: max-age=63072000; includeSubDomains; preload
x-matched-path: /
x-robots-tag: noindex
x-vercel-cache: HIT
x-vercel-id: fra1::whj5w-1659002893394-d391c65644a9
```

**Comment by metmarkosaric** [comment]
Thanks for the details! We use a crowdsourced list of user agents that we block by default. I can see that [Vercelbot is already excluded by default](https://github.com/matomo-org/device-detector/search?q=vercel) so this seems to be something different. Finding the actual user agent that they use for this functionality means that we could get it added to this crowdsourced list so it would be excluded by Plausible by default too

**Comment by gabalafou** [comment]
Oh yeah I saw [the closed issue in this repo about Vercel and Netlify bots](https://github.com/plausible/analytics/issues/280), but I think my issue is quite different. I'm actually not all that concerned about the Vercel bot showing up so long as the volume of that data is low (so it doesn't skew our data). 

The issue for me is that at my company we use the Vercel preview URLs extensively to make sure that the site looks good, and it's all of those events accumulated by the dev team in the process of developing and reviewing our website that I want to exclude. Our solution to the problem was simple: we simply [don't load Plausible if we're not on the domain that we want to track](https://github.com/Quansight/Quansight-website/pull/337/files#r918920736).

But the fact that there wasn't specific documentation for this and that the existing documentation [led to opposing conclusions](https://github.com/Quansight/Quansight-website/pull/337#discussion_r918860753) within our company made me think that I should open an issue about it.

**Comment by gabalafou** [comment]
Here's another way to think about this.

A lot of websites use staging environments. Perhaps a paragraph or two in the docs with recommendations from Plausible's dev team about how to handle Plausible in staging environments would reduce potential confusion for future customers.

Even better would be smart defaults to exclude analytics events from end users who visit preview/staging versions of websites on *.vercel.app or *.netlify.app because visits to those pages are typically from people on the dev team, so they almost never contain information that's relevant to the people who are looking at analytics data for the live production website.

**Comment by metmarkosaric** [comment]
We have a couple of options for you to exclude your own traffic that are documented:

You can exclude yourself by using a browser extension. See the instructions here: https://plausible.io/docs/excluding. 

Alternatively, you can exclude your visits by setting a localstorage flag in your browser. See https://plausible.io/docs/excluding.

There's also a way to exclude pages from being tracked. See https://plausible.io/docs/excluding-pages

**Comment by metmarkosaric** [comment]
I'll close this now as we keep this list to actual bugs in the product.

**Comment by gabalafou** [comment]
I appreciate you taking the time pull up those links.

I also went ahead and created a [minimal reproduction of the issue](https://github.com/gabalafou/plausible-minimal-repro/pull/1).

## Actual behavior

1. With your the network panel open in your browser's dev tools, and ad blocker off, shields down, go to https://plausible-minimal-repro-gqqpuade7-gabalafou.vercel.app/.
2. Filter network requests with the string "plausible" and notice a request to plausible.io/api/event.

If you can look at the Plausible dashboard for the gabalafou.com domain, you'll see that not only did the script send an event, but the Plausible backend accepted it as a legitimate site visit, even though the request originated from a Vercel preview deployment URL.

## Expected / desired behavior

At my company, the desired behavior, if you follow the same two steps above, is that no event gets logged to Plausible.

## Does this matter?

As I mentioned in a previous comment, the fix for this issue is easy: simply wrap the Plausible script in a domain check, like so:

```js
{
  typeof window !== "undefined" && 
  /gabalafou\.com$/.test(window.location.hostname) &&
  <script 
    defer 
    data-domain="gabalafou.com" 
    src="https://plausible.io/js/plausible.js"
  />
}
```

However, isn't it concerning that this minimal reproduction seems to suggest that anybody can mess with your website's statistics on Plausible by simply including the Plausible script snippet for your domain on their site?

**Comment by metmarkosaric** [comment]
ahh thanks for the explanation! i understand better what you mean now. sending traffic stats to any data-domain regardless of what hostname the script is running is intentional and it's how Plausible works (GA too). you can read more in this thread https://github.com/plausible/analytics/discussions/183. so basically the best way to avoid these views at the moment is to exclude your own visits from being tracked by using one of the method linked to above

**Comment by gabalafou** [comment]
I really appreciate you linking me to that discussion, and your support, thank you!

That discussion you linked mentioned a hostname=my-website.com filter. I poked around this repo a little bit, searching the keyword "hostname," but it doesn't seem like this feature is anywhere on the horizon. Which is fine, I was just wondering. :)

**Comment by metmarkosaric** [comment]
yeah, that feature has not been built yet
