### ISSUE TITLE
400 Status when the client sends a header with a space in its name

### ISSUE THREAD

**Issue by Gongui** [plausible/analytics#2079]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Self-hosting

### Describe the bug

I configured openlitespeed as a reverse proxy for Plausible (it is used for some Wordpress sites) and started receiving 400 responses when connecting to my Plausible instance trough https. Upon further inspection i found that openlitespeed sends the header "X-ForProto -Proto" which the Plausible server doesn't seem to like.

The error can be reproduced running a request like the following:

> \> curl http://127.0.0.1:8000/login -I -H "Some Header: test"
HTTP/1.1 400 Bad Request
connection: close
content-length: 0

**Note that 127.0.0.1:8000 points directly to the Plausible instance.**

The error happens on any kind of request not only pages.

### Expected behavior

Process the request, show a page, serve a static file, etc.

### Environment

```markdown
- OS: Manjaro Linux (using docker)
- Browser: Google Chrome, curl, Openlitespeed
- Browser Version: 103, 7.84.0, 1.7.16
```

**Comment by RobertJoonas** [comment]
Hi @Gongui!

I think it's invalid to use whitespace in a HTTP header field name in general. See https://stackoverflow.com/questions/31773667/handling-whitespaces-in-http-headers. I believe if you'd curl any other domain with that header present, it would respond with a status 400 Bad Request. Closing this as I don't think it's an issue on our side.
