### ISSUE TITLE
Percentages in bounce rate graph are miscalculated

### ISSUE THREAD

**Issue by danieljb** [plausible/analytics#2107]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

Percentages in the _bounce rate_ graph include extremely high values. It appears like some values are multiplied by `100,000,000`, here’s the API response JSON for a _bounce rate top stat_ of `38%`:

```json
{
  "imported_source": null,
  "interval": "date",
  "labels": ["2022-08-10", "2022-08-11", "2022-08-12", "2022-08-13", "2022-08-14", "2022-08-15", "2022-08-16"],
  "plot": [0, 100, 4294967271, 0, 0, 80, 50],
  "present_index": 6,
  "with_imported": false
}
```

When dividing the extreme number `4,294,967,271 / 100,000,000` the resulting average almost corresponds to the top stat shown:
```
(0 + 100 + (4294967271 / 100000000) + 0 + 0 + 80 + 50) / 7 = 38.9928103871
```

This only happens on one of four registered websites in our Plausible account. The rest is working as expected.

### Expected behavior

Bounce rate values should be between `0` and `100` percent.

### Screenshots

![bouncerate](https://user-images.githubusercontent.com/630609/184847100-a294e2b0-a637-47db-bd89-adfa05fe97d4.jpg)

### Environment

```markdown
- OS: macOS
- Browser: Firefox
- Browser Version: 103.0

also validated:
- OS: macOS
- Browser: Chrome
- Browser Version: 104.0.5112.79
```

**Comment by duckchip** [comment]
I can reproduce this issue when fetching results from the stats/aggregate api endpoint. 
It's seems to happen only in a few cases. Out of 8000 requests, we had this problem 7 times. 

The value we receive is always 2147483647, which is the MAX value for an INT32

**Comment by ukutaht** [comment]
Good clues, thank you!

**Comment by metmarkosaric** [comment]
this is now fixed!
