### ISSUE TITLE
Import / export all data

### ISSUE THREAD

**Issue by tckb** [plausible/analytics#211]
## Prerequisites
- [x] I have searched open and closed issues to make sure that the feature has not yet been requested.

Similar features were requested in https://github.com/plausible/analytics/issues/210 and https://github.com/plausible/analytics/issues/142 asking about importing data into Plausible. 

## Feature request

The Idea of this feature is that we need to enable an easy import of events into Plausible from the external vendors such as GA or other analytic solutions. To make an external import easier I propose the following --

### Define Import Data format
Since, the idea is to import only analytics data, i.e, the event data it is possible to import this directly into Clickhouse.  Clickhouse already suppports data import via CSV (related docs [here](https://clickhouse.tech/docs/en/interfaces/formats/#csv)).  We can define any additional fields required in the format and enable import.

### Exporter plugins/scripts 
Since, we now have a "pre-defined" format of data to be imported, we can now start writing exporters for different vendors or different use-cases: 

- Import from GA is possible for by downloading GA data and _exporting_ it into plausible format and then _importing_ it.  This can achieved completely in the UI
- For any other non-supported vendor, one can run the exporter and then import it. 
- The same way it is possible to import analytics data from server-side logs

**Comment by ukutaht** [comment]
Agreed, defining an import spec would make things easier for sure. Couple thoughts:
1. A super important use-case here is moving from Plausible Cloud to self-hosted and back. We don't want to keep anyone hostage. Making it super easy to go from hosted to self-hosted would give customers more ownership of their data.
2. I haven't looked into what's offered but I doubt most tools will export event-level data. I'm guessing the exports are aggregated to daily or monthly stats. This creates a problem in our schema as currently all stats are done based on event-level data. We might need special schema design for 'imported aggregated stats'.

**Comment by tckb** [comment]
> super important use-case here is moving ...

this is a very legit use-case. I totally see this coming and this can addressed by keeping a consistent data format (spec) for both exporting and importing data. This keeps the implementation simple. 

>I'm guessing the exports are aggregated to daily or monthly stats...This creates a problem in our schema 

You are right. Free Plan on GA provides only aggregated stats.  Only premium plan members are able to extract full raw event data. 

>we might need special schema design for 'imported aggregated stats'.

I think there should be a way to import aggregated data and "spread"  this data (of course this factually will not be true data). 

as a first step, I believe we need to get the data format (spec) prepared.

**Comment by hirusi** [comment]
> * A super important use-case here is moving from Plausible Cloud to self-hosted and back. We don't want to keep anyone hostage. Making it easy to go from hosted to self-hosted would give customers more ownership of their data.

Is there any active interest in this at the moment?

**Comment by ukutaht** [comment]
Not that I'm aware of

**Comment by vincentdoerig** [comment]
Hi there. In order to write a migration tool, the data schema for the various other analytics platforms have to be known to the team. 

I'll start off with the schema from [Simple Analytics](https://simpleanalytics.com/). Since I can't directly upload CSVs here, I have uploaded it as a gist: https://gist.github.com/vincentdoerig/7b108450b46c8ad2de433f7cdd47486b

The data is cleaned up from a personal site, everything should be pretty self-explanatory.

// cc @metmarkosaric

**Comment by dewey** [comment]
Hey, adding to this I have the schema for http://get.gaug.es - they don't offer an export but I wrote a tool today (https://github.com/dewey/gaug.es-analytics-export) to export the daily aggregated data. In this case I use the same format they return it in the API but it could be adapted to support whatever "aggregated events" schema we come up with.

In this case the format is just:

```
date,views,people
2020-07-11,11,7
2020-07-12,21,15
```

**Comment by BloodShura** [comment]
+1. Would be much appreciate if we could import data from Google Analytics (just like Matomo does too).

**Comment by telmiger** [comment]
+1 As [mentioned in the forum](https://plausible.discourse.group/t/plans-for-more-downloads/166/3) I am interested in exporting features mostly (Goal Conversions in combination with campaign tracking data).

**Comment by tckb** [comment]
I haven't had a lot of time in the past months to do some work here. I will muster some time and get something done to help this task. @ukutaht  did you manage to do anything wrt to this topic?

**Comment by ukutaht** [comment]
Not yet @tckb
