### ISSUE TITLE
Filters with custom properties are not editable

### ISSUE THREAD

**Issue by zabatonni** [plausible/analytics#2110]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Self-hosting

### Describe the bug

When I click on custom props in Goals section, filter is created in top section, but it is not clickable nor editable. When I hover over, title says "[object Object]".

I'm able to change filters by directly changing params in URL.

### Expected behavior

I would like to change filters with custom properties like other filters. 

### Screenshots

![image](https://user-images.githubusercontent.com/1357370/184911619-77c46ed2-6157-49ab-8e87-94c3e7ffd669.png)

### Environment

```markdown
- OS: windows
- Browser: chrome
- Browser Version: 104
```

**Comment by ruslandoga** [comment]
@zabatonni 👋

I wonder if you could check if it's still reproducible in [`v1.5.1`?](https://github.com/plausible/analytics/discussions/2507)

**Comment by zabatonni** [comment]
in v1.5.1 it's solved
