### ISSUE TITLE
Events are shown multiple times

### ISSUE THREAD

**Issue by ps73** [plausible/analytics#2118]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Self-hosting

### Describe the bug

In my self-hosted instance I get a weird behavior in which some goals are shown twice in the overview.

When I click this event the results shown are correct. Since the responded events from the api are also correct I think that this may be just a display error.

### Expected behavior

Event should be displayed once.

### Screenshots

Twice shown event in overview: ![Bildschirmfoto 2022-08-18 um 09 27 15](https://user-images.githubusercontent.com/17291660/185336148-97526001-f983-4489-96ab-b8261662bcb3.png)

Detail view: ![Bildschirmfoto 2022-08-18 um 09 27 22](https://user-images.githubusercontent.com/17291660/185336570-9cb119dd-f29a-41d8-b2c9-7f011f225d27.png)

Api Results: ![Bildschirmfoto 2022-08-18 um 09 33 10](https://user-images.githubusercontent.com/17291660/185336881-aea36ea1-54ed-45cb-a5a7-c8365a95cb79.png)

### Environment

```markdown
- OS: MacOS
- Browser: Chromium
- Browser Version: 104.0.5112.81
```

**Comment by ukutaht** [comment]
Ah, maybe a missing React key... thanks for reporting!

**Comment by ruslandoga** [comment]
@ps73 👋

I wonder if you could check if it's still reproducible in [`v1.5.1`?](https://github.com/plausible/analytics/discussions/2507)

**Comment by ps73** [comment]
@ruslandoga I have not updated to `v1.5` yet. But it is on my bucket list and will give feedback on this after the update.

**Comment by vinibrsl** [comment]
This issue has been fixed by https://github.com/plausible/analytics/pull/2562 ✨ thank you for reporting!
