### ISSUE TITLE
Embeddable mode

### ISSUE THREAD

**Issue by cassidyjames** [plausible/analytics#213]
>## Precheck
>
>Please note that this tracker is only for feature requests. Do not use the issue tracker for help or support. [Our docs](https://docs.plausible.io/) are a great place for most answers, but if you can’t find your answer there, you can [contact us](https://plausible.io/contact). Thanks!

👍

>## Prerequisites

- [x] I have searched open and closed issues to make sure that the feature has not yet been requested.

>## Feature request
>**Is your feature request related to a problem? Please describe.**

I am making a [native/web hybrid Plausible app](https://github.com/cassidyjames/plausible) (think: similar to Electron, but more native) for my own use on elementary OS and probably distribution on [Flathub](https://flathub.org) or [AppCenter](https://developer.elementary.io). I would like to have more of the app native than just having one big web view, so I can follow the native design patterns of elementary OS.

>**How would you like it to work**
>A clear and concise description of what you want to happen.

I have thought of three potential solutions:

1. An “embedded” flag, i.e. via URL query parameter, that tells Plausible to hide the header, footer, and other bits of navigation. The embedding app would be expected to implement that navigation in its own (native) way.

2. Individually embeddable widgets, so a native app could have smaller web frames that just show the specific graphs/widgets as needed. These could also be useful if a site wanted to share some social proof—similar to #119.

3. A full REST/JSON API of some sort. That would be a lot more work for everyone, but ultimately the most flexible. 

For my uses, I prefer solutions 1 or 2 the most.

>**Screenshots (If applicable)**
>If applicable, add screenshots to help explain the proposed solution.

Here's what I'm doing with my app:

![20200709_134939.jpg](https://user-images.githubusercontent.com/611168/87084192-0eeb5300-c1eb-11ea-8f1c-1ffc47b51a65.jpg)

I hide the top and bottom navigation manually by injecting CSS, and then show certain buttons in the native HeaderBar depending on the current page.

**Comment by ArsalaBangash** [comment]
Hi! I'd love this feature as well to display on my org's website org.grey.software/stats

I'm in favor of the first implementation as a minimally viable solution at this point.

**Comment by ArsalaBangash** [comment]
Hi @cassidyjames, I've emailed Plausible Analytics about this issue and CC'ed you. This would be a very useful feature for @grey-software because I'd like to display weekly analytics on https://grey.software/this-week

How did you manage to get the screenshot working? 

I get the following error: 

``The loading of “https://plausible.io/grey.software” in a frame is denied by “X-Frame-Options“ directive set to “SAMEORIGIN“.``

**Comment by cassidyjames** [comment]
@ArsalaBangash my screenshot is of a native app, so the Plausible site is actually loaded in the top-level of a webkit frame—not embedded into some other page.

**Comment by bradkane** [comment]
Having my team take a run at this.  Currently thinking of allowing embed mode on a per website basis and adding the necessary header (either Content Security Policy or X-Frame) to allow analytics page to be embedded only in the domain tracked.  For example, if abc.domain.com is the tracked website, then analytics page can only be embedded in domain abc.domain.com.

**Comment by cassidyjames** [comment]
@bradkane that sounds interesting and probably a good approach. Just to clarify my use case, though: I would be embedding the Plausible dashboard into a native app, not a website. So as long as this solution works for both, it sounds reasonable to me. Of course for my uses, I can also control the “browser” itself and decide how it injects CSS, handles headers, etc. so some of that is not directly needed for me.

I think the biggest thing for me is hiding the footer and any other “website” sort of UI from the Plausible side; while this can be achieved with external CSS, it is more prone to breaking than of the Plausible codebase was aware of an “embedded” flag that could also alter its own UI to make it more friendly to being embedded.

**Comment by bradkane** [comment]
@cassidyjames The external CSS is a nice to have, rather than a need to have and technically doesn't really relate to "embeddable" featureset.  External CSS is optional and not required for "embeddable" solution.  When the "embeddable" flag is detected, we are planning on suppressing the header/footer and adding the necessary addition to the headers.  In your native app, will a SAME ORIGIN restriction work?  We were going to implement it that way to reduce potential for configuration errors and security issues.

**Comment by cassidyjames** [comment]
@bradkane I believe that should be fine, yes.

**Comment by davidsteeb** [comment]
@bradkane This sounds interesting for us, as we would like to include a shared dashboard inside our TYPO3 CMS's backend so editors can have a convenient way to access statistics.
