### ISSUE TITLE
Exclude Netlify deploy previews

### ISSUE THREAD

**Issue by mehulkar** [plausible/analytics#214]
## Precheck

Please note that this tracker is only for feature requests. Do not use the issue tracker for help or support. [Our docs](https://docs.plausible.io/) are a great place for most answers, but if you can’t find your answer there, you can [contact us](https://plausible.io/contact). Thanks!

## Prerequisites
- [x] I have searched open and closed issues to make sure that the feature has not yet been requested.

##Feature request

Exclude Netlify deploy previews from stats. Similar to how local host is excluded. 

**How would you like it to work**

A user provided list of domains to avoid tracking would be fine. 

**Screenshots (If applicable)**
If applicable, add screenshots to help explain the proposed solution.

**Comment by metmarkosaric** [comment]
Closing this in favor of #280
