### ISSUE TITLE
Feedback about timezone handling

### ISSUE THREAD

**Issue by toothbrush** [plausible/analytics#216]
## Prerequisites 
- [x] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report
When adding a new web property to Plausible, i selected my timezone (Australia/Melbourne, AEST, UTC+10).  However, when looking at the `?period=day` metrics, the display is in some other timezone.

**Expected behavior**
I expect activity to be reported in my local time, namely the timezone i set when adding my web property.

**Screenshots (If applicable)**
![image](https://user-images.githubusercontent.com/423357/87237102-3d5c6e80-c435-11ea-86ba-81a810ce0c7a.png)
The screenshot above shows 9pm as the "current/in progress hour".  Whereas my local time is actually `11:46 AEST` (am). I would like that to be reflected in Plausible's interface, so i don't have to do mental arithmetic.

It appears Plausible is reporting in USA East-coast time.  For example:

```shellsession
$ TZ=America/New_York date   
Sat Jul 11 21:47:52 EDT 2020
$ date
Sun Jul 12 11:48:34 AEST 2020
```

**Environment (If applicable):**
macOS (10.15.5), desktop, Safari version 13.1.1

**Comment by tckb** [comment]
@toothbrush are you using the selfhood version or the cloud ?

**Comment by toothbrush** [comment]
I'm using the Playsible.io-hosted SaaS.

**Comment by ukutaht** [comment]
Fix is now deployed. @toothbrush can you confirm it's fixed on your end as well?

**Comment by daugsbi** [comment]
@ukutaht The timeline shows now "NaN undefined" in the timeline. Our Timezone is GMT +1.

![PlausibleBug](https://user-images.githubusercontent.com/5528706/87406018-7aa13780-c5c0-11ea-977f-9e5daf2d8d6d.png)

**Comment by metmarkosaric** [comment]
Same issue for me https://plausible.io/markosaric.com

**Comment by toothbrush** [comment]
It appears working for me, but.. That code looks quite brittle, no?

https://github.com/plausible/analytics/commit/c6714b3ce0a105299ccf72701fcb08cc0501f71a#diff-ee2aa1b1643fbc4c7f825ead3c4fb0afR110-R111

I'm no JavaScript developer, but wouldn't it be better to use a native function to parse the date and then get the components that way, instead of a `split`?  ~Also, unrelated, but later on i see there's a bunch of logic to work out 'am' and 'pm' and such hard-coded. I wonder if a format string would be more appropriate there?~ Uh oh, it looks like JavaScript doesn't have that.  Never mind.

**Comment by ukutaht** [comment]
My bad. Now both hourly and daily views should work OK.

**Comment by toothbrush** [comment]
Thank you! 🙏
