### ISSUE TITLE
`exclusions` extensions does not work with `hash` extension

### ISSUE THREAD

**Issue by vincent-czi** [plausible/analytics#2167]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

The [`exclusions` extension](https://plausible.io/docs/excluding-pages) appears to not work when capturing hash-based routing via the [`hash` extension](https://plausible.io/docs/hash-based-routing).

I'm developing locally with this script src `https://plausible.io/js/script.exclusions.hash.local.js`. For non-excluded pages, everything is working great. However, I've included a `data-exclude` with value of `"/#/fetch/**"`. I can see the attribute is correctly set in the dom, but Plausible is still sending pageview events when I visit routes under that, eg `/#/fetch/sensitiveData`. I thought it might be that the `#` character was messing things up, but changing the data-exclude to `"/#/fetch/**"` did not fix it either.

Looking into the code here, I think the issue is that the [`exclusions` portion of the tracker code](https://github.com/plausible/analytics/blob/99fd101135f0a992f4a38df627622496268e5a6d/tracker/src/plausible.js#L42) relies on the function `pathMatches`, which itself relies on `location.pathname`, so it's only extracting the non-hash part of the URL, so it's impossible to exclude anything hash-based there.

### Expected behavior

The `excludes` extension to work the same for hash-based routing.

### Environment

```markdown
- OS: MacOS
- Browser: Chrome
- Browser Version: 104.0.5112.101 (Official Build) (x86_64)
```

**Comment by RobertJoonas** [comment]
Thanks for reporting that @vincent-czi!

Indeed, a `script.exclusions.hash.js` extension wrongly ignores the hash part of the URL when excluding pages. I've created a PR with a fix for this.

**Comment by vincent-czi** [comment]
That is a fast fix! Much appreciated!

**Comment by vincent-czi** [comment]
@ukutaht Hi, I looked over the PR and I'm sure it will fix the issue, but it doesn't seem to have gone live yet. I see it's been merged, but the bug is still present (even after clearing my cache). When I grab the script (https://plausible.io/js/script.exclusions.hash.local.js) it looks like it hasn't actually changed to represent the merged PR yet.

I don't know your deploy process: if it's been merged, do you have an expectation of when I'll start seeing the change in the script I'm loading? Thanks!

**Comment by ukutaht** [comment]
Will deploy it tomorrow. Sorry we'll make it clearer what's deployed and what isn't in the future :)

**Comment by metmarkosaric** [comment]
it's live now!

**Comment by vincent-czi** [comment]
Great! Can confirm it works as expected!

Sadly, I realize now that I missed the forest for the trees: it appears that using a `HashRouter` with `react-router-dom` means that hash changes do _not_ register as `hashchange` events because they go through the `history.pushState` API instead. This appears to work as designed and is not the fault of Plausible, but it means that a pretty common React + react-router set up using the Plausible `hash` extension won't actually work as expected. I'll write up another issue and you guys can decide what you think of it there.

Regardless, thanks for the fast fix on this!
