### ISSUE TITLE
Dynamic custom event support

### ISSUE THREAD

**Issue by mkay581** [plausible/analytics#218]
## Prerequisites
- [x] I have searched open and closed issues to make sure that the feature has not yet been requested.

## Feature request

**Is your feature request related to a problem? Please describe.**
I'm trying to use custom events that are dynamic. Ex. User clicks to play video, I'd like to track which video was clicked by adding the video ID in the string sent to Plausible. But I can't get the events to show up because Plausible only allows for specific strings.

**How would you like it to work**
I'd like to be able to send custom event strings with dynamic data and have them show up in the dashboard.

**Comment by ukutaht** [comment]
Hey, thanks for your suggestion!

Do you think #134 would also solve your use-case? You could have one event `Play Video` or something like that and send the video ID as metadata. Would that work?

**Comment by mkay581** [comment]
Hmm I must've missed #134 in my search before creating this issue. But I guess it would depend on how the events would show up in the dashboard (I still can't see custom events there even though I've manually added them to my account). 

I was hoping to be able to see all a user's events in chronological order in a very "human readable" way:

```
Signed Up
    |
Clicked to Open 'Welcome' Banner 
    |
Dismissed 'Welcome' Banner
    |
Played 'Cooking' Video
    |
Paused 'Cooking' Video
```
In the above, `Welcome` and `Cooking` would be dynamic variables that I'm already tracking in my application.
If we do #134, I would assume this sort of human readable arrangement wouldn't be possible, right?

**Comment by metmarkosaric** [comment]
There's also #171 which is about visualizing events in a funnel. Your request seems to be a mix of both? First you need to be able to add some metadata to the individual events and then you also need to be able to assign relevant events as part of a funnel so you can the user progress in a more visual way.

**Comment by ukutaht** [comment]
@mkay581 Can you make your use-case work with the recently launched [custom event props](https://docs.plausible.io/custom-event-goals#using-custom-props)?

**Comment by mkay581** [comment]
@ukutaht thank you. I'll try to configure it this weekend and see if all is well but it definitely looks like it would give the ability to do what I mentioned. I'm just not sure if looking at the the custom events will allow me to easily see which events led up to the custom one. Should I wait on #171 for that?

**Comment by metmarkosaric** [comment]
Yeah, this would cover the first part of your request but not the funnel part. But would be good to hear from you after you try it out. I'll close this for now as we have #171 for the funnel part of your request.

**Comment by mkay581** [comment]
@ukutaht @metmarkosaric Just implemented this on my site and works really well! I can see all the custom events in the dashboard. It's more of a data dump so kinda difficult to wrap my head around. So I'll wait for a better way to visualize it similar to what I mentioned in [my comment above](https://github.com/plausible/analytics/issues/218#issuecomment-658703111). Thanks again!

**Comment by metmarkosaric** [comment]
good to hear @mkay581! we plan to introduce some kind of funnel visualisation feature at some point in the future. cannot promise any timeline at this stage.
