### ISSUE TITLE
Alternative geolocation database

### ISSUE THREAD

**Issue by ColdHeat** [plausible/analytics#219]
I saw Plausible on HN awhile ago and noticed that it used Maxmind databases for ip to country mapping. I had a similar issue myself and did not want to force users to download the database and attribute IP data to Maxmind for basic country dat

I wrote an open source country geoip database that perhaps could be useful: 
https://github.com/geoacumen/geoacumen-country

I am using it in my own projects and intend to make it automatically publish new versions every so often. 

I imagine this is more of something that self-hosters could use but I figured I would mention it.

**Comment by ukutaht** [comment]
Thanks for the suggestion (and sorry for my slow response).

I'm definitely interested in packaging a freely licensed country database with Plausible so people don't have to bring their own. As you probably know, I can't distribute Maxmind's own database easily.

A couple questions:
* Are there any accuracy pitfalls with iptoasn.com ?
* Is there any freely available datasets that go to city level? More granular location data has been requested many times.

**Comment by ColdHeat** [comment]
From my research and discussion with people, leveraging a mapping from an ASN to their IP ranges is more reliable than using the RiR's directly published data. 

I don't know the accuracy of iptoasn or the approach in general. But I'm willing to add more data sources if they can be provided to me. 

As for a city level database, I've been trying to do that myself as well and it basically seems impossible unless you use another company's data (and deal with the licensing) or if you build the dataset yourself.

**Comment by ukutaht** [comment]
Thanks!

I'm thinking maybe it's possible to package your country database with Plausible and ask people to bring their own only if they want city level data.

So I'm in favour of packaging the geoacumen database and leaving a config option open to use a custom database. I don't have much motivation to work on this at the moment as we're already running MaxMind happily. Happy to merge a PR for this, I can't give a timeline for when I can pick it up myself.

**Comment by Findus23** [comment]
Hi,

Just for your information: Since the Maxmind license change at the beginning of 2020, Matomo uses the free db-ip database by default:
https://db-ip.com/db/lite.php

It works like the Maxmind database, but is still licensed under a Creative Commons Attribution 4.0 International License.

**Comment by ukutaht** [comment]
Thanks @Findus23 

I like this option more as it also includes cities, which is a highly requested feature for Plausible.
