### ISSUE TITLE
AMP measurement support

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/analytics#220]
"My website supports AMP. Given that AMP is growing, measuring this would be key for me. The AMP standard is an open one. There were more than 55 analytics providers supporting AMP even in 2018, like Amplitude or Adobe Analytics or New Relic. [Here's a link](https://instapage.com/blog/amp-analytics) with a bunch of the AMP API spec for many providers."

feedback via email

**Comment by gergelyorosz** [comment]
Here is the documentation on how to be added as an AMP vendor: https://amp.dev/documentation/components/amp-analytics/ . Here's an [example PR for RudderStack ](https://github.com/ampproject/amphtml/pull/28597/files)on being added as a vendor or one [for BlueConic](https://github.com/ampproject/amphtml/pull/28102/files).

**Comment by tckb** [comment]
@gergelyorosz  I plan to add this in my next PR.  Keep a watch

**Comment by davidsteeb** [comment]
Any news on this? If you need support in testing let me know, eager to try this.

**Comment by HopsWrites** [comment]
Hey Plausible,

After inspecting my main URL on Search Console, it said the “AMP Page is invalid” due to custom Javascript not being allowed. The only custom script I have is Plausible's.

Google is moving to indexing only mobile-responsive pages.

Any updates on AMP and Plausible?

Thanks, and LOVE Plausible so far!  (-:

**Comment by metmarkosaric** [comment]
Thanks, glad to hear that! We're about to release metadata for goals and after that [our roadmap](https://github.com/plausible/analytics/projects/1) is focused on other popular requests (browser/os versions, API, export/import). After that we'll consider what to do next and see if we can put AMP on the roadmap at that point. Obviously if there's a PR before, we'll happily merge it. You don't have a native mobile responsive page but only an AMP?

**Comment by HopsWrites** [comment]
Thanks for getting back!

Well, I revised my blog using Publii, which offers code injection for both
the main site (which is mobile responsive), and AMP. I had placed Plausible
code in both Headers, but Google Search Console said the custom Javascript
invalidated my AMP page. No idea why. I removed the code from AMP for now.
My blog is at blog.hopswrites.com

Thanks for your time.

-Jordan

**Comment by metmarkosaric** [comment]
Makes sense. Can see that your blog is mobile responsive on its own too. For AMP, we'll need to be added as a vendor before Plausible can be used on AMP pages.

**Comment by HopsWrites** [comment]
Thanks for checking and replying!
