### ISSUE TITLE
Unable to deploy on ARM machines 

### ISSUE THREAD

**Issue by hexclann** [plausible/analytics#2206]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Self-hosting

### Describe the bug

I followed the official documentation and tried deploying using docker on my Raspberry Pi 4. However the containers keep on restarting.

### Expected behavior

All containers should be running and UI should be accessible on the specified port 

### Environment

```markdown
- OS:Debian 11
- Browser: Chrome
- Browser Version: 105
```

**Comment by metmarkosaric** [comment]
hi @hexclann! Plausible doesn't support ARM at the moment. you can read more here https://github.com/plausible/analytics/discussions/903
