### ISSUE TITLE
Plausible Chrome tab hangs if left open for too long

### ISSUE THREAD

**Issue by janvitos** [plausible/analytics#2210]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Self-hosting

### Describe the bug

When leaving Plausible open (**realtime**) in a Chrome tab for an extended period of time (many hours), it hangs and cannot be used until the tab is reloaded.

I noticed this mostly happens when opening the Plausible Chrome tab in the morning after leaving my computer open overnight.

### Expected behavior

I would expect the Plausible Chrome tab to remain functional even after many hours of interrupted use.

### Environment

```markdown
- OS: Windows 11 21H2
- Browser: Chrome
- Browser Version: 105.0.5195.102
```

**Comment by metmarkosaric** [comment]
thanks for reporting @janvitos! hmm sounds weird. i keep my Plausible dashboard in a Firefox tab all day long every day and haven't encountered this. nobody has reported this either. to me it sounds like an environment specific issue rather than a bug. you could post in our self-hosted community forum with details on your traffic, server capacity etc and and perhaps someone can help in terms of what type of server you may need so everything runs optimally: https://github.com/plausible/analytics/discussions/categories/self-hosted-support.

**Comment by janvitos** [comment]
Hi @metmarkosaric, thanks for your quick response.

The Plausible instance itself doesn't actually hang or crash. It's the Chrome tab that hangs, like if there was a memory leak in the Plausible application.

I'm closely monitoring the server with different tools, and it is running at 2-3% CPU capacity and 70% memory capacity, so I doubt the server has anything to do with the issue.

I will install Firefox to test and see if I can replicate the issue there.

**Comment by janvitos** [comment]
Alright, I've done my tests on both Chrome and Firefox, and here are my results.

**Chrome**

I woke up this morning and directly when to the Plausible realtime Chrome tab. As I expected, the tab was unresponsive. 
https://imgur.com/a/kyiunUm

This time, instead of force closing the tab, I let it idle for some time. To my surprise, the tab became responsive again after 30-40 seconds.

**Firefox**

After testing the Chrome tab, I went to the Plausible realtime Firefox tab. The tab was responsive and did not hang.

I will close this ticket as it seems the problem resolves itself on Chrome after a little while.
