### ISSUE TITLE
Import stats from Google Analytics 4 properties are missing

### ISSUE THREAD

**Issue by matthieucaron64** [plausible/analytics#2218]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

I only see the GA Universal Analytics properties in the dropdown selection when I use the import feature. The GA4 properties are missing but the Universal Analytics properties are available (and functional). Maybe because I have both type of properties on my account ?

### Expected behavior

Get the GA4 & GA Universal Analytics properties available in the drop-down selection when the import is made.

### Environment

```markdown
- OS: Mac OS
- Browser: Chrome
- Browser Version: 105.0.5195.102
```

**Comment by metmarkosaric** [comment]
hi @matthieucaron64! Our Google Analytics import works for UA properties only at the moment as that's the main product that most people use and want to switch away from. We hope to build a GA4 import in the future when that becomes the default Google Analytics experience.

**Comment by matthieucaron64** [comment]
Hi @metmarkosaric!

Thank you for your quick reply and this information, it's a great news that Google Analytics import is back.

Good continuation ! 💪

**Comment by metmarkosaric** [comment]
Thank you! Enjoy Plausible!

**Comment by navendu-pottekkat** [comment]
@metmarkosaric Do you have any plans to implement import from GA4 in the near future? I think many people might have switched to GA4 after Google repeatedly mentioned that UA is deprecated. It is the only issue I have from completely switching a couple of websites to Plausible. Thanks!

**Comment by kgantchev** [comment]
Is there a way to do a manual import from GA4?

**Comment by olimortimer** [comment]
Ah, so this is why I have a large chunk of data missing from my GA import?

Any plans to support the import of GA4 data soon?

**Comment by ruslandoga** [comment]
@olimortimer 👋 

GA4 imports are supported now. In the self-hosted version they are supported in the latest v2.1.0 release candidate: https://github.com/plausible/analytics/releases

**Comment by olimortimer** [comment]
Thanks for the quick reply @ruslandoga !

Great news, however I've just run through the instructions, containers are running, but Plausible isn't loading.

```
curl http://localhost:8000
curl: (52) Empty reply from server
```

```
curl http://localhost:8000
curl: (56) Recv failure: Connection reset by peer
```

**Comment by ruslandoga** [comment]
@olimortimer let's move the discussion to https://github.com/plausible/analytics/discussions/4084

To start debugging, we'd need `docker compose logs` and more information about your setup (proxy/no proxy, `docker-compose.yml`, etc.)
