### ISSUE TITLE
Graph - NaN Undefined when custom date range is applied

### ISSUE THREAD

**Issue by dragstor** [plausible/analytics#222]
## Prerequisites 
- [x] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report
**Describe the bug**
When custom date range is applied, the x-axis on graph displays `NaN Undefined` instead of specific date.

**Expected behavior**
Each tick on X-axis should have designated date from the selected range.

**Screenshots (If applicable)**
![Dates issue](https://i.imgur.com/jnQ6Ww2.png)

**Live link**
https://plausible.io/hostedstatus.page?period=custom&from=2020-07-01&to=2020-07-14

**Environment (If applicable):**
 - Browser
 - Latest Plausible live

**Comment by ukutaht** [comment]
Fixed on production instance now. Related to #216
