### ISSUE TITLE
Get data about several pages having in common a part of the URL using the GET api/v1/stats/timeseries API endpoint

### ISSUE THREAD

**Issue by danielegaliffa** [plausible/analytics#2220]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

Hello.
I tried to use the GET listed above to get traffic data related to several pages having the "blog/" prefix in their URLs.

`{{BASE_URL}}/api/v1/stats/timeseries?site_id={{mysiteID}}&period=6mo&date=2022-09-01&interval=date&filters=event:page==/blog/**`

If I run the API call listed above, I get 0 for every single day in the interval, even if the same filter "Page is /blog/**" in the Plausible.io dashboard provides clear data about each within the time-frame.

Maybe the "event:page" option in the filter parameter doesn't support the wildcard character?

### Expected behavior

I do expect to get data filterd by page:name using wildcard character

### Environment

```markdown
- OS: Windows 10
- Browser: chrome
- Browser Version: latest
```

**Comment by danielegaliffa** [comment]
I close the issue since I discovered that the filter should have been `filters=page:name` and not `filters=event:page`.

Sorry

**Comment by metmarkosaric** [comment]
hi @danielegaliffa! wildcards are not supported in the stats API unfortunately, they're only supported directly in the dashboard. there's a thread about this in our forum where we keep track of all feature requests: https://github.com/plausible/analytics/discussions/1282

**Comment by danielegaliffa** [comment]
I need to reopen the issue since I discovered that the `filters=page:name` didn't work...the API replies with the traffic data of the whole website :-(

**Comment by danielegaliffa** [comment]
@metmarkosaric thanks for your feedback
