### ISSUE TITLE
** pattern does not work on the API

### ISSUE THREAD

**Issue by wladiston** [plausible/analytics#2221]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Self-hosting

### Describe the bug

The ** for matching any page works perfectly on local
<img width="1177" alt="Screen Shot 2022-09-13 at 2 35 38 PM" src="https://user-images.githubusercontent.com/1843792/189971629-18583569-e840-49d3-8ad7-a0ff68154cd4.png">

But on the API it does not
<img width="1046" alt="Screen Shot 2022-09-13 at 2 39 00 PM" src="https://user-images.githubusercontent.com/1843792/189972519-9e852dbf-c9a1-43ce-8ce3-b1d12e886b44.png">

### Expected behavior

It should work as the web version

### Environment

```markdown
- OS: 
- Browser:
- Browser Version:
```

**Comment by vinibrsl** [comment]
Thanks for the suggestion, @wladiston! We use GitHub Discussions for discussing and tracking new features, and there is one open with what you described #1282
