### ISSUE TITLE
Favicon missing

### ISSUE THREAD

**Issue by dewey** [plausible/analytics#2256]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

It looks like some favicons are broken for the past 2 days. The URL it's calling is: `https://plausible.io/favicon/sources/Google` which just results in a not found image with http status code 200. There's a bunch of them that don't work in my dashboard.

<img width="98" alt="Screen Shot 2022-09-22 at 11 01 40" src="https://user-images.githubusercontent.com/790262/191705164-e1384218-b514-4d35-b486-24f8c3600b3e.png">

### Expected behavior

The favicon to show like before instead of an empty white square.

### Screenshots

See above

### Environment

```markdown
- OS: macOS
- Browser: Safari
- Browser Version: Version 16.0 (17614.1.25.9.10, 17614)
```

**Comment by taylorlapeyre** [comment]
<img width="253" alt="Screen Shot 2022-09-22 at 11 09 59 AM" src="https://user-images.githubusercontent.com/1610503/191820660-21b1a072-7df0-4a88-a0bb-16ed14e2c453.png">

Same issue here

**Comment by metmarkosaric** [comment]
thanks both for reporting! we're working on a fix https://github.com/plausible/analytics/pull/2257. thanks for your patience!
