### ISSUE TITLE
Direct Traffic Does Not Appear In Top Sources Preview

### ISSUE THREAD

**Issue by jsm386** [plausible/analytics#2276]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

When looking at the dashboard for for any time period other than realtime, direct traffic does not appear among the top sources in the top sources overview/preview? container. After clicking 'details' to reveal all of the top sources, Direct appears where it belongs in the list. This is _not_ the case that Direct doesn't make the cutoff for inclusion before clicking See Details, rather it simply doesn't appear regardless if it is in the top 3/5/etc

### Expected behavior

If Direct is one of the top 9 sources for traffic in a given time period, it should appear in the Top Sources container without having to click to display all of the top sources.

### Screenshots

![preview](https://user-images.githubusercontent.com/2320172/192576924-180afb45-796d-4bc1-b744-e9810f51b2aa.jpg)
![detail](https://user-images.githubusercontent.com/2320172/192576927-5edaa5df-f078-4894-b2e2-6e82a661c7fb.jpg)

### Environment

```markdown
- OS: Mac OS
- Browser: Safari
- Browser Version: 16
```

**Comment by metmarkosaric** [comment]
thanks for the feedback @jsm386! this is an intentional choice from us as many people asked for "direct/none" not to be displayed in the main view. it stands for majority of traffic for many sites so it skews the comparison we have and it's also less actionable than the regular sources.

**Comment by jsm386** [comment]
Got it. Any chance we could get a settings toggle to enable that?

**Comment by metmarkosaric** [comment]
perhaps we can do that in the future. there are no current plans to do this that i can promise you about. until now, we've tried not to introduce any optional settings like these as they would make Plausible more difficult to use while we try to focus on being as simple and easy to use as possible.

**Comment by ukutaht** [comment]
Closing the issue as the product is working as designed
