### ISSUE TITLE
Getting certificate error when using Events API and documentation site

### ISSUE THREAD

**Issue by markcellus** [plausible/analytics#2283]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

Getting the following certificate error when attempting to fetch/curl to plausible event's API. It was working before today. I also tried navigating to https://plausible.io/docs/events-api and getting a certificate error as well.

```
Message: request to https://plausible.io/api/event failed, reason: Hostname/IP does not match certificate's altnames: Host: plausible.io. is not in the cert's altnames: DNS:*.b-cdn.net, DNS:b-cdn.net
```

### Expected behavior

No error.

### Environment

```markdown
- OS:
- Browser:
- Browser Version:
```

**Comment by metmarkosaric** [comment]
Thanks for reporting @markcellus! Our CDN provider seems to be having some issues. We're back up now and our team is investigating what happened. Sorry for the inconvenience!
