### ISSUE TITLE
Favicons only offered in SVG format show as broken images in site dropdown

### ISSUE THREAD

**Issue by Lucent** [plausible/analytics#2286]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

Sites which only offer a favicon in SVG format, which is now accepted by all browsers, will appear as a broken image in the site selector dropdown.

### Expected behavior

Site icon is displayed.

### Screenshots

![image](https://user-images.githubusercontent.com/106736/193192796-1943ac2d-dadd-41d2-89bb-69519009a788.png)

**Comment by metmarkosaric** [comment]
thanks for reporting @Lucent! we get all the favicons (your site favicon and the favicons of all the referral sources) directly from the DuckDuckGo API and don't have any control over them. we display the same icon that DuckDuckGo shows in their search results and i can see they also show the broken image for your favicon in their search results. seems like they don't support this format? we will automatically show any new favicon that you add as soon as DDG shows it too so
