### ISSUE TITLE
Spaces in tracking parameters not displayed properly

### ISSUE THREAD

**Issue by corbindavenport** [plausible/analytics#229]
**Describe the bug**
Spaces in utm tracking parameters are not displayed as spaces. Other characters might be broken as well. This is the sample URL I was testing with:
```
https://edit.photostack.app/?utm_source=Android%20App
```

**Expected behavior**
Google Analytics converts `%20` to a space when displaying information.

**Screenshots (If applicable)**

![image](https://user-images.githubusercontent.com/3879063/87798387-f1853d00-c819-11ea-9d8c-25d4b5628f47.png)

**Environment (If applicable):**
 - OS: Linux
 - Browser: Firefox
 - Version 77

**Comment by fabianfett** [comment]
I can see this problem as well. Though not for spaces but for pluses “%2B”. 

Further it would be great if the source for “hello%2Bworld” could be merged with “hello+world” in the dashboard.

**Comment by nsitti** [comment]
Ok

Le jeu. 6 août 2020 à 08:05, Fabian Fett <notifications@github.com> a
écrit :

**Comment by ukutaht** [comment]
@corbindavenport @fabianfett I have now deployed a fix to the live site. Can you confirm the issue is resolved on your side?

**Comment by fabianfett** [comment]
@ukutaht Works for me. Thanks so much for fixing this!
