### ISSUE TITLE
431 (Request Header Fields Too Large)

### ISSUE THREAD

**Issue by grempe** [plausible/analytics#2339]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

We are getting 431 (Request Header Fields Too Large) when using next-plausible and auth0/nextjs-auth. The auth library sets a couple of http only cookies for an encrypted session which are quite large (size 4000 and 3300 respectively).

This was originally filed as a bug for this wrapper library but my inclination is that this is the plausible server rejecting these valid requests.

https://github.com/4lejandrito/next-plausible/issues/67

### Expected behavior

Proxied requests should not throw 431 errors.

### Environment

```markdown
Next.js application hosted on Vercel
```

**Comment by vinibrsl** [comment]
We've increased our maximum header length to be more permissive (#2353), and it's already in production. That fixes HTTP 431 errors but this still need to be addressed in https://github.com/4lejandrito/next-plausible/issues/67, as @grempe [mentioned here](https://github.com/4lejandrito/next-plausible/issues/67#issuecomment-1284034379).
