### ISSUE TITLE
Support server-side generated analytics data via POST from middleware

### ISSUE THREAD

**Issue by dch** [plausible/analytics#234]
## Prerequisites

- [x] I have searched open and closed issues to make sure that the feature has not yet been requested
- commented https://github.com/plausible/analytics/issues/210 but broken out for discussion

## Feature request

site visitors who disable javascript, or use adblocker tech, have their visits lost. CNAMEing and
similar tricks are already tracked and disabled by current adblockers, and this is likely to grow.

If we can send analytics data from the server side directly after each request, we get similar
data without needing any client-side tracking.

## How would you like it to work

If the `POST /api/event` format is documented, it should be possible to submit the analytics data
server side directly in the web framework, as pluggable middleware. This is both nice from a
configuration point of view, and also from an analytics view - we won't miss anything, and users
don't need to run the javascripts.

For example, in Elixir there are 2 major frameworks - Plug and Phoenix - which allow stackable
middleware. The analytics request can extract most of the info from haproxy or nginx details,
and the web server framework, so while we get a reduced set of info, we do get 90% of the value.

Ideally the `POST ...` request would only include the analytics data in the BODY, and use either
HTTP Headers or a query parameter to track an API key, so that these can safely be logged
locally without exposing plausible.io API tokens.

**Comment by tckb** [comment]
@dch Although, not explicitly documented, you can find the event data documented here https://github.com/plausible/analytics/blob/master/lib/plausible_web/controllers/api/external_controller.ex#L73  To be clear, this is the data posted to the event controller in **plain text**.


POST /api/event HTTP/1.1
Host: <plausible_base_url>
Content-Type: text/plain
```json
{
    "name": "pageview",
    "url": "https://domain-added-to-plausible.com/your-page",
    "domain": "domain-added-to-plausible.com",
    "referrer": "https://tldr.net",
    "source": "google",
    "user_agent": "Mozilla",
    "screen_width": 1920
}
```
_Most_  Appservers/Webservers dump the above information. 

NB: You need to pass-along the clients/visitors IP along with your call. use [`x-forwarded-for`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Forwarded-For)  header to pass on the IP.   

It being a plain rest call, you can write your own middle ware for your favorite framework for posting the data. 

Currently, there's no API key that is being passed along from the client side either. Technically, there's also some need of rate-limiting and/or filtering of bad-actors that might be addressed at a later point.

**Comment by ukutaht** [comment]
Same as #130, I will close that one in favour of this issue since the discussion seems to be here.

Generally this would work and I have planned to support something like this in the future. Two issues come to mind:
* We cannot get the screen width from server-side. Maybe it's better to align with most other tools and detect device type from User-Agent instead of screen width.
* Tons of bot traffic on server logs. We can exclude the ones that identify themselves via the User-Agent, but beyond that we don't do any sort of advanced bot detection. In a normal setup, having to load and run JS filters out a lot of bots

**Comment by tckb** [comment]
Regarding the bot detection, I have previously worked with [yauaa](https://techlab.bol.com/making-sense-user-agent-string) and is pretty great at detecting bots or getting any sense of client based on UA analysis, if you can [test it here](https://try.yauaa.basjes.nl/). I would like to implement this in elixir or probably for Plausible but more on that later.

**Comment by dch** [comment]
wow just seen that plausible is written in Elixir :-)  :rocket: :fire: :champagne:

**Comment by ItalyPaleAle** [comment]
I am (potentially) interested in this feature too.

I'd like to add that a REST endpoint for adding data would ideally allow for batching too, so the back-end could have a buffer internally and then submit the requests to Plausible at regular intervals. This would allow for much better performance.

From the standpoint of a REST API, it could be as simple as allowing an array of objects in addition to a single object, also providing the timestamp of the request.
