### ISSUE TITLE
Compress static files

### ISSUE THREAD

**Issue by RealOrangeOne** [plausible/analytics#235]
## Prerequisites

- [x] I have searched open and closed issues to make sure that the feature has not yet been requested.

## Feature request

**Is your feature request related to a problem? Please describe.**

It'd be great if the static files were compressed and served using gzip. For regular site files it might make the site feel snappier.

The real benefit comes from the `plausible.js` tracker:

```bash
$ curl -s https://plausible.io/js/plausible.js | gzip | wc --bytes
780
$ curl -s https://plausible.io/js/plausible.js | wc --bytes
1264
```

**How would you like it to work**

Files would be served gzip compressed assuming the relevant `accept-encoding` header was provided.

My knowledge of the Elixir ecosystem isn't great, but https://github.com/ne-sachirou/stream_gzip looks like it might work for serving `plausible.js`, as it's dynamic. https://www.dwightwatson.com/posts/gzip-static-assets-in-phoenix maybe for the regular assets?

**Comment by ukutaht** [comment]
Hey,

With `curl` you have to send a HTTP header to ask for it:
```
$ curl -s https://plausible.io/js/plausible.js | wc -c
1264

$ curl -s -H 'Accept-Encoding: gzip' https://plausible.io/js/plausible.js | wc -c
780

$ curl -s -H 'Accept-Encoding: br' https://plausible.io/js/plausible.js | wc -c
679
```

In modern browsers that support Brotli, you should see the compression encoding in devtools:

<img width="506" alt="Screenshot 2020-07-22 at 11 04 38" src="https://user-images.githubusercontent.com/3731516/88151253-2410aa80-cc0b-11ea-89ef-6dcafc1ffdc5.png">

**Comment by ukutaht** [comment]
Oh, in my case (the official Plausible Cloud deployment) it's the reverse proxy doing the compression. Is this request to make the service itself apply compression?

**Comment by RealOrangeOne** [comment]
Ah I see. I guess in reality the reverse proxy should be the thing doing the compression there. Although maybe being able to serve pre-compressed assets would make serving that bit easier.

The request _is_ to make the service do compression itself, although now I think about it I wonder whether it's better to encourage people to use a reverse proxy. Although that would make the selfhosting setup harder, and definitely shouldn't be something enforced. 

Maybe this issue is actually unnecessary?

**Comment by tckb** [comment]
@RealOrangeOne  Compressing of static files, js, html, css etc are taken care by the reverse proxy that is sitting in-front of your app, and in most cases is done automatically without you explicitly asking for it.  For eg,

```
$ http head https://analytics.dev.tgrthi.me/js/plausible.js
HTTP/1.1 200 OK
Connection: keep-alive
Content-Encoding: gzip
Content-Type: application/javascript
...
```

This could be your in-house edge server like ngnix, traefik etc or a cdn if you are deploying it else where. Edge servers have advantage of caching  the responses.  Compressing the static files on the app server in-time does increase the load on the server considerably and in most cases the responsibility of the edge servers.

**Comment by RealOrangeOne** [comment]
Yeah on reflection that's the opinion i'm leaning towards too. This is probably _just fine_ for right now. In future it might be better to pre-compress the regular assets at compile time so they don't need to be compressed as they stream, but that's not especially necessary right now!
