### ISSUE TITLE
Custom event goals not showing in dashboard

### ISSUE THREAD

**Issue by mkay581** [plausible/analytics#238]
### Precheck

Please note that this tracker is only for bugs. Do not use the issue tracker for help or support. [Our docs](https://docs.plausible.io/) are a great place for most answers, but if you can’t find your answer there, you can [contact us](https://plausible.io/contact). Thanks!

## Prerequisites
- [x] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report
**Describe the bug**
When I log into my dashboard, none of my custom event goals show up on my dashboard and I get an infinite spinner (see attached screenshot) with a 500 error in console. Tried on both Firefox and Chrome on Linux.

**Expected behavior**
Custom event goals show up on the dashboard.

**Screenshots (If applicable)**
![Screenshot from 2020-07-22 03-33-32](https://user-images.githubusercontent.com/1446916/88148470-a332be00-cbcc-11ea-8a44-17c296fe0b1e.png)

**Environment (If applicable):**
 - OS: Linux
 - Browser: Firefox, Chrome
 - Version: latest

**Comment by ukutaht** [comment]
Thanks for reporting. I can see a database error in our logs, will look into it as soon as I can.

**Comment by mkay581** [comment]
Hey @ukutaht any word on this? I'm still not seeing. I've replaced Google Analytics with Plausible so really need to see this data. Is the data even being tracked? Or have I lost all of the data all this time? Thanks!

**Comment by ukutaht** [comment]
Hey, sorry I'm still catching up with stuff. The data is being collected fine, just something doesn't like spaces in the goal names when querying them.

I will look at this immediately after #252 is live.

**Comment by mkay581** [comment]
Thanks so much for your help with this @ukutaht. I can see events in dashboard now. You are amazing ❤️

**Comment by ukutaht** [comment]
Thanks for reporting the issue! Hope nothing breaks going forward but do let me know 😄
