### ISSUE TITLE
"One" being a plural in the number of current visitors

### ISSUE THREAD

**Issue by TheEvilSkeleton** [plausible/analytics#239]
### Precheck

Please note that this tracker is only for bugs. Do not use the issue tracker for help or support. [Our docs](https://docs.plausible.io/) are a great place for most answers, but if you can’t find your answer there, you can [contact us](https://plausible.io/contact). Thanks!

## Prerequisites
- [x] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report
**Describe the bug**

It's not really a bug but rather a typo. When there is one [current] visitor, Plausible will say "One current visitor**s**.

**Expected behavior**

It should be saying "One current visitor" instead.

**Screenshots (If applicable)**

![image](https://user-images.githubusercontent.com/50847364/88225814-1e31be00-cc39-11ea-8eb8-6eada97b4220.png)

**Environment (If applicable):**

Everywhere

**Comment by ukutaht** [comment]
Pluralization in current visitors is now fixed but let's also fix in:
* The main graph when hovering (27 July - 1 Visitor)
* Country map when hovering (United States of America - 1 Visitor)
