### ISSUE TITLE
Percentage change of unique visitors is N/A if count is the same as previous range

### ISSUE THREAD

**Issue by codecalm** [plausible/analytics#2397]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

Hi! When count of the visitors is the same as previous scope (in my example this is today/yesterday) the difference is counted as `N/A`, but difference is known: it's 0%

### Expected behavior

Should be 0% and horizontal arrow (or minus?), not N/A (not avaliable)

### Screenshots

![Screenshot 2022-10-27 at 23 45 07](https://user-images.githubusercontent.com/1282324/198404599-e9460c2b-3aa3-4e5e-b994-e30925da9b52.png)

### Environment

```markdown
- OS: MacOS
- Browser: Chrome
- Browser Version: Version 107.0.5304.62
```

**Comment by metmarkosaric** [comment]
good point @codecalm!

**Comment by vinibrsl** [comment]
Thanks for reporting! I'll deploy this to production on Monday :)

**Comment by codecalm** [comment]
awesome, fast fix ❤️
