### ISSUE TITLE
Healthcheck endpoint

### ISSUE THREAD

**Issue by RealOrangeOne** [plausible/analytics#240]
## Prerequisites
- [x] I have searched open and closed issues to make sure that the feature has not yet been requested.

## Feature request
**Is your feature request related to a problem? Please describe.**

When self-hosting, it'd be great to know whether the site is up and functioning correctly, and pluggable into existing uptime monitoring

**How would you like it to work**

Some URL which you could send a request to, and it'd return a status code based on whether the site was up (200/400). This can currently be sort of achieved by pointing at the homepage, but as I just found out, that doesn't check if everything is up and operating (namely clickhouse).

**Comment by tckb** [comment]
This is added in our [recent commits](https://github.com/plausible/analytics/commit/15f6594ddb77715aa7e4b27c8b35d33fcaf1ea92), health endpoint available at [<baseurl>/health](https://github.com/plausible/analytics/blob/master/lib/plausible_web/router.ex#L62)

**Comment by RealOrangeOne** [comment]
Awesome. Yup if I go to `/api/health`, there's a healthcheck page!
