### ISSUE TITLE
Regex in Pageview Goals path

### ISSUE THREAD

**Issue by alpha077412** [plausible/analytics#241]
## Prerequisites
- [x] I have searched open and closed issues to make sure that the feature has not yet been requested.

## Feature request
**Is your feature request related to a problem? Please describe.**
Currently Pageview Goal paths must be identical to those tracked in Plausible, meaning it is not possible to create goals for dynamic URLs without using custom events. For example, a Woocommerce checkout page redirects users to _/checkout/order-received/12345/_ where the final part of the URL is unique for each order. 

**How would you like it to work**
Allow entry of regex or more simply an asterisks * in Pageview Goal paths. For example, _/checkout/order-received/*_

**Comment by ukutaht** [comment]
Makes sense, thanks for the request!

**Comment by youngbrioche** [comment]
Plausible should at least allow for partly URL matching (e.g. „ends with“). Would make it possible to track pageviews like

- /de/signup/thanks
- /en/signup/thanks

Without configuring two goals.

**Comment by n0th** [comment]
Yes, please, this is sooo important for dynamic pages like Woocommerce
