### ISSUE TITLE
Goal conversion is showing wrong on "RealTime" (seems OK on "today")

### ISSUE THREAD

**Issue by divinerites** [plausible/analytics#242]
## Prerequisites
- [X] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report

I was trying to have some custom event for goal conversion.

I was lurking on the "real time" page, and saw nothing.

I was debugging until I saw that my event was logged if I was looking at the "today" page.

So I guess there is a difference between the 2 and at least some missing goal conversion on the "real time" page.

**Expected behavior**

I expect that the event captured on "today" are showing up on "real time" (if they are on the last 30 min obv.).

Or if it is not possible technically, to have a warning.

**Screenshots (If applicable)**

**Environment (If applicable):**
 - OS: [e.g. macos] Mac OSX 10.14.6
 - Browser [e.g. safari, firefox] : Brave (Chrome)
 - Version [e.g. 78] Version 1.11.97 Chromium: 84.0.4147.89 (Build officiel) (64 bits)

**Comment by divinerites** [comment]
Not sure if it is really a bug.

It seems that after clicking once on an event, if you do it again, even later and even on. a refreshed page, no more click on this custom event is added.

**Comment by metmarkosaric** [comment]
> Not sure if it is really a bug.
> 
> It seems that after clicking once on an event, if you do it again, even later and even on. a refreshed page, no more click on this custom event is added.

Right now same event/goal conversion is only counted once per session. We plan to allow same goal conversions to be counted multiple times in the same session but display them as "unique conversions" and "total conversions". See #223

**Comment by divinerites** [comment]
ok thanks

**Comment by divinerites** [comment]
I re-open it, because for example right now in the real-time: no page reach in the last 30 min but 1 goal setup is shown.

And today, I made some tests with fresh stats and 3 different browsers, and I think there is something wrong in the real-time goals (not)shown in real-time.

**Comment by ukutaht** [comment]
Hey, can you take screenshots the next time this happens? I haven't noticed any issues myself and realtime features are difficult to debug.

**Comment by divinerites** [comment]
I just reset my sats yesterday, so it was easy (I should have think by myself doing it, sorry). And thanks for taking time to respond.

- First connexion /root/legal 
- Change page to /root
- click on a custom goal.
 
You will see that the custom goal is only on the 7days page. Not on real time. Even if I come back some minutes later.

# Screenshot for real-time

<img width="1219" alt="Capture d’écran 2020-07-28 à 14 42 55" src="https://user-images.githubusercontent.com/32342823/88667140-427e1680-d0e1-11ea-8695-faf2cbc91da5.png">

<img width="1202" alt="Capture d’écran 2020-07-28 à 14 43 03" src="https://user-images.githubusercontent.com/32342823/88667174-4ca01500-d0e1-11ea-9f33-3e7941715e42.png">

# Screenshot for 7 days

<img width="1202" alt="Capture d’écran 2020-07-28 à 14 43 21" src="https://user-images.githubusercontent.com/32342823/88667267-6e999780-d0e1-11ea-8753-e3201ea8175c.png">

<img width="1284" alt="Capture d’écran 2020-07-28 à 14 43 14" src="https://user-images.githubusercontent.com/32342823/88667301-78bb9600-d0e1-11ea-8ec8-2642dbfcb449.png">

**Comment by ukutaht** [comment]
Thanks for taking the time to take screenshots :)

I will attempt to reproduce on my end using the same actions. Will report back as soon as I get to it.

**Comment by divinerites** [comment]
> I will attempt to reproduce on my end using the same actions.

And If needed for, do not hesitate to use the real web site. It is not in production yet. So only you and me :-)
Will give you the url by PM.

**Comment by divinerites** [comment]
I don't know if you"re aware and/or it is related to this timezone pb, but on an other site, the "real time" numbers seems OK, while there is no data shown at all. 0 reporting.

let me know if you want me to test it further.

<img width="1124" alt="Capture d’écran 2020-08-01 à 17 54 10" src="https://user-images.githubusercontent.com/32342823/89105310-52b72e00-d420-11ea-95a4-8d759c32aaeb.png">

**Comment by ukutaht** [comment]
Thanks for letting me know. Looks related, I'll test this site with the new PR as well

**Comment by divinerites** [comment]
> Thanks for letting me know. Looks related, I'll test this site with the new PR as well

Thanks the PR #260 seem to get OK the goal conversion in real time. Perfect.

But the flat curve seems still a problem tho. Tested on Chrome/Brave and Safari.

**Comment by divinerites** [comment]
If I download the csv file, data are all 0.

https://plausible.io/camping-arolla.com/visitors.csv?period=realtime&date=2020-08-03&from=undefined&to=undefined&filters=%7B%22goal%22%3Anull%2C%22source%22%3Anull%2C%22referrer%22%3Anull%7D

**Comment by ukutaht** [comment]
Hey can you test again. I didn't deploy immediately after the PR closed so maybe it hadn't taken effect yet

**Comment by divinerites** [comment]
Ah !!! Just coming now OK. Thanks a lot for the "real-time'" fix about "real-time". Inception.

**Comment by ukutaht** [comment]
Sorry for introducing the bug in the first place 😄

**Comment by divinerites** [comment]
Burn !! Burn !!! Burn !!!
