### ISSUE TITLE
Self-hosted setup fails to connect to Clickhouse

### ISSUE THREAD

**Issue by StudioLE** [plausible/analytics#243]
### Precheck

Please note that this tracker is only for bugs. Do not use the issue tracker for help or support. [Our docs](https://docs.plausible.io/) are a great place for most answers, but if you can’t find your answer there, you can [contact us](https://plausible.io/contact). Thanks!

## Prerequisites
- [x] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report
**Describe the bug**
Clickhouse database creation/migration fails when following the steps for [docker self-hosted setup](https://github.com/plausible/analytics/blob/master/HOSTING.md).

```
docker-compose run --rm setup
```

**Expected behavior**
Expected an error free setup but instead errors are returned (shown in red) during the setup and the webserver returns 500 errors on a variety of pages.

**Screenshots (If applicable)**

![image](https://user-images.githubusercontent.com/193290/88475542-bc1ed480-cf28-11ea-9d61-224950c3e043.png)

**Environment (If applicable):**
Docker version 19.03.12, build 48a66213fe
docker-compose version 1.25.5, build 8a1c60f6
Ubuntu Server 20.04
Using default environment variables https://github.com/plausible/analytics/blob/master/plausible-variables.sample.env

**Comment by tckb** [comment]
@StudioLE  those error message are expected while creating the database. Can you test it further by  following all steps?

**Comment by StudioLE** [comment]
If I continue with the setup and launch plausible the webserver seems to work. I can login with the admin credentials configured in the `.env` but when I go to add a new site on the page following the "snippet" I get a 500 error.

![image](https://user-images.githubusercontent.com/193290/88477704-23915000-cf3a-11ea-9b8d-aaaff7f07f9c.png)


 Checking the logs with `docker logs **plausible container name**` show's it's filled with connection errors. Hence why I assumed that there was an issue with the Clickhouse setup/migration.

![image](https://user-images.githubusercontent.com/193290/88477657-d1e8c580-cf39-11ea-80b4-5799a4493d53.png)

**Comment by tckb** [comment]
@StudioLE are you running the stock docker-compose? Can you share your compose file ?

**Comment by samuel-p** [comment]
I had the same error setting up a self-hosted instance and solved it by adding the following environment variables to the setup and plausible container.

```
CLICKHOUSE_DATABASE_USER=default
CLICKHOUSE_DATABASE_PASSWORD=
```

**Comment by StudioLE** [comment]
> I had the same error setting up a self-hosted instance and solved it by adding the following environment variables to the `setup` and `plausible` container.
> 
> ```
> CLICKHOUSE_DATABASE_USER=default
> CLICKHOUSE_DATABASE_PASSWORD=
> ```

Thanks @samuel-p that was indeed the issue. 

I still get a little noise when running `docker-compose run --rm setup` but only from the initial postgres call. WHich I guess is the expected error you were referring to @tckb .

![image](https://user-images.githubusercontent.com/193290/88484650-fd82a480-cf67-11ea-8e4a-827526686e89.png)

`docker logs **plausible container name**` is now clear and the web app works as one would expect.

**Comment by tckb** [comment]
Glad that cleared up! Thanks for suggestion @samuel-p

**Comment by ukutaht** [comment]
@StudioLE Can this be closed?

**Comment by Kovah** [comment]
Before opening a new issue, I would like to hook into this one as my problem is quite similar.
I have set up Plausible using the Docker configuration, I replaced the Dockerfile build configuration with the actual Docker image from the Hub.
When running the setup command (`docker-compose run --rm setup`), I get the following output:

```
Loading plausible..
Starting dependencies..
Starting repos..
create Plausible.Repo database if it doesn't exist
create "plausible_events_db" clickhouse database/tables if it doesn't exist
00:32:02.320 [error] Clickhousex.Protocol (#PID<0.254.0>) failed to connect: ** (ErlangError) Erlang error: :nxdomain
00:32:04.026 [error] Clickhousex.Protocol (#PID<0.254.0>) failed to connect: ** (ErlangError) Erlang error: :nxdomain
Creation of Db successful!
Loading plausible..
Starting dependencies..
Starting repos..
Running migrations for plausible
00:32:08.433 [error] Clickhousex.Protocol (#PID<0.248.0>) failed to connect: ** (ErlangError) Erlang error: :nxdomain
00:32:09.954 [error] Clickhousex.Protocol (#PID<0.248.0>) failed to connect: ** (ErlangError) Erlang error: :nxdomain
Migrations successful!
Loading plausible..
Starting dependencies..
Starting repos..
Admin user already exists. I won't override, bailing
```

Based on the error `failed to connect: ** (ErlangError) Erlang error: :nxdomain` I would assume that something with the container connection is wrong. The message "Creation of Db successful!" seems wrong as no Clickhouse database was created.
What could be the issue here? :/

**Comment by Kovah** [comment]
Ping @ukutaht @tckb

**Comment by ukutaht** [comment]
Hey, sorry I don't run docker-compose myself but I can give it a go. Can you post your full docker-compose file so I can reproduce?

**Comment by Kovah** [comment]
It is basically the [one in the repository](https://github.com/plausible/analytics/blob/b29afdeb92576f401f5886e0f29a3447e742024e/docker-compose.yml), with the only change that I restricted all ports except the one for Plausible itself:


```
plausible_events_db:
    image: yandex/clickhouse-server:latest
    volumes:
      - event-data:/var/lib/clickhouse
    ports:
      - 127.0.0.1:8123:8123
```

But changing the ports should not be a problem because Plausible uses the internal Docker host `plausible_events_db` to connect to the Clickhouse container.

**Comment by Kovah** [comment]
I tried to setup Plausible with the same docker-compose file on my local machine and it's working without issues. Guess there's something else wrong on my server. So no further help needed here I guess.

**Comment by tckb** [comment]
@Kovah is the issue resolved?  I can't think of any specific reason why this is not working on your server, unless the port is already busy.  You can try to just bring up the Clickhouse separately and see if it works.

**Comment by Kovah** [comment]
Yes, I have messed up the internal Docker networks. 😅
