### ISSUE TITLE
Issues with clickhouse running in a non-UTC timezone

### ISSUE THREAD

**Issue by ameshkov** [plausible/analytics#2432]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Self-hosting

### Describe the bug

The issue is that the behavior with Clickhouse that runs in a non-UTC timezone. Namely, hourly graph missing data since 
Clickhouse returns dates in the timezone it has configured instead of what's expected in the code.

I made a naive attempt to resolve this, but it failed: https://github.com/plausible/analytics/pull/2430

## Steps to reproduce the issue

1. `make clickhouse`
2. `docker exec -it plausible_clickhouse /bin/bash`
3. `vim /etc/clickhouse-server/config.xml`
4. Change `<timezone>` there to anything non-UTC (`CET` for instance)
5. Restart `plausible_clickhouse` and try running the tests. This one in particular: `mix test test/plausible_web/controllers/api/stats_controller/main_graph_test.exs:42` will fail.

Maybe there's an easy option to make the client use UTC timezone (there's a `use_client_time_zone` in the official client, not sure where to set it for Ecto). Apparently, now it uses the server's timezone.

### Expected behavior

I'd expect that Plausible works properly with Clickhouse running with a different timezone.

### Environment

```markdown
- OS:
- Browser:
- Browser Version:
```

**Comment by ruslandoga** [comment]
👋 @ameshkov 

> Maybe there's an easy option to make the client use UTC timezone (there's a use_client_time_zone in the official client, not sure where to set it for Ecto). Apparently, now it uses the server's timezone.

Right now the HTTP interface is used in the Ecto adapter. I have tried a few curl requests supplying `x-clickhouse-timezone` header and/or `timezone` query arg, but none worked. So I guess the conversion would need to be done in the app ...

**Comment by ameshkov** [comment]
It's supported in the command-line client only. Unfortunately, it's simply not supported in the HTTP client yet: https://github.com/ClickHouse/ClickHouse/issues/4548

So it seems there's no simple way to fix this yet. I guess there might be some rather ugly solution on the Plausible side, i.e. introducing a new environment variable `CLICKHOUSE_TZ` and adjusting the buckets as I did in my initial PR. Not ideal at all but may solve this for the time being until Clickhouse supports setting client time zone for the HTTP interface.

**Comment by ameshkov** [comment]
I haven't noticed any issues with other types of queries yet.

`SELECT timezone()` is an option indeed, let me quickly try it.

**Comment by ameshkov** [comment]
Well, seems to be solving immediate issues, see https://github.com/plausible/analytics/pull/2430
