### ISSUE TITLE
Month dropdown in Custom Range is light even with dark theme

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/analytics#2453]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

The month dropdown in the Custom Range date picker uses the light theme even with the dark theme enabled.

In Firefox:

![Screenshot from 2022-11-18 10-01-39](https://user-images.githubusercontent.com/34340819/202663651-ce7faf78-153a-4add-a3dd-5fb3429956cd.png)

In Chrome:

![Screenshot from 2022-11-18 10-05-15](https://user-images.githubusercontent.com/34340819/202663886-4e9f05ca-ccf3-4566-8af3-766a5463c6f6.png)

### Expected behavior

The month dropdown should be dark theme too when dark theme is selected 

### Environment

```markdown
- OS:
- Browser:
- Browser Version:
```

**Comment by djanda97** [comment]
This is my first time diving into the codebase, but I have a feeling that the [`renderDropDownContent`](https://github.com/plausible/analytics/blob/master/assets/js/dashboard/datepicker.js#L317) function in the [`DatePicker`](https://github.com/plausible/analytics/blob/master/assets/js/dashboard/datepicker.js#L112) component would be a good place to investigate.

After seeing that the [`DatePicker`](https://github.com/plausible/analytics/blob/master/assets/js/dashboard/datepicker.js#L112) component uses the Flatpickr library, I found this [comment](https://github.com/plausible/analytics/blob/master/assets/css/flatpickr.css#L15) which might be related to the theming issue shown in the screenshots above.

**Comment by ukutaht** [comment]
@djanda97 yes this seems like the correct place to add some custom styling for dark mode. Are you working towards a PR? I would gladly accept a fix for this 😊

**Comment by djanda97** [comment]
@ukutaht I just got my development environment up and running, so yes I'd like to start working on a PR for this issue! :smile:

**Comment by djanda97** [comment]
A few notes that I've gathered:

- `assets/js/dashboard/datepicker.js` uses the `Flatpickr` component from the `react-flatpicker` library to generate the calendar dropdown
- The option elements that the `Flatpickr` component generates have the `flatpickr-monthDropdown-month` class attribute
- I tried adding this snippet to `assets/css/flatpickr.css`, but there were no noticeable changes in the UI:
  
  ```
  .dark .flatpickr-monthDropdown-month {
    color: #f3f4f6 !important;
    background-color: #1f2937 !important;
  }
  ```
- The `Flatpickr` component generates the following HTML starting at `<div class=”flatpickr-wrapper”>`:

![image](https://user-images.githubusercontent.com/8923819/211960077-72637713-a45a-47c5-8942-fe0435fbebc2.png)

- From [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/option):
  - "Styling the `<option>` element is highly limited. Options don't inherit the font set on the parent. In Firefox, only `color` and `background-color` can be set however in Chrome or Safari it's not possible to set any properties."

- From [MDN](https://developer.mozilla.org/en-US/docs/Learn/Forms/Advanced_form_styling):
  - "The second, slightly more major issue is that you don't have control over the box that appears containing the options when you click on the `<select>` box to open it. You'll notice that the options don't inherit the font set on the parent. You also can't consistently set things like spacing and colors. For example, Firefox will apply `color` and `background-color` when set on the `<option>` elements, Chrome won't. Neither of them will apply any kind of spacing (e.g. padding)."
  - "If you really need full control over the option styling, you'll have to either use some kind of library to generate a custom control, or build your own custom control."

**Comment by ukutaht** [comment]
Thanks @djanda97!

So based on this it looks like changing the background color is not possible with the `<option>` tag... doesn't look like there's much we can do on this one.

**Comment by metmarkosaric** [comment]
thanks for the investigation @djanda97! i'll close this for now as there doesn't seem to be anything actionable we can do. we can always reopen if/when we have a plan for how to handle it
