### ISSUE TITLE
Add ability to "import" goals names.

### ISSUE THREAD

**Issue by divinerites** [plausible/analytics#246]
## Prerequisites
- [X] I have searched open and closed issues to make sure that the feature has not yet been requested.

## Feature request

I have  60 goals (see #134 for reducing this number).

As  use gohugo.io and create my goal names programatically, it is really easy to generate a txt/csv/json/yaml/whatever file for importing those names and avoid the pain to create them by hand (and it is more error prone).

**Comment by stefanbuck** [comment]
I faced the same situation although I have much less goals. Adding more than three goals at the same time is not the best experience. After adding a goal, the page reloads and therefore scrolls up. Now in order to add another goal you have to scroll down again ...

**Comment by divinerites** [comment]
No more accurate because of https://github.com/plausible/analytics/issues/134. Closing.

**Comment by ukutaht** [comment]
Thanks @divinerites :)
