### ISSUE TITLE
Add a forum so users can exchange skills/questions/help

### ISSUE THREAD

**Issue by divinerites** [plausible/analytics#247]
## Prerequisites
- [X] I have searched open and closed issues to make sure that the feature has not yet been requested.

## Feature request

This git place is only for bug/features which is perfectly fine by me.

But i miss a forum where we can request/provide help without sending mails to @plausible or using git responses as hack for that :-)

**Comment by metmarkosaric** [comment]
Thanks @divinerites! We were actually thinking the same so we're working on adding a Discourse forum.

**Comment by metmarkosaric** [comment]
The forum is now live on https://plausible.discourse.group/
