### ISSUE TITLE
Broken links in footer when self-hosted

### ISSUE THREAD

**Issue by samuel-p** [plausible/analytics#250]
# Prerequisites
- [x] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report
I have setup a self-hosted plausible instance using the official docker image [`plausible/analytics`](https://hub.docker.com/r/plausible/analytics) and integrated it one of my websites. I have noticed that there are many links in the footer which don't work, because they are not available in my instance. Only the community links work. See https://plausible.sp-codes.de/sp-codes.de

**Expected behavior**
The links should be removed for self-hosted instances and only valid links should be visible.

**Screenshots (If applicable)**
![Bildschirmfoto von 2020-07-27 18-04-17](https://user-images.githubusercontent.com/7959516/88564600-acd87d80-d033-11ea-8b3e-5fada64882d5.png)

**Comment by tckb** [comment]
Yes. These are added new in the cloud version. I expect to fix this in the next PR.
