### ISSUE TITLE
Direct traffic missing from exported stats

### ISSUE THREAD

**Issue by bogplau** [plausible/analytics#2523]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

direct traffic missing from sources.csv when exporting the stats. 

### Expected behavior

direct traffic should be present in sources.csv. 

### Environment

```markdown
- OS:
- Browser:
- Browser Version:
```

**Comment by ukutaht** [comment]
Agreed. Exports should contain traffic for `Direct / None`
