### ISSUE TITLE
Third Party Requests

### ISSUE THREAD

**Issue by samuel-p** [plausible/analytics#254]
## Prerequisites
- [x] I have searched open and closed issues to make sure that the feature has not yet been requested.

## Feature request
At the moment plausible uses some third party requests to Cloudflare and DuckDuckGo. CDNs are bad from a privacy and security perspective. So please replace them completely with self-hosted files or at least provide an option to disable it for self-hosted instances.

**Screenshots (If applicable)**
![Bildschirmfoto von 2020-07-28 23-01-39](https://user-images.githubusercontent.com/7959516/88721547-e76f1280-d126-11ea-9fb2-0a1bafaac92f.png)

https://webbkoll.dataskydd.net/en/results?url=http%3A%2F%2Fplausible.io%2Fplausible.io

**Comment by ukutaht** [comment]
Thanks for the suggestion.

We can definitely host the flatpickr javascript ourselves no problem.

The call to DuckDuckGo is to show favicons in our referral report:
<img width="563" alt="Screenshot 2020-07-29 at 10 00 30" src="https://user-images.githubusercontent.com/3731516/88767460-575eb680-d182-11ea-948f-682a6140c2bc.png">

I don't want to write our own favicon fetcher so the only way to get rid of DDG in this case is to remove the icons from the UI. In my opinion the icons make it a lot nicer and I'm leaning towards keeping it.

**Comment by samuel-p** [comment]
I'm OK with the DDG Favicons, but I think it should be possible to disable it if someone doesn't need / want it in their self-hosted instance. Another option would be to proxy all DDG through the own server to improve the privacy of the visitors.

**Comment by ukutaht** [comment]
I have now removed the request to cdnjs.cloudflare.com by hosting the Flatpickr css ourselvers.

DDG icons are unchanged.

**Comment by metmarkosaric** [comment]
Closing this as we've removed the Cloudflare third-party request. The one remaining is DDG for icons but this is essential part of the look of the app so we don't plan to remove that feature as we don't see any privacy concerns with it.
