### ISSUE TITLE
Upgrading to v1.5.1 causes 502 Bad Gateway with nginx reverse proxy

### ISSUE THREAD

**Issue by timbowhite** [plausible/analytics#2545]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Self-hosting

### Describe the bug

After following this [upgrade guide](https://github.com/plausible/analytics/releases/tag/v1.5.1) on an existing self-hosted install with nginx reverse proxy and performing the "Upgrading ClickHouse to 22.6" step, the plausible website began responding with "502 Bad Gateway".

Was able to fix by following the instructions in discussion #2533:

1. Removed the ```LISTEN_IP=127.0.0.1``` line from ```plausible-conf.env```.
2. Modified ```docker-compose.yml```:
```
plausible:
    ports:
      - 127.0.0.1:8000:8000
```
3. Ran these commands:
```
$ docker compose stop plausible
$ docker compose rm plausible
$ docker compose up -d
```

See discussion #2533 

### Expected behavior

Expected the plausible website to be accessible via a browser.

### Environment

```markdown
- OS:
- Browser:
- Browser Version:
```

**Comment by Facerafter** [comment]
Same thing here but only happended after a few weeks Clickhouse seems to be in a crash loop

`(version 22.6.9.11 (official build))
2023.01.06 08:33:11.426451 [ 43 ] {} <Error> Application: DB::Exception: Suspiciously many (12 parts, 0.00 B in total) broken parts to remove while maximum allowed broken
parts count is 10. You can change the maximum value with merge tree setting 'max_suspicious_broken_parts' in <merge_tree> configuration section or in table settings in .sql file (don't forget to return setting back to default value): Cannot attach table `plausible_events_db`.`events` from metadata file /var/lib/clickhouse/store/167/167227ed-36d5-4826-8965-657eacc4dd1b/events.sql from query ATTACH TABLE plausible_events_db.events UUID '400605e2-ac0c-453f-a2d0-4a80dce3daa8' (`name` String, `domain` String, `user_id` UInt64, `session_id` UInt64, `hostname` String, `pathname` String, `referrer` String, `referrer_source` String, `country_code` LowCardinality(FixedString(2)), `screen_size` LowCardinality(String), `operating_system` LowCardinality(String), `browser` LowCardinality(String), `timestamp` DateTime, `utm_medium` String, `utm_source` String, `utm_campaign` String, `meta.key` Array(String), `meta.value` Array(String), `browser_version` LowCardinality(String), `operating_system_version` LowCardinality(String), `subdivision1_code` LowCardinality(String), `subdivision2_code` LowCardinality(String), `city_geoname_id` UInt32, `utm_content` String, `utm_term` String, `transferred_from` String) ENGINE = MergeTree PARTITION BY toYYYYMM(timestamp) ORDER BY (name, domain, user_id, timestamp) SAMPLE BY user_id SETTINGS index_granularity = 8192`

**Comment by ruslandoga** [comment]
👋 @timbowhite 

Why did you have `LISTEN_IP=127.0.0.1` set in your `plausible-conf.env`?

**Comment by timbowhite** [comment]
@ruslandoga 

Security. Server listening on localhost can't be accessed by internet.

First section of [self-hosting config options doc](https://plausible.io/docs/self-hosting-configuration):

> LISTEN_IP	0.0.0.0	The IP address on which the server is listening. 0.0.0.0 means all interfaces, 127.0.0.1 means localhost. Also see the related section Erlang platform ports below.

**Comment by ruslandoga** [comment]
Isn't it only relevant when you use host networking in Docker? I'm not an expert in this, but I don't think a container that binds on 127.0.0.1 can't be accessed at all from the outside (under default network config in Docker).

**Comment by timbowhite** [comment]
Dunno, I don't know enough about Docker. I suppose you could test if it's accessible by setting ```LISTEN_IP=0.0.0.0``` and then doing ```telnet my.server.ip.address 8000``` externally.

**Comment by ruslandoga** [comment]
It won't be accessible if you've set 

```yml
plausible:
    ports:
      - 127.0.0.1:8000:8000
```

:)
