### ISSUE TITLE
Invite link generation fails for previously removed users

### ISSUE THREAD

**Issue by colinwilson** [plausible/analytics#2553]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Self-hosting

### Describe the bug

Not sure if this is a bug or expected behaviour. 

If an invited user is subsequently removed (via `settings/people`), the generated registration link in any further invites incorrectly links to `http(s)://plausible-domain/sites` as opposed to a valid registration link e.g. `https://plausible-domain/register/invitation/pYr6tDgLv5GWtDqSwMvM4`.

Do you have to wait 48hrs before sending another invite?

#### example invite email template:
---
Hey,

colin@my-domain.com has invited you to the colinwilson.uk site on Plausible Analytics. [Click here](https://plausible-domain/sites) to view and respond to the invitation. The invitation will expire 48 hours after this email is sent.

Regards,
The Plausible Team 💌

-- 

http(s)://plausible-domain/

---

### Expected behavior

Expect a valid invite link in the invite email if the invited users' email has already been remove from `Pending Invitations` by an owner/admin user

---

Hey,

colin@my-domain.com has invited you to join the colinwilson.uk site on Plausible Analytics. [Click here](https://plausible-domain/register/invitation/pYr6tDgLv5GWtDqSwMvM4) to create your account. The link is valid for 48 hours after this email is sent.

Plausible is a lightweight and open-source website analytics tool. We hope you like our simple and ethical approach to tracking website visitors.

Regards,
The Plausible Team 💌

-- 

http(s)://plausible-domain/

---

### Environment

```markdown
- Plausible Version: 1.5.1
- DISABLE_REGISTRATION set to `invite_only`
```

**Comment by colinwilson** [comment]
Just confirmed that once a user has set up their password and accepted their invitation removing them via `setting/people` in the UI sends the 'revoked access' email but fails to delete them from the postgres `users` table.

**Comment by ruslandoga** [comment]
@colinwilson 👋

Sorry for taking so long to reply. This does appear to be a feature:

https://github.com/plausible/analytics/blob/c4b8bf8c3281068dd242948ae4e8d1e0fb1dc3e6/lib/plausible_web/controllers/site/membership_controller.ex#L65-L70

The template differs based on whether the user already exists. The existing users can accept the invitation on `/sites`. Looks like this:

<img width="1308" alt="Screenshot 2023-01-18 at 21 51 23" src="https://user-images.githubusercontent.com/67764432/213203156-635f3c9c-457e-4d59-92af-4d548752ea08.png">

My steps to reproduce this were:

- invite `zloba` user
- register and accept the invitation as `zloba` user
- remove `zloba` user from the site
- invite `zloba` again
