### ISSUE TITLE
GA imported everything except Unique Visitors 

### ISSUE THREAD

**Issue by joffreypersia** [plausible/analytics#2565]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

Hi, 

I am using Plausible on a based subscription (not self hosted)
I recently imported datas from GA and it is the first time that it didn't catch the "unique visitor" stats. 
The bounce rate, time, and page views are OK

I didn't find the bug on the github, so here is my message. 

It is about the website particeep.com
Maybe it is related to a proxy on Clever-cloud because it is the first time I got a bug with the imported datas, and it is the first time it is on Clever-Cloud.

What do you think guys ? 

### Expected behavior

GA Import doesn't work as expected. 

It imported Time, Page view and bounce rate without the unique visitors. 

[visitors.csv](https://github.com/plausible/analytics/files/10345458/visitors.csv)

### Screenshots

![SCR-20230104-nav](https://user-images.githubusercontent.com/94628273/210593981-720883ba-8b60-49c4-b670-6c0e62f6431a.png)
![SCR-20230104-nac](https://user-images.githubusercontent.com/94628273/210594006-16f4c221-3ae3-4569-a31a-b0ff5cb85871.png)

### Environment

```markdown
- OS: Mac Os
- Browser: Arc Browser
- Browser Version: Version 0.81.2
- Hoster : Clever-cloud
```

**Comment by ukutaht** [comment]
@joffreypersia thanks for reporting.

If you're a Plausible.Cloud user I'd recommend writing to hello@plausible.io. We monitor this channel more actively and you'll get more prompt responses from there. You can also leave it here on Github but it'll be a slower process most likely.

**Comment by joffreypersia** [comment]
> @joffreypersia thanks for reporting.
> 
> If you're a Plausible.Cloud user I'd recommend writing to [hello@plausible.io](mailto:hello@plausible.io). We monitor this channel more actively and you'll get more prompt responses from there. You can also leave it here on Github but it'll be a slower process most likely.

Thank you, 
I just emailed them :)

**Comment by metmarkosaric** [comment]
thanks @joffreypersia! i see we've responded now so let's continue the conversation there
