### ISSUE TITLE
`/api/v1/sites/shared-links` API endpoint returns invalid key w/valid key

### ISSUE THREAD

**Issue by siebird** [plausible/analytics#2575]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

Using a valid API token (works with other endpoints) we continue to get an error trying to find/create a shared link via the API `/api/v1/sites/shared-links` endpoint: 

`"error": "Invalid API key. Please make sure you're using a valid API key with access to the resource you've requested."`

### Expected behavior

The shared-links endpoint should return a 200 response:

```
{
    "name": "Wordpress",
    "url": "https://plausible.io/share/site.com?auth=<random>"
}
```

### Environment

```markdown
- OS: MacOS
- Browser: Postman
```

**Comment by metmarkosaric** [comment]
hi @siebird! to use the sites API, you need to have a sites API key. please [contact us](https://plausible.io/contact) so we can create a sites API key for you (this is a different key from your stats API key).

**Comment by siebird** [comment]
@metmarkosaric thanks for the quick response. Is there anyway of creating a self serve sites API key in customer accounts? 

We're building an integration with Plausible and asking customers to reach out to your support to wait to get one created is not ideal.

**Comment by metmarkosaric** [comment]
you're welcome @siebird! that's not possible, unfortunately. only the stats API key can be created self-serve at this stage. shared links can be created in site settings directly without an API so you could ask people to present the shared link URL somehow perhaps? we do the same in our own WP plugin for instance

**Comment by siebird** [comment]
That's an option that will solve it for now. Thanks for sharing.
