### ISSUE TITLE
Inconsistency between total visitors and the sum of each visitors per source

### ISSUE THREAD

**Issue by slybridges** [plausible/analytics#2582]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

I noticed an  inconsistency between the "Unique Visitors" number and the sum of all sources for a given period. The Unique visitor number is always lower than the sum of visitors from all sources. 

To repro:
1. Set your view as a month (haven't tried on other views)
2. Hover the Unique Visitors number to get the exact number
3. In the Top Source Panel, click on Details
4. Copy and paste the table in a Google Sheet
5. Replace all rounded up numbers by their exact number displayed when hovering the number in Top Source (e.g. replace 5k by 5073)
6. Compute the sum of all visitors and compare with the number obtained in step 2

In my test the sum was always greater than the overall number given by plausible.

I also tried using the API, with the same results.

### Expected behavior

I would expect the numbers to match.

I was trying to segment my visitors by Search / Social / Direct / Backlinks and ended up having a negative number for the backlinks because it was computed as Total - (Search + Social + Direct).

### Environment

```markdown
- OS:
- Browser:
- Browser Version:
```

**Comment by metmarkosaric** [comment]
thanks for reporting that @slybridges! this is expected as the same visitor can enter the site from multiple sources. so for instance if i enter your site right now from DDG and then later in the day, come back again by typing your URL, I'll be counted as 1 one unique visitor in the top chart but also one visitor for DDG and one visitor for Direct / None. We have a bit more on this in our docs here: https://plausible.io/docs/dashboard-faq#numbers-not-adding-up. i hope this helps, thanks!

**Comment by slybridges** [comment]
Hi @metmarkosaric - many thanks for the speedy reply!

It totally makes sense and I had missed that bit in the docs.

Any way I could somewhere see (or compute via the API) the sum of all visitors per source, acknowledging some would be counted twice? Copying and pasting in Google Sheets is not the most practical :-)

**Comment by metmarkosaric** [comment]
you're welcome! the main metric we have next to any individual source would show the number of unique visitors coming to the site from that specific source. is that what you mean or?

**Comment by slybridges** [comment]
Not really, as mentioned before I'm trying to segment our traffic sources.

> I was trying to segment my visitors by Search / Social / Direct / Backlinks and ended up having a negative number for the backlinks because it was computed as Total - (Search + Social + Direct).

For that to work I would need a total number of visitor that is the sum of each individual sources, or else I could have inconsistencies like negative number of visitors from my "Backlinks" segment (which is everything except what was tagged as Search, Social and Direct).

**Comment by metmarkosaric** [comment]
ah i see. yes, that would be the number of total visits/sessions. that number should match with what you're getting when you sum up all the individual sources. we're currently working on adding the number of sessions to the top bar of our dashboard but at the moment you can pull this number from the stats API. see https://plausible.io/docs/stats-api#metrics

**Comment by slybridges** [comment]
That did the trick indeed! Many thanks @metmarkosaric. Plausible is wonderful :o)

**Comment by metmarkosaric** [comment]
thanks for letting me know @slybridges and glad to hear you're finding Plausible useful!
