### ISSUE TITLE
Plausible is leaking memory

### ISSUE THREAD

**Issue by joshavant** [plausible/analytics#2603]
Issue Resolved :)

**Comment by joshavant** [comment]
The Caddy component is not expected to be the source of the memory leak - I haven't noticed the problem in other deployments with exactly the same configuration - and should be an easy task to extract from the provisioning files from anyone with Docker Compose experience.

That said, if anyone would like me to, I'm happy to perform this extraction myself, validate, and re-post the provisioning files with it removed.

**Comment by ruslandoga** [comment]
@joshavant 👋

Can you please try and pinpoint the process / container that leaks memory?

**Comment by ruslandoga** [comment]
@joshavant I think this is more of a https://github.com/plausible/hosting issue. Do you mind if I reopen it there?
