### ISSUE TITLE
OS versions are missing from the CSV export

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/analytics#2624]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

We've just had a report that our CSV export doesn't include referrers.csv which would include the full list of urls that have sent traffic from a specific source (the list you see in the Top Sources report when you filter the dashboard by a specific source). We currently only have the sources.csv in the export which only has the top level sources. i'm pretty sure that we did use to export the referrers too in the past in its own separate CSV if you click on the export icon after filtering the dashboard by a specific source?

### Expected behavior

Export the referrers too in its own separate CSV when you click on the export icon after filtering the dashboard by a specific source

### Environment

```markdown
- OS:
- Browser:
- Browser Version:
```

**Comment by gpouilloux** [comment]
Hey @metmarkosaric 

Currently getting back at Elixir programming, I'm interested in contributing to open-source projects using this language.
I stumbled upon this project which I would definitely consider for other projects 🙇 

I'd like to work on this issue if it is still accurate.
Would you be able to share more details on the expected headers for the referrers CSV export and other requirements?

**Comment by kiote** [comment]
hey @gpouilloux I'm also new to the code, but I looked around a bit and noticed this file: lib/plausible_web/controllers/stats_controller.ex it seems to be responsible for current csv creation. I'm also not sure it was ever creating referrers, since I searched through the history of commits and found nothing. If you still wish to work on it, maybe it will help you somehow. If not, I could take it over.

**Comment by metmarkosaric** [comment]
another report that the CSV download doesn't include browser versions and OS versions

**Comment by kiote** [comment]
Would you like me to work on it? seems like @gpouilloux is busy with something else and not responding here

**Comment by ukutaht** [comment]
Hey @kiote 👋 Good to see you around :)

Feel free to work on this, we'd be happy to receive a PR for this. It's fairly well-defined feature addition that doesn't require any architectural changes/decisions. Let me know if you have any questions about it.

**Comment by kiote** [comment]
created a PR: https://github.com/plausible/analytics/pull/3002

**Comment by kiote** [comment]
ok, I re-seed the local db and now can see the results. `referrers.csv` file is populated, data looks like that:

```
name,visitors,bounce_rate,visit_duration
Direct / None,182554,100,0
```

Which seems to correlate with what I see on Top Sources -> UTM Source panel.

![Screenshot 2023-06-02 at 13 41 29](https://github.com/plausible/analytics/assets/123637/8eebefd1-0cb7-44dc-834d-9273b9c7ac44)

**Comment by kiote** [comment]
I'll add Browser / OS support too. Should be pretty much straightforward now

**Comment by kiote** [comment]
ok, as I see this ticket is probably got outdated with time :) Browser / OS data is already there:

operating_systems.csv
```
name,visitors
Linux,1140
Windows,1121
macOS,1118
```

browsers.csv
```
name,visitors
Safari,994
Chrome,990
Vivaldi,980
Firefox,967
Edge,962
```

@metmarkosaric

**Comment by metmarkosaric** [comment]
Hi @kiote! It's the browser version numbers and os version numbers that are missing. Basically the numbers that show when you filter the dashboard by a browser or by an os. Thanks!

**Comment by kiote** [comment]
hey, will fix that too. Sorry for not being able to read the issue title :D

**Comment by kiote** [comment]
Made a change in https://github.com/plausible/analytics/pull/3296. Unfortunately looks like all Elixir jobs are failing (locally everything ok, so must be permissions issue).

File looks like:

browser_version.csv

```
name,version,visitors
Chrome,49,15
Edge,18,15
Firefox,33,14
Firefox,32,14
Safari,31,13
Chrome,26,13
Chrome,8,13
Firefox,28,13
Firefox,15,12
Chrome,5,12
Chrome,6,12
Chrome,37,12
Firefox,19,12
Vivaldi,19,12
Vivaldi,20,12
```
