### ISSUE TITLE
AUR Package

### ISSUE THREAD

**Issue by rhysperry111** [plausible/analytics#263]
## Prerequisites
- [x] I have searched open and closed issues to make sure that the feature has not yet been requested.

## Feature request
Hi, I am looking to use this self-hosted on my server. My server is very limited on resources, so I would prefer to avoid docker if possible.

What I would like to be able to do is install this as a standard package on my server. This could be easily done for me by submitting it to the AUR.

I am fine to maintain the AUR package, but I would like to know, how do I properly build this from source/package it for a standard system?

**Comment by ukutaht** [comment]
> I am fine to maintain the AUR package, but I would like to know, how do I properly build this from source/package it for a standard system?

I don't have experience with building an AUR package myself. It may be possible to do it using [Mix release](https://hexdocs.pm/mix/Mix.Tasks.Release.html). This is what the Dockerfile does to package the application: https://github.com/plausible/analytics/blob/master/Dockerfile#L61

**Comment by rhysperry111** [comment]
> I don't have experience with building an AUR package myself.
They're pretty simple, take [this](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=mako-git) as an example.

> It may be possible to do it using Mix release.
Thanks, I'll look into if that's possible. If I find a way I'll make sure to notify you about the package

**Comment by rhysperry111** [comment]
I have finished the [AUR package](https://aur.archlinux.org/packages/plausible-git). It obviously has errors that it cannot connect to the SQL server. Does the location of the SQL server need to be configured at build time, or can it be configured by the user at run time?

**Comment by rhysperry111** [comment]
============================================================================================
 Sorry for the spam above. I have finished with the package and gone with the Systemd solution.

You should let users know that they can start plausible using `systemctl start plausible`, they can enable it at boot with `systemctl enable plausible` and they can change the environment variables by editing `/etc/plausible.conf`

**Comment by metmarkosaric** [comment]
Thanks @rhysperry111! I've added this to our community integrations list now.
