### ISSUE TITLE
Broken Link on Learn More Button on Live Demo Page

### ISSUE THREAD

**Issue by mutewinter** [plausible/analytics#264]
## Prerequisites
- [x] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report
**Describe the bug**
The **Learn More** link at the bottom of the [live demo](https://plausible.io/plausible.io) page is not linked.

**Expected behavior**
Links to learn more page.

**Comment by ukutaht** [comment]
Thanks for reporting!
