### ISSUE TITLE
search for specific page + stats on this page

### ISSUE THREAD

**Issue by devrand** [plausible/analytics#265]
There is a strong need to check stats for pages that are not in main listing. 

**How would you like it to work**
Search with text field by URL or part of URL, get stats on this page

**Comment by metmarkosaric** [comment]
Thanks @devrand! Is this because you cannot see the specific page in the list when you click on the "More" button on the "Top Pages" report or because you'd like an easier way to find a specific page in that list?

**Comment by devrand** [comment]
It's both, but first user case  is more important - I have a site with thousands of pages

**Comment by Spone** [comment]
Same need here, I added a :+1:

**Comment by davidsteeb** [comment]
Same here.
