### ISSUE TITLE
Plausible throwing 502 Bad Gateway

### ISSUE THREAD

**Issue by bynormous** [plausible/analytics#266]
## Prerequisites
- [yes] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report

Tracking with custom domains are throwing 502 Bad Gateway or 404 Not Found errors today (I sent an email with the custom domain link):

502 Bad Gateway
nginx/1.19.0

**Comment by bynormous** [comment]
It's also happening on Marko Saric's site: https://ms.markosaric.com/js/index.js

**Comment by metmarkosaric** [comment]
Thanks for reporting this @bynormous! We had a temporary issue with the custom domains but everything is back up now again. Sorry for the inconvenience!
