### ISSUE TITLE
Grouping URLs goal using asteriks

### ISSUE THREAD

**Issue by SemaphoreOxalis** [plausible/analytics#2670]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

Hi,
We 
- filter on the outbound link goal
- click on a goal URL
- edit filter setting : Edit filter is property
- try to group URLs using ** functions :  value is www.someurl.com/**

Plausible return some visitors numbers but no other data

### Expected behavior

We expect to get data based on grouping URL

### Screenshots

![image](https://user-images.githubusercontent.com/10586254/218523603-7657918b-83b8-430f-9a79-7dddf8f0ebcb.png)

![image](https://user-images.githubusercontent.com/10586254/218523537-3f680198-62cc-40ee-bd71-68946a91e83d.png)

![image](https://user-images.githubusercontent.com/10586254/218523455-38b5c346-6623-409e-903e-29191880f94c.png)

### Environment

```markdown
- OS: Windows
- Browser: Firefox
- Browser Version: 109
```

**Comment by metmarkosaric** [comment]
thanks for the feedback @SemaphoreOxalis! we don't support wildcard filtering on external link clicks at this moment unfortunately. wilcard filtering can be used to group your own pages using the filter button or the pageview goals. 

i'll close this thread as we keep the issues list to actual bugs with the product only. we have a similar feature request thread here already so please do follow it for updates or do add any extra comments there: https://github.com/plausible/analytics/discussions/1229. thanks!
