### ISSUE TITLE
Can't click on different filters under last 30 days

### ISSUE THREAD

**Issue by cheeseblubber** [plausible/analytics#2700]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

I can't click on filter by month or year. When I do it goes to the date selection on the chart

This is on a chrome browser with incognito mode on on a mac os

### Expected behavior

I can click on monthly filters

### Screenshots

<img width="373" alt="Screen Shot 2023-02-22 at 8 27 09 AM" src="https://user-images.githubusercontent.com/4218509/220635949-1e50f938-1605-411d-82aa-a2d17d3e4b54.png">

### Environment

```markdown
- OS: MacOS
- Browser: Chrome
- Browser Version: 109.0.5414.119
```

**Comment by ukutaht** [comment]
Thanks for reportin!

The fix will be deployed shortly: https://github.com/plausible/analytics/pull/2699
