### ISSUE TITLE
File Download not getting logged

### ISSUE THREAD

**Issue by roedoejet** [plausible/analytics#2701]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

Hi there, big fan of this project and just trying out the demo. I noticed that our file downloads are not being logged. I added 

```html
<script src="https://plausible.io/js/script.file-downloads.tagged-events.js" defer="" data-domain="<REDACTED>" file-types="html,eaf,textgrid,srt,vtt"></script>
```

to our site and also configured the `File Download` goal as per: https://plausible.io/docs/file-downloads-tracking

We're using Angular and clicking on a download button essentially does this:

```javascript
 element.href = window.URL.createObjectURL(blob);
 element.download = "readalong.html";
 document.body.appendChild(element);
 element.click();
 document.body.removeChild(element);
```

Is there some other expectation that Plausible has with file downloads?

### Expected behavior

The event should be counted!

### Environment

```markdown
- OS: MacOS
- Browser: Chrome
- Browser Version: 110.0.5481.100
```

**Comment by metmarkosaric** [comment]
thanks for reaching out @roedoejet! it's difficult to troubleshoot this without knowing your site. please [contact our support](https://plausible.io/contact) with details as we can help out better there. we use github issues for bugs with the product only. thanks!

**Comment by roedoejet** [comment]
I think this is a bug! Either with the product or documentation. I've set everything up as documented and all other events are tracking just fine. Seems like maybe there is an expectation for what counts as a file download that's missing in the documentation. I'll contact support though, thanks!

**Comment by metmarkosaric** [comment]
thanks! we can always reopen here if it turns out to be a bug after we review it. our process for these types of questions is more suited for emails so you'll get faster response that way than on github. or at least we would need the site details posted here too as without a site and specific url where the issue happens it's difficult to troubleshoot

**Comment by roedoejet** [comment]
So, as per email support:

>>> The file downloads script extension uses the final part of the href attribute to infer the file type. For example, if you have a dynamically generated anchor with href="https://readalong-studio.mothertongues.org/yourfile.html", it will use the final part of the string to match what you specified in the file-types allow list.

Since the href on our dynamically created anchor is too a blob (ie something like `blob:https://domain.test/46dc4afd-3f62-4ac5-b0d7-5d9c14706be6`) it breaks the logic seemingly. There might be other issues related to my problem, but I would say the code should be more robust to these types of differences in "file downloads" or there should be documentation to describe exactly what Plausible is expecting in order to catch a file download event. I ended up just implementing a custom JavaScript event trigger, just posting this here so others may benefit.
