### ISSUE TITLE
POST request being send to my website instead of to Plausible

### ISSUE THREAD

**Issue by szymond** [plausible/analytics#2706]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

I've noticed in my website's logs unexpected POST requests like: `<host>/<path>/undefined/api/event`. I assume those are requests which for some reason are not being sent to Plausible. I can't provide more details apart of user agents which trigger such requests:

> "Mozilla/5.0 (BB10; Kbd) AppleWebKit/537.35+ (KHTML, like Gecko) Version/10.3.3.3216 Mobile Safari/537.35+"
> "Mozilla/5.0 (Linux; U; Android 4.4.2; pl-pl; LG-D802 Build/KOT49I.D80220h) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.1599.103 Mobile Safari/537.36"
> "Mozilla/5.0 (SMART-TV; Linux; Tizen 2.4.0) AppleWebkit/538.1 (KHTML, like Gecko) SamsungBrowser/1.1 TV Safari/538.1"
> "Mozilla/5.0 (Linux; Android 4.4.2; Cavion Base 10 Build/KOT49H) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/30.0.0.0 Safari/537.36"
>  "Mozilla/5.0 (Linux; Android 4.2.2; SM-G350 Build/JDQ39) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/30.0.1599.82 Mobile Safari/537.36"

### Expected behavior

I expected Plausible to be requested.

**Comment by metmarkosaric** [comment]
thanks for reaching out @szymond! could you please share your domain name and how you integrated Plausible into your site? it's difficult to troubleshoot without those details. if you don't want to share it here in public, please [contact our support](https://plausible.io/contact) instead. our support is best place for these types of questions. we keep github issues to actual bugs in the product only. i'll close this here for now but can reopen. thanks!
