### ISSUE TITLE
Web page frozen when displaying "all time" data 

### ISSUE THREAD

**Issue by mquandalle** [plausible/analytics#2713]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

Since a few days I can't display my stats page on Firefox, the page is loading, my fan starts spinning and I some point I have to kill it.

### Expected behavior

No infinite loop, the page should load.

### Screenshots

![Peek 28-02-2023 16-13](https://user-images.githubusercontent.com/1730702/221896148-3bd95ada-3804-4a3e-9ab8-40d6c587cb8b.gif)

### Environment

```markdown
- OS: Linux PopOS
- Browser: Firefox
- Browser Version: 109.0.1
```

**Comment by metmarkosaric** [comment]
thanks for reporting that @mquandalle! it seems related to changing the interval to daily as on default view it works fine. if you clear your browser cache, you should be able to see the default view again at least. we'll take a look at what's going on

**Comment by mquandalle** [comment]
Yes it seems related to the daily view. But even if I reload with clearing the cache (<kbd>Ctrl</kbd> + <kbd>Maj</kbd> + <kbd>R</kbd>) it still stays on the daily view and can't load the page (so I'm stuck I can't change to the monthly view as I cannot interact with the app). Also this is a regression as this view worked before.

**Comment by metmarkosaric** [comment]
could you try to clear the cookies and site date? then you can log back in and you should be able to view the default view again

![Screenshot from 2023-02-28 16-53-06](https://user-images.githubusercontent.com/34340819/221906702-b0dad1c5-b86a-495f-b99f-3ee712065705.png)

**Comment by mquandalle** [comment]
Yes, this works as a workaround, thanks

**Comment by a-alhusaini** [comment]
@metmarkosaric Is the page in question a liveview? This sort of error can easily occur when the liveview is doing way too much work (Like enumerating a list of users)

Also, I am new to the codebase. Could you link me to the file that renders that page so I can take a look?

**Comment by metmarkosaric** [comment]
this has now been fixed. the default interval is now set to monthly on very long date ranges including those manually selected using custom range and it's no longer possible to choose daily interval on such long date ranges when there's so much data that it would end up freezing the browser
