### ISSUE TITLE
Empty Domain with https:// and http://

### ISSUE THREAD

**Issue by sn00py1310** [plausible/analytics#2725]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Self-hosting

### Describe the bug

When entering the websites `https://` or `http://` on `https://[domain]/sites/new` an empty domain is added.
With this, all managing URLs have some sort of double slash i.e. `https://[domain]//settings` because of the empty domain.
Thus the domain can't be managed, not even with the API.

Probably the `https://` and the `http://` is removed for copy past convenience, but after this the domain is empty.

### Expected behavior

The domains `https://` and `http://` would not be accepted.

### Environment

```markdown
- Server OS: Docker
- Reverse Proxy: Traefik

- Browser: Firefox
- Browser Version: 110
```

**Comment by metmarkosaric** [comment]
Hi @sn00py1310! This is expected. Please, remove https and www from the URL, just keep the hostname (`yourdomain.com`). For example, if your site is `https://www.yourdomain.com` then the part to enter in the "Domain" field is `yourdomain.com`. See https://plausible.io/docs/add-website#enter-the-domain-name-of-the-website-you-want-to-track

**Comment by sn00py1310** [comment]
@metmarkosaric maybe I described it not well. I know you are not supposed to enter it with `https://` but you should never trust user input. I've added more information to reproduce it.

# Trigger the bug
Go to `/sites/new` and enter `https://` or `http://`. After this, there should be an empty domain for a website visible on the overview on other pages.

# Example image
I'm using `[empty]` as the representation of an empty string.
In the image, there is a website with the id `example.com` and a website with an id `[empty]`
![example](https://user-images.githubusercontent.com/61204194/222959807-d486ae21-0304-4e4a-99ba-2e0186cee3b4.png)

# Settings link extracted from the HTML response
- example.com: `<a href="/example.com/settings">`
- [empty]: `<a href="//settings">`

# Raw response from /api/sites
```json
{
  "data": [
    {
      "domain": ""
    },
    {
      "domain": "example.com"
    }
  ],
  "pagination": [
    {
      "current": true,
      "label": "1",
      "page": 1,
      "url": "/api/sites?page=1"
    }
  ]
}
```
---
Hopefully, you can now understand what a meant. If not feel free to get in touch with me.
I still think this should not be allowed because it's quite confusing.
But if I'm wrong and this is expected then please show me a way to remove the empty domain.

**Comment by sn00py1310** [comment]
@metmarkosaric could you please verify that this is really working as intended?

**Comment by aerosol** [comment]
@sn00py1310 try this:

```
docker-compose exec plausible_db psql -U postgres -d plausible_db -c "DELETE FROM sites WHERE domain = ''"
```

**Comment by sn00py1310** [comment]
If something isn't working as intended then you normally change it. I don't know how hard it is to have an empty string check.
And what the harm depends on your definition, multiple hours of wasted debugging could be interpreted that way.
I think each optimization if even as simple as this shows how good the product is.

**Comment by aerosol** [comment]
@sn00py1310 Sure thing, apologies for confusion. Hope you enjoy plausible!
