### ISSUE TITLE
Cannot deploy with Elixir 1.11

### ISSUE THREAD

**Issue by feld** [plausible/analytics#2740]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Self-hosting

### Describe the bug

mix.exs says `elixir: "~> 1.11"`, but Plausible uses `then` which was not introduced until Elixir 1.12

```
lib/plausible/billing/paddle_api.ex:112: undefined function then/2
```

### Expected behavior

You can successfully deploy Plausible with Elixir 1.11

**Comment by ruslandoga** [comment]
👋 @feld 

Thank you for the report. I think we'll need to update `mix.exs` to `~> 1.14` as it's the version that's used for [development](https://github.com/plausible/analytics/blob/ad3edbfb9a4d83a00654f584499b84b592e55753/.tool-versions#L2), [testing](https://github.com/plausible/analytics/blob/ad3edbfb9a4d83a00654f584499b84b592e55753/.github/workflows/elixir.yml#L46-L53), and [official releases.](https://github.com/plausible/analytics/blob/ad3edbfb9a4d83a00654f584499b84b592e55753/Dockerfile#L5)
