### ISSUE TITLE
Add comparison with some other periods

### ISSUE THREAD

**Issue by divinerites** [plausible/analytics#277]
## Prerequisites
- [X] I have searched open and closed issues to make sure that the feature has not yet been requested.

## Feature request

Being able to compare the actual showed period with an other would be a good & useful feature.

There is 2 main use case :

1. Same period last year : *(7 days <-> same dates last year)*
1. The period just before this one : *(7 days <-> the 7 days just before)*

There is a minor use case : Use `last month/trimester/semester` instead of `last year` when this option makes sense.

**How would you like it to work**

Add a checkbox/selecter and :

- Shows the curve in an other color
- Shows the drilldowns in 2 columns (top pages, top sources, countries, goals)

The perfect UI would let us choose whether we see : actual period, old period, both periods.

**Comment by divinerites** [comment]
This also works for https://github.com/plausible/analytics/issues/126

**Comment by Lucent** [comment]
One big improvement over Google Analytics would be if "compared to one year ago" shifted to the nearest same weekday.
