### ISSUE TITLE
SSL not enabled even with SCHEME set to https

### ISSUE THREAD

**Issue by jhalexand** [plausible/analytics#279]
## Prerequisites
- [ X ] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report
**Describe the bug**
I initially installed plausible (using docker-compose) with the default environment variables just to try it out.  I discovered it was using HTTP only so I tried to change it to https via the `SCHEME` environment variable as described in the HOSTING.md doc. I tried rebuilding and it didn't change even though my port number did (it wasn't clear what actually had to be removed when changing the variables).  So, to be sure, I wiped out all docker containers, images, and volumes. I copied the sample environment variables to a new file, deleted the sample file, and updated docker-compose.yml to point at my new file. I made sure I added a line showing `SCHEME=https` and I set the port to 8443 (and changed the port mapping in the docker-compose.yml to be 443:8443).  When I reran the setup, then up'ed plausible, I discovered that it was running on 443, but it was still HTTP, not HTTPS.

Am I missing a step here?

**Expected behavior**
Setting SCHEME to https should enable SSL (presumably with a self-signed certificate).

**Environment (If applicable):**
 - Oracle Linux 7.8

**Comment by ukutaht** [comment]
I can confirm that setting SCHEME to `https` does not enable ssl on the server. For the cloud version we are running behind a reverse proxy that terminates ssl for us so there has been no need to enable it on the app server.

At the moment, the `SCHEME` variable is used to control URL generation only. When we include a link in an email, for example, we want it to be `https://yourdomain.com/...`

I'm torn between using the `SCHEME` variable to enable/disable ssl or whether to introduce a new variable like `SSL_ENABLED`. For my own use-case, we want the urls to be https but I don't want to accept ssl connections on the app server. OTOH it wouldn't hurt to automatically enable it, I can just ignore the ssl port in my mapping.

**Comment by tckb** [comment]
@ukutaht  / @jhalexand  the scheme param is meant only for URL generation. This param _by no means_  enables any automatic SSL capability.  In most cases, ssl termination is handled by the reverse proxy/edge servers sitting in-front of the app server. It is usually not encouraged for app servers to handle SSL termination, for good reasons. 


In future if we choose to enable this, we might need to add a different parameter as @ukutaht  mentioned as `SSL_*`

**Comment by ukutaht** [comment]
Not planning to support SSL within the phoenix app itself. Please use a reverse proxy as explained here: https://docs.plausible.io/self-hosting#2-reverse-proxy
