### ISSUE TITLE
Switch website/domain

### ISSUE THREAD

**Issue by kevquirk** [plausible/analytics#283]
I monitor more than one website on Plausible. At the moment, if I want to switch between sites, I need to go back to the homepage, then select the other site.

It would be great if when there’s more than one domain assigned to an account the bit where it says “Analytics for <domain>” had a drop down to switch domains.

**Comment by metmarkosaric** [comment]
Thanks @kevquirk. Take a look at the update we released an hour ago or so. It does exactly what you ask :)

**Comment by kevquirk** [comment]
Goddam, that's some good customer service! :-D
