### ISSUE TITLE
Weekly Email Mobile Formating Issues

### ISSUE THREAD

**Issue by chrislentz** [plausible/analytics#284]
### Precheck

Please note that this tracker is only for bugs. Do not use the issue tracker for help or support. [Our docs](https://docs.plausible.io/) are a great place for most answers, but if you can’t find your answer there, you can [contact us](https://plausible.io/contact). Have an issue with your self-hosted install? You can ask in [our community forum](https://plausible.discourse.group/). Thanks!

## Prerequisites
- [X] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report
**Describe the bug**
On mobile, the weekly analytics email has loads of formatting issues. See attached screenshot. The same issues can be seen on desktop by shrinking down the window. It looks like 

**Expected behavior**
The formatting should better match the larger view of the email with some padding around the edges and proper formatting around the 3 stats at the top.

**Screenshots (If applicable)**
![email-issues](https://user-images.githubusercontent.com/428312/90158887-9b92af00-dd5d-11ea-9815-bfe0de5a49ef.jpg)

**Environment (If applicable):**
 - OS: iOS, MacOS
 - Email Client: Gmail, Edison Mail
 - Version: n/a

**Comment by gabllux** [comment]
Hello, I'm experiencing formatting issues also on Outlook Desktop (Office 365, version 16.0) on Windows10.

![Screenshot_1](https://user-images.githubusercontent.com/74540704/109477888-da2d5400-7a78-11eb-9185-dd3d41abc0fc.png)

Thanks

**Comment by metmarkosaric** [comment]
"maybe the logo need tiny white border for dark mode, to shine better !"

![FHDv2oeXMAoAoc2](https://user-images.githubusercontent.com/34340819/146788817-5ae13174-1c34-4641-b8ae-7154d682f7f0.jpeg)

"The fonts could also be a bit larger."

![FHDy6rsXoAEEU3a](https://user-images.githubusercontent.com/34340819/146788942-6e2c985f-ea2e-4228-b760-ffc74f97b126.jpeg)

(from [twitter](https://twitter.com/martindonadieu/status/1472940952650190859))

**Comment by Swiss-Mac-User** [comment]
Issue still persists in iOS 16.4.1 – see #2866 

Affects default device portrait mode when opening email initially; when moving device into landscape mode the styling is much better, and moving back to portrait keeps some improved formattings.

**Comment by aerosol** [comment]
Hi folks, just letting you know we've just released a new, simplified version of the weekly/monthly report e-mail.
