### ISSUE TITLE
Custom goals removed after a domain name change

### ISSUE THREAD

**Issue by mquandalle** [plausible/analytics#2852]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

I used the new feature to change the domain name https://plausible.io/changelog
It worked but custom goals where lost in my settings.

### Expected behavior

Transfer custom goals config over the new domain

### Environment

```markdown
- OS:
- Browser:
- Browser Version:
```

**Comment by metmarkosaric** [comment]
thanks for reporting @mquandalle! we fixed this in this PR: https://github.com/plausible/analytics/pull/2828. in your case for domain changes previous to this fix, please manually add the goal names in the site settings for the goals to populate again. sorry for the trouble!
