### ISSUE TITLE
The new filter with multiple selection break "wildcard path"

### ISSUE THREAD

**Issue by mquandalle** [plausible/analytics#2853]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

It used to be possible to filter pages using `*` to indicate "all pages matching a subpath". I can't input this filter anymore with the new input box.

### Expected behavior

Be able to type and enter `/mysubpath/*` to filter pages matching a subpath.

### Screenshots

![wildcard-path-issue](https://user-images.githubusercontent.com/1730702/232237737-411ba106-cca6-476f-9b99-ee1c14048c7f.gif)

### Environment

```markdown
- OS:
- Browser:
- Browser Version:
```

**Comment by metmarkosaric** [comment]
hi @mquandalle! we now have the "contains" option in the "filter" menu in addition to "is" and "is not". you can use "contains" and just insert the word itself no need to do the wildcards anymore

**Comment by ukutaht** [comment]
You can also still use the wildcards when you scroll down in the suggestions and click the `Filter by /department/*` option.

<img width="535" alt="Screenshot 2023-04-18 at 11 44 17" src="https://user-images.githubusercontent.com/3731516/232753788-f351cbac-c570-4731-b1c8-d7fa150ef1da.png">


Sorry, the UX for this isn't very clear. That option should probably be highlighted more prominently when a * is used in the filter.
