### ISSUE TITLE
%-comparison is way off - not considering imported GA data?

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/analytics#2870]
### Discussed in https://github.com/plausible/analytics/discussions/2867

<div type='discussions-op-text'>

<sup>Originally posted by **Swiss-Mac-User** April 23, 2023</sup>
The comparison vs previous period of my site are way off, e.g. when using „Current month“ view. Is this a bug in correlation with GA data import, where also native Plausible data has been tracked ?

I started tracking with Plausible last month (March) and it recorded „natively“ 550 pageviews. All the other data was imported from Google Analytics to keep the historical data.

It seems to me, that the data comparison vs last period (increase / decrease) does not take the imported data into account…

* Current month: 2.9k pageviews
* Last month: 4.1k pageviews
* Comparison: should be „-34%“
* _Instead it shows as_: „+450%“? (That’s the 550 pageviews natively recorded by Plausible in the last period)

![IMG_2158](https://user-images.githubusercontent.com/47624464/233833925-a2a4ca39-a8f4-4dc8-85f1-4e95706b8082.jpeg)
![IMG_2159](https://user-images.githubusercontent.com/47624464/233833928-f2e5e18c-f0c4-4459-8a0b-551089a5e753.jpeg)
</div>

**Comment by vinibrsl** [comment]
Oops! This was caused by the refactoring we did for comparisons. I'm currently working on a fix :)
