### ISSUE TITLE
Clicking on browser's scrollbar closes details dialog

### ISSUE THREAD

**Issue by FINDarkside** [plausible/analytics#2872]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

On desktop browsers when you open a details dialog and try to scroll by dragging the browser's scrollbar handle, Plausible will close the details dialog.

### Expected behavior

Expected behaviour is details dialog staying open when user clicks the scrollbar and starts scrolling.

### Environment

```markdown
- OS: Ubuntu 22.04.2 LTS
- Browser: Chrome
- Browser Version: 112
```

**Comment by DavidOliver** [comment]
Same in Firefox.
