### ISSUE TITLE
Event goals -- not tracked in CMS that DOES support =

### ISSUE THREAD

**Issue by wheeleran** [plausible/analytics#2887]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Self-hosting

### Describe the bug

hi. On divi sites which DO actually support using '=' equals sign in the plausible-event-name CSS class name, i've tested using '--' because i'm curious, but primarily because i want to use one format on all my tracked sites, so divi = supported and non-divi not supported =. i've discovered (and checked) that because divi DOES support using the equals sign in the class name, using the double dash DOESN'T work. can someone check this for me, because the documentation callout note on [this](https://plausible.io/docs/custom-event-goals) page should be updated to include the qualification that "double dashes ONLY work if the equals sign ISN'T supported."

either that or i'm wrong?

### Expected behavior

double dashes should be support on sites that do also support the equals sign.

### Environment

```markdown
- OS:
- Browser:
- Browser Version:
```

**Comment by metmarkosaric** [comment]
thanks for reporting @wheeleran! this is a new feature. our self-hosted code is not updated as frequently as the Plausible managed hosting in the cloud, which changes daily. this means that the latest features won't be immediately available. you can read more here https://plausible.io/self-hosted-web-analytics
