### ISSUE TITLE
Project name is not shown on mobile

### ISSUE THREAD

**Issue by lucafaggianelli** [plausible/analytics#2924]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

On mobile, the project name is not shown, the project selector though work and shows the available projects when you open it.

In general the UI is not very comfortable on mobile, the click targets are very small

### Expected behavior

I would like to see the current project name

### Screenshots

<img width="276" alt="image" src="https://github.com/plausible/analytics/assets/4471043/aa0e28c6-5dfc-47a0-b31f-c36d7782a688">

### Environment

```markdown
- OS: MacOS
- Browser: Chrome
- Browser Version: 109.0.5414.119
```

**Comment by metmarkosaric** [comment]
thanks for the feedback @lucafaggianelli! this is intentional as there's no space on smaller screens to show everything that we show on larger screens. we do show your site's favicon there so if you add a favicon to your site it will allow you to easily recognize what dashboard you're looking at
