### ISSUE TITLE
Outbound Link Tracking adds significant delays on click

### ISSUE THREAD

**Issue by noclat** [plausible/analytics#2940]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

Hi there,

When turning on Outbound Link Tracking with `script.outbound-links.tagged-events.js`, clicking on an external link adds a significant delay before opening it, counting in seconds.

The delay doesn't happen when I add `target="blank"`, but for some links we'd rather not open a new tab. For now we use this fixture otherwise the site looks like it's stalling or that the link is broken (opening the user dashboard from the marketing site).

The website runs on NextJS and we only use SSG to host it on Firebase CDN. The issue persists whether we use Next `<Link>` or native `<a>`, `localStorage.plausible_ignore=true` or not, development or production. I also turned off my `smoothScroll` router events for anchor links that may alter the links behavior.

### Expected behavior

I'd expect a small delay because of the extra Plausible API call, but a few milliseconds, not seconds.

### Environment

```markdown
- OS: MacOS
- Browser: both Safari and Chrome
- Browser Version: latest
```

**Comment by RobertJoonas** [comment]
Thanks for reporting that @noclat! We do have max delay of 5 seconds for all custom events. This is to make sure that the event requests have enough time to be sent reliably. As you're always experiencing this delay, I suspect that the custom events are not going through to Plausible either? Or do you see the `Outbound Link: Click` events in your dashboard?

It would be best if you could reach out to us via email (hello@plausible.io) and share the exact page where this is happening. This would help us better understand what's going on. Thanks!

**Comment by noclat** [comment]
Thanks @RobertJoonas, email sent!

**Comment by noclat** [comment]
To reproduce the bug: https://github.com/noclat/plausible-outbound-links

**Comment by nicbou** [comment]
I regularly experience this too, as of July 26. I don't think that the issue can be closed, @RobertJoonas .
