### ISSUE TITLE
Next.js head-manager conflict (error when loading Plausible)

### ISSUE THREAD

**Issue by galkowskit** [plausible/analytics#295]
### Precheck

Please note that this tracker is only for bugs. Do not use the issue tracker for help or support. [Our docs](https://docs.plausible.io/) are a great place for most answers, but if you can’t find your answer there, you can [contact us](https://plausible.io/contact). Have an issue with your self-hosted install? You can ask in [our community forum](https://plausible.discourse.group/). Thanks!

## Prerequisites
- [x] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report
**Describe the bug**
Plausible might be doing something weird with the `<head>` tag. In Next.js head manager should be the one to handle it but it might be Plausible's fault. I'm not sure about where the issue lies so I'm leaving this issue here and cross-linking to Next.js issue over here: https://github.com/vercel/next.js/issues/9573.

I'm not 100% sure that it is Plausible's fault, so I'll keep digging and provide more information here as I uncover what is happening.

```
[Error] Unhandled Promise Rejection: TypeError: null is not an object (evaluating 'j.tagName')
	updateElements (head-manager.js:53)
	(anonymous function) (head-manager.js:103)
	forEach
	(anonymous function) (head-manager.js:102)
	promiseReactionJob
```

**Expected behavior**
No errors.

**Screenshots (If applicable)**
Not applicable, an error in Console.

**Environment (If applicable):**
 - OS: all of them
 - Browser: all of them
 - Version: N/A

**Comment by metmarkosaric** [comment]
Thanks! Seems like this is a problem on their side so closing this. Do let us know if there's something else.

**Comment by galkowskit** [comment]
Yes, it seems to be something on Next.js side. I got it fixed "somehow", I'm not sure how but during refactoring in Next.js's `_document.js` and `_app.js` Plausible stopped irritating Next.js. I'm sorry I cannot provide anything more specific. However, you are right that this is on Next.js side.

**Comment by metmarkosaric** [comment]
Thanks for the update @galkowskit!
