### ISSUE TITLE
Missing Direct Source visitors

### ISSUE THREAD

**Issue by kendoscl** [plausible/analytics#2950]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Self-hosting

### Describe the bug

Hello, 
My website have used from both Plausible Cloud and Plausible self-hosting
The comparison results between both version is quite far different. some how the plausible self-hosting does not received and display the visitors came from "direct source". On plausible self-hosting totally ignoring "**direct visitors**"
And also there are missing data on self-hosting version, please see my attachment

Plausible cloud result:
<img width="850" alt="image" src="https://github.com/plausible/analytics/assets/122953838/16f1186f-97d1-421e-b2c9-470307cee49d">

Plausible self-hosting result:
<img width="833" alt="image" src="https://github.com/plausible/analytics/assets/122953838/cb41cd09-b3b1-4aa2-8479-9f39a803ca56">

### Expected behavior

I expected both are showing same result

### Environment

```markdown
- OS:
- Browser:
- Browser Version:
```

**Comment by metmarkosaric** [comment]
hi @kendoscl!

traffic numbers are not necessarily expected to be equal between managed hosting in the cloud and the self-hosted installations as the tracking depends on the infrastructure. factors such as the capacity of servers and whether the script runs from a global cdn impact stability and speed which makes a difference to how many visitors it counts. as you have many visitors so you can look at improving your self-hosted infrastructure to capture more traffic.

for "direct" traffic on self-hosted you can click on the "details" button. we've changed this on the cloud. our self-hosted code is not updated as frequently as the managed hosting in the cloud, which changes daily. this means that the latest features won't be immediately available.

**Comment by kendoscl** [comment]
Hello, what is your specs recommendation for 5 Pageviews per day?

**Comment by kendoscl** [comment]
Hello, what is your specs recommendation for 5M Pageviews per day?
