### ISSUE TITLE
All time view not working correctly

### ISSUE THREAD

**Issue by LuD-up** [plausible/analytics#2982]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

Hello,

For a few days now, the "All time" view has been blocked at "Month" only.

https://github.com/plausible/analytics/assets/77074386/5d3f643c-e8d9-4ccc-993f-23fd6418a965

### Expected behavior

Normally, the tab changes over the selected duration.

### Environment

```markdown
- OS: MacOS/iOS
- Browser: Safari
- Browser Version: 16.4
```

**Comment by ukutaht** [comment]
Sorry I don't fully understand the report. What do you expect to see in the dashboard and what do you see instead?

**Comment by LuD-up** [comment]
I can't get the Days/Weeks views in All time, only Months. It happen only on the "All time" view, everything else is working correctly.

**Comment by metmarkosaric** [comment]
thanks for reporting @LuD-up! i'm able to reproduce this too. in all time view, it's not possible to change the interval from the default month to week or day. when you click on a different interval, it goes back the the default monthly interval. doesn't look to be happening on other time ranges

**Comment by toniengelhardt** [comment]
Would also love to see this fixed. 

A temporary workaround is to use custom range and then select the first available date and the last.

**Comment by kekkodance** [comment]
I get this now. Latest version

**Comment by ruslandoga** [comment]
@kekkodance 👋

Note that the current `latest` self-hosted release might not contain all bug fixes that have been merged.
