### ISSUE TITLE
Search in Filters is broken

### ISSUE THREAD

**Issue by marekzelezny** [plausible/analytics#2991]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

Searching for a value of a property doesn't work. It shows only (none) option. 

It seems there is a problem with XHR props undefined as shown on screenshot.

<img width="654" alt="Snímek obrazovky 2023-05-31 v 12 31 40" src="https://github.com/plausible/analytics/assets/6258792/7e733f3d-b6db-4c2b-b5cc-116285f78794">

### Expected behavior

Get the value matching the query

### Environment

```markdown
- OS: MacOS Ventura
- Browser: Microsoft Edge
- Browser Version: 113.0.1774.57
```

**Comment by metmarkosaric** [comment]
thanks for reporting @marekzelezny! i can reproduce that too. we'll see to fix it before the public release of properties

**Comment by RobertJoonas** [comment]
Closing this as completed in https://github.com/plausible/analytics/pull/3126
