### ISSUE TITLE
Offline support for PWAs

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/analytics#300]
"Queue up events/page changes when the PWAs are offline and then send them all when network connectivity is restored"

(feedback via email)

**Comment by Lucent** [comment]
Happy for any kind of detection of standalone mode to track PWA usage.

**Comment by bzoum** [comment]
Hello,
I would be interested as well to track the use of the PWA. In particular, I would be interested by detecting when the visitors are on the app or on their usual browser.
