### ISSUE TITLE
Custom/Random tracking script name per property

### ISSUE THREAD

**Issue by marban** [plausible/analytics#306]
In addition to a custom domain, this should add some extra leeway to circumvent blockers.

**Comment by ukutaht** [comment]
Thanks for the suggestion!

On a custom domain you can already use any filename you want e.g. `stats.mydomain.com/js/anything-works-here.js`. Maybe it needs to be better documented?

On the hosted version it doesn't matter. Blocklists can just enter the `plausible.io` domain and the filename doesn't matter.

**Comment by ukutaht** [comment]
@marban can you clarify the request? Does it apply to a self-hosted situation, hosted via `plausible.io` or hosted via custom domain?

**Comment by metmarkosaric** [comment]
Closing this
