### ISSUE TITLE
Breakdown API by custom prop and filter by custom prop

### ISSUE THREAD

**Issue by JohannesRudolph** [plausible/analytics#3071]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

The API docs say we can breakdown and filter by custom prop to overcome limitations that breakdown is only supported by a single prop at a time. https://plausible.io/docs/stats-api#breaking-down-by-multiple-properties-at-the-same-time

> So if you want a breakdown by both event:page and visit:source for example, you would have to make multiple queries (break down on one property and filter on another) and then manually/programmatically group the results together in one report

The API docs have an example filtering by `event:name` and breakdown by `event:prop:method`, see 
https://plausible.io/docs/stats-api#breakdown-custom-event-by-custom-props

However, whenever I'm making a query where both the filter and the breakdown property are custom event props like `filters=event:props:foo%3D%3D` and `property=event:props:bar` I get back an empty result from the API and not properly filtered like the example in the API docs. Is this a limitation in plausible? 

This behavior is consistent with the dashboard, which I also can't seem to do this. 

### Expected behavior

I get results broken down and filtered by two different custom props

### Environment

```markdown
Using the api
```

**Comment by bogplau** [comment]
Hey @JohannesRudolph, can you please [send us an email](https://plausible.io/contact) so I can take a closer look and see what's going on?

Please mention the dashboard, goal/prop and, if possible, a screenshot of the results you're getting on your end. 

Thank you!

**Comment by metmarkosaric** [comment]
closing this as for support questions, it's best to contact [our customer support directly](https://plausible.io/contact) so we can take a look at what's going on. we keep github issues to the bugs with the product only and support is best place for anything related to your specific account. thanks!
