### ISSUE TITLE
UTM parameters being ignored on events sent via the API

### ISSUE THREAD

**Issue by rodrigotassinari** [plausible/analytics#3074]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

I've sent a bunch of test events via the API, with and without UTM tags on the event URL. The [API docs](https://plausible.io/docs/events-api#request-body-json-parameters) says that "_If the URL contains UTM parameters, they will be extracted and stored_", however this does not seem to be the case. I cannot see any of the UTM tags I'd sent with the event on the dashboard. 

### Expected behavior

The UTM tags' values shouls appear on the dashboard when filtering by the event.

### Screenshots

Example event API call:

![CleanShot 2023-06-24 at 13 31 22](https://github.com/plausible/analytics/assets/15730/61ae9f3d-c3b1-4618-a526-c538e24b5c0f)

Dashboard filtering by the event goal, not showing any UTM tags:

![CleanShot 2023-06-24 at 13 32 49](https://github.com/plausible/analytics/assets/15730/26388a0c-bf63-444f-ad9e-eab3fde65db1)

![CleanShot 2023-06-24 at 13 33 02](https://github.com/plausible/analytics/assets/15730/3bc4ece2-2663-4c36-a8e2-16ee1ea62158)

![CleanShot 2023-06-24 at 13 33 09](https://github.com/plausible/analytics/assets/15730/7c77771c-6f1c-40d5-9a35-125d1cbf2008)

### Environment

```markdown
- OS: MacOS
- Browser: Firefox
- Browser Version: 114
```

**Comment by metmarkosaric** [comment]
hi @rodrigotassinari! could it be that you're not starting a new session when testing these? all referral sources including utm query parameters are counted only when they start a new session on your site. so if you've visited your site earlier in the day and now try to visit again, your initial referral source would still count and the latest source won't be included in the Top Sources report. 

this is why you don't see all of your own sources if you, for instance, click to test several different UTM-tagged links at the same time. you would need to start a new session by using a different browser, a different IP address, or a different device for the new source to be included in the report.

**Comment by rodrigotassinari** [comment]
> could it be that you're not starting a new session when testing these?

that was it @metmarkosaric ! sorry about not catching this and wrongly opening the issue. and thanks for your excellent explanation.
