### ISSUE TITLE
Occasional 502 and 504 Errors in Plausible Requests

### ISSUE THREAD

**Issue by k9ordon** [plausible/analytics#3084]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

#2545, #1976, #1815, #443, #266

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

We are using the hosted version of Plausible and proxying the events through a Vercel edge function. Everything works perfectly (IP, location, uniques, etc.) but we noticed something while going through the logs. We are seeing occasional 502 and sometimes 504 errors in Plausible requests. I've noticed there were some closed issues on this matter previously. 

Could this be related to peak times when many events are being sent at once? Should we implement retries on our end via the Vercel proxy for these requests?

### Expected behavior

We expected the requests to Plausible to be handled without these errors. 

### Environment

```markdown
- node 18
- vercel edge runtime
- web fetch
```

**Comment by metmarkosaric** [comment]
thanks for reaching out @k9ordon! for support questions, it's best to contact [our customer support directly](https://plausible.io/contact) so we can take a look at what's going on. we keep github issues to the bugs with the product only and support is best place for anything related to your specific account. could you please contact us with more details on what you're seeing and we'll get back to you? thanks!
