### ISSUE TITLE
Same results when paginating

### ISSUE THREAD

**Issue by kringkaste** [plausible/analytics#3100]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

When paginating results with the following sequence of API requests

https://plausible.io/api/v1/stats/breakdown?site_id=example.com&period=day&property=event:page&limit=1000&page=1&metrics=visit_duration&date=2023-06-29
https://plausible.io/api/v1/stats/breakdown?site_id=example.com&period=day&property=event:page&limit=1000&page=2&metrics=visit_duration&date=2023-06-29
https://plausible.io/api/v1/stats/breakdown?site_id=example.com&period=day&property=event:page&limit=1000&page=3&metrics=visit_duration&date=2023-06-29
[...]

I get always the same 1000 results.

### Expected behavior

Paginating results when using `page` and `limit`.

**Comment by metmarkosaric** [comment]
hi @kringkaste! do you have more than 1000 pages with visitors in that time period? i'll close this for now as we keep the issues for bugs with the product only but please do [contact our customer support](https://plausible.io/contact) so we can help out
