### ISSUE TITLE
Difficulty in integration

### ISSUE THREAD

**Issue by bro99** [plausible/analytics#3127]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

I'm having problems integrating with my website that is hosted on cloudshop, link https://usematerialescolar.com.br/

the problem is that transactions or revenue do not appear, I have tried with everything that is adjusted, but nothing of revenue is plotted.

I already simulated a purchase and put the tags in all cloudshop options, but I don't receive anything in plausible

### Expected behavior

The expected would be the same in google analytics to see the purchases made by users by origin, media and campaign during the day

### Screenshots

![image](https://github.com/plausible/analytics/assets/51249721/add4b08e-d53a-4d54-bc9e-6058266b708b)
![Imagem do WhatsApp de 2023-07-11 à(s) 16 40 59](https://github.com/plausible/analytics/assets/51249721/41fdaf98-9019-47f0-99a4-f20bab1f1994)

### Environment

```markdown
- OS: WIN 11
- Browser: CHROME
- Browser Version: 104...
```

**Comment by metmarkosaric** [comment]
hi @bro99! you've also emailed our support and we've responded. let's continue the conversation via email as that's the best place for any type of support questions. we keep the issues for actual bugs with the product only
