### ISSUE TITLE
plausible.io website is down

### ISSUE THREAD

**Issue by tomjuggler** [plausible/analytics#3149]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

I'm hoping to use the service but cannot access the docs

### Expected behavior

open plausible.io website and read docs

### Environment

```markdown
- OS: android
- Browser: Firefox
- Browser Version: latest from f-droid
```

**Comment by ruslandoga** [comment]
👋 @tomjuggler 

It seems to be up for me and https://downforeveryoneorjustme.com/plausible.io

**Comment by tomjuggler** [comment]
Well it's back up now. Not sure what happened..
