### ISSUE TITLE
Custom Range Setting Broken

### ISSUE THREAD

**Issue by ryanscdavis** [plausible/analytics#315]
## Prerequisites
- I did not find this bug reported in opened or closed issues.

## Bug report
**Describe the bug**
In the site analytics dashboard, when I click on "Custom Range" from the dropdown all I see is a bunch of numbers appear below the chart.

**Expected behavior**
I was expecting a date-picker to popup.

**Screenshots (If applicable)**
The image shows my screen just after clicking "Custom Range" from the dropdown
![Screen Shot 2020-09-10 at 5 42 01 PM](https://user-images.githubusercontent.com/38838551/92818160-00591d80-f38d-11ea-9e9f-276533a7752c.png)

**Environment (If applicable):**
 - OS: macOS Catalina 10.15.6
 - Browser Chrome
 - Version 85.0.4183.83 (Official Build) (64-bit)

**Comment by metmarkosaric** [comment]
Thanks for reporting this @ryanscdavis! I can replicate the same issue on my side. We'll take a look and fix this asap. Sorry for the inconvenience!

**Comment by ukutaht** [comment]
Thanks for reporting.

Fixed in f871aaa195138631cd7b4c60f6b1fc4e42ca7547
