### ISSUE TITLE
Custom data (custom dimensions) attached to pageviews

### ISSUE THREAD

**Issue by davidfischer** [plausible/analytics#320]
## Precheck

Please note that this tracker is only for feature requests. Do not use the issue tracker for help or support. [Our docs](https://docs.plausible.io/) are a great place for most answers, but if you can’t find your answer there, you can [contact us](https://plausible.io/contact). Have an issue with your self-hosted install? You can ask in [our community forum](https://plausible.discourse.group/). Thanks!

## Prerequisites
- [X] I have searched open and closed issues to make sure that the feature has not yet been requested.

## Feature request
**Is your feature request related to a problem? Please describe.**
I would like to be able to attach custom data (think [GA custom dimensions](https://support.google.com/analytics/answer/2709828?hl=en)) when sending a pageview. Then I would like to aggregate on those dimensions. I saw the documentation on [custom events](https://docs.plausible.io/custom-event-goals) but I didn't see anything on attaching custom data to a pageview.

**How would you like it to work**
I'm pretty flexible here. Perhaps the custom data could come from custom meta tags or perhaps there would be an option to manually trigger a pageview with JavaScript and send the data that way.

Sorry if this feature is available somewhere else and I couldn't find it.

**Comment by ukutaht** [comment]
Agreed, this would make the platform a lot more powerful.

One use-case we've been asked before is filtering articles by the author of the post. Instead of implementing specific fields like `author`, it would probably make more sense to allow flexible custom dimensions. 

I'm really open for suggestions on how the API for this could look. Some options off the top of my head:

### 1. Manual

In this case, to send a custom dimension you need to disable automatic pageview collection and instead send them manually along with your custom dimensions:

```html
<script async defer data-manual="true" data-domain="plausible.io" src="https://plausible.io/js/plausible.js"></script>
```

... later

```javascript
plausible('pageview', custom: {author: 'Uku Taht'})
```

2. Automatic via script tag

This option would probably be less flexible but maybe more convenient depending how you render your page. Just set the custom dimension via html attributes on the script tag:

```html
<script async defer custom-author="Uku Taht" data-domain="plausible.io" src="https://plausible.io/js/plausible.js"></script>
```

The tracker could check for any attribute following the `custom-{key}="{value}"` pattern and automatically send them along.

**Comment by davidfischer** [comment]
Another option as I mentioned is to have custom meta tags that are sent. This could work in a somewhat similar fashion to something like opengraph. Think tags like


```html
<meta property="analytics:author" content="David" />
<meta property="analytics:another_field" content="Another Value" />
```

Any tags with the appropriate prefix get picked up and sent as custom dimensions. These same pieces of data could get picked up for custom events as well.

Something like your manual proposal could work as well.

**Comment by ukutaht** [comment]
Right, that looks like a great option as well.

**Comment by janejuenyang** [comment]
Hello! Glad to see this feature request has already been raised. :) Chiming in to mention another use case for this feature: A/B testing. To make sure we have a large enough sample size for a test, we’d need to know how many visitors saw a particular variation.

FWIW on the API form, we’re also flexible but would prefer the data-attribute or meta tag forms over the manual configuration.

**Comment by ukutaht** [comment]
@janejuenyang Yeah thanks for bringing that up, we don't have a good way to segment visitors for A/B testing.

I think implementing custom props on pageviews will definitely be helpful. You can tag the pageview with the visitor's segment and also tag the conversion event. It will work for getting conversion rates but there's some manual work involved where you have to grab the numbers and plug them into a calculator.

A second phase could be full support for A/B testing. This would involve:
1. Adding a session-level `segment` property to capture which variant the user is shown
2. Making Plausible aware of A/B testing so we can calculate the conversion rates and confidence intervals for you
