### ISSUE TITLE
Public Key exposed in priv folder

### ISSUE THREAD

**Issue by Aju100** [plausible/analytics#324]
## Bug report
The public key is pushed in priv folder. Here is the link to the public key.
https://github.com/plausible/analytics/blob/master/priv/paddle.pem

## Weakness 
- Cleartext Storage of Sensitive Information

**Comment by ukutaht** [comment]
Thanks for the report.

I don't believe this is a problem. Public keys can safely be, well, public. As long as Paddle keeps the corresponding private key secret, it is impossible to sign a fake webhook that passes our verification. What sort of attack would hiding the public key prevent?
