### ISSUE TITLE
New custom props functionality seems broken

### ISSUE THREAD

**Issue by zacnoo** [plausible/analytics#3243]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

Old property drill down on event goals have disappeared (but I guess that's just being replaced by the new custom properties stuff)

However, upon trying to go to the new Custom Properties section in the settings of the website, it just refresh loops, so there's currently no way for me to see all of the custom properties I've been submitting, that were previously accessible.

### Expected behavior

To be able to access all custom properties in the event goal drill down, and be able to access the custom properties settings page to edit custom properties that are visible.

### Screenshots

![Screenshot 2023-08-08 at 2 05 06 PM](https://github.com/plausible/analytics/assets/3452866/d8cd4e15-3db3-4802-a22f-32c065514dd3)
![Screenshot 2023-08-08 at 2 05 52 PM](https://github.com/plausible/analytics/assets/3452866/c6d98c62-757d-47a0-a07e-e0dda67a9420)

### Environment

```markdown
- OS: macOS 13.5
- Browser: Safari
- Browser Version: 16.6
```

**Comment by metmarkosaric** [comment]
thanks for reporting @zacnoo and sorry for the trouble! to fix this, please clear the cookies stored in your browser for plausible.io and log into your Plausible account again. then it should work all fine
