### ISSUE TITLE
Display Brave browser visitor numbers

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/analytics#325]
"Do you think you can add the ability to detect Brave even though they’re using Chrome’s user agent? I saw an article about how to detect Brave and thought maybe you could implement it to Plausible? https://www.ctrl.blog/entry/brave-user-agent-detection.html"

(request via email)

**Comment by tlghnb** [comment]
According to the article, this is how easy it is;

`(navigator.brave && await navigator.brave.isBrave() || false)`

**Comment by ukutaht** [comment]
oh, that seems pretty easy.

I wonder when would `navigator.brave` be defined but `navigator.brave.isBrave` resolve to false? Wouldn't it be sufficient to just check presence of `navigator.brave`?

**Comment by metmarkosaric** [comment]
Brave is taking so many steps in order to make themselves look like Chrome (and always evolving their approach) so we've decided that we will not try and work on identifying Brave browser users. They will be listed with the browser name that Brave wants to be listed with.
