### ISSUE TITLE
Visits from Yahoo Japan Crawler appear in the analytics.

### ISSUE THREAD

**Issue by andyj2022** [plausible/analytics#3253]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Self-hosting

### Describe the bug

Hundreds of pageviews from Japan appear in the analytics, with this user-agent:

`Mozilla/5.0 (compatible; Y!J-WSC/1.0; +https://yahoo.jp/3BSZgF)`

### Expected behavior

Web crawlers do not send pageviews.

### Environment

```markdown
- OS: all
- Browser: all
- Browser Version: all
```

**Comment by ruslandoga** [comment]
👋 @andyj2022 

What Plausible version are you using?
