### ISSUE TITLE
Multiple users and roles

### ISSUE THREAD

**Issue by vermorel** [plausible/analytics#327]
Right now, a Plausible account only supports a single user, which is rather troublesome for a corporate use. It would be very nice if it was possible to add multiple users. To keep things simple, two roles would be sufficient:

* Admin, everything is allowed (including removing another admin)
* Viewer, a read-only access to the account

**Comment by metmarkosaric** [comment]
Thanks @vermorel! That makes sense and we plan to build it. I'll close this thread as there's another thread already for this feature request #176

**Comment by vermorel** [comment]
Thanks!
