### ISSUE TITLE
Add Event "label" to Custom Events

### ISSUE THREAD

**Issue by mark-wff** [plausible/analytics#330]
## Feature request
In Google-Analytics you have the possibility to Track Custom Events with more information. Like: 

ReactGA.event({
  category: 'User',
  action: 'Download',
  label: 'My First PDF',
});

In my case i want to track which PDFs get downloaded the most. If i have to create a Goal for each
PDF I add to my CMS it whould be a lot of work. It would be great if something like that would be possible: 

plausible('Download - PDF', 'My First PDF');

**Comment by ukutaht** [comment]
Thanks for your request! 

This is actually the next thing on the roadmap. It's been requested before so closing in favour of #134
