### ISSUE TITLE
Cannot select Sundays in the date picker on iPhone mini

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/analytics#3304]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

"I'm on a iPhone mini and when I view the date comparison calendar I can't see / select Sundays."

<img width="420" alt="Screenshot 2023-08-29 at 15 06 34" src="https://github.com/plausible/analytics/assets/34340819/545a4f24-e774-40e5-b985-9064617ea3c6">

### Expected behavior

List all the week days

### Environment

```markdown
- OS:
- Browser:
- Browser Version:
```

**Comment by adityaraute** [comment]
haha this is so weird

**Comment by siddiqss** [comment]
Plausible frontend has issues with responsiveness. The date picker component does have Sunday but due to overflow on x axis it's not showing Sunday. Try swiping to the left/right. It should show Sunday.
