### ISSUE TITLE
Refactoring opportunity

### ISSUE THREAD

**Issue by preslavrachev** [plausible/analytics#332]
Hey guys,

You may decide to ignore this issue altogether. However, I have spotted a few places, where we could work towards making the code easier to read and simpler to comprehend.

Take, for instance the `if-else` block here:
https://github.com/plausible/analytics/blob/924c96f0a563432fffcb83c6c01cb04169d1a819/lib/plausible_web/controllers/stats_controller.ex#L17

Generally, nested blocks increase complexity. What I would do instead, is focus on the happy path inside the controller action, and take care of externalities in their respective components. IMO, the check whether a user's trial has expired could perfectly fit a separate Plug (e.g. `UserBillingPlug`) that you can wrap this controller action with. With that alone, you remove one level of indentation, i.e. code complexity.

Another trick I'd use is to avid `else` as much as possible. Take the inner ìf-else` block, for example:
https://github.com/plausible/analytics/blob/924c96f0a563432fffcb83c6c01cb04169d1a819/lib/plausible_web/controllers/stats_controller.ex#L20

If you focus on taking the case of NOT having page views inside the if, you wouldn't need the `else` at all. It will  just be the default.

If you accept supporters on your journey, I would gladly offer my knowledge in helping out with such refactoring suggestions ;)

Cheers!

**Comment by ukutaht** [comment]
Hi. Thanks for the suggestions. Care to open a PR for this?

**Comment by preslavrachev** [comment]
Yes, I'd be glad to. I'd try to do it in the coming days
