### ISSUE TITLE
Hosting docs not correct for SMTP Setup

### ISSUE THREAD

**Issue by samuel-p** [plausible/analytics#334]
## Prerequisites
- [x] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report
The [docs for SMTP Setup](https://github.com/plausible/analytics/blob/master/HOSTING.md#mailersmtp-setup) says that the default values for `SMTP_HOST_SSL_ENABLED` and `SMTP_MX_LOOKUPS_ENABLED ` are `false`. But in [`config.exs`](
https://github.com/plausible/analytics/blob/master/config/config.exs#L152) they are `true`.

**Expected behavior**
Docs should be correct.

(I can make a pull request for this, but need to know if I should change the docs or the default config.)

**Comment by ukutaht** [comment]
Thanks for noticing.

I'm rebuilding the self-hosting docs from the ground up for the 1.0 release (hopefully this week). Will make sure to update these as well

**Comment by metmarkosaric** [comment]
Closing this as we've released the 1.0 release with brand new docs: https://docs.plausible.io/self-hosting
