### ISSUE TITLE
Add data download for all panels

### ISSUE THREAD

**Issue by matiasandina** [plausible/analytics#335]
I love the way the data is displayed on the dashboard. However, I would also like to be able to get the data for the different panels  into a csv file easily (just as it's possible to do with the visitor data).
I was looking for something script-friendly so that we can re-generate stats to share with our audience/potential funding opportunities (right now, we copy and paste the data manually from the popus).

Here's an example of tabular data that we would like to parse
https://plausible.io/open-neuroscience.com/countries?period=6mo

**Comment by metmarkosaric** [comment]
Thanks Matias! Makes sense and it's something we'd like to provide. Closing this as there's the #211 where we have a discussion about building a feature that allows you to import or export all of your data.
