### ISSUE TITLE
Feature request: Option to combine stats for pages with and without trailing slashes

### ISSUE THREAD

**Issue by TheodoreChu** [plausible/analytics#336]
## Precheck

Please note that this tracker is only for feature requests. Do not use the issue tracker for help or support. [Our docs](https://docs.plausible.io/) are a great place for most answers, but if you can’t find your answer there, you can [contact us](https://plausible.io/contact). Have an issue with your self-hosted install? You can ask in [our community forum](https://plausible.discourse.group/). Thanks!

## Prerequisites
- [x] I have searched open and closed issues to make sure that the feature has not yet been requested.

## Feature request
**Is your feature request related to a problem? Please describe.**
My website does not add trailing slashes to the end of each URL (e.g., example.com/hello vs example.com/hello/). Plausible counts them separately. For example, see https://plausible.io/docs.plausible.io/pages

**How would you like it to work**
I would like an option to combine the stats for pages with and without trailing slashes

**Screenshots (If applicable)**
If applicable, add screenshots to help explain the proposed solution.

**Comment by ukutaht** [comment]
Thanks for the suggestion, I've noticed this myself on https://plausible.io/docs.plausible.io/pages

If possible, I think the best solution is to change the website itself to redirect to ensure a consistent URL style.

If not then I agree, there should be a way to merge analytics for paths with trailing slash and ones without.

**Comment by svprdga** [comment]
The problem is not with the website itself, the problem is with third party services that manipulate the URLs.

For instance, my website has all the endpoints without the final slash, but I submit some URLs of my site to third party services that alter them, and then serve the same URL with a final slash.

That's why I think that's very critical to add an option to merge this kind of URLs, to have reliable stats.

**Comment by davidsteeb** [comment]
Is there an option to set the "pageview url" that's being tracked? That could enable developers to set the url for pageviews to the canonical for example.

**Comment by ukutaht** [comment]
@davidsteeb Not at the moment. Makes sense to add that option though
