### ISSUE TITLE
`visit_duration` from API Request is wrong when using `event:page` filter

### ISSUE THREAD

**Issue by troyeisert** [plausible/analytics#3418]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

When making an API request for `visit_duration` along with an `event:page` filter set the data is completely wrong. In all cases from my tests the value from API is way higher than it should be.

**Example:**

https://plausible.io/api/v1/stats/aggregate?site_id=xxx&metrics=visit_duration&period=7d&filters=event:page==/xxx
Returns 651 

Dashboard w/ the same filter/period
Shows 1m 13s

**Example without a page filter:**

https://plausible.io/api/v1/stats/aggregate?site_id=xxx&metrics=visit_duration&period=7d
Returns 129

Dashboard w/ the same period
Shows 2m 9s

### Expected behavior

The values returned from the API should match the dashboard values.

**Comment by bogplau** [comment]
Hi @troyeisert 

Can you please [contact our support](https://plausible.io/contact) so we can have a further look?

Thank you!
