### ISSUE TITLE
Is plausible-tracker still maintained?

### ISSUE THREAD

**Issue by HenkVanMaanen** [plausible/analytics#3419]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Self-hosting

### Describe the bug

Is the plausible-tracker repo / npm package still maintained? See https://github.com/plausible/plausible-tracker/issues/53

### Expected behavior

See  https://github.com/plausible/plausible-tracker/issues/53

**Comment by metmarkosaric** [comment]
hey @HenkVanMaanen! plausible-tracker is still maintained but it is currently not up to date with all the new stuff we have released. we're a small team with limited resources and things take time so i cannot make any promise on when the next release of the tracker will be but we'll post it as soon as it's ready. thanks for your patience!

**Comment by Daniel15** [comment]
> plausible-tracker is still maintained but it is currently not up to date with all the new stuff we have released

@metmarkosaric  - Is there a reason there's two separate versions of the script (the plausible-tracker repo plus the one in this version) rather than both of them being built from the same codebase? I would have thought that the one in this repo could be a build artifact as part of a build process in the plausible-tracker repo.

**Comment by metmarkosaric** [comment]
@Daniel15 Mostly for legacy reasons as they started out as two separate projects. The npm package was created by an external contributor who offered to give ownership of it to us.

We plan to put some time later this year into trying things out in terms of merging the two without impacting the size of our regular script.

If merging doesn't work then we will update the npm package as part of our regular workload. The plan is for our regular script, the api and the npm package to all be consistent in the future
