### ISSUE TITLE
Custom subdomain

### ISSUE THREAD

**Issue by varonblu** [plausible/analytics#342]
Hola, he dado de alta la web de https://ruthmontenegro.com/ en https://plausible.io/ y he creado un subdominio personalizado stats.ruthmontenegro.com en cloudfare (adjunto imagen) y utilizando la URL donde tieneque carga el rastreador de JavaScript. https://stats.ruthmontenegro.com/js/index.js y salta error, pueden comprobar y ayudarme en donde está el problema.
****************************************
Hello, I have registered the website of https://ruthmontenegro.com/ in https://plausible.io/ and I have created a custom subdomain stats.ruthmontenegro.com in cloudfare (image attached) and using the URL where it has to load the JavaScript crawler. https://stats.ruthmontenegro.com/js/index.js and it jumps error, can you check and help me where the problem is

**Comment by metmarkosaric** [comment]
Hola! 

Two possible solutions:

- It may take up to 4 hours for the DNS changes to propagate and for us to obtain an SSL certificate for your subdomain. 

- Are you having your site proxied behind Cloudflare? Cloudflare proxy doesn't allow our server to provision an SSL certificate to you. Removing the proxy and making it just a DNS record in your Cloudflare settings solves the issue.

Take a look at our docs here: https://docs.plausible.io/custom-domain/

Closing this now as GitHub is for feature requests. Do reach out here if you're still having issues: https://plausible.io/contact

Gracias!

**Comment by varonblu** [comment]
Hello, thanks for the help, I think it is already done.

Thank you

**Comment by metmarkosaric** [comment]
ah great! so it's all working now? thanks for reporting back!

**Comment by varonblu** [comment]
I think not, I just realized that the link https://stats.ruthmontenegro.com/js/index.js does not work What can happen? I feel my clumsiness is the first time I do any of this.

thanks

**Comment by metmarkosaric** [comment]
Yeah, it doesn't seem like you changed it correctly. Can you take a look at these instructions please: https://docs.plausible.io/custom-domain/#create-a-new-cname-record-for-your-chosen-subdomain

And then email us with details on what you've done and we'll take a look: https://plausible.io/contact

**Comment by henk23** [comment]
I have the same problem. Is it possible that it comes from the difference between `plausible.js` and `index.js`?
`index.js` does not seem to exist (throws 404).

When I put `my-cnamed-subdomain.example.com/js/plausible.js` the file is being loaded. BUT all the event requests still go to `original-plausible-installation.com/api/event`, which kind of defies the whole point of having a first-party resource.

Am I doing something wrong?

**Comment by metmarkosaric** [comment]
Index.js and plausible.js are same files so either one works. And yeah, that is basically what it is. The file is not actually loaded from your own server but it just redirects to the file on our server.
