### ISSUE TITLE
Current URL is disclosed to DuckDuckGo

### ISSUE THREAD

**Issue by dessant** [plausible/analytics#343]
When visiting https://plausible.io/plausible.io/sources, favicons are fetched from https://icons.duckduckgo.com, and the current page URL is sent to their servers in the `Referer` header, which could be undesirable when Plausible is self-hosted.

The issue can be solved by setting the [referrerpolicy](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-referrerpolicy) attribute for image elements that point to other origins.

```html
<img referrerpolicy="no-referrer" src="https://icons.duckduckgo.com/ip3/news.ycombinator.com.ico">
```

**Comment by JimDabell** [comment]
Which browser are you using?  I was under the impression most browsers send the origin when HTTPS is in use these days, not the current URL.  I just checked the URL you mentioned in Chrome and didn’t reproduce the behaviour you describe; Chrome sent the origin, not the current URL.

**Comment by dessant** [comment]
@JimDabell, the `Referer` header is sent for the favicon requests in all major browsers. You have probably inspected the wrong request, requests initiated by the an `<img>` element do not send the `Origin` header, unless you enable CORS with the [crossorigin](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-crossorigin) attribute.

**Comment by dessant** [comment]
I see you were referring to [this](https://developers.google.com/web/updates/2020/07/referrer-policy-new-chrome-default) change in Chrome, not the `Origin` header. Chrome 85 and newer only sends the host part of the URL, though that still discloses the host at which the self-hosted instance can be accessed, the `Referer` header can be dropped entirely to avoid disclosing any data to DuckDuckGo.

**Comment by ukutaht** [comment]
Thanks for reporting. I agree we should add the `referrerpolicy="no-referrer"`, no reason to share that data.
