### ISSUE TITLE
Filtering by campaign, issue with double quotes

### ISSUE THREAD

**Issue by reinder42** [plausible/analytics#348]
When a UTM campaign name has quotes, and you click it to filter visits for that campaign, it won't show any data. The quotes are currently escaped with a slash. I suspect this results in a mismatch when selecting the data.

How to reproduce:
1. Log a visit with an UTM tag (campaign) that includes a double quote
2. Find the campaign in Plausible – note that the double quote is escaped on the link/label
3. Click that campaign – no visits are shown in the graph
4. Remove escaped slash manually from Plausible URL – visits are now shown

Bit of an edge case, of course. It could be that more UTM tags are affected.

Example URL: https://example.com/?utm_source=drip&utm_medium=email&utm_campaign=Do%20you%20have%20%22gaps%22%20in%20your%20knowledge%20of%20iOS%20development%3F (This URL turned out urlencoded when I copied it, the quotes are around "gaps")

**Comment by ukutaht** [comment]
Thanks for reporting, seems like a bug

**Comment by ukutaht** [comment]
Fixed in ef4af9249f8384aa13e747e4f6a9004d15d8705d
