### ISSUE TITLE
script.revenue.js broken (self-hosted, v2.0)

### ISSUE THREAD

**Issue by dreadedhamish** [plausible/analytics#3519]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Self-hosting

### Describe the bug

Adding 'revenue' to the script filename leads to a 404.
I've tried adding most of the other (apart from local and manual) and they all function correctly, but added 'revenue' throws a 404.

Tested in multiple browsers/computers with adblock off.
When I try to access the file directly I get a plausible-branded 404 (see screenshot), which leads me to believe the request is getting to the plausible server.

### Expected behavior

Actual:
script.js - works
recipt.revenue.js - 404
script.tagged-events.exclusions.file-downloads.pageview-props.outbound-links.hash.js - works
script.revenue.tagged-events.exclusions.file-downloads.pageview-props.outbound-links.hash.js - 404

Expected - all to work.

### Screenshots

https://drive.google.com/file/d/16S8gANbiDojVD_xfAXdfWwiTdCPS1apj/view?usp=sharing

### Environment

```markdown
Docker Compose
Hosted on coolify.
```

**Comment by ruslandoga** [comment]
👋 @dreadedhamish 

I think revenue (and funnel) features are not included in `v2.0.0`

**Comment by dreadedhamish** [comment]
> 👋 @dreadedhamish
> 
> I think revenue (and funnel) features are not included in `v2.0.0`

OK - documentation is needed then - there is no indication in the docs that any features are missing from the self-hosted version.

**Comment by olimortimer** [comment]
> > 👋 @dreadedhamish
> > I think revenue (and funnel) features are not included in `v2.0.0`
> 
> OK - documentation is needed then - there is no indication in the docs that any features are missing from the self-hosted version.

Yeah there's quote a few things in the docs that need to be clear on whether or not it is included in the self-hosted version.  Another example would be excluding IP addresses, as 'Shields' is missing from the site settings section of the self-hosted version.

**Comment by ruslandoga** [comment]
@olimortimer 👋 

Shields are not excluded in v2.1.0 release candidates.
