### ISSUE TITLE
Top Sources on 'All' does not show all Top sources

### ISSUE THREAD

**Issue by LickABrick** [plausible/analytics#3545]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Self-hosting

### Describe the bug

Might not be a bug but a misunderstanding of how the Top Sources displays itself.

When you have 'All' Selected it does not show entries from the 'UTM xxx'.

### Expected behavior

As it says All I thought it would show literally entries from all sources (e.g. utm_medium, utm_source)

### Screenshots

With All selected:
![image](https://github.com/plausible/analytics/assets/17205583/9f6d6901-ca2a-480c-ae61-87f4c80e8cf1)

You see it does not show entries from utm_medium:
![image](https://github.com/plausible/analytics/assets/17205583/ddf55218-f4e7-4c66-ab37-807124b7f8c6)

### Environment

```markdown
- OS: not relevant
- Browser: Firefox, Edge and Chrome (not tested any others)
- Browser Version: Latest available at this date
```

**Comment by metmarkosaric** [comment]
Hi @LickABrick!This works as intended. We show sources only including UTM source in the all tab and we have the campaign tabs where we show all the additional the UTM tags that provide campaign information rather than the source itself.
