### ISSUE TITLE
URI decode for UTM params with diacritics not working

### ISSUE THREAD

**Issue by krystof-k** [plausible/analytics#3551]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Self-hosting

### Describe the bug

When using diacritics in UTM params, the URI decode doesn't work.

Related to #229?

### Expected behavior

E.g. `utm_source=Socail+paid` is displayed as `Social paid`, but `utm_campaign=Li%C5%A1%C3%A1ck%C3%A9+p%C5%99edplatn%C3%A9+black+friday+2023` is displayed as `Li%C5%A1%C3%A1ck%C3%A9+p%C5%99edplatn%C3%A9+black+friday+2023`, not `Lišácké předplatné black friday 2023`.

### Screenshots

![image](https://github.com/plausible/analytics/assets/11633481/ddf7a7d1-6018-49db-a231-c77c88efcd88)
![image](https://github.com/plausible/analytics/assets/11633481/e663cf4a-47c6-40b4-acf2-259135461fae)

### Environment

```markdown
- OS: macOS Ventura 13.5.1 (22G90)
- Browser: Chrome
- Browser Version: 119.0.6045.159
```

**Comment by ruslandoga** [comment]
👋 @krystof-k 

I couldn't reproduce on my instance running `plausible/analytics:v2.0.0`:

<img width="560" alt="Screenshot 2023-11-25 at 18 05 29" src="https://github.com/plausible/analytics/assets/67764432/940ec944-2620-41e2-ae94-3d71fb1b2f40">

**Comment by krystof-k** [comment]
@ruslandoga Yeah, it looks like it somehow miraculously started working fine for me to. Maybe an issue on the Instagram end. Sorry for a false alarm!
