### ISSUE TITLE
Documentation outdated?

### ISSUE THREAD

**Issue by Jannik44** [plausible/analytics#3610]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Self-hosting

### Describe the bug

there are images on dockerhub with arm64 Support so this part of the documentation needs Update :)

"The server must have a CPU with x86_64 architecture and support for SSE 4.2 instructions."
https://plausible.io/docs/self-hosting

### Expected behavior

-

**Comment by ruslandoga** [comment]
I've opened a PR into the docs repo: https://github.com/plausible/docs/pull/452
