### ISSUE TITLE
Keyboard shortcuts interfering with browser keyboard shortcuts

### ISSUE THREAD

**Issue by hirusi** [plausible/analytics#363]
### Precheck

Please note that this tracker is only for bugs. Do not use the issue tracker for help or support. [Our docs](https://docs.plausible.io/) are a great place for most answers, but if you can’t find your answer there, you can [contact us](https://plausible.io/contact). Have an issue with your self-hosted install? You can ask in [our community forum](https://plausible.discourse.group/). Thanks!

## Prerequisites
- [x] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report
I use <kbd>Alt+Left/Right</kbd> to navigate backwards and forwards within my browser. Today I accidentally discovered Plausible's dashboard also has the same keybinding to go back and ahead in the timeline (today, yesterday, day before, etc.).

Please consider using a keyboard shortcut that does not interfere with any system/browser defaults.

**Expected behavior**
Don't do anything when <kbd>Alt+Left/Right</kbd> is pressed.

**Environment (If applicable):**
 - OS: Pop!_OS 20.04 LTS
 - Browser: Firefox
 - Version: 81.0

**Comment by ukutaht** [comment]
Thanks for reporting!

It's intended to navigate when you press _only_ arrow keys. So we could keep that behaviour but do nothing when `Alt` is involved
