### ISSUE TITLE
Refused to execute script from 'https://plausible.io/js/script.js' because its MIME type ('image/png') is not executable.

### ISSUE THREAD

**Issue by paulmbw** [plausible/analytics#3630]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

I've noticed none of my events are being tracked and visible on Plausible anymore, and I can't identify why. No changes have been made client side (i.e. my project). I'm using the `next-plausible` library for my nextjs project (I already raised an issue [here](https://github.com/4lejandrito/next-plausible/issues/115)), but raising this issue for visibility.

### Expected behavior

I expect my events to be tracked and visible in the Plausible UI.

### Screenshots

<img width="1776" alt="Screenshot 2023-12-13 at 14 23 38" src="https://github.com/plausible/analytics/assets/9769730/80524e84-9580-4f7e-b765-571cb33acdbb">

### Environment

```markdown
- OS: Mac OS Sonoma
- Browser: Chrome
- Browser Version: Version 119.0.6045.159 (Official Build) (arm64)
```

**Comment by metmarkosaric** [comment]
Thanks @paulmbw! Closing this as it's been reported as working fine again

**Comment by carlajarchuleta1-a11y** [comment]
- OS: Mac OS Sonoma
- Browser: Chrome
- Browser Version: Version 119.0.6045.159 (Official Build) (arm64)
