### ISSUE TITLE
Bug: Get "414 Request-URI Too Large Error" from plausible when clicking on Details (Top Pages)

### ISSUE THREAD

**Issue by alexnuttinck** [plausible/analytics#3674]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Self-hosting

### Describe the bug

We got this error for several requests when we click on the "Details" on Top Pages:
It seems to only appear when the payload is bigger than ~13000 (approximately).

Here are the logs from plausible presenting this error:
```
plausible-analytics 08:33:21.327 [error] #PID<0.3202.165> running PlausibleWeb.Endpoint (connection #PID<0.2094.165>, stream id 21) terminated                                             │
│ plausible-analytics Server: plausible.imio.be:80 (http)                                                                                                                                    │
│ plausible-analytics Request: GET /api/stats/***/pages?period=30d&date=2024-01-09&filters=%7B%7D&with_imported=true&auth=-***&limit=100&page=1&detailed=true       │
│ plausible-analytics ** (exit) an exception was raised:                                                                                                                                     │
│ plausible-analytics     ** (MatchError) no match of right hand side value: {:error, %Ch.Error{code: nil, message: "<html>\"\\r\"\n<head><title>414 Request-URI Too Large</title></head>\"\ │
│ plausible-analytics         (plausible 0.0.1) lib/plausible/stats/breakdown.ex:263: Plausible.Stats.Breakdown.breakdown_time_on_page/3                                                     │
│ plausible-analytics         (plausible 0.0.1) lib/plausible/stats/breakdown.ex:108: Plausible.Stats.Breakdown.breakdown/5                                                                  │
│ plausible-analytics         (plausible 0.0.1) lib/plausible_web/controllers/api/stats_controller.ex:704: PlausibleWeb.Api.StatsController.pages/2                                          │
│ plausible-analytics         (plausible 0.0.1) lib/plausible_web/controllers/api/stats_controller.ex:1: PlausibleWeb.Api.StatsController.action/2                                           │
│ plausible-analytics         (plausible 0.0.1) lib/plausible_web/controllers/api/stats_controller.ex:1: PlausibleWeb.Api.StatsController.phoenix_controller_pipeline/2                      │
│ plausible-analytics         (plausible 0.0.1) lib/plug/error_handler.ex:80: PlausibleWeb.Api.StatsController.call/2                                                                        │
│ plausible-analytics         (phoenix 1.7.2) lib/phoenix/router.ex:430: Phoenix.Router.__call__/5                                                                                           │
│ plausible-analytics         (plausible 0.0.1) lib/plausible_web/endpoint.ex:1: PlausibleWeb.Endpoint.plug_builder_call/2                                                                   │          │
```
Have you any ideas of what could cause these errors?

Ideas to resolve it:

I think this could be the result of these defined values in the config/runtime.exs : https://github.com/plausible/analytics/blob/master/config/runtime.exs#L312C5-L312C21 
Maybe a way to resolve it would be to increase these values. (It would be great if we could modify it by environment variables in order to be able to test it)

Another idea would be to be able to decrease the limit value in loadPages function (https://github.com/plausible/analytics/blob/c87b165aefb1f45572fae39d3383896e370c82d8/assets/js/dashboard/stats/modals/pages.js#L34)

Can you help me on this Issue?

### Expected behavior

Not having these errors.

### Screenshots

Section in plausible that causes the problem:
![Sélection_897](https://github.com/plausible/analytics/assets/17699324/47db0571-5b44-454a-981a-c5523fe85a3f)
1: The problem happens when we click on DETAILS.
2: Top pages section is empty

Example of URL that causes the problem (https://plausible.xxx.be/api/stats/xxx.be/pages?period=30d&date=2024-01-08&filters={}&with_imported=true&limit=100&page=1&detailed=true ):
![Sélection_898](https://github.com/plausible/analytics/assets/17699324/4e5de2d6-7673-463e-89f9-25452b7747b6)

### Environment

```markdown
- OS: Any
- Browser: Any
- Browser Version: Any
```

**Comment by ruslandoga** [comment]
👋 @alexnuttinck 

The error seems to come from nginx. Are you using nginx in front of ClickHouse by any chance?

**Comment by alexnuttinck** [comment]
We managed to resolve it by adding this configuration in our Nginx Ingress Controller:
`large-client-header-buffers: "8 24k"
I close this issue.
