### ISSUE TITLE
Building the Dockerfile on Windows will put flawed CRLF shell files, breaking entrypoint.sh and others

### ISSUE THREAD

**Issue by doctorpangloss** [plausible/analytics#3748]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Self-hosting

### Describe the bug

`docker build .` on Windows will create an image that cannot run because the .sh files are copied with CRLF.

There is no easy non-commit fix for this nor end-user configuration change. It will appear that there is, but there isn't. The repository needs a .gitattributes that specifies the line endings for .sh files.

### Expected behavior

The files need to be copied into the Docker context with correct line endings.

### Environment

```markdown
- OS: Windows
- Browser: --
- Browser Version: --
```

**Comment by ruslandoga** [comment]
I'll check what Dockerfile and sctrips are generated with [`mix phx.gen.release --docker`](https://hexdocs.pm/phoenix/Mix.Tasks.Phx.Gen.Release.html) and open a PR to adapt the scripts, but I won't be able to verify that it works.

**Comment by doctorpangloss** [comment]
All you have to do is check in `.gitattributes` with 

```
*.sh text eol=lf
```

**Comment by ruslandoga** [comment]
Does adding it to your global config work?
