### ISSUE TITLE
It should be possible to bring up a Plausible self-hosted instance on a new, clean clustered Clickhouse

### ISSUE THREAD

**Issue by doctorpangloss** [plausible/analytics#3751]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Self-hosting

### Describe the bug

Starting Plausible in a clustered Clickhouse will cause it to create non-replicated tables.

All the v1 tables are created without the possibility of clustering in the code. There is no non-replicated to replicated migration.

### Expected behavior

-

### Environment

```markdown
- OS:
- Browser:
- Browser Version:
```

**Comment by ruslandoga** [comment]
@doctorpangloss 

Do the v2 tables have the same problem?

**Comment by ukutaht** [comment]
@doctorpangloss Plausible can work with replicated tables but you're right the DDL queries are not quite correct to set it up. We discussed your issue and decided against taking action on it. It's not something we want to support (as in, invest engineering time into) right now.
