### ISSUE TITLE
Proxied events being dropped?

### ISSUE THREAD

**Issue by raulrpearson** [plausible/analytics#3758]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

I deployed a proxy on Deno that's basically doing the same as the [Cloudflare Worker example](https://plausible.io/docs/proxy/guides/cloudflare):

```ts
Deno.serve((req: Request) => {
  if (req.url.endsWith("/pap/script.js")) {
    return fetch("https://plausible.io/js/plausible.js")
  } else if (req.url.endsWith("/pap/event")) {
    const request = new Request(req)
    request.headers.delete("cookie")
    return fetch("https://plausible.io/api/event", request)
  }
  return new Response(null, { status: 404 })
})
```

This had been working for a few months but I've recently noticed it stopped working at some point. My sites have close to 0 visitors, so it's difficult to know exactly when, but the last time my Plausible dashboard shows an event is on the 21st of December.

I skimmed over the commits on those dates and found this one [dropping datacenter IP events](https://github.com/plausible/analytics/commit/147597cd98a1522bab66a76c5bda7283b8d91240). Could this be the culprit?

Just to double-check, I deployed another proxy, this time on Cloudflare Workers, trying to follow the example as close as possible. In both cases I can see that my browser is triggering the relevant requests and getting 200 for the script and 202 for the event POST.

As an example, [metronome.raulrpearson.com](https://metronome.raulrpearson.com/) is now using that Cloudflare Workers proxy. I get no pageview events displayed on my Plausible dashboard, though.

### Expected behavior

Proxy approach should work.

### Environment

```markdown
- OS: N/A
- Browser: N/A
- Browser Version: N/A
```

**Comment by metmarkosaric** [comment]
hi @raulrpearson! thanks for reporting! we keep issues list here for bugs with the product only. I can see you've also emailed our support (which is the best place for these types of questions) and we've responded with some more info on some potential issues with your custom proxy setup. I'll close this. thanks!

**Comment by raulrpearson** [comment]
Thanks @metmarkosaric. For the record, the solution was to add an `X-Forwarded-For` header with the user's IP. The final working script is the following:

```typescript
const SCRIPT_PATH = "/pap/script.js";
const EVENT_PATH = "/pap/event";

Deno.serve((req, info) => {
  if (req.url.endsWith(SCRIPT_PATH)) {
    return fetch("https://plausible.io/js/plausible.js");
  } else if (req.url.endsWith(EVENT_PATH)) {
    const request = new Request(req);
    request.headers.delete("cookie");
    request.headers.set("X-Forwarded-For", info.remoteAddr.hostname);
    return fetch("https://plausible.io/api/event", request);
  }
  return new Response(null, { status: 404 });
});
```

A version of the script had been working for a few months and likely stopped working after [the change](https://github.com/plausible/analytics/commit/147597cd98a1522bab66a76c5bda7283b8d91240) I mentioned. I believe the [Cloudflare Workers example](https://plausible.io/docs/proxy/guides/cloudflare) from the docs still works without explicitly setting the `X-Forwarded-For` header because Cloudflare add it themselves.

I created an example repo for the [Deno proxy](https://github.com/raulrpearson/plausible-proxy-deno) and one for the [Cloudflare Workers proxy](https://github.com/raulrpearson/plausible-proxy-cloudflare-workers). I think having these would be helpful for folks. I'm happy to transfer them to the Plausible org if you'd like to make them more official.

I also think we could add Deno proxy instructions to the docs and make it more clear that `X-Forwarded-For` should be set. This is mentioned in the [events API page](https://plausible.io/docs/events-api#unique-visitor-tracking), but I hadn't thought of checking that out when working on this problem. Would it be helpful if I created a PR on the [docs repo](https://github.com/plausible/docs)?

**Comment by metmarkosaric** [comment]
thanks for the details @raulrpearson, glad to hear it's solved! and yeah our Cloudflare instructions send the correct IP address so no need to change anything about those instructions. 

if you have time, feel free to submit instructions for how to set up a proxy on Deno to our docs. this could be useful to others in the future. you can see an example here of how someone else contributed proxy instructions for Vercel: https://plausible.io/docs/proxy/guides/vercel. your help with this is appreciated!
