### ISSUE TITLE
Shared link shows a 404

### ISSUE THREAD

**Issue by vindarel** [plausible/analytics#376]
### Precheck

> Please note that this tracker is only for bugs. Do not use the issue tracker for help or support. [Our docs](https://docs.plausible.io/) are a great place for most answers, but if you can’t find your answer there, you can [contact us](https://plausible.io/contact). Have an issue with your self-hosted install? You can ask in [our community forum](https://plausible.discourse.group/). Thanks!

My issue happens on plausible.io.

## Prerequisites
- [X] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report
**Describe the bug**
I created a shared link. I open it and I have a 404 "Oops there's nothing here" error.

The link redirects to `https://plausible.io/lispcookbook.github.io/cl-cookbook`. My (private) working URL is `https://plausible.io/lispcookbook.github.io%2Fcl-cookbook`.

**Expected behavior**

I expected to see analytics.

and also the uniq URL to not change.

**Screenshots (If applicable)**
> If applicable, add screenshots to help explain your problem.

if necessary…

**Environment (If applicable):**
plausible.io

Regards

**Comment by ukutaht** [comment]
Thanks for the report! Sounds like the URL is not being escaped in the shared link redirect

**Comment by vindarel** [comment]
Hello, friendly ping?

**Comment by ukutaht** [comment]
Hey, I will do a round of bug fixes this December/January and I will fix this one as well. Thanks for your patience :)

**Comment by ukutaht** [comment]
@vindarel I will deploy this tomorrow :)

**Comment by vindarel** [comment]
Thanks! 

Related question: is it normal that the private shared link, which looks like `https://plausible.io/share/iHlnXx9AdyjAHzKvPd9Je`, is transformed to a guessable ` https://plausible.io/lispcookbook.github.io%2Fcl-cookbook`? (this link privacity is not important, but my clients' will be)
