### ISSUE TITLE
Logging plausible event results in CORS error

### ISSUE THREAD

**Issue by codemonkey800** [plausible/analytics#3769]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

For some reason a plausible event we send is throwing a CORS error on some pages. We're not entirely sure what could be the issue because the tracking event is reused in two different pages. It works on one page, but it doesn't work on the other.

The payload of the successful event looks like:
```json
{
  "name": "View tomogram",
  "domain": "cryoetdataportal.czscience.com",
  "url": "https://cryoetdataportal.czscience.com/datasets/10002",
  "props": {
    "datasetId": 10002,
    "organism": "Homo sapiens",
    "runId": 623,
    "tomogramId": 11134,
    "type": "dataset"
  }
}
```

The payload of the event with the CORS error looks like:
```json
{
  "name": "View tomogram",
  "domain": "cryoetdataportal.czscience.com",
  "url": "https://cryoetdataportal.czscience.com/runs/623",
  "props": {
    "datasetId": 10002,
    "organism": "Homo sapiens",
    "runId": 623,
    "tomogramId": 11134,
    "type": "run"
  }
}
```

### Expected behavior

It should log the event on both pages and not throw a CORS error.

### Screenshots

<img width="725" alt="image" src="https://github.com/plausible/analytics/assets/2176050/be5acc22-af58-435c-b40d-56414901566e">

<img width="420" alt="image" src="https://github.com/plausible/analytics/assets/2176050/fd1c06ce-9891-4484-ab97-058793c63ba4">

### Environment

```markdown
- OS: MacOS 14.3 
- Browser: Google Chrome
- Browser Version: 121.0.6167.160
```

**Comment by aerosol** [comment]
@codemonkey800 hey, thanks for the report. Would you mind sharing the exact URL that I could observe this behavior at?

**Comment by aerosol** [comment]
I went to https://cryoetdataportal.czscience.com/runs/623 and I can see the event being registered:

![image](https://github.com/plausible/analytics/assets/173738/eec7d018-006a-49d8-b974-700f44c71623)

although I see a little different payload:

![image](https://github.com/plausible/analytics/assets/173738/67813ba8-e503-4251-a6e3-6daa66b8be85)

I'd like to reproduce the exact same thing you're experiencing. Is this only happening on Safari?

**Comment by aerosol** [comment]
I have reproduced the issue and will get back to you.

**Comment by aerosol** [comment]
Hi @codemonkey800 

I think the problem originates from this package: https://www.npmjs.com/package/axios-cache-interceptor?activeTab=readme

Please see https://github.com/arthurfiorette/axios-cache-interceptor/blob/ad69e6d6e491cfa5fe2cb542bc90fd205fc823e3/docs/src/config/request-specifics.md#cachecachetakeover

in particular this bit:

![image](https://github.com/plausible/analytics/assets/173738/b3bd01dc-084e-486f-b9c0-5e47a3aa1924)

Please try the fallback suggested and see if the OPTIONS XHR requests are handled then.

**Comment by aerosol** [comment]
FWIW the problem occurs only for that button:

![image](https://github.com/plausible/analytics/assets/173738/5137a1a6-0f2f-4941-a7e6-3138bb21ddae)


and not that one:

![image](https://github.com/plausible/analytics/assets/173738/4020d297-2e50-4cf0-a352-b9fd0b6f1c90)

That should help you figure out the difference

**Comment by metmarkosaric** [comment]
closing this now but feel free to [contact our support](https://plausible.io/contact) if you have any further questions

**Comment by awacode21** [comment]
i am struggling with the same issue. What exactly is meant with the fallback?

**Comment by awacode21** [comment]
i am using Plausible with vercel. Does that look like the correct setting?

//vercel.json
```
{
    "headers": [
        {
            "source": "/(.*)",
            "headers": [
                {
                    "key": "Cache-Control",
                    "value": "max-age=0, s-maxage=86400, stale-while-revalidate=59"
                },
                {
                    "key": "Access-Control-Allow-Headers",
                    "value": "Cache-Control, Pragma, Expires"
                }
            ]
        }
    ]
}
```
