### ISSUE TITLE
Docker self-host plausible/analytics:v2.0 doesn't track referer

### ISSUE THREAD

**Issue by PetervdPerk-NXP** [plausible/analytics#3775]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Self-hosting

### Describe the bug

I've set up a self-hosting environment through plausible/hosting running docker.
Everything is working fine but the sources end up being "Direct / None"

### Expected behavior

Different sources i.e. Google, DuckduckGo, I've checked on my own browser but referer header is set when visited.

### Screenshots

<img src="https://github.com/plausible/analytics/assets/57130844/b95ac77f-4b90-4dc7-abf5-df89d40d655f" width="300">

### Environment

```markdown
- OS: Linux
- Browser: Firefox
- Browser Version: 122
```

**Comment by kbzowski** [comment]
I cannot confirm:
![obraz](https://github.com/plausible/analytics/assets/2268743/b1825f39-1675-4fc0-838b-db32aba1f996)

How did you integrate analytics?

**Comment by PetervdPerk** [comment]
```
<script defer data-domain="site.nl" src="[https://analytics.perkbedrijven.nl/js/script.js](view-source:https://site.nl/js/script.js)"></script>
```
Just the default one Plausible gives when creating a website.
I've just migrated my docker image from `v2.0` to `ghcr.io/cretezy/plausible` which solves the issue for me.
