### ISSUE TITLE
Laptop vs Desktop

### ISSUE THREAD

**Issue by ItalyPaleAle** [plausible/analytics#379]
## Prerequisites
- [X] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report
The UI considers all visitors with a screen wider than 1440px to be "desktops", and the smaller ones are "laptop". This is a bit of an arbitrary number that doesn't keep into account modern laptops that have high-res screens.

**Expected behavior**
"Desktops" and "laptops" cannot reliably be distinguished by the screen resolution, so they should be grouped together. The reason is that when separate, they cause a "distortion" on the analytics, that might make it look like mobile gets a larger share.

**Comment by ukutaht** [comment]
That's fair, I agree we should change it.

At the moment it's working as intended so I will remove the bug label.
