### ISSUE TITLE
Discussion: How to add extra features without bloating the tracker script

### ISSUE THREAD

**Issue by ukutaht** [plausible/analytics#382]
This week I've been working on event metadata #134 

One common use-case for this feature is tracking outbound links. I would like to add an automatic link-tracking module to the Plausible tracker so people can enable the feature easily without everyone having to figure out the Javascript code for it.

Normally these features would be added to the default script with the option to enable it at runtime.  However, since most people do not use link tracking I don't want to bloat up the standard Plausible script which currently weighs <1KB and being lightweight is a huge plus.

I would like to build a way to load different versions of the script with different modules/features enabled. This feels pretty novel, I haven't seen people do something like this. I have an idea on how to go about it but I wanted to gather some feedback about stuff I haven't thought about.

My idea is to add a query parameter to the script tag as follows:

```
<script src="https://plausible.io/js/plausible.js?load=link-tracking,hash-routing"></scrip>
```

On the backend, every possible combination of extra features is already pre-compiled so the backend sees this URL, sorts the extra features alphabetically and looks for a corresponding file on the filesystem. There will be a bit of a combinatorial explosion of script files but it should be OK if the numbre of extra features stays reasonable.

Does this make sense? What concerns or suggestions do you have about this?

I will close the issue once the API for loading extra modules is defined.

**Comment by abanka27** [comment]
I may be wrong, but from what I understand, the script file that is served (especially for self-hosted) is not set up on a CDN, or something that would allow us to trivially use query parameters to load files dynamically - so how would the above proposed solution work? 

Alternatively, could there be a multi-selector in the "Javascript Snippet" section of settings in the Dashboard that allows us to choose what features we want, and shows us the script tag to use?

For example, let's say we select **link-tracking** and **hash-routing** as extra features we want to use in the settings. This would show us a precomputed script tag with the file we need:

```
<script src="https://plausible.io/js/plausible-hr-lt.js"></scrip>
```

**Comment by ukutaht** [comment]
> I may be wrong, but from what I understand, the script file that is served (especially for self-hosted) is not set up on a CDN, or something that would allow us to trivially use query parameters to load files dynamically - so how would the above proposed solution work?

The JS tracker is served from the plausible server itself: https://github.com/plausible/analytics/blob/master/lib/plausible_web/controllers/tracker_controller.ex

This can be modified to handle query params and an optional CDN in front of it could cache the different versions of the script.

I don't know if all CDN's have an option to use the query params as part of their cache key. For this reason it may make more sense to make the extra feature flags part of the filename itself (like your example).

> Alternatively, could there be a multi-selector in the "Javascript Snippet" section of settings in the Dashboard that allows us to choose what features we want, and shows us the script tag to use?

Yes, I think that would be a great addition!
