### ISSUE TITLE
Issue when using SMTP mail (Bamboo SMTPAdapter)

### ISSUE THREAD

**Issue by kotani123** [plausible/analytics#3839]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Self-hosting

### Describe the bug

When setting up the email for smtp, the system could not send a email using the smtp server setup.

Here is the env file for reference with personal information redacted:
MAILER_EMAIL=***
SMTP_HOST_ADDR=smtp.mailserverexample.com
SMTP_HOST_PORT=587
SMTP_USER_NAME=***
SMTP_USER_PWD=***
SMTP_HOST_SSL_ENABLED=false
SMTP_RETRIES=2

Here is the error log with the mailserver redacted:
01:13:46.055 request_id=F7eTMeBk0JDvdLwAABPh [error] Failed to send e-mail
hosting-plausible-1  | 01:19:14.348 [error] Task #PID<0.4406.0> started from #PID<0.4405.0> terminating
hosting-plausible-1  | ** (ArgumentError) raise/1 and reraise/2 expect a module name, string or exception as the first argument, got: {:network_failure, ~c"smtp.mailserverexample.com", {:error, {:options, :incompatible, [verify: :verify_peer, cacerts: :undefined]}}}

This issue above seems to happen with other solutions using the bamboo SMTPAdapter.

I tried changing the SMTP_HOST_SSL_ENABLED to "true" and "1". Nothing was working.

The solution for me was to change the tls setting in the config/runtime.exs file.

```
password: get_var_from_path_or_env(config_dir, "SMTP_USER_PWD"), 
-  tls: :if_available, 
+  tls: :never, 
```

This allowed the mail to be sent w/o errors.

### Expected behavior

Mail setup using SMTP should work as documented.

**Comment by ruslandoga** [comment]
👋 @kotani123 

The SMTP adapter has been broken for a while: https://github.com/plausible/analytics/discussions/3335#discussioncomment-6958961.
v2.1.0 will include a new one: https://github.com/plausible/analytics/pull/3654
