### ISSUE TITLE
White-label for self-hosted

### ISSUE THREAD

**Issue by MoryCorp** [plausible/analytics#384]
## Prerequisites
- [X ] I have searched open and closed issues to make sure that the feature has not yet been requested.

## Feature request

It would be great to have the self-hosted instances white-labeled. I plan to potentially use plausible.io for some of my customers but I'd like the name "plausible" to not appear anywhere.

The best would be to be able to change the Plausible logo to the company I host the tool for.

**Screenshots (If applicable)**

![image](https://user-images.githubusercontent.com/26336203/97170305-c2bd2200-178b-11eb-9832-bed6978ed410.png)

**Comment by metmarkosaric** [comment]
Closing this as there's another thread #152
