### ISSUE TITLE
Option to rename plausible.js script

### ISSUE THREAD

**Issue by Empty2k12** [plausible/analytics#387]
## Prerequisites
- [x] I have searched open and closed issues to make sure that the feature has not yet been requested.

## Feature request
Regex blocking is one common way, Ad/Script-Blockers use to filter out unwanted scripts. For example, domains and script names containing substrings like `stats`, `analytics` or `monitor` are blocked greedily by these algorithms. It's only a matter of time until the substring `plausible.js` starts appearing on those block-lists. Allowing CNAME cloaking (e.g. using custom domain with Plausible) is already an excellent step in preventing the script get blocked. However, the script-name could still be used for blocking. If there was a way to rename the script to `script.js`, `app.js`, `jquery.js` or something similar, detection rate could be lowered even further.

**How would you like it to work**
Either, the script is renamed to something more innocent for everybody (e.g. `app.js`), or we could allow configuring the script name in the site settings and the server would serve the script from the renamed source as well.

**Comment by ukutaht** [comment]
@Empty2k12 Thanks for the request.

For custom domains, you can already use any filename to load the javascript. `script.js`, `app.js` etc is valid if you're running a custom domain.

On the cloud domain (plausible.io) it's not possible but I don't think we're going to fool anyone by loading `plausible.io/js/script.js`. Blockers can just block the whole `plausible.io` domain fully.

**Comment by Empty2k12** [comment]
> For custom domains, you can already use any filename to load the javascript. script.js, app.js etc is valid if you're running a custom domain.

That's good to know. Is it documented anywhere?

**Comment by Empty2k12** [comment]
I just tried loading as jquery.js, but I am getting the 404 page. Also, when trying app.js, the actual frontend code is served. What Am I doing wrong?

**Comment by ukutaht** [comment]
Where are you trying to load it from? Please provide the full URL. What I meant is that when you use a custom domain like `stats.yourdomain.com` then any JS filename works: `stats.yourdomain.com/js/app.js`

**Comment by Empty2k12** [comment]
That's what I am talking about.
We're using a self-hosted Plausible. It seems in that case the feature is not enabled, even though it's technically already a custom domain. I will try setting another subdomain from the Plausible GUI and see if that works.

**Comment by ukutaht** [comment]
Ah sorry I wasn't aware this is a self-hosted installation. Supporting this does require a code change. The server only supports loading `plausible.js` at the moment.

For custom domains on the Cloud version this is solved with a reverse proxy in front of the server but I don't think that's very relevant for self-hosted installations.

**Comment by oliver3** [comment]
Triggered by the reaction of @ukutaht, I've added the following rule to my reverse proxy nginx configuration
```
rewrite ^/js/pls.js$ /js/plausible.js last;
```
Not sure if this is the best way to do it, but I can now access the script with `/js/pls.js`. Maybe this can be added as a comment in https://github.com/plausible/hosting/blob/master/reverse-proxy/nginx/plausible ?
