### ISSUE TITLE
/api/v1/sites/goals PUT endpoint results in 404 on Plausible v2.1.0-rc.0

### ISSUE THREAD

**Issue by furnacecreek** [plausible/analytics#3909]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Self-hosting

### Describe the bug

Running this command, adapted from the [docs](https://plausible.io/docs/sites-api):

```
curl -X PUT https://selfhostedaddress.com/api/v1/sites/goals \
                          -H "Authorization: Bearer <token created in UI>" \
                          -F 'site_id="some-site"' \
                          -F 'goal_type="event"' \
                          -F 'event_name="Signup"'
```

Results in a 404 response:

```
<div class="container flex flex-col items-center text-center mt-24">
  <h1 class="text-5xl font-black dark:text-gray-100">404</h1>
  <div class="mt-4 text-xl dark:text-gray-100">Oops! There's nothing here</div>
  <div class="text-xl dark:text-gray-100">Trying to access your dashboard? You may need to log in again to see it</div>
  <div class="mt-6 flex">
<a class="button" href="/login">Login</a>
<a class="button button-outline ml-2" href="/">Go to homepage</a>
  </div>
</div>
```

We are trying v2.1.0-rc.0 of the Community Edition. The API for sending events (/api/event) seems to work fine on the other hand.

Repro steps:
1. Set up v2.1.0-rc.0 of the Community Edition on Linode using nginx as the reverse proxy
2. Go to Account Settings -> API Keys
3. Create an API key
4. Issue the curl command above with the API key as the Bearer token
5. Receive 404 page

<img width="680" alt="image" src="https://github.com/plausible/analytics/assets/150642383/cfa809af-cdeb-464c-8621-89478ee261cf">

### Expected behavior

Working /api/v1/sites/goals endpoint, as described on https://plausible.io/docs/sites-api

### Environment

```markdown
- OS: macOS
- Browser: Safari and curl
- Browser Version: 17.4
```

**Comment by ruslandoga** [comment]
👋 @furnacecreek 

Thank you for the report! It seems like Sites API is not available in Community Edition build: https://github.com/plausible/analytics/blob/d3586a81e394816d9aaee3565c5fa140f18ea6cc/lib/plausible_web/router.ex#L171-L183

`on_full_build` means the Cloud build.

I'll check with the core team if it's actually intended.

**Comment by ruslandoga** [comment]
According to https://plausible.io/blog/community-edition it's intentional.

**Comment by tataihono** [comment]
@furnacecreek did you figure a work around? we were using the sites api on v2 but have recently upgraded to v2.1.1 and have discovered that the api is no longer available.

**Comment by puecher** [comment]
Can we uncomment `on_ee` on https://github.com/plausible/analytics/blob/v2.1.0/lib/plausible_web/router.ex#L171? We would like to re use the /api/v1/sites calls.
