### ISSUE TITLE
Change "This Month" to display Month To Date view

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/analytics#391]
"This Month" currently displays the full month which is not that useful, especially in the first half of the month which leaves most of the top graph empty and the comparison wrong too. If "This Month" simply shows month to date view rather than the full month would be much more useful. 

(request from [Twitter](https://twitter.com/nbgoodall/status/1322149369378938882))

**Comment by nbgoodall** [comment]
Thank you, Marko! 🚀

**Comment by ukutaht** [comment]
Agreed 💯
