### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by DrTrills** [plausible/analytics#392]
Hi all, just discovered Plausable and so far I am impressed with its power and simplicity. I am tryin to setup goals for our careers page which is the basic install of [Bullhorn Careers Portal](https://github.com/bullhorn/career-portal). 

Looking at the docs and trying to use the basic JS provided and match it with the /signup on your site. I am still running into some issues.

Ideally i'd like to track

1. Who click Apply Now on each listing, and of those who click it, how many actually fill and submit the form / for which job.

```
<script>window.plausible = window.plausible || function() { (window.plausible.q = window.plausible.q || []).push(arguments) }</script> 
  <script>
    if (novo-form) {
      novo-form.addEventListener('submit', function(e) {
        e.preventDefault();
        setTimeout(submitForm, 1000);
        var formSubmitted = false;
    
        function submitForm() {
          if (!formSubmitted) {
            formSubmitted = true;
            registerForm.submit();
          }
        }
    
        plausible('APPLY NOW', {callback: submitForm});
      })
    }
  </script>
```

Happy to DM the URL if that helps any. Will keep playing around see if I can crack the code, any help would be appreciated.

P.S. the hashing JS script works perfect on this 👍 

 Thanks!

**Comment by metmarkosaric** [comment]
Thanks @DrTrills! GitHub is not the best place for these types of support questions so I'll close this. Perhaps you could post this [on our forum instead](https://plausible.discourse.group/) and if someone has experience the same issue they can help out? In general, it is really difficult for us to provide support for the queries about the code for goals as it depends on so many things on your own site. We do hope to provide some more easy examples of code in the future and perhaps even automate some popular event categories. Sorry about that!

**Comment by DrTrills** [comment]
@makitsune no worries, thanks and will do
