### ISSUE TITLE
Merge sources regardless of capitalization

### ISSUE THREAD

**Issue by DrTrills** [plausible/analytics#393]
## Prerequisites
- [x] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report
**Describe the bug**
Referral sources are duplicating. It lists Linkedin as one source, linkedin as another as one of the links has a capital L.
**Expected behavior**
LinkedIn (or whichever) should be 1 source regardless of capitalization.

**Screenshots (If applicable)**
![Screen Shot 2020-11-02 at 4 39 10 PM](https://user-images.githubusercontent.com/1430005/97887764-a17ba900-1d2a-11eb-814b-0cc1c9893146.png)

**Comment by metmarkosaric** [comment]
In the "All" tab in Top Sources everything is combined. Clicks you get with a referral header and clicks you get with UTM tags. "linkedin" must be a UTM tagged link click you have. LinkedIn clicks are official as "LinkedIn" in the referral header. Same problem can happen with other sites such as Twitter and Facebook. If you want your UTM tagged clicks to be merged with the clicks that come with a referral header, the names need to match at this time (LinkedIn).

**Comment by DrTrills** [comment]
Ah will look into that. Thanks

**Comment by metmarkosaric** [comment]
No problem! There's this introduction to UTM tags with some best practices that you can take a look at: https://plausible.io/blog/utm-tracking-tags
