### ISSUE TITLE
removing a goal makes it disappear from the reporting

### ISSUE THREAD

**Issue by divinerites** [plausible/analytics#394]
## Prerequisites
- [x] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report
When we remove a goal it says that the goal is removed but the statistics will remains.

But removing a goal makes it disappear from the reporting.

You can see what i've done  on centre202.netlify.app domain.

**Expected behavior**

I expect to see the "removed goals" in the reporting. Or I expect the message to tell me it will be removed.

**Comment by ukutaht** [comment]
Thanks @divinerites 

I don't fully understand the issue. Is this what you expect?
1. Create a goal
2. Let's say 10 people convert for the goal
3. Remove the goal
4. Add the same goal again
5. Plausible shows 0 conversions (?)

**Comment by divinerites** [comment]
Ahh, I get it.

From the web message, I understood that the stat will remains *showed on the site*.
But you mean the stats remains *inside the database*.
Makes sense. 

So sorry for the misunderstanding.
