### ISSUE TITLE
SVG map in shared link is not correctly aligned

### ISSUE THREAD

**Issue by thelfensdrfer** [plausible/analytics#3941]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Self-hosting

### Describe the bug

The SVG map is not correctly aligned (see screenshots). I am using the self-hosted version with the latest commit 9989ce6927ef02a4d26e51e93f5301231bf42a71. The issue is only on the shared/embedded page, not the default page.

### Expected behavior

/

### Screenshots

![Screenshot 2024-03-25 at 10 41 17](https://github.com/plausible/analytics/assets/699106/896fff4a-8b89-49b2-8ead-22bf19404323)
![Screenshot 2024-03-25 at 10 41 58](https://github.com/plausible/analytics/assets/699106/5f0f972c-e8b3-4b6a-af9f-c6943ecebae0)
![Screenshot 2024-03-25 at 10 42 14](https://github.com/plausible/analytics/assets/699106/8d78590f-c92c-41f9-b0c5-27249cc8f054)
![Screenshot 2024-03-25 at 10 42 22](https://github.com/plausible/analytics/assets/699106/4e08e0fe-8e61-4f44-a12d-b36636721152)

### Environment

```markdown
- OS: macOS
- Browser: Firefox
- Browser Version: 124.0.1

- Browser: Google Chrome
- Browser Version: 123
```

**Comment by ruslandoga** [comment]
@thelfensdrfer 👋

This seems to only affect `width=manual` embeds, right? I haven't been able to reproduce the issue for other embed types.

**Comment by thelfensdrfer** [comment]
> This seems to only affect `width=manual` embeds, right? I haven't been able to reproduce the issue for other embed types.

Yes, you are right.

**Comment by ruslandoga** [comment]
I think this has been fixed in https://github.com/plausible/analytics/pull/4427 as I can't reproduce it anymore on staging.

**Comment by thelfensdrfer** [comment]
Confirmed, we use the `plausible/analytics:v2.0` docker tag and the bug is not visible anymore.
