### ISSUE TITLE
Script is no longer <1kb

### ISSUE THREAD

**Issue by ivangreene** [plausible/analytics#3962]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

The tracking script is no longer <1kb as claimed in multiple places (this repo, the Plausible.io website, etc)

### Expected behavior

The tracking script should be <1kb

### Screenshots

```
$ curl -s https://plausible.io/js/script.js | wc -c
    1346
```

### Environment

```markdown
- OS:
- Browser:
- Browser Version:
```

**Comment by digital88** [comment]
Try gzip it.

**Comment by ukutaht** [comment]
> Try gzip it.

Correct. 99%+ of requests are compressed via gzip or brotli so the compressed size is what we count as the script size.
