### ISSUE TITLE
Allow main stats to appear in site domain

### ISSUE THREAD

**Issue by riderx** [plausible/analytics#399]
In website list in can be nice to have an overview with main stats (unique visitor )on the list:
![63BCE5BC-E6F5-44F0-A6ED-ECBE4987D641](https://user-images.githubusercontent.com/4084527/98544312-1d7a7180-2294-11eb-9647-c503843e9b89.png)
To do it I suggest to remove the « setting » word since the icon do the job already .

The goal of this request is to allow user to know witch domain is important to check or not .

Maybe the % of change vs last week can be interesting too, it’s depend the space maybe on mobile it will be too much info .

**Comment by metmarkosaric** [comment]
Thanks @riderx ! There's the #123 already for a similar request so I'll close this one to keep all the conversation about this in one place.

**Comment by riderx** [comment]
@metmarkosaric oups yes in voted for the other so !
