### ISSUE TITLE
Q: cron for self-hosted instances?

### ISSUE THREAD

**Issue by patschi** [plausible/analytics#400]
Unfortunately there's no further clarification in the [docs](https://docs.plausible.io) nor am I able to find them during searching through the code. So apparently there's a `CRON_ENABLED` environment variable which enables cron functionality, but is disabled by default.

But as the env variable is not documented nor mentioned somewhere in the GitHub issues, I'm wondering if enabling is required for a self-hosted instance for the functionality like fetching the tweets or sending stats summaries?

https://github.com/plausible/analytics/blob/039480a0d14186f2f3f13da030dd7a7c39f50673/config/config.exs#L102-L109

P.S.: Using Plausible since a few days, and liking it so far. Awesome work - thanks!

**Comment by ukutaht** [comment]
> But as the env variable is not documented nor mentioned somewhere in the GitHub issues, I'm wondering if enabling is required for a self-hosted instance for the functionality like fetching the tweets or sending stats summaries?

Yes, you can enable these jobs using the `CRON_ENABLED` environment variable.

The default setup isn't ideal. I think it would make sense to enable background jobs by default.

**Comment by patschi** [comment]
> I think it would make sense to enable background jobs by default.

Important to note: I'm not about pushing this, as I'm running `CRON_ENABLED` for a few months just fine, so this is basically solved for me.

But as you appear keeping the Issues section clean, wouldn't it be a very easy, quick change from `false` to `true` to also close this issue?

**Comment by ukutaht** [comment]
@patschi Yeah pretty much. There are some jobs in that cron table that are specific to our cloud instance, e.g. provisioning SSL certificates for custom domains or sending end-of-trial emails. But they shouldn't create a problem when running in a self-hosted context.

For the next release (which I will cut this month), I am planning to disable trials + custom domains and enable background jobs by default.

**Comment by ukutaht** [comment]
@patschi Release candidate `v.1.2-rc.0` has background jobs enabled by default, except ones that are strictly used for the hosted version (`provision_ssl_certificates` and `send_trial_notifications`)

**Comment by patschi** [comment]
I've seen PR #603 - brilliant changes, thanks a lot!

Not sure if it belongs in #603 or here: As a public code repo, wouldn't it make sense to default `SELFHOST` to `true` and specify `false` in your cloud environment? (And yeah, I think that's a bit unfair ask, given to the fact you're developing the whole thing for your own business)

**Comment by ukutaht** [comment]
Ah, thanks for letting me know @patschi. It was a mistake, I intended to default it to `true`. Totally, the default config is and should be aimed at self-hosters.

**Comment by ukutaht** [comment]
Just checked and I'm pretty sure it does default to `true`? https://github.com/plausible/analytics/blob/master/config/runtime.exs#L66

**Comment by ukutaht** [comment]
Fixed in [v1.2](https://github.com/plausible/analytics/releases/tag/v1.2.0)
