### ISSUE TITLE
Plausible logo in emails not visible

### ISSUE THREAD

**Issue by sswany** [plausible/analytics#4055]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Self-hosting

### Describe the bug

It seems the logo file src referenced by the standard email templates isn't available at the URL included.

Currently, the file listed in our self-hosted instances' template is:
https://plausible.io/images/icon/plausible_logo-973ea42fac38d21a0a8cda9cfb9231c9.png

But that URL isn't available.

Thanks!

### Expected behavior

URL would be resolvable

### Screenshots

![Screenshot 2024-05-01 at 09 05 55@2x](https://github.com/plausible/analytics/assets/2540331/80520dd4-1823-4ed1-b3a4-7a3c4b97a5cf)

### Environment

```markdown
- OS: MacOS
- Browser: Chrome
- Browser Version: n/a
```

**Comment by ruslandoga** [comment]
This is fixed in v2.1.0. v2.0.0 probably won't be "back-fixed".
