### ISSUE TITLE
Make dashboard header sticky

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/analytics#409]
"When I click on a link in the dashboard to filter the analytics, I have to scroll back up to reset it. It would be nice if that reset button was floating?"

(feedback via email)

**Comment by VictorBaudot** [comment]
yes, or be able to click a second time on a filter to unfilter.

Example:
I want to click again on "new event" to unselect it
![image](https://user-images.githubusercontent.com/33088396/98935095-9805f400-2515-11eb-9e5f-f5def444af01.png)
