### ISSUE TITLE
Mini Chart on Dashboard does not reset if the data has been resetted

### ISSUE THREAD

**Issue by Wuemeli** [plausible/analytics#4095]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

If you create a Site and go to the main Site you have this Mini Chart that displays the % and Visitors. If you then delete the Data from the site this Mini Chart doesn't get reseted

### Expected behavior

It shows nothing

### Environment

```markdown
- OS: Linux/Windows
- Browser: Chrome
- Browser Version:
```

**Comment by Wuemeli** [comment]
Its just minimal

**Comment by ukutaht** [comment]
Deleting data can take some time because it's done in the background. Did the mini chart update eventually?

**Comment by Wuemeli** [comment]
Yes after 24 Hours have passed
