### ISSUE TITLE
Duplicate case value in Plausible.Stats.Filters.DashboardFilterParser

### ISSUE THREAD

**Issue by karlosmid** [plausible/analytics#4135]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Self-hosting

### Describe the bug

There is duplicate case value here:
https://github.com/plausible/analytics/blob/c81cb1693320b35a0d4a1fddbcb5d7bb7cbcf9bf/lib/plausible/stats/filters/dashboard_filter_parser.ex#L44
and here
https://github.com/plausible/analytics/blob/c81cb1693320b35a0d4a1fddbcb5d7bb7cbcf9bf/lib/plausible/stats/filters/dashboard_filter_parser.ex#L59

### Expected behavior

Second statement is "dead code"

### Environment

```markdown
Source code issue
```

**Comment by ruslandoga** [comment]
👋 @karlosmid 

Thank you! I've opened a PR that removes the duplicate clause: https://github.com/plausible/analytics/pull/4137
