### ISSUE TITLE
Don't add any localhost address

### ISSUE THREAD

**Issue by thepra** [plausible/analytics#414]
It busted all the services running on my server, in the journalctl there was something about :nxdomain not found, don't remember, but just don't put any localhost address into your instance!

**Comment by ukutaht** [comment]
Sorry I don't understand the issue, did your self-hosted instance crash when you added a domain with localhost?

**Comment by thepra** [comment]
Nevermind, something else went wrong in the server, plausible despite being in a docker container felt the disruption.
