### ISSUE TITLE
IPv6 (only) SMTP not working

### ISSUE THREAD

**Issue by DennisGlindhart** [plausible/analytics#4147]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Self-hosting

### Describe the bug

When using IPv6-only SMTP-server Plausible cannot send mail and gives NX-domain bacause it only tries to connect to IPv4/inet, instead of IPv6/inet6 with fallback to IPv4/inet. (only AAAA-record is available)

Happens with both Bamboo.SMTPAdapter and Bamboo.Mua (MAILER_ADAPTER=Bamboo.Mua after update to 2.1)

Using Bamboo.SMTPAdapter IPv6 can be enabled with adding sockopts in config/runtime.exs (https://github.com/plausible/analytics/blob/c15ce1fa154f1226f07c3abddc77727d236c01d9/config/runtime.exs#L473)

```
-      no_mx_lookups: get_var_from_path_or_env(config_dir, "SMTP_MX_LOOKUPS_ENABLED") || true
+      no_mx_lookups: get_var_from_path_or_env(config_dir, "SMTP_MX_LOOKUPS_ENABLED") || true,
+      sockopts: [:inet6, {:ip, {0,0,0,0,0,0,0,0}}]
```

I have no IPv4 environment to test in, so I don't know if this patch stops IPv4 from working.

I have not found a workaround for Bamboo.Mua.

When using Bamboo.SMTPAdapter the following error is printed when sending a password-reset mail:

```
[error] Task #PID<0.4539.0> started from #PID<0.4538.0> terminating
** (ArgumentError) raise/1 and reraise/2 expect a module name, string or exception as the first argument, got: {:network_failure, ~c"smtp", {:error, :nxdomain}}
	(bamboo 2.3.0) lib/bamboo/strategies/task_supervisor_strategy.ex:25: anonymous fn/3 in Bamboo.TaskSupervisorStrategy.deliver_later/3
	(elixir 1.16.0) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2
Function: #Function<0.95237244/0 in Bamboo.TaskSupervisorStrategy.deliver_later/3>
	Args: []
```
When using Bamboo.Mua the following error is printed when sending a password-reset mail:
```
[error] Task #PID<0.4396.0> started from #PID<0.4395.0> terminating
** (Mua.TransportError) non-existing domain
	(bamboo 2.3.0) lib/bamboo/strategies/task_supervisor_strategy.ex:25: anonymous fn/3 in Bamboo.TaskSupervisorStrategy.deliver_later/3
	(elixir 1.16.0) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2
Function: #Function<0.95237244/0 in Bamboo.TaskSupervisorStrategy.deliver_later/3>
	Args: []
```

### Expected behavior

Either:
- IPv6-connection is preferred with fallback to IPv4 when connecting to SMTP
- Ability to "turn on" IPv6-mode for SMTP like ECTO_IPV6/ECTO_CH_IPV6

### Environment

```markdown
- OS:Linux
```

**Comment by ruslandoga** [comment]
https://github.com/plausible/analytics/pull/4134 would make this automatic in CE.
