### ISSUE TITLE
600 API Request limit in plausible API

### ISSUE THREAD

**Issue by Bipund** [plausible/analytics#4199]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Self-hosting

### Describe the bug

**Bug Description:**
We are currently utilizing Plausible, a self-hosted analytics tool, to analyze website traffic. Our website pulls data from the Plausible server using its API. However, we've encountered an issue with the API limiting the number of requests made using a single API key to 600 calls.

**<img width="1015" alt="Screenshot 2024-06-08 at 4 43 44 AM" src="https://github.com/plausible/analytics/assets/41412272/6cba9c61-1593-440f-a683-5520783005ab">**
The bug arises from the imposed limit of 600 API calls per API key within a specific time frame.

### Expected behavior

correct data to be fetch and API should work without any limit

### Environment

```markdown
- OS: IOS
- Browser: - 
- Browser Version:
```

**Comment by ruslandoga** [comment]
👋 @Bipund 

Thank you for the report! I've started a PR that would fix this: https://github.com/plausible/analytics/pull/4200

**Comment by Bipund** [comment]
it is working now thanks @ruslandoga
