### ISSUE TITLE
Stats API "requires subscription" on Community Edition

### ISSUE THREAD

**Issue by ROFISH** [plausible/analytics#4243]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Self-hosting

### Describe the bug

Access to the Stats API on a self-hosted Community Edition asks for a "subscription" and then points to the official subscription signup workflow.

### Expected behavior

Stats API is unrestricted on Community Edition.

Workaround: In a database editor, set the user's `trial_expiry_date` to NULL and `inserted_at` to before the [business tier launch time](https://github.com/plausible/analytics/blob/a5c61e493013cc15439185ec9db71ecea9d63d23/lib/plausible/billing/plans.ex#L29). Relevant code looks for a [pre_business_tier_account](https://github.com/plausible/analytics/blob/a5c61e493013cc15439185ec9db71ecea9d63d23/lib/plausible/billing/feature.ex#L227C46-L227C71) but since it's for internal use only, I don't "sell subscriptions".

### Screenshots

![image](https://github.com/plausible/analytics/assets/5236/eb3840b8-0782-470a-a92d-a2b174966506)

### Environment

```markdown
- OS: MacOS
- Browser: Safari
- Browser Version: Version 17.5 (19618.2.12.11.6)
```

**Comment by ruslandoga** [comment]
👋 @ROFISH 

Quick check, what version you using?

**Comment by ROFISH** [comment]
> 👋 @ROFISH
> 
> Quick check, what version you using?

2.1.1 . It was no issue on 2.0.

**Comment by ruslandoga** [comment]
Do you get this warning at /settings when creating an API key or someplace else?

**Comment by ROFISH** [comment]
> Do you get this warning at /settings when creating an API key or someplace else?

The screenshot shown is on /settings.

As well as 401 `Invalid API key or site ID. Please make sure you're using a valid API key with access to the site you've requested.` responses to API keys created before 2.1
