### ISSUE TITLE
HTTPClient not support HTTP/HTTPS proxy

### ISSUE THREAD

**Issue by HADB** [plausible/analytics#4269]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Self-hosting

### Describe the bug

First of all, thank you for the great work on this project!

Currently, the `HTTPClient` seems not support using HTTP or HTTPS proxies set via environment variables (`HTTP_PROXY` and `HTTPS_PROXY`). This functionality is important for users who need to route traffic through a proxy for various reasons, such as network restrictions or privacy concerns.

In my case, I'm facing network restrictions while connecting to Google services or Gravartor avatars.

### Expected behavior

The HTTPClient should respect the `HTTP_PROXY` / `HTTPS_PROXY` environment variables and route HTTP/HTTPS requests through the specified proxy.

**Comment by ruslandoga** [comment]
👋 @HADB 

Where do the `HTTP_PROXY` and `HTTPS_PROXY` environment variables come from? Have they been documented somewhere? I don't think we have them anywhere in the code base.

**Comment by HADB** [comment]
@ruslandoga Hi, thanks for replying. HTTP_PROXY and HTTPS_PROXY are environment variables used to specify proxy servers for HTTP and HTTPS traffic respectively. Many applications and libraries recognize and use these variables to route their network traffic through specified proxy servers, such as：`curl`, `wget` and Python’s requests library.

**Comment by ruslandoga** [comment]
I see. We might be able provide support for these env vars later, but for now we can at least make [proxying](https://hexdocs.pm/mint/Mint.HTTP.html#connect/4-proxying) configurable via [custom config files.](https://github.com/plausible/analytics/pull/3906) I'll open a PR for that later today.

**Comment by ruslandoga** [comment]
@HADB would you be able to try out the image I [built](https://github.com/ruslandoga/plausible/pull/317) from #4270?

Here're the changes you'd need to make:

<sub><kbd>[docker-compose.yml](https://github.com/plausible/community-edition/blob/v2.1.1/docker-compose.yml)</kbd></sub>
```diff
plausible:
- image: ghcr.io/plausible/community-edition:v2.1.1
+ image: ghcr.io/ruslandoga/plausible:build-allow-finch-config-9456444
+ volumes:
+   - ./my_config.exs:/app/my_config.exs
```

<sub><kbd>my_config.exs</kbd></sub>
```elixir
import Config

# Plausible uses HTTPS, and our HTTP client (Mint) doesn't support HTTPS->HTTPS proxying
# https://hexdocs.pm/mint/Mint.HTTP.html#connect/4-proxying recommends HTTP->HTTPS in this case
config :plausible, Plausible.Finch, conn_opts: [proxy: {:http, _"some.proxy.com", _port = 1080, _opts = []}]
```

<sub><kbd>[plausible-conf.env](https://github.com/plausible/community-edition/blob/v2.1.0/plausible-conf.env)</kbd></sub>
```diff
+ EXTRA_CONFIG_PATH=/app/my_config.exs
```

**Comment by HADB** [comment]
@ruslandoga I have tried this image and it works as expected! Great job! Thanks a lot!
