### ISSUE TITLE
Live Demo with iOS Brave Browser dont work

### ISSUE THREAD

**Issue by linuxr01** [plausible/analytics#428]
### Precheck

Please note that this tracker is only for bugs. Do not use the issue tracker for help or support. [Our docs](https://docs.plausible.io/) are a great place for most answers, but if you can’t find your answer there, you can [contact us](https://plausible.io/contact). Have an issue with your self-hosted install? You can ask in [our community forum](https://plausible.discourse.group/). Thanks!

## Prerequisites
- [x] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report
**Describe the bug**

Live Demo dont work if the Brave Shield is enabled.

**Expected behavior**

Life Demo should work if the Brave Shield is enabled.

**Screenshots (If applicable)**

![brave-error](https://user-images.githubusercontent.com/49744994/99663991-c3359980-2a67-11eb-83fd-3b19782d4924.gif)

**Environment (If applicable):**
 - OS: iPad OS 14.2
 - Browser: Brave 1.21 (20.11.10.16)

**Comment by metmarkosaric** [comment]
thanks for reporting this! this is not down to us but to Brave. do they have a way to report bugs in their shields?

**Comment by linuxr01** [comment]
I have reported it.

![brave](https://user-images.githubusercontent.com/49744994/99665539-0bee5200-2a6a-11eb-9181-ba58b9339d59.jpg)

**Comment by metmarkosaric** [comment]
thank you! hope they fix it! i may try to reach out to them myself too

**Comment by metmarkosaric** [comment]
I've tested the site using Brave now and it works all fine even with the strictest shield settings enabled. So perhaps they fixed it already!? Will close this as there's nothing we can do about this on our end and hopefully Brave have sorted it after it's been reported to them.
