### ISSUE TITLE
.world top level domain with analytics not working

### ISSUE THREAD

**Issue by thepra** [plausible/analytics#430]
## Prerequisites
- [x] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report
**Describe the bug**
I does seem like from my domain with the top level domain .world the generated script doesn't work:
`<script async defer data-domain="[redacted].world" src="https://plausible.[redacted].app/js/plausible.js"></script>`
Plus I can't seem to find any console or XHR error about that script not working, it's as if the script never loaded.
_PS: on other domains the scripts do work totally fine._

**Expected behavior**
I expect that at the website analytics page https://plausible.[redacted].app/[redacted].world receives analytic data from the .world domain.

**Screenshots (If applicable)**
Despite no explicit errors, from Sources is missing that domain of the script:
![image](https://user-images.githubusercontent.com/7032509/99852809-097f1b80-2b82-11eb-932a-89f9c67c04be.png)

**Environment (If applicable):**
 - OS: Linux
 - Browser: firefox, chromium
 - Version: 82, 85

**Comment by ukutaht** [comment]
<img width="1215" alt="Screenshot 2020-11-24 at 16 22 48" src="https://user-images.githubusercontent.com/3731516/100106562-5a885b80-2e71-11eb-8af4-99aef5d2ed63.png">

I did not manage to reproduce this issue – seems to work fine with testing.world domain.

Closing this for now. If you're comfortable sharing your live URL so I can debug on your site, please send it over email: uku@plausible.io

**Comment by thepra** [comment]
With Uku I figured out that there was an overlap of headers and by spec such setup didn't allow the CSP exception to function properly. 
Fortunately there is a way to disable that header from the software and put everything in nginx, so this is the way to workaround such case.

Thanks for all,
Bye
