### ISSUE TITLE
Sudden Drop in UTM Source Tracking and Surge in Non-existent Page Views

### ISSUE THREAD

**Issue by giammarcotassinari** [plausible/analytics#4363]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

For the past month, we have observed a significant drop in UTM source tracked sessions, alongside a surge in non-existent page views with URLs formatted as /landing_page/utmsource/utm_campaign.

### Expected behavior

We are expecting to have plausible to read correctly the utm_source

**Comment by metmarkosaric** [comment]
hi @giammarcotassinari! we keep the issues list here to the actual bugs with the product. for any kind of tracking issue and other support questions, please [contact our customer support directly](https://plausible.io/contact). thanks!
