### ISSUE TITLE
Open link uses main domain when traffic goes to subdomain

### ISSUE THREAD

**Issue by mcapodici** [plausible/analytics#4379]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

When tracking clicks off a subdomain, the link to open the URL uses the main domain.

In the screenshot attached, you can see the filter for the blog subdomain, and the link target behing shown for the main domain.

### Expected behavior

The link target should match the same subdomain that was visited. It looks like you have the data in the back end, because the filter works. It is probably just a UI thing.

### Screenshots

![image](https://github.com/user-attachments/assets/1f20e0a1-3bf0-4521-a72d-3a29ed86a847)

### Environment

```markdown
- OS: Windows 11
- Browser: Chrome
- Browser Version: 126.0.6478.182
```

**Comment by ukutaht** [comment]
@mcapodici Hey! Thanks for the suggestion. We're tracking a similar feature request here: https://feedback.plausible.io/207

Closing this as we're not using Github issues for feature requests anymore

**Comment by mcapodici** [comment]
It's a bug!
