### ISSUE TITLE
VPN events and views being dropped

### ISSUE THREAD

**Issue by MeanBoyCousin** [plausible/analytics#4385]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

This has been previously reported in #3764 but appears to still be an issue. I have noted the `🏳️
 Anonymous VPN Service` appears in countries but this doesn't always work. In my experiments and like the previous reporter, all events behind a Mullvad VPN are marked as `x-plausible-dropped`. As soon as the VPN is off, everything tracks fine as expected. I've switched through countless VPN locations and they all seem to get dropped.

### Expected behavior

VPN events should still be registered and not dropped.

### Environment

```markdown
- OS: N/A
- Browser: N/A
- Browser Version: N/A
```

**Comment by pauliusef** [comment]
I'd like to re-open this issue as I'm still experiencing VPN requests being dropped by Plausible. I'm proxying my script via Vercel with custom rewrites according to your documentation. Using Proton VPN (e.g. 130.195.243.20 as the IP address). 

BTW, I have never experienced `🏳️ Anonymous VPN Service` appearing in countries.
