### ISSUE TITLE
Selecting today doesn't work when on a different day

### ISSUE THREAD

**Issue by VictorBaudot** [plausible/analytics#439]
If you select Today, then click on the horizontal arrows to change day and then select Today, it won't bring you back to the current day.

Here I'm clicking on Today, but it doesn't move me because it's a link to the 20 of november.
![image](https://user-images.githubusercontent.com/33088396/100337358-dd441e80-3009-11eb-9ea9-3462afc9952e.png)

**Comment by metmarkosaric** [comment]
Thanks! Tested it here and same things happens to me. Also for "this month" but interestingly enough not for "last month".
