### ISSUE TITLE
Disable time travel

### ISSUE THREAD

**Issue by mishushakov** [plausible/analytics#446]
### Precheck

Please note that this tracker is only for bugs. Do not use the issue tracker for help or support. [Our docs](https://docs.plausible.io/) are a great place for most answers, but if you can’t find your answer there, you can [contact us](https://plausible.io/contact). Have an issue with your self-hosted install? You can ask in [our community forum](https://plausible.discourse.group/). Thanks!

## Prerequisites
- [x] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report
**Describe the bug**
When picking a date you can select a date or range before the website was added or in the future

**Expected behavior**
You should not be able to select a date before the website was added and in the future

**Screenshots (If applicable)**

<img width="327" alt="Screenshot 2020-12-03 at 01 43 16" src="https://user-images.githubusercontent.com/10400064/100948991-6e832b80-3509-11eb-9993-a11557983a28.png">

**Environment (If applicable):**
 - OS: macOS
 - Browser Safari
 - Version 14.0.1

**Comment by ukutaht** [comment]
Thanks for reporting!

**Comment by mishushakov** [comment]
no, thank you for your great work!

**Comment by maco** [comment]
I can't reproduce being able to choose dates in the future, but I made PR to fix choosing dates before the site was added to Plausible.

**Comment by mishushakov** [comment]
@maco press here

<img width="313" alt="Screenshot 2020-12-16 at 10 24 07" src="https://user-images.githubusercontent.com/10400064/102329704-fc8af780-3f88-11eb-8ef7-58a248aef406.png">

**Comment by ukutaht** [comment]
Keeping this open for now until the arrow to a future date is also greyed out.

**Comment by maco** [comment]
Ah, ok I thought it was just the calendar being talked about. I'll take a look at disabling the arrow buttons too.

**Comment by ukutaht** [comment]
I've noticed it myself where I spam the arrow right button and end up in the future. It's a very minor annoyance for me but worth improving. Arrow left allowing to move to the past is not an issue for me personally.

**Comment by metmarkosaric** [comment]
Thanks! I was just testing this on staging. The arrow right button still shows up (and it looks clickable when you hover over it) even when it cannot be clicked such as on "Today". Not sure how much extra work it is to remove it completely when it cannot be clicked or make it look not clickable?

![Screenshot from 2021-01-07 18-11-10](https://user-images.githubusercontent.com/34340819/103922432-07faba00-5114-11eb-9e84-993c6a4744fe.png)

**Comment by maco** [comment]
It's a disabled button. That's why it's darker. Do you have a suggestion for more-disabled-looking styling in dark mode? Maybe I should make the icon a bit darker too in disabled mode? 

Removing it makes the left button scoot over, which results in a really weird user experience of it bouncing around as you go forward and backward.

**Comment by metmarkosaric** [comment]
The color looks fine to me. If it cannot be removed when it's not clickable, perhaps there's a way to make the mouse cursor not change and appear like clickable when you hover over the button?

**Comment by maco** [comment]
That makes sense. I just moused around Github and see how the cursor looks on disabled versus enabled buttons. I'll put in a PR for that....probably tonight (after work).

**Comment by metmarkosaric** [comment]
That's great! Thanks @maco for your help! It's live on staging so you can test it there too: https://staging.plausible.io/plausible.io

**Comment by ukutaht** [comment]
I noticed we have a disabled button in the settings which has the same cursor issue. I took the liberty to fix it in 4fb78265a8fb4671475c92fae21f60c31cafc84a

Some seem to suggest `cursor: not-allowed` for disabled buttons but I personally prefer the default (unclickable) cursor like Github does. The `not-allowed` cursor can be pretty jarring.
