### ISSUE TITLE
Unable to add ip to shield

### ISSUE THREAD

**Issue by roygroothulze** [plausible/analytics#4462]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Self-hosting

### Describe the bug

I am unable to a my ip to the shield

### Expected behavior

After filling the ip and the name I want to submit the form. But the 'Add IP Address ->" button does not seems to work. 

### Environment

```markdown
- OS: MacOS
- Browser: FireFox
- Browser Version: 129.0.2 (64-bit)
- Plausible: 2.1.1
```

**Comment by ruslandoga** [comment]
👋 @roygroothulze 

Please check for errors in the browser console and describe your setup in more detail, i.e. do you have WebSockets enabled in your reverse proxy?

**Comment by roygroothulze** [comment]
There are no errors in the browser console. No I don't have WebSockets enabled.

**Comment by ruslandoga** [comment]
WebSockets need to be enabled for Shield IP form to work. Please check https://github.com/plausible/analytics/discussions?discussions_q=is%3Aopen+websocket for how to do that for various proxies. Configuration files in https://github.com/plausible/community-edition/tree/v2.1.1/reverse-proxy might also be useful.

**Comment by roygroothulze** [comment]
Thank you for the information. I added the WebSockets and I can add my ip now. 

But I am not sure if this works correctly. Plausible say my current ip is: 192.168.178.1. Which is the local ip of my router. When I try adding the ip using my iPhone I get a different ip which is indeed my home ip. 

Can you help me fixing this?

**Comment by ruslandoga** [comment]
First, please make sure your reverse proxy sets the correct `x-forwarded-for` headers. if that doesn't help, trace the requests and check where the local IP address comes from.

**Comment by ruslandoga** [comment]
These discussions might be relevant:
- https://github.com/plausible/analytics/discussions/3978
- https://github.com/plausible/analytics/discussions/3248
- https://github.com/plausible/analytics/discussions/2767

**Comment by roygroothulze** [comment]
I added the following set header to my nginx config:
`proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;`
