### ISSUE TITLE
[Search Console integration] Missing required parameter: client_id

### ISSUE THREAD

**Issue by Heziode** [plausible/analytics#448]
## Prerequisites
- [X] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report
**Describe the bug**
When I trying to integrate Search Console, I get this error when I click on the button "Continue with Google":

```
Erreur 400 : invalid_request
Missing required parameter: client_id
```

**Expected behavior**
I can continue the integration workflow, like in the [doc](https://docs.plausible.io/google-search-console-integration/#allow-plausible-analytics-to-access-your-search-console).

**Screenshots**

![image](https://user-images.githubusercontent.com/16735076/101050863-20ac0900-3585-11eb-961f-4bee9c3010fe.png)

**Comment by Heziode** [comment]
Hum... I have found the related part on the [doc](https://docs.plausible.io/self-hosting-configuration#google-search-integration).

**Comment by m00nyONE** [comment]
i got this problem too. the Docs don't describe such behaviour.
