### ISSUE TITLE
Self hosted email mentions 30 day trial period

### ISSUE THREAD

**Issue by semanticfire** [plausible/analytics#4492]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Self-hosting

### Describe the bug

Once the first site view comes in, self hosted Plausible sends an email notification.

This email contains:
You're on a 30-day free trial with no obligations so do take your time to explore Plausible. Here's how to get [the most out of your Plausible experience](https://plausible.io/docs/your-plausible-experience).

### Expected behavior

I am not sure if I need this line at all, in a self-hosted installation.

### Environment

```markdown
Not relevant
```

**Comment by ruslandoga** [comment]
👋 @semanticfire 

Thank you for the report! Seems to be the same as https://github.com/plausible/community-edition/issues/150

Quick check, are you using v2.1.1?

**Comment by semanticfire** [comment]
I deployed plausible/community-edition:latest yesterday so I assume yes. 
how can I check it ?

I didn't search in that repo for issues, sorry about that.

**Comment by semanticfire** [comment]
Showing the version somewhere on the admin frontend would be helpful, should I create an issue for that? (and where?)

**Comment by ruslandoga** [comment]
> Showing the version somewhere on the admin frontend would be helpful

It's tricky: https://github.com/plausible/analytics/discussions/4131

> should I create an issue for that? (and where?)

It's already being tracked internally. But there is no ETA yet.
