### ISSUE TITLE
Outbound link tracking breaks shortcuts to Open in New Tab

### ISSUE THREAD

**Issue by matchu** [plausible/analytics#451]
## Prerequisites
- [x] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report
**Describe the bug**
When I use the outbound link tracking version of the Plausible script, outbound links no longer open in a new tab when I Ctrl-Click or Cmd-Click them.

Instead, the current tab navigates to the destination after the event fires, the same as if I had clicked the link without any modifier keys.

**Expected behavior**
Normally, when I Ctrl-Click or Cmd-Click a link in my browser, it opens in a new tab. I expect outbound links on my site to behave this way too, even when Plausible is tracking the clicks.

**Environment (If applicable):**
 - OS: Windows and macOS
 - Browser: Firefox
 - Version: 83.0b9

**Comment by ukutaht** [comment]
Thanks for reporting, will fix this one soon.
