### ISSUE TITLE
Allow sorting Top Sources by each of the three categories

### ISSUE THREAD

**Issue by preslavrachev** [plausible/analytics#458]
## Prerequisites
- [x] I have searched open and closed issues to make sure that the feature has not yet been requested.

## Feature request
At the moment, the full list of top sources is ordered by the number of visitors. It would be very helpful to make it possible to sort them based on any of the remaining categories (e.g. Bounce Rate and Visit Duration)

![image](https://user-images.githubusercontent.com/86060/101527221-01024f80-398e-11eb-925d-cb7655467d96.png)

**How would you like it to work**
By default, Top Sources will remain sorted by the number of visitors, but the column will have a sort icon, suggesting it is the one that results have been sorted upon. All column headers will be clickable. By clicking on any of the remaining columns, it will become the actively sorted upon and the list of results will be re-rendered to reflect that 

---
**NOTE:** As usually, If there is enough interest in getting this feature implemented, I can implement it myself and send a PR.

**Comment by ukutaht** [comment]
Agreed, I think this would be a great addition

**Comment by metmarkosaric** [comment]
Would be great for Top Pages too!
