### ISSUE TITLE
TOTP Crash after upgrading to 2.1.2

### ISSUE THREAD

**Issue by adamu** [plausible/analytics#4619]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Self-hosting

### Describe the bug

After upgrading to 2.1.2 I see the following error in the console on app startup, and TOTP codes fail to verify:

```
12:24:56.655 [error] GenServer Plausible.Site.Cache.All terminating
** (ArgumentError) errors were found at the given arguments:

  * 1st argument: the table identifier does not refer to an existing ETS table

    (stdlib 6.0) :ets.lookup(Plausible.Auth.TOTP.Vault.Config, :config)
    (cloak 1.1.2) lib/cloak/vault.ex:285: Cloak.Vault.read_config/1
    (plausible 0.0.1) deps/cloak/lib/cloak/vault.ex:252: Plausible.Auth.TOTP.Vault.decrypt/1
    (plausible 0.0.1) deps/cloak_ecto/lib/cloak_ecto/type.ex:64: Plausible.Auth.TOTP.EncryptedBinary.load/1
    (ecto 3.12.2) lib/ecto/type.ex:1031: Ecto.Type.process_loaders/3
    (ecto 3.12.2) lib/ecto/repo/queryable.ex:423: Ecto.Repo.Queryable.struct_load!/6
    (ecto 3.12.2) lib/ecto/repo/queryable.ex:269: Ecto.Repo.Queryable.preprocess/4
    (ecto 3.12.2) lib/ecto/repo/queryable.ex:270: Ecto.Repo.Queryable.preprocess/4
Last message: :"$cycle
```

### Expected behavior

No error and TOTP works without crashing.

**Comment by adamu** [comment]
It looks like this might be a one-off upgrade issue. Restarting again + clearing cookies resolved the issue.

**Comment by mentalstring** [comment]
Perhaps not the best place to report this as it's not even TOTP related, but its perhaps not worth an issue of it's own and it relates to the previous comment.

After upgrading today to 2.1.2 I also couldn't login (login form would simply show up again; no error message). But, after reading the above and clearing cookies, everything worked as expected. Leaving it here in case it saves time to someone.

**Comment by ruslandoga** [comment]
@mentalstring 👋 

https://github.com/plausible/analytics/pull/4621 would probably fix the cookie issue.

**Comment by ruslandoga** [comment]
👋 @adamu 

This seems like a race-condition in app startup.
