### ISSUE TITLE
Custom event props missing in Safari

### ISSUE THREAD

**Issue by tornqvist** [plausible/analytics#463]
## Prerequisites
- [x] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report
The custom event props breakdown is missing in Safari.

### Safari
![Screenshot 2020-12-11 at 10 38 30](https://user-images.githubusercontent.com/985518/101887663-7859fe00-3b9d-11eb-9d18-7d0658ca9b99.png)

### Chrome
![Screenshot 2020-12-11 at 10 38 27](https://user-images.githubusercontent.com/985518/101887657-77c16780-3b9d-11eb-88b5-8fe52c50743f.png)

**Expected behavior**
Custom event props should be visible in Safari.

**Environment (If applicable):**
 - OS: macOS
 - Browser Safari 
 - Version 14.0.1

**Comment by ukutaht** [comment]
Thanks for reporting.

I am unable to reproduce. The following screenshot shows firefox on the left and safari on the right. Custom props are visible on both.

<img width="1680" alt="Screenshot 2020-12-14 at 09 47 42" src="https://user-images.githubusercontent.com/3731516/102054065-7a1bff80-3df1-11eb-8bf2-32e760d785cf.png">
