### ISSUE TITLE
CSV Import/Export does not work with mounts on different devices

### ISSUE THREAD

**Issue by David-Development** [plausible/analytics#4638]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Self-hosting

### Describe the bug

When using an external docker mount (on a different device than the docker image) (as seen here: https://github.com/plausible/community-edition/issues/163#issuecomment-2381308973) the import / export does not work.

The following error is shown in the logs:

```bash
plausible             | ** (File.RenameError) could not rename from "/tmp/plug-1727-SETA/live_view_upload-1727613873-224587708695-6" to "/var/lib/plausible/plausible-imports/2/live_view_upload-1727613873-224587708695-6": cross-device link
plausible             |     (elixir 1.17.1) lib/file.ex:793: File.rename!/2
plausible             |     (plausible 0.0.1) lib/plausible_web/live/csv_import.ex:48: anonymous fn/3 in PlausibleWeb.Live.CSVImport.mount/3
plausible             |     (phoenix_live_view 0.20.3) lib/phoenix_live_view/upload_channel.ex:21: Phoenix.LiveView.UploadChannel.consume/3
plausible             |     (elixir 1.17.1) lib/enum.ex:1703: Enum."-map/2-lists^map/1-1-"/2
plausible             |     (plausible 0.0.1) lib/plausible_web/live/csv_import.ex:222: PlausibleWeb.Live.CSVImport.handle_event/3
plausible             |     (phoenix_live_view 0.20.3) lib/phoenix_live_view/channel.ex:497: anonymous fn/3 in Phoenix.LiveView.Channel.view_handle_event/3
plausible             |     (telemetry 1.3.0) /app/deps/telemetry/src/telemetry.erl:324: :telemetry.span/3
plausible             |     (phoenix_live_view 0.20.3) lib/phoenix_live_view/channel.ex:250: Phoenix.LiveView.Channel.handle_info/2
plausible             | Last message: %Phoenix.Socket.Message{topic: "lv:phx-F_m3qTX2RDI1MwXl", event: "event", payload: %{"event" => "submit-upload-form", "type" => "form", "value" => ""}, ref: "60", join_ref: "4"}
```

A quick chat with ChatGPT revealed that `rename` is not capable of moving a file past device boundaries. Thus the `cp` was suggested.

> Use of `mv` or `cp` Instead of `rename`: Instead of using the rename function, which fails across devices or mounts, ensure that `cp` (copy) and `rm` (remove) are used to move files from /tmp to /var/lib/plausible/.

My understanding is that just the following three locations would need to be adjusted: https://github.com/search?q=repo%3Aplausible%2Fanalytics%20File.rename&type=code. Is that correct? I guess the mv function does not exist in Elixir thus a cp / rm solution would be required.

### Expected behavior

Import / Export works even if data is stored on a different device than Docker Image itself.

### Environment

```markdown
- OS: Docker
- Browser: -
- Browser Version: -
```

**Comment by ruslandoga** [comment]
:wave: @David-Development 

Thank you for the report. I actually thought `File.rename` was equivalent to unix `mv` ... Live and learn :)

I'll try to replace it with a File.cp followed by File.rm as you suggest tomorrow.

**Comment by ruslandoga** [comment]
👋 @David-Development 

I built a custom image (x86 only) for #4640: https://github.com/ruslandoga/plausible/pkgs/container/plausible/281532216?tag=build-file-rename-fallback

Would you be able to try it out?

```diff
plausible:
- image: ghcr.io/plausible/community-edition:v2.1.3
+ image: ghcr.io/ruslandoga/plausible:build-file-rename-fallback
```

**Comment by David-Development** [comment]
@ruslandoga It works! Thank you so much for the quick fix! 🚀
