### ISSUE TITLE
Plausible dashboard and UDP port 9443

### ISSUE THREAD

**Issue by root-io** [plausible/analytics#4664]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

Accessing https://plausible.io/sites my browser is doing outgoing UDP connections to plausible.io and ingest.plausible.io port 9443

I always find weird when websites are asking for anything else than 80 or 443.

### Expected behavior

Only connections on ports 80 and 443.

### Environment

```markdown
- OS: N/A
- Browser: N/A
- Browser Version: N/A
```

**Comment by ruslandoga** [comment]
Looks like HTTP/3. https://plausible.io sends me `Alt-Svc: h3=":9443"; ma=2592000` in headers.

**Comment by cnkk** [comment]
Thanks @ruslandoga!
It's fixed now.
