### ISSUE TITLE
Incorrect Top pages view with multiple subdomains

### ISSUE THREAD

**Issue by wkng** [plausible/analytics#4670]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Self-hosting

### Describe the bug

We have a setup today where we use multiple subdomains for our services.
i noticed that the top pages results view is not correct if you are using multiple subdomain.
The external link is also wrong since we get the same path as displayed.

Domain used for snippet: `sub.domain.com`

Top pages view:
`https://sub.domain.com/sub2/index`
`https://sub.domain.com/sub3/index`

### Expected behavior

Top pages view
`https://sub2.sub.domain.com/index`
`https://sub3.sub.domain.com/index`

### Screenshots

![Skärmbild 2024-10-11 161643](https://github.com/user-attachments/assets/a8a554f6-98c7-4d93-898d-bb4380800433)

### Environment

```markdown
- OS:Windows
- Browser:Arc
- Browser Version:1.22.2 (55438)
```

**Comment by ruslandoga** [comment]
👋 @wkng 

What CE version are you using? Would you be able to show the requests the tracker makes from your subdomains?

**Comment by ruslandoga** [comment]
The URLs seems to include commercialsupport both in subdomain and in path.

**Comment by wkng** [comment]
The name isn't much of a problem. The main issue is that the URL to the site is broken because it get the same URL as the name in the "Top Pages."

So for example the page shown in the images gets this url `sub.domain.com/788.html` instead of `commercialsupport.sub.domain.com/788.html`


![Skärmbild 2024-10-11 175352](https://github.com/user-attachments/assets/16db5b0c-b695-4280-b4f7-a738c758243a)

**Comment by ruslandoga** [comment]
So the name is correct? Only the uURL is wrong?

**Comment by ruslandoga** [comment]
It seems like a request to /pages only returns pathnames which are used to build the link based on the site.domain instead of where the event actually arrived from.

\cc @macobo

**Comment by ukutaht** [comment]
This is an existing request on our feature request page: https://feedback.plausible.io/207. Please continue the discussion there.
