### ISSUE TITLE
HTML code is displayed on sites page

### ISSUE THREAD

**Issue by hobthross** [plausible/analytics#4710]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

I am a user who has come to the end of my trial period. The website tells me I should upgrade when I go to the Sites page. (fair enough!)

There’s what looks like some HTML comment showing on the page. Screenshot attached.

### Expected behavior

HTML comments should not be displayed

### Screenshots

<img width="1187" alt="Screenshot 2024-10-21 at 17 16 27" src="https://github.com/user-attachments/assets/9716e506-a217-455d-a17a-f3e1bd3fade1">

### Environment

```markdown
- OS: OSX
- Browser: DuckDuckGo
- Browser Version:
```

**Comment by ruslandoga** [comment]
Thank you for the report @hobthross! It should be fixed now :)
