### ISSUE TITLE
Comparison % not visible on main chart

### ISSUE THREAD

**Issue by Vrq** [plausible/analytics#4730]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

The comparison percentage are not visible for the top level stats.

### Expected behavior

The percentages should be visible as it was before

### Screenshots

![Screenshot 2024-10-23 at 21 52 13](https://github.com/user-attachments/assets/ce2b81f4-27ca-4c7a-ba48-9030b4b756ae)

### Environment

```markdown
- OS: MacOS
- Browser: Chrome
```

**Comment by metmarkosaric** [comment]
thanks for the report @Vrq ! we're working on adding the percentage increase/decrease arrows to all metrics in our comparison view so we accidentally removed the arrows from the main view. they're back now! thanks and enjoy Plausible!
