### ISSUE TITLE
ARM64 Clickhouse High memory usage

### ISSUE THREAD

**Issue by isFxh** [plausible/analytics#4743]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

When I used the clickhouse-22.8.9.24-alpine version of the docker arm64 image, there was less than 200M of data in clickhouse. When I started clickhouse, the memory usage was about 7G, but the memory continued to grow. I adjusted the container's memory limit to 64G, and the maximum memory used by clickhouse was configured to 32G. However, the memory of clickhouse increased from 7G to 63G within 1 hour, which eventually caused clickhouse to shut down abnormally and fail to provide services.

my runtime env
docker-compose file
![image](https://github.com/user-attachments/assets/518e38d1-e902-4d1e-9694-0b0ee668d032)

docker info
![image](https://github.com/user-attachments/assets/c9deb1d8-3181-4933-8901-869d4ff1589c)

### Expected behavior

When the amount of ClickHouse data is small, the memory usage should be less than 3G. I ran the same version of ClickHouse on an X86_64 server and this did not happen.

### Screenshots

![image](https://github.com/user-attachments/assets/e71709a6-16df-4efd-8a20-93494136e23b)
![image](https://github.com/user-attachments/assets/afaff3b2-cf85-4aa1-8b1a-4c0dae7da94a)
![image](https://github.com/user-attachments/assets/8416544d-4ef5-4dda-9b7c-c72e8dc37b2e)

### Environment

```markdown
- OS: openEuler 20.03 (LTS-SP3)
- ARCH: arm64
- Runtime: Docker
```

**Comment by ruslandoga** [comment]
👋 @isFxh 

This might be better answered on https://github.com/clickhouse/clickhouse
