### ISSUE TITLE
Hostname dropdown limited to 25

### ISSUE THREAD

**Issue by SemaphoreOxalis** [plausible/analytics#4773]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

I select Hostname in the filter.
I know there is more than 25 entries but I can't see or select them.
I can find specific one by typing some characters but I need to know them...

### Expected behavior

I expect to be able to see every hostname.

### Screenshots

No need it's easy to check the DOM to see it.

### Environment

```markdown
- OS:Firefox
- Browser: Windows
- Browser Version:132
```

**Comment by metmarkosaric** [comment]
thanks for your feedback @SemaphoreOxalis! in the issues list here on GitHub, we only keep track of actual bugs with the product. what you are reporting here is more like a feature request so I'll close this. currently the filter menu works as we made it intentionally but expanding the list to show more entries by default can certainly be considered in the future. could you please add this idea to [our feedback board](https://feedback.plausible.io) where we keep track of feature ideas? thanks!
