### ISSUE TITLE
Framer > Navigation events are not triggered 

### ISSUE THREAD

**Issue by JanCizmar** [plausible/analytics#4822]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Plausible Cloud from plausible.io

### Describe the bug

Hello! 

Thanks for the great product. I am enjoying working with it a lot!

Few weeks before we migrated our webpage from Docusaurus to Framer, and suddenly it navigation events stopped to be reported leading to decrease in visits of all routed pages. 

Framer is based on React and it's pretty popular now, so I believe plausible should support it correctly.

According to this article, Plausible should support React navigation out of the box.

https://plausible.io/docs/spa-support

Our website is https://tolgee.io. You can reproduce it by navigating and checking the network tab.

### Expected behavior

Navigation event reporting requests should be visible in the network tab.

### Environment

```markdown
- OS: MacOS
- Browser: Chrome
- Browser Version: 130.0.6723.92
```

**Comment by metmarkosaric** [comment]
thanks for reaching out @JanCizmar and for the kind words! please do contact our support directly https://plausible.io/contact as that's the best place for questions about integration and set up. we keep the issues list on GitHub for actual bugs with the product only. thanks!
