### ISSUE TITLE
I cannot signup because of an error with the captcha

### ISSUE THREAD

**Issue by orballo** [plausible/analytics#487]
## Prerequisites
- [x] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report
**Describe the bug**
I cannot signup because of an error with the captcha

**Expected behavior**
I should be able to signup.

**Screenshots (If applicable)**
<img width="481" alt="Screen Shot 2020-12-17 at 12 10 11" src="https://user-images.githubusercontent.com/13615057/102480969-61874000-40a4-11eb-8704-9af9a8b19f10.png">
<img width="410" alt="Screen Shot 2020-12-17 at 12 10 19" src="https://user-images.githubusercontent.com/13615057/102480973-62b86d00-40a4-11eb-89f4-c193f0563e40.png">

**Environment (If applicable):**
 - OS: Mac
 - Browser:  Chrome 87.0.4280.88 and Firefox 83.0

**Comment by metmarkosaric** [comment]
thanks for reporting this @orballo! i get the same issue. must be something to do with the update we just released... we will look at it immediately!

**Comment by metmarkosaric** [comment]
this is now fixed! thanks again @orballo!
