### ISSUE TITLE
domain_unique_error

### ISSUE THREAD

**Issue by dandaniel5** [plausible/analytics#4875]
I cannot add my domain to CE because of the domain_unique_error. This is happening only if I register my site in the cloud beforehand.
The issue is located in the file site.ex lib/plausible on line 88.

**Comment by ruslandoga** [comment]
Related discussion: https://github.com/plausible/analytics/discussions/4874

**Comment by dandaniel5** [comment]
ok im in 2.1.4
error in site.ex lib/plausible line 75

**Comment by dandaniel5** [comment]
Ok, I don’t know how, but the domain was in the database and wasn’t showing in the interface.
I dropped the database, and it worked. Thanks for your patience.
