### ISSUE TITLE
Configuration to allow ignoring segments of path that represent a parameter (like an ID)

### ISSUE THREAD

**Issue by dbernheisel** [plausible/analytics#488]
I looked in issues and docs, and couldn't find a solution; I apologize if this is answered in already.

Is there a way a to group hits on paths that include a parameter in the path, such as an ID? It's not a URL parameter.

For example:
![image](https://user-images.githubusercontent.com/643967/102644138-4fea7a80-412e-11eb-82fa-198d4d0650a2.png)

These all represent a show page for different IDs of a sink resource, but I don't care about the IDs for this route. Is there a way I can group these together?

**Comment by metmarkosaric** [comment]
Thanks! Unfortunately not at this time. Closing this as there's already a thread with a similar feature request: #136
