### ISSUE TITLE
How to get most visited pages using Stats API?

### ISSUE THREAD

**Issue by KarelWintersky** [plausible/analytics#4892]
### Past Issues Searched

- [X] I have searched open and closed issues to make sure that the bug has not yet been reported

### Issue is a Bug Report

- [X] This is a bug report and not a feature request, nor asking for self-hosted support

### Using official Plausible Cloud hosting or self-hosting?

Self-hosting

### Describe the bug

How to get most visited pages using Stats API?

Request like
```
https://plausible.wintersky.ru/api/stats/imaginaria.ru/pages/?period=30d&date=2024-12-10&filters=[]&with_imported=true&detailed=true&order_by=[["visitors","desc"]]&limit=100&page=1
```
works from console, but request via API like:

```
curl -H 'authorization: Bearer <correct API>' 'https://plausible.wintersky.ru/api/stats/imaginaria.ru/pages/?period=30d&detailed=true&limit=100'
```
reports 
```
{"error":"Site does not exist or user does not have sufficient access."}
```

### Expected behavior

JSON answer

### Screenshots

![image](https://github.com/user-attachments/assets/14f203d1-5dbb-4671-a68c-f4491ec27919)

### Environment

```markdown
- OS:Linux
- Browser: curl
- Browser Version: curl 7.81.0 (x86_64-pc-linux-gnu)
```

**Comment by macobo** [comment]
Take a peek at the stats API docs: https://plausible.io/docs/stats-api

**Comment by KarelWintersky** [comment]
![изображение](https://github.com/user-attachments/assets/c52c6ebe-f780-40b4-a315-a413826b8443)
not found this term...  example, please!
