### ISSUE TITLE
"Start my free trial" button is hidden behind the footer on latest Safari

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/analytics#492]
"Wanted you to know that there is a small issue on the sign up page on latest Safari. The "Start my free trial" button is hidden behind the footer. You can see it but you can't click it."

<img width="799" alt="Screen Shot 2020-12-20 at 18 31 57" src="https://user-images.githubusercontent.com/34340819/102714972-882abe00-42d2-11eb-960a-65e72279ac29.png">

(report via email)

**Comment by metmarkosaric** [comment]
Another report of the register page being broken on Safari: https://twitter.com/stevediaconou/status/1346211360003280896

**Comment by metmarkosaric** [comment]
Another report about not being able to sign up from Safari:

"I'm trying to sign up for a new account on an ipad pro 12 inch. The register button is not working after I fill out step 1 of the form."

**Comment by ukutaht** [comment]
Fixed in e5ab45eb090f7cbc1f19af834a416c8329f6e012
