### ISSUE TITLE
UX Improvement - do not hide “cog” icon on mobile

### ISSUE THREAD

**Issue by kevquirk** [plausible/analytics#497]
Since the cog icon for website settings is a hover effect, it's almost impossible to get to settings from a mobile device.

Can the the hover effect be removed and just have the cog always there?

**Comment by Vigasaurus** [comment]
That's a great point! For now, if you just tap on the right spot it does work correctly - but getting it shown by default on devices without precise pointers would definitely be a good improvement.

**Comment by ukutaht** [comment]
Agreed :+1:
