### ISSUE TITLE
cannot add "." at the end of CNAME target in GoDaddy

### ISSUE THREAD

**Issue by daniel-karl** [plausible/analytics#50]
Godaddy doesn't allow me to add the `.` at the end of the CNAME target. It always takes it away automatically. Is there something you can do on your end to allow it without a `.`? Or would it work without the `.` already anyways? As of right now it doesn't load the script yet (20 minutes after setup).

**Comment by andreasvirkus** [comment]
@daniel-karl could you share the exact value or format of the CNAME you've entered in Godaddy? If you don't want to share the exact domain, then change the words, but keep the dot-notation exactly the same (e.g. `my.domain` would become `applie.pie`)

The `.` at the end of a CNAME is a best practise to indicate a [FQDN](https://en.wikipedia.org/wiki/Fully_qualified_domain_name), but it seems Godaddy no longer allows the trailing dot. It seems they now require you to enter only the left-hand record of your host field. See [this question](https://uk.godaddy.com/community/Managing-Domains/Trailing-period-is-cut-off-from-cname-value-Why/td-p/119966) in their community page for a more detailed answer by one of their staff members.

**Comment by metmarkosaric** [comment]
Sounds like a GoDaddy issue rather than a Plausible issue. Closing this now but please do reopen if there's something new. Thanks!

**Comment by metmarkosaric** [comment]
We just had another user with the same GoDaddy issue. The user ended up not including the last dot. It looks like GoDaddy automatically adds the last dot themselves so it all worked fine in the end. Just adding the info here in case someone else has the same issue. Skip adding the last dot if on GoDaddy and it should still work fine. Do let me know if there are issues. Thanks!
