### ISSUE TITLE
The chart canvas overflow

### ISSUE THREAD

**Issue by bluebeel** [plausible/analytics#501]
## Bug report
**Describe the bug**
The graph goes beyond the container and it is therefore impossible to see the X axis. 

**Expected behavior**
The graphic should be smaller and stay in the container or increase the size of the container so that there is no overflow.

**Screenshots (If applicable)**
On my Desktop screen 27"
![image](https://user-images.githubusercontent.com/13916626/102887987-30b65a80-4458-11eb-892e-c1189cefadb9.png)

On my Ipad Pro
![image](https://user-images.githubusercontent.com/13916626/102888195-91de2e00-4458-11eb-8c8d-a984948fbabb.png)

**Environment (If applicable):**
 - OS: Windows 10
 - Browser Chrome
 - Version Version 87.0.4280.88 (Build officiel) (64 bits)

**Comment by metmarkosaric** [comment]
Thanks @bluebeel! Did you by any chance manually select a larger font size in your browser? We've seen this issue before when having a large font size #124

**Comment by bluebeel** [comment]
Oh yes, I have a bigger font size set 🤦🏽‍♂️

**Comment by metmarkosaric** [comment]
ok thanks for the update! i'll close this thread as we have the other one open already.
