### ISSUE TITLE
TypeError: c is undefined / TypeError: Cannot read property 'properties' of undefined

### ISSUE THREAD

**Issue by velut** [plausible/analytics#506]
## Prerequisites
- [x] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report
**Describe the bug**

On plausible.io, when clicking on "Singapore" from the "Top Countries" modal or when visiting https://plausible.io/jsdocs.io?country=SGP an error page comes up with the error "TypeError: c is undefined" on Firefox and "TypeError: Cannot read property 'properties' of undefined" on Chrome.

**Expected behavior**
The page loads like for other countries.

**Environment (If applicable):**
 - OS: Ubuntu 19.10
 
 - Browser Firefox
 - Version 78.0.2
 
 - Browser Chrome
 - Version  87.0.4280.88

**Comment by metmarkosaric** [comment]
Same issue on our live demo! https://plausible.io/plausible.io?period=day&country=SGP

Thanks for reporting this @velut!

**Comment by Vigasaurus** [comment]
This seems to be because the DataMaps library doesn't have a provision for Singapore in its world map. Kinda weird, but should just need a fallback to prevent this error and nothing more.
