### ISSUE TITLE
Cannot revert from custom domain to hosted

### ISSUE THREAD

**Issue by daniel-karl** [plausible/analytics#51]
There's no button to revert the setting after having once configured a custom domain to server the JS file

**Comment by metmarkosaric** [comment]
You can now remove / manage your custom domain integration in the website settings of your Plausible account without any manual intervention and support needed from us.

![Eb2ZFk4WAAAnBYB](https://user-images.githubusercontent.com/34340819/87551107-24abbd00-c6b0-11ea-8b0f-8babf9620e75.png)
