### ISSUE TITLE
TimeRange "Month To Date" results in error

### ISSUE THREAD

**Issue by patschi** [plausible/analytics#518]
## Prerequisites
- [X] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report
**Describe the bug**
Steps:
1. Previously using Plausible container image based on October 2020
2. Now using custom-built docker image based on commit ef4af9249f8384aa13e747e4f6a9004d15d8705d (using official Dockerfile)
3. Now receiving following server-side error with Plausible when using TimeRange `Month to Date` (https://plausible/domain.tld?period=month)
```
{"message":"Server error","status":500}
```

In DevConsole in browser:
![image](https://user-images.githubusercontent.com/2029878/103160613-757f2000-47cf-11eb-9bdb-aec615974383.png)

**Expected behavior**
Not seeing such an error/crash.

**Environment (If applicable):**
Unrelated to browser as it's a server-side error. However, using latest Chrome on Windows.

**Comment by ukutaht** [comment]
Would need the output of `docker logs <plausible-container-name>` to debug this one.

My hunch is that your DB schema is out of date. You can run DB migrations with `docker run --env-file .env plausible/analytics db migrate` and see if it fixes it.

**Comment by patschi** [comment]
> Would need the output of `docker logs <plausible-container-name>` to debug this one.

Initially, before posting this issue, I opened the docker log output to get exactly that. But for my own surprise there were no logs related to this particular issue - beside warnings I opened #517 for. Also verified the same just right now.

> My hunch is that your DB schema is out of date.

That doesn't seem to be the case.

1. During the startup the database migrations are always run:
```
$ docker-compose logs -f plausible
[...]
plausible_1            | Loading plausible..
plausible_1            | Starting dependencies..
plausible_1            | Starting repos..
plausible_1            | Running migrations for Elixir.Plausible.Repo
plausible_1            | Running migrations for Elixir.Plausible.ClickhouseRepo
plausible_1            | Migrations successful!
```

2. Also when manually running the migrate script:
```
$ docker-compose exec plausible sh migrate.sh
Loading plausible..
Starting dependencies..
Starting repos..
Running migrations for Elixir.Plausible.Repo
Running migrations for Elixir.Plausible.ClickhouseRepo
Migrations successful!
```

So the database seems to be up-to-date. Also, I can save the spike notification email, so the database field for the email address seems to be existent in the database, leading to the assumption that this specific migration also run through just fine.

**Comment by ukutaht** [comment]
Was a problem with different Elixir version in dev vs prod. Thanks @patschi
