### ISSUE TITLE
Outbound URL doesn't display on mobile portrait orientation

### ISSUE THREAD

**Issue by oscarbaruffa** [plausible/analytics#534]
### Precheck

Please note that this tracker is only for bugs. Do not use the issue tracker for help, support or feature requests. 

[Our docs](https://docs.plausible.io/) are a great place for most answers, but if you can’t find your answer there, you can [contact us](https://plausible.io/contact). 

Have a feature request? Please search the ideas [on our forum](https://github.com/plausible/analytics/discussions) to make sure that the feature has not yet been requested. If you cannot find what you had in mind, please [submit your feature request here](https://github.com/plausible/analytics/discussions/new). 

Have an issue with your self-hosted install? You can ask in [our community forum](https://plausible.discourse.group/). Thanks!

## Prerequisites
- [x] I have searched open and closed issues to make sure that the bug has not yet been reported.Not closed issues

## Bug report
**Describe the bug**
For the outbound link click data, the URLs don't display on portrait mode (see screenshot).

**Expected behavior**
I expected to see the URLs, or be able to scroll the table left or right, but neither of those happened.

**Screenshots (If applicable)**
See attached.
![Screenshot_20201230_070635_com android chrome](https://user-images.githubusercontent.com/16580713/103333334-f0656680-4a6d-11eb-9d31-3e28d8625386.jpg)

**Environment (If applicable):**
 - OS: Android (9 I think)
 - Browser: Chrome 
 - Version: near latest

**Comment by gavinmn** [comment]
Following this up that this is also an issue on iOS 14 + Safari. Both when expanded and non expanded.

![IMG_2437308F1464-1](https://user-images.githubusercontent.com/59900904/104968105-f4bcd980-59b2-11eb-831e-673750fdcf8e.jpeg)
![IMG_4A022AD2E8F2-1](https://user-images.githubusercontent.com/59900904/104968111-f6869d00-59b2-11eb-849b-2e69e495dc73.jpeg)

**Comment by ukutaht** [comment]
Thanks for reporting! Closing this one in favour of #972
