### ISSUE TITLE
Third-party authentication.

### ISSUE THREAD

**Issue by mlukasik-dev** [plausible/analytics#540]
Are there any plans to add third-party authentication in the future.
It can be useful if someone wanted to develop custom dashboard or custom server application, which uses plausible analytics (#95 , #150 )
Can help with developing server-side api clients in node.js and Go.

**Comment by metmarkosaric** [comment]
Thanks @mlukasik-dev! We're keeping Issues for bug reports only and Discussions for feature requests so I'm going to close this. There's no current short term plan to add any third party authentication but there's a similar request already that you can subscribe to and get updates on our progress: https://github.com/plausible/analytics/discussions/383
