### ISSUE TITLE
Feature request: Download daily raw statistics from plausible.io

### ISSUE THREAD

**Issue by lgrammel** [plausible/analytics#541]
Hi! I've created a plausible account and it works great 👍🏻 

For some of my analytics use cases, I need to analyze the data in more detail. Would it be possible to add a feature to export the raw data (query e.g. by day)?

By raw data, I mean a table with the following column: page, session, referrer, options (and similar for events), timestamp.

My goal is to do a more detailed analysis of the visitor flow and conversion rates. E.g. to answer questions like:

- How did visitors who landed on page X convert to goal A and then to goal B?
- How did visitors who landed on page X that came from source Q convert to goal A and then to goal B?
- On which pages did visitors who converted goal A land?
- What are my best performing sources for visitors who landed on page X and converted to goal A?

**Comment by metmarkosaric** [comment]
thanks @lgrammel! export is already on the roadmap. take a look at this thread please: https://github.com/plausible/analytics/discussions/211

could you please share your ideas in that thread as we keep "Issues" for issues only and not for feature requests? I'll close this now.

**Comment by lgrammel** [comment]
Sure, thanks :) didn't know about the other thread
