### ISSUE TITLE
Connecting to Google Search Console shows empty property list

### ISSUE THREAD

**Issue by Caroga** [plausible/analytics#555]
## Prerequisites
- [X] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report
**Describe the bug**
After connecting with the google search console the list of properties stays empty.

**Expected behavior**
Properties are provided and selectable.

**Screenshots (If applicable)**
![image](https://user-images.githubusercontent.com/4005934/103762175-211e4080-5018-11eb-895b-a1208b70cd0c.png)

**Environment (If applicable):**
 - OS: docker, ubuntu
 - Browser: Chrome on linux
 - Version: Version 87.0.4280.88 (Official Build) (64-bit)

**Comment by metmarkosaric** [comment]
Thanks for this @Caroga! As you've already submitted the same question in the self-hosting forum, I'll close this in favour of that: https://github.com/plausible/analytics/discussions/553

**Comment by Caroga** [comment]
Yes sorry for that, I did not know if this was an issue or a discussion. I figured: why not both ? 😄
