### ISSUE TITLE
Using HOSTED SOLUTION to track multiple subdomains

### ISSUE THREAD

**Issue by stccorp** [plausible/analytics#572]
Hello,
I would like to use the paid version.  I need to track 2 subdomains. How can I configure subdomain1.mydomain.com and subdomain2.mydomain.com so I can switch on the dashboard and see their stats independently?

Thank you

**Comment by metmarkosaric** [comment]
Hi @stccorp. You can add as many sites/subdomains as you want to the same Plausible account. And they'll all be separate with their own independent stats dashboard. Log in to your account and on [the first page you see](https://plausible.io/sites) click on the "Add a website" button to add another website.

If you would like to track a subdomain then please include the subdomain in the domain field when registering the site. For example, if your subdomain is https://subdomain1.mydomain.com then the part to enter in the "Domain" field is subdomain1.mydomain.com.

**Comment by stccorp** [comment]
Thank you for the information.  I didnt se THE BIG BUTTON in front of me.
One last question. Will I need to create a custom domain domain for every site, or by just creating one  stats.mydomain.com
by some magic voodoo plausible will detect the right subdomain?

Thank you

**Comment by metmarkosaric** [comment]
You should be able to use the same custom subdomain for them all. Make sure that the data-domain attribute in the snippet has the correct subdomain though. Do let me know if this works please.

**Comment by stccorp** [comment]
It seems to work.  Thank you

**Comment by stccorp** [comment]
do you work for plausible?

**Comment by metmarkosaric** [comment]
> do you work for plausible?

yes

**Comment by stccorp** [comment]
cool,  Just made a suggestion on the forum.  I think there should be a link above Settings, that take you to the main dashboard(where the Create Website Button resides).  At least I have never seen the logo use to go to part of the application. I assume the logo always take you to the main website of the product. 
![brave_2021-01-09_14-03-50](https://user-images.githubusercontent.com/8180135/104116702-059d8900-52e9-11eb-9066-4e6153d8c9a2.png)

**Comment by stccorp** [comment]
Or maybe better. like this , having an "All"
![brave_2021-01-10_02-15-56](https://user-images.githubusercontent.com/8180135/104116822-17cbf700-52ea-11eb-9c22-f18950235adb.png)
 Link, where all the sites are.

**Comment by metmarkosaric** [comment]
thanks for the feedback! it's there in the discussions now so we'll consider it.
