### ISSUE TITLE
Ability to sign out on https://plausible.io/activate

### ISSUE THREAD

**Issue by ACPK** [plausible/analytics#581]
After signing up, a user is redirected to https://plausible.io/activate. If the user makes a typo in their email (see that I misspelled Gmail.com below), they won't get the confirmation email and thus are unable to proceed.

As such, they may want to finish signing up with their correct email. Without the ability to change the email the confirmation pin is going to, they'll need to clear their cookies so they can get back to https://plausible.io/register.

**Possible Solution:**  

1. Add the text that says:

"Need to change the email? Click here to create a new registration."

2. The link goes to an endpoint that (a) deletes the user's registration and (b) redirects them to the register page.

<img width="793" alt="Screen Shot 2021-01-11 at 1 08 47 PM" src="https://user-images.githubusercontent.com/2019893/104221190-93bf5f80-540e-11eb-9b8d-a05204af9b74.png">

**Comment by ukutaht** [comment]
Pushing a fix to this:

![Screenshot from 2021-04-01 10-44-00@2x](https://user-images.githubusercontent.com/3731516/113260701-40ef9880-92d7-11eb-95de-1471deee776e.png)
