### ISSUE TITLE
Able to add blank email addresses to "Weekly report recipients"

### ISSUE THREAD

**Issue by ACPK** [plausible/analytics#583]
I am able to click "Add recipient" on the "Email reports" admin form without adding an email address.

When I tried deleting the "blank email" recipient, I am redirected to a 404 page as shown in the screenshot below.

On a side note, the 404 response prevents the error from being caught (i.e., the application didn't notify Sentry and AppSignal).

Last, I haven't tested it but I don't know if the cron jobs try to send the email to a recipient with a blank email.

**https://plausible.io/plausible.io/settings/email-reports**

<img width="980" alt="Screen Shot 2021-01-11 at 3 14 54 PM" src="https://user-images.githubusercontent.com/2019893/104233931-b2c6ed00-5420-11eb-844b-a1611614ddf8.png">

**Page when I click the delete button next to the blank recipient:**

<img width="824" alt="Screen Shot 2021-01-11 at 3 15 06 PM" src="https://user-images.githubusercontent.com/2019893/104233940-b5c1dd80-5420-11eb-93ed-e28db420e2d9.png">

**Comment by metmarkosaric** [comment]
thanks @ACPK! got similar report [on Twitter](https://twitter.com/carl_chenet/status/1351213562006556673):

"when you add recipient for email monthly reports, it seems trailing spaces are not sanitized for the email field. Also you can also add an empty email, which is confusing."
