### ISSUE TITLE
Copyright date is hardcoded.

### ISSUE THREAD

**Issue by ACPK** [plausible/analytics#584]
This is a minor bug (if you can call it that) but the copyright date is hardcoded in a number of places.

<img width="802" alt="Screen Shot 2021-01-11 at 3 40 32 PM" src="https://user-images.githubusercontent.com/2019893/104235707-5913f200-5423-11eb-96c9-c5a77108fdb8.png">

<img width="1075" alt="Screen Shot 2021-01-11 at 3 30 20 PM" src="https://user-images.githubusercontent.com/2019893/104234892-1dc4f380-5422-11eb-896a-3ba641ff2f28.png">

**Comment by srameshr** [comment]
Fixed it. Sent a PR
