### ISSUE TITLE
Cannot get back to Plausible.io's home page after logging in even if I log out.

### ISSUE THREAD

**Issue by ACPK** [plausible/analytics#585]
I signed into my Plausible.io account and wanted to get back to your extremely informative home page :)

Since the Analytics application doesn't use a sub-domain, I thought logging out may help me get back to the marketing website's home page. However, https://plausible.io redirects me to https://plausible.io/login automatically.

**Comment by Vigasaurus** [comment]
Hmm, normally logging out from the dashboard should definitely redirect you back to the homepage and prevent the redirection. (And it did for me in my short testing, just now). Did you log out normally from the dashboard drop-down?

**Comment by metmarkosaric** [comment]
Logout in the menu works all fine for me too. Leads me back to the home page

**Comment by ACPK** [comment]
@Vigasaurus @metmarkosaric 

Here is a screen recording of my experience.

https://www.loom.com/share/161a0d7b388e4672915479bc481d0065

I'm using Safari Private Window (Version 14.0.2 -16610.3.7.1.9)

**Comment by metmarkosaric** [comment]
Thanks for sharing! Same problem when you try without the private window?

**Comment by ACPK** [comment]
Not a priority as I only experienced this issue in Safari Private Window. It worked fine for me today in Safari when not using a private window in addition to Google Chrome (both regular and incognito).  I'm curious though what the hiccup is when using Safari Private Window.

**Comment by ACPK** [comment]
@metmarkosaric  - Would you mind seeing if you're able to access the Home Screen in Safari after "logging out"? I'm unable to again.

**Comment by metmarkosaric** [comment]
hi @ACPK! I just tested on Firefox and everything seems to work fine. Don't have Safari but perhaps someone else can confirm that.

**Comment by Vigasaurus** [comment]
@ACPK I just tried it on Safari 12 and 13 on Mojave (in a VM, but still) and it worked as intended - are you using any Safari extensions by chance?

**Comment by ACPK** [comment]
No, a brand new computer actually.
