### ISSUE TITLE
Public dashboards and the API can be reached over unencrypted http

### ISSUE THREAD

**Issue by klaemo** [plausible/analytics#592]
## Prerequisites
- [x] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report
**Describe the bug**
Public dashboards can be reached over http and all subsequent requests triggered by the page are unencrypted. This includes requests to the API. Neither `http` -> `https` redirects nor `HSTS` are in place.

```sh
❯ curl -v http://plausible.io/dividi.app
*   Trying 2a05:d014:275:cb00:29f:95e8:f0de:2bdd...
* TCP_NODELAY set
* Connected to plausible.io (2a05:d014:275:cb00:29f:95e8:f0de:2bdd) port 80 (#0)
> GET /dividi.app HTTP/1.1
> Host: plausible.io
> User-Agent: curl/7.64.1
> Accept: */*
> 
< HTTP/1.1 200 OK
< Access-Control-Allow-Credentials: true
< Access-Control-Allow-Origin: *
< Access-Control-Expose-Headers: 
< Cache-Control: max-age=0, private, must-revalidate
< Content-Length: 9198
< Content-Type: text/html; charset=utf-8
< Cross-Origin-Window-Policy: deny
< Date: Wed, 13 Jan 2021 09:10:54 GMT
< Server: Netlify
< X-Content-Type-Options: nosniff
< X-Download-Options: noopen
< X-Frame-Options: SAMEORIGIN
< X-Permitted-Cross-Domain-Policies: none
< X-Request-Id: Flm_pHUebL1BPKgOADvB
< X-Robots-Tag: noindex
< X-Xss-Protection: 1; mode=block
< Age: 0
< Connection: keep-alive
< X-NF-Request-ID: 511aa12d-059b-4b7d-b29c-9e00441ae54c-78427069
```

**Expected behavior**
- requests to `http` get redirected to `https`
- `HSTS` is enabled for `plausible.io`

**Screenshots**
<img width="1552" alt="image" src="https://user-images.githubusercontent.com/778624/104430303-c9875400-5586-11eb-8929-8feefe7565c3.png">

**Environment (If applicable):**
 - OS: macOS
 - Browser Firefox
 - Version 85.0b8

...but can also be observed with curl.

**Comment by ukutaht** [comment]
Thanks, I wasn't aware of this issue. Will fix asap.

**Comment by ukutaht** [comment]
I've now set up the redirect and HSTS header. Thanks for bringing this to my attention @klaemo !
