### ISSUE TITLE
After Website has been deleted it's not possible to add it again

### ISSUE THREAD

**Issue by wolfganghofer** [plausible/analytics#598]
I deleted a website and then tried adding it again.
The error message says: "has already been taken".
OS: macOS
Browser: Firefox & Chrome
Cache cleared

![Screenshot](https://user-images.githubusercontent.com/77409222/104496407-404d3d00-55d9-11eb-9862-c2629defa4c8.jpg)

**Comment by metmarkosaric** [comment]
thanks for reporting this @wolfganghofer! we'll take a look!

**Comment by wolfganghofer** [comment]
Hi Marko,

did you already find the time to take a look at the problem?
I like plausible and when I can add my domain again, I will upgrade.

Thanks!

Wolfgang
_


Wolfgang Hofer
Uferstraße 92
6020 Innsbruck
UID: ATU45685708
TEL: +43 699 1966 2809
URL: www.social-webwork.at

Verlässlichkeit + Kundenservice + Integrität

Am 13.01.2021 um 19:58 schrieb Marko Saric <notifications@github.com>:


thanks for reporting this @wolfganghofer <https://github.com/wolfganghofer>! we'll take a look!

**Comment by metmarkosaric** [comment]
sorry for the delay @wolfganghofer! it's a bit of a manual process so please give us a bit more time. hopefully we'll be able to deal with this tomorrow and you'll then be able to add the domain again. thanks for your patience!

**Comment by ukutaht** [comment]
Hey @wolfganghofer I've deleted your site from our database. Thanks for your patience :)

**Comment by wolfganghofer** [comment]
Thank you very much!

**Comment by windswept321** [comment]
I have the same issue after deleting and reinstalling my docker containers for my site trigan.org.
Can you help me with this, please
<img width="1135" alt="Screenshot 2022-02-16 at 17 12 42" src="https://user-images.githubusercontent.com/10297044/154319217-1b925ce2-1267-45d7-bb2a-7d73c6f4be0c.png">
?
