### ISSUE TITLE
Is it possible to use Plausible without javascript?

### ISSUE THREAD

**Issue by A1CY0N** [plausible/analytics#604]
Currently it's not possible to track users who don't use javascript. 

Would it be possible to add as in [shynet](https://github.com/milesmcc/shynet) and [google analytics](https://developers.google.com/analytics/resources/concepts/gaConceptsTrackingOverview) a transparent tracking pixel of 1px by 1px?

It would be an awesome improvement in my opinion.

**Comment by metmarkosaric** [comment]
Thanks for the feedback @A1CY0N! There's another thread for this feature request so I'm going to close this one. Please check: https://github.com/plausible/analytics/discussions/388
