### ISSUE TITLE
Adding a site with space in the name creates an un-deletable site

### ISSUE THREAD

**Issue by hyperknot** [plausible/analytics#608]
## Prerequisites
- [x] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report
**Describe the bug**
Add a site with a space in it's name, like "my domain". It'll break the app, meaning that this new site cannot be opened nor deleted.

It **is** possible to open the site page by manually replacing space with `%20`, but it is not possible to delete the item even from there.

**Expected behavior**
Adding an item should slugify it.

**Environment (If applicable):**
docker latest

**Comment by Vigasaurus** [comment]
This was fixed in d71e40f16f573611b6b1bdba9fb3acefc5757214 and plausible/analytics#427 - and subsequently is fixed in [v1.2](https://github.com/plausible/analytics/releases/tag/v1.2-rc.1), which is not yet fully released for self-hosters
