### ISSUE TITLE
500 internal server error when deleting site

### ISSUE THREAD

**Issue by srameshr** [plausible/analytics#609]
### Precheck

Please note that this tracker is only for bugs. Do not use the issue tracker for help, support or feature requests. 

[Our docs](https://docs.plausible.io/) are a great place for most answers, but if you can’t find your answer there, you can [contact us](https://plausible.io/contact). 

Have a feature request? Please search the ideas [on our forum](https://github.com/plausible/analytics/discussions) to make sure that the feature has not yet been requested. If you cannot find what you had in mind, please [submit your feature request here](https://github.com/plausible/analytics/discussions/new). 

Have an issue with your self-hosted install? You can ask in [our community forum](https://plausible.discourse.group/). Thanks!

## Prerequisites
- [ x] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report
**Describe the bug**
Under the danger zone inside settings, deleting site traffic data and then removing the site causes 500 internal server error.

**Expected behavior**
Should delete the site.

**Screenshots (If applicable)**
```
constraint error when attempting to delete struct:
    * spike_notifications_site_id_fkey (foreign_key_constraint)

If you would like to stop this constraint violation from raising an
exception and instead add it as an error to your changeset, please
call `foreign_key_constraint/3` on your changeset with the constraint
`:name` as an option.

if site.google_auth do
      Repo.delete!(site.google_auth)
    end
    Repo.delete!(site)
    Plausible.ClickhouseRepo.clear_stats_for(site.domain)
    conn
    |> put_flash(:success, "Site deleted succesfully along with all pageviews")
    |> redirect(to: "/sites")
```

**Environment (If applicable):**
 - OS: [e.g. macos] Macos
 - Browser [e.g. safari, firefox] Chrome
 - Version [e.g. 78]: Master & Stable both

**Comment by metmarkosaric** [comment]
thanks @srameshr! just got another report about the same error on the cloud version. we'll take a look.

**Comment by ukutaht** [comment]
Thanks for letting us know. It's been fixed on our cloud instance, I also released a new candidate version that has the same fix: https://github.com/plausible/analytics/releases/tag/v1.2-rc.1
