### ISSUE TITLE
"Click to enable weekly email report" button should link to the correct URL

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/analytics#614]
"I just noticed that the "Click to enable weekly email report" button takes you to ```https://plausible.io/XSITEX/settings/general#email-reports``` instead of the actual link: ```https://plausible.io/XSITEX/settings/email-reports```"

(feedback via email)

**Comment by Vigasaurus** [comment]
The same issue exists for the placeholder for Google Search Integration when the connection isn't set up, and as the callback url from the Search OAuth page.

**Comment by metmarkosaric** [comment]
thanks @Vigasaurus!
