### ISSUE TITLE
Feature Request: LDAP Authentication for selfhosted instance

### ISSUE THREAD

**Issue by Duponin** [plausible/analytics#631]
Hi,

I would like to self-host a Plausible instance for me and a few people, but to create another account is an annoying chore.
Sure it's eased with Password managers but still annoying.

Anyway, I'd like to be able to plug an LDAP server in to authenticate already existing users (from the LDAP directory).

I have Elixir and Phoenix knowledge, so I'm willing to try to implement it.
But I'd gladly take advices and/or inputs to do it well. (and if it would merge/rebase in upstream)

Duponin

**Comment by ukutaht** [comment]
I think we can support different auth methods on the `Plug` layer with different plugins essentially. Happy to merge this upstream if you decide to build it!
