### ISSUE TITLE
undefined is not an object (evaluating 'this.observer.unobserve')

### ISSUE THREAD

**Issue by ukutaht** [plausible/analytics#639]
### Precheck

More information: https://github.com/plausible/analytics/discussions/605#discussioncomment-298672

**Comment by metmarkosaric** [comment]
this may be happening again. got a report [on twitter](https://twitter.com/lsocrate/status/1471880306693218313):

"I’m getting this error when trying to open a website dashboard on mobile Safari (iOS 15.2). It works fine on my computer"

![FG0rVjcX0AomwuM](https://user-images.githubusercontent.com/34340819/146599577-d9eeb470-5bef-4d89-93b5-4a7f5f12e9fd.jpeg)

**Comment by mikeycannon** [comment]
Hi there this is happening for me on mobile since creating my account, any ideas on how to clear it? ![image](https://user-images.githubusercontent.com/8246222/152703598-ccb62d24-3250-4654-a4ca-dfb6fab9d07e.png)

**Comment by ukutaht** [comment]
Thanks for reporting. Attempting another fix. @mikeycannon can you please test again and let me know if it's resolved for you?

**Comment by benjaminwittorf** [comment]
I also/still encounter this error on iOS 15.3, also ever since creating an account two weeks ago.

**Comment by benjaminwittorf** [comment]
![image](https://user-images.githubusercontent.com/93603146/153072138-d1ad0250-b20c-48eb-b3ff-496b2c169001.png)

New error text! Both on being logged in/out.

**Comment by ukutaht** [comment]
Thanks! Looks like we need a polyfill for InteractionObserver. I'll see what I can do

**Comment by ukutaht** [comment]
OK. Polyfill for this is something like 30kb. I don't think it's worth it for what it does.

Given that the `InteractionObserver` is used just for lazy loading and sticky header, I think the better solution is to disable these 'features' when the observer is unavailable. I've added a fallback now, can you please test https://staging.plausible.io/plausible.io again?

**Comment by benjaminwittorf** [comment]
![image](https://user-images.githubusercontent.com/93603146/153354532-3118eb2b-e520-4e97-8ea4-f1e2ca3cb791.png)

That works!

**Comment by ukutaht** [comment]
great! I'll deploy this feature to the live environment soon.
