### ISSUE TITLE
Firefox's "Do Not Track" feature is ignored

### ISSUE THREAD

**Issue by xuhdev** [plausible/analytics#644]
## Prerequisites
- [x] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report
**Describe the bug**
Set [Firefox's "Do Not Track" feature](https://support.mozilla.org/en-US/kb/how-do-i-turn-do-not-track-feature) to "always". Visiting a page uses plausible. The visit is still tracked. (Tested on https://plausible.io)

**Expected behavior**
The visit should not be tracked.

**Environment (If applicable):**
 - OS: Linux
 - Browser Firefox
 - Version 84.0.2

**Comment by Vigasaurus** [comment]
That's not exactly how DNT is intended to work; largely, its meaning is to say that users should not be tracked or have any data retained on them that isn't inherently privacy friendly or anonymized fully.

> It also includes exceptions that respect the ordinary functionality of a site, that allow measures for security purposes and prevent fraud, and **allow data analysis techniques that protect the anonymity of the users**.

https://www.eff.org/issues/do-not-track

Plausible does fall under the last point there in most definitions, given the strict protection/lack of retention of user data. 
 https://plausible.io/privacy-focused-web-analytics

There could of course be good reason for Plausible to adhere to a stricter set of DNT rules, but I'd argue that wouldn't be fully intended or required behavior as per DNT standards.
