### ISSUE TITLE
Add deleted domain again

### ISSUE THREAD

**Issue by laubw0lf** [plausible/analytics#650]
When I try to re-add my domain _kioku.eskool.de_, it just says that the page has already been taken. It seems like a domain cannot be added once it has been deleted from plausible.io. It would be great if you could help me out.

Bastian

**Comment by ukutaht** [comment]
Sorry about this Bastian. I've deleted your site completely so you can add it again. We are aware of the issue with deletion and are workign to fix it.

**Comment by mr-sonj** [comment]
I am also facing similar issue. Although I use self-hosted. My domain name is [smailpro.com](https://smailpro.com). Can you help me delete it?

**Comment by ukutaht** [comment]
Sure. Log into your Postgresql database and run `DELETE FROM sites WHERE domain='smailpro.com'`
