### ISSUE TITLE
invalid_grant error when fetching Google Search Console domains -- whenever you setup several websites

### ISSUE THREAD

**Issue by ameshkov** [plausible/analytics#663]
### Precheck

This might be important that I am testing the self-hosted version, but it looks like this bug **should** happen with the SAAS version as well.

## Prerequisites
- [X] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report

1. Add two different websites to Plausible
2. Setup Google Search Console integration for the first of them - everything works great
3. Setup integration for the second one - everything seems to be okay as well
4. Check the first one again - you'll see the "invalid_grant" error there

**Expected behavior**
Integration works for both websites

**Screenshots (If applicable)**
![image](https://user-images.githubusercontent.com/5947035/106303527-485cdc00-626b-11eb-9a9b-f579e72bb289.png)

**Comment by metmarkosaric** [comment]
thanks for reporting this @ameshkov! i tested it on the cloud but there it seems to work all fine. we'll check if we can see this on the self-hosted version.

by the way as i see you work for Adguard: any chance we can get you to whitelist Plausible? you use Plausible yourself as I assume you believe that this is the better way of doing web analytics. not only as third-party but we've had couple of reports from people using your DNS that you're blocking our website too when it's first party so they for instance cannot read our blog without disabling your DNS. would be good if you can help out with this. thanks!

**Comment by ameshkov** [comment]
hi @metmarkosaric!

Note that I am using the same Google account to create integration with two different domains. Have you also used the same acc?

Regarding AdGuard, as I recall, in our tracking protection list we use a more granular approach and block just the JS file (so it's blocked even on our own website) and don't block the whole domain. Probably the rule comes from EasyPrivacy, I'll see if we can avoid blocking your website in AG DNS.

However, if you want a really viable way to avoid content blockers doing their job, please consider extending the API to allow importing website access logs. You see, the root cause for blocking is that there's an arbitrary JS loaded from a third-party. I understand that you're only sending a limited amount of data, but this can be changed any time, this is a good enough reason for people to be concerned about it.

Using a logs-based analytics system completely eliminates that possibility, there're no external trackers, site owners have their stats, everyone is happy. At first glance, it'd be enough simply to extend [create_event](https://github.com/plausible/analytics/blob/master/lib/plausible_web/controllers/api/external_controller.ex#L67) and add an optional `timestamp` parameter. `screen_width` can be made optional and replaced with `User-Agent` parsing. I thought about pull requesting it myself, but I am not quite sure about how it aligns with your plans.

**Comment by metmarkosaric** [comment]
Thanks for the update! I tried with the same account and it works fine. I'm only testing the cloud version so not sure if there's something else on the self-hosted.

we have no current plans to import server logs as they're not that useful with mostly bot traffic so we would need to find a way to make those stats accurate and insightful first. we keep the option open for the future and there's [a thread already](https://github.com/plausible/analytics/discussions/234). 

we're an open source and transparent project so you'll easily see if we make some evil moves and can block us any time we do something you think is not ethical. but obviously it's your decision. just wanted to mention it as it's not the best user experience for your users to have normal websites blocked and then they have to reach out to us asking why our server is down.

**Comment by ameshkov** [comment]
> Thanks for the update! I tried with the same account and it works fine. I'm only testing the cloud version so not sure if there's something else on the self-hosted.

Are there any logs I could look into and try to figure it out myself?

> we have no current plans to import server logs as they're not that useful with mostly bot traffic so we would need to find a way to make those stats accurate and insightful first. we keep the option open for the future and there's a thread already.

Thank you, subscribed there! So the problem is just filtering out the bot traffic? We could experiment on our side with different ways of doing it and share the result.

> just wanted to mention it as it's not the best user experience for your users to have normal websites blocked

Don't worry, we'll definitely address this in AG DNS. DNS is supposed to be casual-user friendly so we avoid blocking whole websites.

**Comment by metmarkosaric** [comment]
> Are there any logs I could look into and try to figure it out myself?

I'm not aware of logs for self-hosting so someone else might be able to help with that part.

> Thank you, subscribed there! So the problem is just filtering out the bot traffic? We could experiment on our side with different ways of doing it and share the result.

Some of the more interesting stats won't be able to be counted using server logs but the main issue really is bot traffic. You can read a bit more here on the comparison we did between Plausible and server logs accuracy: https://plausible.io/blog/server-log-analysis

**Comment by ukutaht** [comment]
Replying to @ameshkov 

> So the problem is just filtering out the bot traffic?

That's the biggest one, yes. We haven't found a server log tool that filters out bots anywhere close to as well as JS-based analytics tools do. I'm very curious about potential solutions in this space.

The second question is getting server logs into our system. I understand and agree that we could easily augment our /api/event endpoint to accept server logs. But how is a non-developer wordpress user supposed to integrate with this? Or even a developer running on Netlify? To make it truly usable we need countless numbers of different integrations for all potential tech/ops stacks.

A javascript-based tracker is much easier to integrate with since the client-side web is fairly standardized. Even then, getting people to install the script is absolutely the most difficult part in getting them to use the tool.

I fear that even if we support some amazing ways to direct your server logs to Plausible, it will be a very niche feature used by <5% of our userbase. Our goal is to remove Google Analytics from as many sites as possible so it makes sense for us to focus on a solution that's convenient for the majority of our audience who is non-technical.

I'm not against log analysis or anything. Technically speaking it's preferable because the end-user doesn't need to load anything and you still get basic stats. If the bot issue can be solved I would happily build some integrations with backend tooling.

But I also believe that the JS-based tracker is more effective in getting people off GA which is our mission.

**Comment by ameshkov** [comment]
@ukutaht oh, I am not implying that you should choose logs over JS, this is definitely just a niche feature.

Also, from reading the thread that Marko linked it actually seems that this is already possible, we'll just have the timestamp a little bit out of sync, this is not that problematic. Anyways, thank you for the answers!

**Comment by ukutaht** [comment]
Sure, thanks for yout input @ameshkov.

BTW you can check logs with `docker logs <name-of-your-container`. Usually the container name is `hosting_plausible_1` or something like that, you can find it with `docker ps`.
