### ISSUE TITLE
EXPOSE 8000 missing in Dockerfile

### ISSUE THREAD

**Issue by p4block** [plausible/analytics#666]
One should not rely on the user to do a port mapping in order to be able to access the service, dockerized applications should use EXPOSE to list the ports they listen for connections at.

This causes issues when running under a reverse proxy such as Traefik. Without the "useless" port mapping to the host it is impossible for it to detect the service, as it has no exposed ports.

Sorry for no PR but I'm not an expert in the container build process, and in order to leverage caching etc I don't know the best place for the EXPOSE would be.

**Comment by ukutaht** [comment]
@RealOrangeOne had a PR for this...

I have 0 experience with Traefik and never had a problem with configuring the exposed port. If we always expose port 8000 then it would make sense to disable the `PORT` configuration option to Plausible, don't you think? I can see a problem where the web server in the container is running on one port but another one has been exposed by the Dockerfile itself.

**Comment by RealOrangeOne** [comment]
I do indeed https://github.com/plausible/analytics/pull/237, although it's closed. 

@p4block the workaround for Traefik is very simple https://github.com/RealOrangeOne/infrastructure/blob/master/ansible/roles/plausible/files/docker-compose.yml#L17

Deprecating `$PORT` would be a way to standardise around this. Alternatively, leave it running, and it's up to whoever wants to change it to update their docker runtime. I suspect people running Plausible outside of Docker would still benefit from having the port configurable, whether it's useful inside Docker or not.

**Comment by ukutaht** [comment]
I think you're right @RealOrangeOne. Sorry for not accepting your earlier PR.

It just doesn't feel right for some reason to hardcode one port and leave the other one configurable. But I guess it's just a feeling thing that doesn't have any strong arguments for why it's wrong. Realistically there shouldn't be any issues.

I would merge a PR on this now. I guess it would also remove the need for this? https://github.com/plausible/hosting/blob/master/docker-compose.yml#L32

**Comment by RealOrangeOne** [comment]
No that would still be necessary. That binds it to the machine's port 8000. `EXPOSE` is more of a hint to things which integrate with Docker.

It's weird, yes, but not an issue. Both are still configurable, this just enables the default to work correctly. Changing it does require changes in multiple places, but it requires that regardless.

I'll open another PR shortly for review / discussion.
