### ISSUE TITLE
Error: (ErlangError) Erlang error: :closed

### ISSUE THREAD

**Issue by ACPK** [plausible/analytics#678]
I have received the error `(ErlangError) Erlang error: :closed` 72 times in Sentry and 77 times in App Signal. I have had the site running for three weeks now but have not started using it (i.e., haven't sent any analytics data except for a few tests).

The website's log shows the message below:

      Feb 04 05:58:15 test-site-prod app/postgres.9 [DATABASE] [7961-1]  sql_error_code = 00000 LOG:  checkpoint starting: time
      Feb 04 05:58:16 test-site-prod heroku/web.1 source=web.1 dyno=heroku.197060244.09b00976-3046-4ea9-b3bc-d0a1fa26de0c sample#load_avg_1m=0.05 sample#load_avg_5m=0.25 sample#load_avg_15m=0.33
      Feb 04 05:58:16 test-site-prod heroku/web.1 source=web.1 dyno=heroku.197060244.09b00976-3046-4ea9-b3bc-d0a1fa26de0c sample#memory_total=113.81MB sample#memory_rss=112.27MB sample#memory_cache=1.54MB sample#memory_swap=0.00MB sample#memory_pgpgin=140705pages sample#memory_pgpgout=114125pages sample#memory_quota=512.00MB
      Feb 04 05:58:17 test-site-prod app/postgres.9 [DATABASE] [7962-1]  sql_error_code = 00000 LOG:  checkpoint complete: wrote 22 buffers (0.0%); 0 WAL file(s) added, 0 removed, 10 recycled; write=2.209 s, sync=0.002 s, total=2.239 s; sync files=7, longest=0.002 s, average=0.000 s; distance=163834 kB, estimate=163840 kB
      Feb 04 05:58:30 test-site-prod app/web.1 10:58:30.086 [error] Clickhousex.Protocol (#PID<0.562.0>) disconnected: ** (Clickhousex.Error) closed

The website is hosted on Heroku which has not showed any issues. Clickhouse is hosted on an AWS EC2 t3.small instance. The instance went from 0 to 2.7% and 5.4% CPU utilization yesterday but during different times than when the errors occurred.

**Comment by ukutaht** [comment]
Hey. We also get this on prod but doesn't seem to cause any issues. It seems to be a bad error message from the db connection library but I'm not sure how to fix it.
