### ISSUE TITLE
Collapse/ignore part of URL

### ISSUE THREAD

**Issue by timroes** [plausible/analytics#686]
It would be nice to have a feature that allows collapsing a specific part of the URL to make it irrelevant what it was and track them as the same.

**What's the use-case?**

You might have URLs where an id might be part of the URL, but you don't actually care what that ID was and want to track all IDs as the same URL.

For example you have the URLs: `/user/123/overview`, `/user/123/posts` The way they are currently tracked you'll see each individual user ID pop up in the statistics. I'd like instead to just see the total number of `/user/*/overview` and `/user/*/posts` visits.

**What's the current alternative?**

The only way I see you can currently achieve that is by emitting events via JavaScript on those pages that strip that part out, e.g. 

```js
plausible('/user/*/overview');
```

The problem with that approach is:

* You can only visualize it using some goal, so they won't automatically show up as "pages".
* It will still leave the original visited URLs in tracking (though you can exclude those manually, using `data-exclude`)

**How could it be improved?**

In my opinion having an easy configuration option (similar to `data-exclude`) might be nice, like:

```html
<script [...] data-collapse="/user/*/overview, /user/*/posts"></script>
```

**Comment by Vigasaurus** [comment]
https://github.com/plausible/analytics/discussions/241

**Comment by timroes** [comment]
Duplicate of #241
