### ISSUE TITLE
Custom range date doesn't return any graphs

### ISSUE THREAD

**Issue by masterzen** [plausible/analytics#691]
## Prerequisites
- [x] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report
**Describe the bug**

When setting a custom range date for the dashboard of my site, no graph appears, and the spinners are running continuously. Using a premade range works correctly (ie 7 days, 30 days, etc).

Apparently all xhr requests return an HTTP 500 error.

**Expected behavior**
It should show graphs and data for the custom range.

**Screenshots (If applicable)**
![custom-range](https://user-images.githubusercontent.com/20242/107229949-b9945000-6a1e-11eb-82d3-46809c2e317d.png)

<img width="1397" alt="Custom Range HTTP 500" src="https://user-images.githubusercontent.com/20242/107230116-ee080c00-6a1e-11eb-9109-79d7a09c6556.png">

**Environment (If applicable):**
 - OS: macos 10.15.7
 - Browser firefox 
 - Version 85.0

**Comment by metmarkosaric** [comment]
thanks for reporting this @masterzen! i can replicate the same issue here too. we'll take a look asap!

**Comment by ukutaht** [comment]
Building and releasing a hotfix withing the next 15 minutes.

**Comment by masterzen** [comment]
I confirm this is fixed.
