### ISSUE TITLE
Option for allowing embedding/iframe a site's stats

### ISSUE THREAD

**Issue by p4block** [plausible/analytics#696]
Long story short, I am running the latest Plausible Docker container and I'd like to be able to display the charts inside another page in our site.

I tried creating an iframe that points to the public url for sharing the site's stats, but that showed:
![image](https://user-images.githubusercontent.com/5960575/107359738-574a5680-6ad5-11eb-9359-54db9fe9c733.png)

On ie. Grafana, one can embed individual charts individually, which would be a great feature as embedding the whole page can definitely cause issues. 

I guess it's just a X-Frame-Options header that I could remove on the reverse proxy (haven't dug up much) but a user friendly way would be welcome.

Thoughts?

**Comment by metmarkosaric** [comment]
thanks @p4block! We don't have support for embedding iframes at this moment. It's something we are looking to introduce in the future. See #213 

As a Plausible self-hoster, sponsoring us is a great way to give back to the community and to contribute to the long-term sustainability of the project and the future updates. See more here https://github.com/sponsors/plausible. Thanks for considering this!
