### ISSUE TITLE
Keyboard shortcuts: cmd does not seem to be ignored correctly

### ISSUE THREAD

**Issue by ukutaht** [plausible/analytics#707]
Since keyboard shortcuts for time period navigation were introduced, I've internalized them and navigating Plausible is now much faster. Great contribution by @Vigasaurus, thank you!!

The only issue both myself and Marko have ran into is the following: when you kill another tab with `cmd+w` and land on an open Plausible dashboard, it seems to pick up the `w` and navigate to the `Last 7 days` view. I never intend to go to the week view when closing another tab so this is a strange conflict that we should ignore.

Looking at the code, it should already ignore the keyboard shortcut when meta key or ctrl is pressed at the same time but for some reason it isn't working. I'm on Elementary OS running Firefox.

Any ideas @Vigasaurus? Can you reproduce?

**Comment by Vigasaurus** [comment]
I had actually noticed a bit of a different issue with the same keybinds, and was planning on it looking into it; will look into this too 👍

I have a hunch it's related to my issue with capital letters being missed/misinterpreted because I missed a reference to `toLowerCase()` and it's still using the old modulo method.

**Comment by ukutaht** [comment]
awesome :+1:

**Comment by Vigasaurus** [comment]
@ukutaht I think it should be fixed - we were using `keyup`, which would always fire the event if the user let go the of the `w` once the original tab was closed (which would always be the case) - I swapped that to a keydown. If you can verify it's fixed here, https://dev.vigneshjoglekar.com/plausible.io, I'll PR :D

**Comment by metmarkosaric** [comment]
@Vigasaurus any chance of adding 3 for last 30 days? https://twitter.com/daflowjoe/status/1360196822510223360?s=19

**Comment by Vigasaurus** [comment]
Sure! Adding new ones is simple. Would you want 6 for 6 months to finish the set too? I feel like 6 months is a lot less used, but it couldn't hurt I suppose.

**Comment by metmarkosaric** [comment]
sure! thanks!
