### ISSUE TITLE
Live demo (https://plausible.io/plausible.io) is down.

### ISSUE THREAD

**Issue by Tzelon** [plausible/analytics#708]
The title says it all. :)

**Comment by metmarkosaric** [comment]
thanks for reporting @Tzelon! what happens when you try? i checked and it works fine for me.

**Comment by ukutaht** [comment]
not down for me. Are you by any chance getting 'this page is not redirecting properly' from Firefox? We've been having issues with Firefox recently, not other browsers

**Comment by Tzelon** [comment]
![image](https://user-images.githubusercontent.com/4432120/107756017-3d568100-6d2c-11eb-8e79-d83cf291dc7c.png)
Hopes this can help

**Comment by Tzelon** [comment]
I tried Incognito and it's working.
Probably something on my side.

**Comment by ukutaht** [comment]
I suspect it had to do with our http -> http redirect being set up wrong. I've reverted that stuff now, is it working OK for you?

**Comment by ukutaht** [comment]
Thanks for reporting by the way :)

**Comment by Tzelon** [comment]
Sure, glad I could help. 
I'm not near my computer, but on my phone it's working.

**Comment by ukutaht** [comment]
OK, I will close the issue for now.  Please do open it back up if you see an issue again. Thanks 🙏
