### ISSUE TITLE
API Documentation for Android SDK

### ISSUE THREAD

**Issue by wbrawner** [plausible/analytics#72]
First off, thanks for working on this! 👏 As a privacy-conscious person, I for one appreciate it.

I wanted to see if you had any API documentation available, as I'd like to build an Android SDK for use of Plausible in some of my apps. Many of the reasons for tracking user interactions with a website apply to an app as well, and I'd like to help provide a nice alternative to Google Analytics for mobile developers as well (at least on Android). I don't imagine you want to take on the burden of supporting an official Android SDK but I'd love to put together an unofficial one an perhaps collaborate if you're interested.

**Comment by ukutaht** [comment]
Hey, that sounds great. We have a request on our public roadmap page for a documented HTTP API: https://plausible.nolt.io/88

Let's continue the conversation over at nolt. If you could upvote the feature request there and subscribe, you'll be notified of any updates. I'll keep Github issues only for bug reports.

**Comment by wbrawner** [comment]
Looks like the roadmap has moved over to GitHub after all so for the sake of anyone searching for this, #130 seems to cover my original concern in a broader scope.

**Comment by laithnurie** [comment]
hi there @wbrawner I am guessing you didnt create the android sdk and just hit the API directly ?

**Comment by wbrawner** [comment]
Hey @laithnurie, I haven't been following this to be honest. At the time there wasn't an API and I haven't been doing much mobile development these days

**Comment by laithnurie** [comment]
No worries thank you for replying so quickly @wbrawner :)

**Comment by wbrawner** [comment]
@laithnurie I know it's been a few months but I actually decided to revisit this. I've been working on an unofficial Android SDK here: https://github.com/wbrawner/plausible-android

It's not on Maven Central yet but I've begun the application process to get it there. In the meantime, you could build it yourself to include it in your apps

**Comment by metmarkosaric** [comment]
nice one @wbrawner, thanks for your contribution! added it to our list of community integrations: https://plausible.io/docs/integration-guides
