### ISSUE TITLE
Funnel stats

### ISSUE THREAD

**Issue by iaicam** [plausible/analytics#727]
I'm not sure if this is the correct place for feature requests. If not please point me in the correct direction.

I would like to be able to create funnel stats. So I would like to set up funnels and probably multiple funnels. I have a sign-up process and I would like to see the stats for each part of the signup funnel in an easy way. Currently, I have to copy the stats into a spreadsheet since I have quite a few custom events.

**Comment by metmarkosaric** [comment]
thanks @iaicam! makes sense to me. we'd like to make this easier so you can order your goals and get a nice funnel visualization. you can see more in this thread #171
