### ISSUE TITLE
Logout button links to /logout, but /logout doesn't exist

### ISSUE THREAD

**Issue by cassidyjames** [plausible/analytics#730]
### Precheck

Please note that this tracker is only for bugs. Do not use the issue tracker for help, support or feature requests. 

[Our docs](https://plausible.io/docs) are a great place for most answers, but if you can’t find your answer there, you can [contact us](https://plausible.io/contact). 

Have a feature request? Please search the ideas [on our forum](https://github.com/plausible/analytics/discussions/categories/feature-requests) to make sure that the feature has not yet been requested. If you cannot find what you had in mind, please [submit your feature request here](https://github.com/plausible/analytics/discussions/new). 

Have an issue with your self-hosted install? You can ask in [our self-hosted forum](https://github.com/plausible/analytics/discussions/categories/self-hosted-support). Thanks!

## Prerequisites
- [x] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report
**Describe the bug**

When I hover the "Logout" button, I see it links to `/logout`. However, navigating to /logout manually does not log me out, and gives me a 404. You can also try middle-clicking the logout link to open it in a new tab and see the 404.

**Expected behavior**

I expected it to log me out. Specifically, I'd like to link to /logout from within the native UI of https://github.com/cassidyjames/plausible to log users out.

**Comment by cassidyjames** [comment]
It looks like under the hood you're actually POSTing to /logout client-side. I could probably do something similar in my app, but that's a lot more work than just linking to /logout :sweat_smile:

**Comment by cassidyjames** [comment]
I've worked around this in my app by just clearing cookies and returning to the login screen, but it still seems like a bug here to me.

**Comment by ukutaht** [comment]
Good point. We use some JS helpers that come with Phoenix to make the logout link POST instead of a regular GET link. The idea is to prevent a cross site request forgery attack.

But logout is not a very risky action.. if someone clicks on a logout link by accident, the worst that can happen is they have to log in again. So I think it makes sense to make it a plain GET link.
