### ISSUE TITLE
Goals section not present in Plausible Analytics account settings

### ISSUE THREAD

**Issue by harmvandendorpel** [plausible/analytics#755]
According to
https://plausible.io/docs/custom-event-goals#2-create-a-custom-event-goal-in-your-plausible-analytics-account
there should be a "Goals Section". But there is none. Where/how to add custom event now?

**Comment by metmarkosaric** [comment]
thanks @harmvandendorpel! are you looking in your account settings or the website settings? Goals section is in the website settings. you can find it here: https://plausible.io/docs/website-settings

**Comment by harmvandendorpel** [comment]
found it, thank you

**Comment by metmarkosaric** [comment]
you're welcome!
