### ISSUE TITLE
Custom range URL query

### ISSUE THREAD

**Issue by gorango** [plausible/analytics#760]
## Prerequisites
- [x] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report
**Describe the bug**

The following path to **site.com** using a date range works as expected:

```https://plausible.io/site.com?period=custom&from=2021-01-01&to=2021-02-25```

But removing `&to=2021-02-25` throws the following error on the page:

```TypeError: Cannot read property 'getDate' of undefined```

**Expected behavior**

The page should show results for the date range up until today's date.

This would be really helpful to bookmark for easy checkins.

![image](https://user-images.githubusercontent.com/5211330/109234986-c80e9580-779a-11eb-873e-dfdd3dd1e5f1.png)

**Comment by ukutaht** [comment]
Instead of inferring `today` when the `to` parameter is missing, I'd prefer an API where you have to explicitly set parameters`from=2021-01-01&to=today`

So we would need to introduce a special date called `today` which will do exactly what you would expect

**Comment by metmarkosaric** [comment]
thanks! we're keeping the list of issues to actual bugs in the product. this is more like a feature request for a different way to use Plausible. i've now added it to our forum where we keep the list of feature requests so we can take a look at it and consider implementing it: https://github.com/plausible/analytics/discussions/1902
