### ISSUE TITLE
Demo page's chart lines overflows outside the chart on Firefox

### ISSUE THREAD

**Issue by fmterrorf** [plausible/analytics#761]
## Prerequisites
- [x] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report
**Describe the bug**
The lines in the chart is overflowing on large screen size when viewing the demo page

**Expected behavior**
The liens shouldn't overflow

**Screenshots (If applicable)**
Firefox Bug:
![Screenshot from 2021-02-25 21-09-36](https://user-images.githubusercontent.com/77761194/109249694-d4501e00-77ad-11eb-85ce-1a468a4aca57.png)

https://user-images.githubusercontent.com/77761194/109249621-aec31480-77ad-11eb-8dd5-9f85e8059e34.mp4

I opened the demo page using chrome and it seems OK. It's only happening on firefox

**Environment (If applicable):**
 - OS: Pop!_OS 20.10
 - Browser: Firefox
 - Version: 85.0.1 (64-bit)

**Comment by fmterrorf** [comment]
I also noticed that the list of top pages is overflowing, just like the chart
![Screenshot from 2021-02-25 21-28-38](https://user-images.githubusercontent.com/77761194/109251099-80930400-77b0-11eb-8dc3-b2ade4a37220.png)

**Comment by metmarkosaric** [comment]
Thanks @fmterrorf! Did you by any chance manually select a larger font size in your browser? We've seen this issue before when having a large font size #124

**Comment by fmterrorf** [comment]
Ah yes. I have manually set it to 20px, and the default is 16px. Sorry i totally missed the existing issue while looking for one :grimacing: 

Going to close this issue now. Thanks

**Comment by metmarkosaric** [comment]
no worries! and thanks for the update!
