### ISSUE TITLE
SPA instructions / support

### ISSUE THREAD

**Issue by patarapolw** [plausible/analytics#77]
Somewhat like, Google Analytics might need an extra step for SPA, as it does not detect `popstate`, nor hash router.

https://developers.google.com/analytics/devguides/collection/gtagjs/single-page-applications

```js
gtag('config', GA_MEASUREMENT_ID, {'page_path': page_path});
```

I believe, [Gatsby](https://www.gatsbyjs.org/) also counts as SPA on latter navigations.

**Comment by ukutaht** [comment]
Hey,

Plausible automatically listens for `pushState` and `popState` events and triggers pageviews based on them. I'm also planning to add support for hash routing soon but that is tracked on our roadmap page in [nolt](https://plausible.nolt.io/84).

I can add a note about this on our docs. Is there anything else you feel like we're missing?

**Comment by patarapolw** [comment]
No, I am just worried if it is not supported.
