### ISSUE TITLE
Details button in Top Sources doesn't display UTM data

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/analytics#780]
This was caused by the latest update earlier today. If you select Source, Medium or Campaign in Top Sources and click on the "details" button you'll get the same report that you see when you have "All". It should show the individual reports for different UTM tags instead.

**Comment by Vigasaurus** [comment]
Whoops, that's my bad for copy+pasting without reading the line fully 🤦‍♂️ - will PR a fix shortly.
