### ISSUE TITLE
People ❤️ Plausible section when decreasing the width of the window

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/analytics#783]
"Hey guys, noticed a little design bug when i decreased the width of my window"

![0zRldmQ0 jpg large](https://user-images.githubusercontent.com/34340819/109764545-fdc8d980-7bf3-11eb-857d-2db4186013ba.jpg)

(from Twitter DM)

**Comment by ukutaht** [comment]
Solved on plausible.io
