### ISSUE TITLE
Long username on mobile issue

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/analytics#784]
"I found some minor issue with your responsive design b/c my surname is quite long. 🙈"

![EviKTWUXcAAsmLW](https://user-images.githubusercontent.com/34340819/109764990-8778a700-7bf4-11eb-80e2-8165c226c9b3.jpg)

([from twitter](https://twitter.com/NBvGersdorff/status/1366994557041332224))

**Comment by niklaas** [comment]
In case I find time to look at this: Which solution do you prefer? 💁🏼‍♂️

1. Truncating the name after a specific amount of letters e.g., "Niklaas Baud..."
2. Something like `<div style="overflow-x: scroll">
3. ...

**Comment by ukutaht** [comment]
I'd go with option 1
