### ISSUE TITLE
Google Searchi Console - only one property is listed

### ISSUE THREAD

**Issue by oliverruhm** [plausible/analytics#785]
Hi there,

I tried to connect Search Console using two different of my Google Workspace accounts, in both cases there is only one property selectable. In fact, there should be many, like, 25 or so.

Is this a known issue? 

Best regards,
Oliver

<img width="400" alt="Bildschirmfoto 2021-03-03 um 09 53 15" src="https://user-images.githubusercontent.com/36993713/109779823-a4b67100-7c06-11eb-88c8-972cbb927385.png">

**Comment by metmarkosaric** [comment]
thanks for reaching out @oliverruhm! there should be no issues with this integration. i just checked my own account and i see all of my properties in that list. what properties do you see in your search console account?

**Comment by oliverruhm** [comment]
Hi Marko, OK, if there is everything up and running, let me try another account before we dig deeper. Let you know if things work out.

**Comment by metmarkosaric** [comment]
Sounds good! Do reopen this thread or [contact us via email](https://plausible.io/contact) if there's something. Thanks!
