### ISSUE TITLE
Bug: External links (Top Pages) incorrectly default to https

### ISSUE THREAD

**Issue by vincentsch** [plausible/analytics#789]
Unter "Top Pages" there are external links to the tracked site. Those links always use https even if the site doesn't support it.

**Comment by ukutaht** [comment]
I just changed this last week.

We don't know on our end if your site is http or https. I changed to link to https as a signal that this is the expected default on the web in 2021. Unencrypted http should be discouraged and this is our way of doing it.

**Comment by vincentsch** [comment]
The thing is, when you link to a http url and the person who runs the website wants everyone to use https, he can just redirect from http to https. However, when you link with https to a site that doesn't support it users just see a big warning, no redirect to http possible.

**Comment by Vigasaurus** [comment]
Yes, but arguably that's a good thing. 

If Plausible sends someone to a site that supports https but doesn't redirect, and then that user has some data stolen over the wire, it's partially on Plausible for not sending them to https. 

Whereas if Plausible sends someone to a site that doesn't support https with https, not only is it a good and easy way for you (or anyone else) to quickly ensure that the site loads as expected (without the warning), there will likely never be an instance where a site supports https and a user is sent to its http version (by Plausible) and stuck there. 

Also realistically in 2021 with tools like [LetsEncrypt](https://letsencrypt.org/) around, there really shouldn't be any active sites without HTTPS left around, or at minimum they should be full throttle towards migrating.
