### ISSUE TITLE
Incorrect content-type header returned for custom javascript include

### ISSUE THREAD

**Issue by ahnick** [plausible/analytics#79]
I setup a custom domain to broker the javascript include and noticed that Firefox was throwing the following error message in the console:

> The script from “https://stats.mashword.com/js/index.js” was loaded even though its MIME type (“text/plain”) is not a valid JavaScript MIME type

Upon inspection it seems that the content-type header is returning "text/plain" when it should be returning "application/javascript".  Firefox still loads the script, but I'd like to avoid having this error show up in the console.

**Comment by ukutaht** [comment]
Thanks, deploying the fix now! :)
