### ISSUE TITLE
Stats API - FunctionClauseError when getting 'todays' time series 

### ISSUE THREAD

**Issue by shornuk** [plausible/analytics#797]
## Bug report

Something else I've been running into. 
Doing a call to the timeseries endpoint, each one works, apart from the 'today'. Calling this...

```
https://plausible.io/api/v1/stats/timeseries?site_id=$SITE_ID&period=day
``` 

Gives the following error...

```
** (FunctionClauseError) no function clause matching in Plausible.Stats.Timeseries.buckets/1
```

## Prerequisites
- [x] I have searched open and closed issues to make sure that the bug has not yet been reported.

**Comment by ukutaht** [comment]
Thanks! Will take a look
