### ISSUE TITLE
Emoji Favicon not showing in dropdown list

### ISSUE THREAD

**Issue by alfranz** [plausible/analytics#798]
## Prerequisites
- [x] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report

In the site dropdown list (site overview) the favicons are not showing next to the site. It only shows a link to a non-existing image.

**Expected behavior**

I would expect some thumbnail image to be shown. According to dev tool the image source is pointing to https://icons.duckduckgo.com/ip3/alexfranz.com.ico - which is not available. When openening my website www.alexfranz.com, you can see the favicon 🥥.

![alt](https://i.imgur.com/8kEsaZh.png "Favico")

The same bug is visible with another site of mine monitored on plausible which also has an emoji favicon.

**Environment (If applicable):**
 - OS: Mac OS 10.14.3
 - Browser Chrome Version 88.0.4324.182

**Comment by Vigasaurus** [comment]
Yeah there should probably be an additional fallback image there, normally the DDG service returns a fallback image, but it seems to error out completely with emoji favicons.

**Comment by ukutaht** [comment]
Yeah we can add an `<img onerror=` fallback
