### ISSUE TITLE
Weekly/monthly report emails cannot be sent over SMTP

### ISSUE THREAD

**Issue by ukutaht** [plausible/analytics#827]
Turns out that many SMTP servers reject emails where a single line exceeds 998 characters  ¯\_(ツ)_/¯

The standard seems really arbitrary but it's not going to change. We should break up the HTML of those emails such that no line can exceed the maximum length.

**Comment by bhavin192** [comment]
Is there any automated way in the templating to achieve this? I can spend some time on this if it needs to be done manually / need to edit all the HTML templates.

**Comment by mattsmallman** [comment]
This issue also appears to be preventing the selfhosted version sending weekly emails. Logs from bytemark/smtp container:

`1077 LOG: smtp_connection MAIN
 1077   SMTP connection from plausible_plausible_1.nginx-proxy (analytics.test.com) [172.20.0.14] closed by QUIT
 1078 LOG: MAIN REJECT
 1078   H=plausible_plausible_1.nginx-proxy (analytics.test.com) [172.20.0.14] F=<analytics@test.com> rejected after DATA: maximum allowed line length is 998 octets, got 1360
 1078 LOG: smtp_connection MAIN
 1078   SMTP connection from plausible_plausible_1.nginx-proxy (analytics.test.com) [172.20.0.14] closed by QUIT
 1079 LOG: MAIN REJECT
 1079   H=plausible_plausible_1.nginx-proxy (analytics.test.com) [172.20.0.14] F=<analytics@test.com> rejected after DATA: maximum allowed line length is 998 octets, got 1360
 1079 LOG: smtp_connection MAIN
 1079   SMTP connection from plausible_plausible_1.nginx-proxy (analytics.test.com) [172.20.0.14] closed by QUIT`

**Comment by bhavin192** [comment]
Exactly, that's how we found this issue: https://github.com/plausible/analytics/discussions/756

**Comment by ukutaht** [comment]
Looks like this was actually addressed in the underlying SMTP adapter library: https://github.com/fewlinesco/bamboo_smtp/blob/develop/CHANGELOG.md#300---2020-09-10

So all we need to do is upgrade `bamboo_smtp` to v4 and it should work.

The next planned self-hosted release is in the summer and I said I wouldn't patch any existing versions to lower my overhead (I'm the only maintainer). However, this is a serious issue preventing people from using a core feature of the platform. So I will patch the latest release with this version upgrade.

**Comment by ukutaht** [comment]
Can you please test tag `v1.2.1` to see if it fixes the issue?

You can wait until next monday or trigger the email manually:
```
$ docker exec -it hosting_plausible_1 /app/bin/plausible remote
iex> site = Plausible.Repo.get_by(Plausible.Site, domain: "plausible.io")
iex> Plausible.Workers.SendEmailReport.perform(%{"interval" => "weekly", "site_id" => site.id})
:ok
```

Make sure the `site` has a weekly report configured. NB: The function will return `:ok` even if it failed. Check SMTP logs to see if it actually went through.

**Comment by ukutaht** [comment]
> Can you please test tag `v1.2.1` to see if it fixes the issue?
> 
> You can wait until next monday or trigger the email manually:
> 
> ```
> $ docker exec -it hosting_plausible_1 /app/bin/plausible remote
> iex> site = Plausible.Repo.get_by(Plausible.Site, domain: "plausible.io")
> iex> Plausible.Workers.SendEmailReport.perform(%{"interval" => "weekly", "site_id" => site.id})
> :ok
> ```
> 
> Make sure the `site` has a weekly report configured. NB: The function will return `:ok` even if it failed. Check SMTP logs to see if it actually went through.

Ignore this for now. Upgrading bamboo_smtp broke everything. Looking into a soluton.

**Comment by bhavin192** [comment]
I was trying one Exim (bytemark/smtp uses it) workaround for this, and used the above steps with `v1.2.0`.
```
Plausible.Workers.SendEmailReport.perform(%{"interval" => "weekly", "site_id" => site.id})
Plausible.Workers.SendEmailReport.perform(%{"interval" => "weekly", "site_id" => site.id})
** (UndefinedFunctionError) function Plausible.Workers.SendEmailReport.perform/1 is undefined or private. Did you mean one of:

      * perform/2

    (plausible 0.0.1) Plausible.Workers.SendEmailReport.perform(%{"interval" => "weekly", "site_id" => 1})
```

I think the _job argument needs to be provided?

**Comment by ukutaht** [comment]
> I was trying one Exim (bytemark/smtp uses it) workaround for this, and used the above steps with `v1.2.0`.
> 
> ```
> Plausible.Workers.SendEmailReport.perform(%{"interval" => "weekly", "site_id" => site.id})
> ** (UndefinedFunctionError) function Plausible.Workers.SendEmailReport.perform/1 is undefined or private. Did you mean one of:
> 
>       * perform/2
> 
>     (plausible 0.0.1) Plausible.Workers.SendEmailReport.perform(%{"interval" => "weekly", "site_id" => 1})
> ```
> 
> I think the _job argument needs to be provided?

Yes it can be `nil`

**Comment by ukutaht** [comment]
I'm stumped. Asking for help in the Elixir forum: https://elixirforum.com/t/upgrading-bamboo-smtp-breaks-test-suite-but-not-the-app/38226

**Comment by ukutaht** [comment]
Managed to find the issue and upgrade the dependency. I've created a release candidate for v1.3.0 which includes a fix for email delivery over SMTP.

Find the changelog and installation instructions here: https://github.com/plausible/analytics/releases/tag/v1.3.0-rc.0

If you do decide to try out the release candidate, please leave a message here. I will address any issues and if everything seems smooth I will create a proper release.
