### ISSUE TITLE
Typing in the year in the custom range date picker no longer works

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/analytics#831]
I've tried this on my own and can replicate the issue.

![6aiGhtfZ png medium](https://user-images.githubusercontent.com/34340819/110912551-5c890400-8314-11eb-9068-636def5405f0.png)

(reported via twitter dm)

**Comment by ukutaht** [comment]
This regression was introduced in #735. The site switching keybindings are interfering with entering numbers into the datepicker.

Fixing it would require some sort of horrible global state so the site switcher can ignore the keybind when datepicker is open. @Vigasaurus any other ideas?

**Comment by Vigasaurus** [comment]
Assuming the datepicker uses a basic input element, we could just have the keydown handler check the event target for if it's of input type and break out. Or honestly, the datepicker is what handles both the keybindings and keeps the flatpickr state, so it could be as simple as checking the `open` state in the keydown, similar to the code below. 

Something like: 

```javascript
if (['INPUT', 'TEXTAREA'].includes(e.target.tagName)) return;

...rest
e.preventDefailt();
```
Or

```javascript
if (this.state.open) return;

...rest
e.preventDefailt();
```

**Comment by ukutaht** [comment]
Fantastic @Vigasaurus that's a much better idea than introducing global state.
