### ISSUE TITLE
Add more details in HOSTING.md

### ISSUE THREAD

**Issue by yasoob** [plausible/analytics#84]
In [HOSTING.md](https://github.com/plausible/analytics/blob/master/HOSTING.md) you have written about the hosting setup you are using with Digital Ocean. It would be nice to have details about what kind of traffic that setup is handling right now.

**Comment by tckb** [comment]
Isn't the page stats available on the website? @yasoob  did you mean https://plausible.io/plausible.io

**Comment by yasoob** [comment]
@tckb That link is surely helpful but I meant more details in terms of system load. As in how many page views per second/minute the current hosting setup (on Digital Ocean in your case) can support and what is the CPU and memory consumption. This can act as a rough guide for people to figure out how much memory and CPU/vCPUs they need to support their own website traffic.

**Comment by Kulcanhez** [comment]
I'm also confused by `Plausible runs as a single server, backed by two databases: PostgreSQL for user data and ClickhouseDB for the stats.` does it need to be in separate droplets or can somehow everything be inside one server for being cost-effective?

**Comment by tckb** [comment]
Both is possible. @Kulcanhez

**Comment by Kulcanhez** [comment]
> Both is possible. @Kulcanhez

Thank you very much. My question is on PostgreSQL and ClickhouseDB because there's no guide on that. Not sure if you have good guides for installing and configuring it, mainly because of performance/security.

**Comment by tckb** [comment]
@Kulcanhez   Installing and configuring PostgreSQL and Clickhouse is already out of scope of the project, because different people have different setups. I might add some general guides for postgres and clickhouse

**Comment by Kulcanhez** [comment]
> @Kulcanhez Installing and configuring PostgreSQL and Clickhouse is already out of scope of the project, because different people have different setups. I might add some general guides for postgres and clickhouse

Of course, that was I was asking for ❤️

**Comment by ukutaht** [comment]
Closed in #209
