### ISSUE TITLE
Main graph broken on mobile

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/analytics#845]
Got couple of reports that the main graph on mobile phones is now broken. Can verify it on my own device both on Brave and on Firefox:

![photo_2021-03-17_09-38-37](https://user-images.githubusercontent.com/34340819/111438483-97b87800-8704-11eb-8ec7-43115f7834c0.jpg)
![photo_2021-03-17_09-38-32](https://user-images.githubusercontent.com/34340819/111438490-98510e80-8704-11eb-8089-5e4f46ef5eed.jpg)

**Comment by ruurtjan** [comment]
There are two more mobile issues that have been there for a while:
1. When scrolling in Firefox on Android, the sticky header shifts a pixel, leaving a gap where other content is visible.
2. The "outbound link: click" button falls of its container.
![Screenshot_20210318-111310_Firefox](https://user-images.githubusercontent.com/1055478/111610197-5cd54380-87db-11eb-9df6-f9b7e67a8262.jpg)
3. The "details" button shows up over the content.
![Screenshot_20210318-111248_Firefox](https://user-images.githubusercontent.com/1055478/111610201-5e067080-87db-11eb-9842-5d7c222aadc1.jpg)

Both screenshots were taken on this page: [https://plausible.io/nslookup.io](https://plausible.io/nslookup.io).
