### ISSUE TITLE
Can't add pageview goals with asterisks (v1.2.0)

### ISSUE THREAD

**Issue by joyqi** [plausible/analytics#847]
Actually added some pageview goals with asterisks in goals panel.

<img width="828" alt="截屏2021-03-17 下午9 25 53" src="https://user-images.githubusercontent.com/59437/111475124-bac84380-8767-11eb-9e15-64e3288d8053.png">

Can't find them in goal conversions. (But the goals without asterisks can be shown.)

<img width="1110" alt="截屏2021-03-17 下午9 26 06" src="https://user-images.githubusercontent.com/59437/111475082-b1d77200-8767-11eb-81fb-b498da688632.png">

**Comment by metmarkosaric** [comment]
Did you get any visits on these pages? Goals don't show up in the dashboard unless there's at least 1 conversion

**Comment by Vigasaurus** [comment]
Since you mentioned v1.2.0, I assume you're self hosting? The self-host track doesn't have this yet, this feature is only a couple of weeks old.

**Comment by joyqi** [comment]
@metmarkosaric Yes, I'm sure there are many visits on these pages.

@Vigasaurus Yes, I'm self hosting. So this feature is not available on self-host version yet?

**Comment by metmarkosaric** [comment]
Not available yet on self-hosting. Bug fixes and new features are released to the cloud version several times per week. Features are battle-tested in the cloud which allows us to fix any bugs before the general self-hosted release. Every six months we combine all the changes into a new self-hosted release. You can read more here https://plausible.io/blog/building-open-source
