### ISSUE TITLE
The site shows USA for visitor, but I am in the UK

### ISSUE THREAD

**Issue by davestewart** [plausible/analytics#849]
## Prerequisites
- [x] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report

I set up the site for the first time, went to the URL and checked the dashboard. It shows visits as all being from the USA.

![image](https://user-images.githubusercontent.com/132681/111554995-5add9700-877f-11eb-9ccd-b4ee05e803a6.png)

**Expected behavior**

Should show me from the UK.

![image](https://user-images.githubusercontent.com/132681/111554937-3681ba80-877f-11eb-8144-d7a59371cb13.png)

**Environment (If applicable):**

- OS: OSX
- Browser: Chrome
- Version: latest
- Host: Netlify / TSO (UK)

**Comment by metmarkosaric** [comment]
thanks @davestewart! Are you using Cloudflare or another proxy by any chance? 

If you're using Cloudflare for DNS, chances are you are having your sites proxied behind Cloudflare too. A proxy can override the remote IP which would lead to wrong geolocation data in your stats. Please remove the proxy and make it just a DNS record in your Cloudflare settings to solve the issue.

**Comment by davestewart** [comment]
Hey! Thanks for the info.

I'll get back to Netlify support and will find out.

I may be some time...
