### ISSUE TITLE
Don't ship marketing site as part of self-hosted package

### ISSUE THREAD

**Issue by RealOrangeOne** [plausible/analytics#85]
Running this self hosted is nice, but it'd be nice if it didn't contain all the marketting site components with it. Having the homepage either be the login prompt, or a list of public sites (configurable?) would be so much nicer!

Specifically, things which act a bit weirdly when self hosting:

- "Live Demo" button doesn't work unless there's a site setup for 'plausible.io'
- Loading up to marketing site for Plausible feels _weird_.
- Footer links don't really work

**Comment by ukutaht** [comment]
Makes total sense 👍
