### ISSUE TITLE
Still inconsistency between Plausible.io dashboard and data from Stats API

### ISSUE THREAD

**Issue by bastienlaval** [plausible/analytics#874]
Hello,

I've had an issue of inconsistency between data shown in the Plausible dashboard, and the data from the Stats API.
I've redone the checks after the latest update, but I'm still having the issue.
The issue is for the **breakdown** endpoint. I'm not having the issue with the aggreg endoint.

For instance, here are the figures I get in the dashboard for the Devices :
![Capture d’écran 2021-03-23 à 11 31 06](https://user-images.githubusercontent.com/21161975/112133532-15c8c300-8bcc-11eb-961f-d3ca97944b0f.png)

And the data I get with the Stats API : 
<img width="859" alt="Capture d’écran 2021-03-23 à 11 30 52" src="https://user-images.githubusercontent.com/21161975/112133601-24af7580-8bcc-11eb-9a6a-92a3c897f1cd.png">

I've redone the checks before/after the screenshots and data have not changed in the meantime.

Is there still an issue with the breakdown endpoint ?

Thanks!

Bastien

**Comment by ukutaht** [comment]
Hi.

Previously, there was an actual bug in how the stats were queried. Now the difference is that the stats for the UI are queried from the `events` table whereas for the API they are queried from the `sessions` table. There can be tiny discrepancies between the two tablesbecause session generation from events is not strongly consistent.

If you find a query where the numbers are way off (not just different by 1) then it's likely that there is a bug. Let me know of any cases like this on your end. Thanks
