### ISSUE TITLE
Feature Request: Event Tracking

### ISSUE THREAD

**Issue by benyanke** [plausible/analytics#888]
It would be great to have arbitrary event tracking that can be attached to things with JavaScript functions, then track the number of times events are triggered.

This could be used to track things like contact form submissions, link clicks to third party sites, or link clicks to non-HTML downloads.

**Comment by metmarkosaric** [comment]
it's possible already. see https://plausible.io/docs/custom-event-goals and https://plausible.io/docs/outbound-link-click-tracking

**Comment by benyanke** [comment]
Cool! I'll be checking that out!
