### ISSUE TITLE
User Agent Cache Crashes Application

### ISSUE THREAD

**Issue by simonalbrecht** [plausible/analytics#905]
### Precheck

Please note that this tracker is only for bugs. Do not use the issue tracker for help, support or feature requests. 

[Our docs](https://plausible.io/docs) are a great place for most answers, but if you can’t find your answer there, you can [contact us](https://plausible.io/contact). 

Have a feature request? Please search the ideas [on our forum](https://github.com/plausible/analytics/discussions/categories/feature-requests) to make sure that the feature has not yet been requested. If you cannot find what you had in mind, please [submit your feature request here](https://github.com/plausible/analytics/discussions/new). 

Have an issue with your self-hosted install? You can ask in [our self-hosted forum](https://github.com/plausible/analytics/discussions/categories/self-hosted-support). Thanks!

## Prerequisites
- [x] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report
After a bunch of requests have hit the server, it crashes the entire application with the following exception:

```
Server: <redacted>:80 (http)
Request: POST /api/event
** (exit) an exception was raised:
    ** (Cachex.ExecutionError) Specified cache not running
        (cachex 3.3.0) lib/cachex.ex:1441: Cachex.unwrap_unsafe/1
        (plausible 0.0.1) lib/plausible_web/controllers/api/external_controller.ex:78: PlausibleWeb.Api.ExternalController.create_event/2
        (plausible 0.0.1) lib/plausible_web/controllers/api/external_controller.ex:9: PlausibleWeb.Api.ExternalController.event/2
        (plausible 0.0.1) lib/plausible_web/controllers/api/external_controller.ex:1: PlausibleWeb.Api.ExternalController.action/2
        (plausible 0.0.1) lib/plausible_web/controllers/api/external_controller.ex:1: PlausibleWeb.Api.ExternalController.phoenix_controller_pipeline/2
        (phoenix 1.5.7) lib/phoenix/router.ex:352: Phoenix.Router.__call__/2
        (plausible 0.0.1) lib/plug/error_handler.ex:65: PlausibleWeb.Router.call/2
        (plausible 0.0.1) lib/plausible_web/endpoint.ex:1: PlausibleWeb.Endpoint.plug_builder_call/2
{"Kernel pid terminated",application_controller,"{application_terminated,plausible,shutdown}"}
Kernel pid terminated (application_controller) ({application_terminated,plausible,shutdown})
```

Even just hitting refresh in the browser a bunch of times on a site where the tracking script is included leads to the crash. 
I've already tried setting the environment variable `USER_AGENT_CACHE_STATS` to `true` (the default is `false`) but the same issue occurs.

It seems there's a check missing if the cache is actually available. The cache was introduced in #547.

**Expected behavior**
Cache works as expected, exception does not crash the entire application.

**Screenshots (If applicable)**
-

**Environment (If applicable):**
 - OS: `Amazon Linux 2/Docker 19.03.13-ce`
 - Browser: `Chrome 89`
 - Version: `plausible/hosting:v1.2.1`

**Comment by ukutaht** [comment]
Yes we get similar errors on our production server. I've been getting error messages like this for errors where I know for a fact that something else is wrong (e.g. DB connection died). So I don't 100% trust the error message itself either.

Sorry to ping you @whitfin, don't feel obligated to reply, but if you have time it would be great if you could take a look and see if we're using Cachex wrong somehow? Do you have any debugging tips for the cache? Here's the PR where we added it: https://github.com/plausible/analytics/pull/547

It's been amazing for performance. Our server was struggling before and now it's chilling at ~10% CPU most of the day :)

**Comment by Heziode** [comment]
I have the same freaking error for month too.
it is very annoying, since I have several millions visitors per month, but the value is truncated by the crash of Plausible.

Any progress on this issue?

**Comment by ukutaht** [comment]
No progress to report. We see the same error logged but we're not experiencing any crashes caused by this. I'll take a look for the next self-hosted release

**Comment by Heziode** [comment]
This does not cause crash, but it does not his job anymore (collect analytics data) when this message happens.

**Comment by Heziode** [comment]
Example, when I get the error, all analytics data are not collected anymore:

![image](https://user-images.githubusercontent.com/16735076/131632255-a12bfdd8-861f-498f-867b-5f9d2442191b.png)

**Comment by Heziode** [comment]
@ukutaht  this issue is a nightmare, it hardly collects data anymore, this is so inaccurate now.

I have tried to restart (with cron job) the whole stack every 6 hours, and even every hour without success.

I can't use Plausible anymore, it's not accurate at all anymore, as it hardly collect analytics data with this bug.

Example of stat in January 2021:

![image](https://user-images.githubusercontent.com/16735076/132680351-e280775e-90e9-4d35-b3ec-18a7df4fb7f2.png)

Now, the last 30 days (August 2021):

![image](https://user-images.githubusercontent.com/16735076/132680495-a493356e-41a5-47b0-bbe7-05bef8924b72.png)

And now, Septembre 7:

![image](https://user-images.githubusercontent.com/16735076/132680783-697d2f9c-3565-45de-b31f-fa38e62003dc.png)

It is very boring to switch back to Matomo, since Plausible fit my needs without too many superfluous features…

**Comment by ukutaht** [comment]
@Heziode How much memory have you given your machine? If it's something low (like <16GB) you can try giving it more to see if that does anything.

**Comment by Heziode** [comment]
It running inside a Container, the VPS have 32 GB of ram.

**Comment by Heziode** [comment]
@ukutaht `docker stats` return this:

![image](https://user-images.githubusercontent.com/16735076/132684020-77ee44b2-b557-4e5d-83b6-4f0c7cdb5303.png)

So I don't think that this problem is related to how many RAM / CPU we have allocated to Plausible.

**Comment by ukutaht** [comment]
yeah that seems plenty

**Comment by Heziode** [comment]
However, the ROM (HDD/SDD storage) used is huge:

```
# du -cksh *
47G	plausible-analytics
```

From `plausible-analytics` dir:

```
# du -cksh *
4.0K	README.md
86M	db-data
4.0K	docker-compose.yml
47G	event-data
4.0M	geoip
4.0K	plausible-conf.env
4.0K	reboot.sh
28K	reverse-proxy
47G	total
```

And in `event-data` (used by `plausible_events_db`, that is a `yandex/clickhouse-server` Docker image): 

```
# du -cksh *
24K	access
80K	data
4.0K	dictionaries_lib
4.0K	flags
4.0K	format_schemas
28K	metadata
4.0K	metadata_dropped
68K	preprocessed_configs
4.0K	status
47G	store
4.0M	tmp
4.0K	user_files
47G	total
```

So I think is a bad configuration of ClickHouse. I don't know what it is and how to configure it to set a size limit on it (because it filled my storage)

**Comment by ukutaht** [comment]
This is probably due to system log tables taking up a ton of space. More info: https://theorangeone.net/posts/calming-down-clickhouse/

**Comment by Heziode** [comment]
After dropping event-data, and do some configuration (what you have put on the repo), ClickHouse just calm down, and Plausible does not crash anymore.

The next few months will show whether the trend remains stable.
