### ISSUE TITLE
Bug: JS errors when backgrounding app on Safari on iPad.

### ISSUE THREAD

**Issue by ukutaht** [plausible/analytics#920]
https://twitter.com/kevinrenskers/status/1381363893453398024

**Comment by kevinrenskers** [comment]
It used to do this when switching between Safari and another app:

![F20D05F1-C6A3-47B6-B3AD-D80A63B86B26](https://user-images.githubusercontent.com/229384/114372872-517afb00-9b82-11eb-9ff2-332c2762236c.png)

Now it gives that JS error instead.

**Comment by metmarkosaric** [comment]
Got couple more screenshots from Safari (iOS and Mac OS) but not sure if they're related to this issue:

<img width="1143" alt="Screenshot 2021-06-10 at 22 11 02" src="https://user-images.githubusercontent.com/34340819/121637728-26c9f780-ca8a-11eb-9cb2-301cf1d3159f.png">

![IMG_6734](https://user-images.githubusercontent.com/34340819/121637742-2af61500-ca8a-11eb-899c-7c6d0c309a88.PNG)

**Comment by RobertJoonas** [comment]
Hi @kevinrenskers!

We now have access to BrowserStack Live which allows us to manually test on various devices, operating systems and browsers. So we should be able to reproduce this issue now.

First of all, are you still encountering this? In that case, could you please confirm that it happens on our live demo at https://plausible.io/plausible.io too? Also, detailed steps to reproduce would be very useful.

Thanks for helping improve Plausible! :)

**Comment by kevinrenskers** [comment]
I can’t reproduce it any longer.

**Comment by metmarkosaric** [comment]
that's great and thanks for the update @kevinrenskers!
