### ISSUE TITLE
Add iOS icon or create an iOS app

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/analytics#93]
"I’ve added Plausible to my home screen, but the website doesn’t have an iOS icon. Creating a simple iOS app using a web view would also be nice.

This would be much appreciated and would take about 5 minutes. Just create a PNG (512x512) file in the root of the site named: apple-touch-icon.png with the apps icon. Done.

I’d recommend this, if you haven’t yet seen it: https://realfavicongenerator.net/"

([imported from the old roadmap](https://plausible.nolt.io/17))

**Comment by metmarkosaric** [comment]
Tried the site referenced above and this is what I got. Has to be tested to see if it actually looks good on a phone screen.

![apple-touch-icon](https://user-images.githubusercontent.com/34340819/85113913-5a2bca80-b218-11ea-8d07-6be06185e569.png)

**Comment by metmarkosaric** [comment]
Couple of higher quality alternatives:

![apple-touch-icon2](https://user-images.githubusercontent.com/34340819/85425621-b032a200-b579-11ea-88ca-25c7fc739389.png)

![apple-touch-icon](https://user-images.githubusercontent.com/34340819/85425623-b163cf00-b579-11ea-97ac-e2e038286402.png)

**Comment by metmarkosaric** [comment]
We pushed an update that includes the iOS icon. Can someone with an Apple device verify if it all works fine please? Thanks!

This is what we included in the code:

<link rel="apple-touch-icon" type="image/png" href="/images/icon/apple-touch-icon.png">

**Comment by tckb** [comment]
![051AD893-5181-434D-A53C-589B240F47BD](https://user-images.githubusercontent.com/939542/86938211-73050d00-c140-11ea-8fdc-6d6b8d8e2f2f.jpeg)
Icon has black background

**Comment by metmarkosaric** [comment]
Thanks @tckb! From what I see iOS fills the transparent regions with black automatically.

**Comment by metmarkosaric** [comment]
Just created an icon with white background too.

![apple-touch-icon](https://user-images.githubusercontent.com/34340819/86940331-f6bff900-c142-11ea-833b-8ab238edc8e0.png)

**Comment by tckb** [comment]
Yes. Apple doesn’t alllow tranperant background. Either fill it with white or settle with black background. Eitherways works for me ;)

**Comment by metmarkosaric** [comment]
The iOS icon is now live :)

**Comment by wheeleran** [comment]
four years later, can we have this on android as well, please?
