### ISSUE TITLE
Form labels basically invisible in dark theme

### ISSUE THREAD

**Issue by emilgoldsmith** [plausible/analytics#945]
### Precheck

Please note that this tracker is only for bugs. Do not use the issue tracker for help, support or feature requests. 

[Our docs](https://plausible.io/docs) are a great place for most answers, but if you can’t find your answer there, you can [contact us](https://plausible.io/contact). 

Have a feature request? Please search the ideas [on our forum](https://github.com/plausible/analytics/discussions/categories/feature-requests) to make sure that the feature has not yet been requested. If you cannot find what you had in mind, please [submit your feature request here](https://github.com/plausible/analytics/discussions/new). 

Have an issue with your self-hosted install? You can ask in [our self-hosted forum](https://github.com/plausible/analytics/discussions/categories/self-hosted-support). Thanks!

## Prerequisites
- [x] I have searched open and closed issues to make sure that the bug has not yet been reported.

## Bug report
**Describe the bug**
The picture kind of speaks for itself. I literally thought there were no labels, and just 3 fields without any explanation of what the difference was between them haha, until a minute later I somehow noticed there was some text, so now I'm reporting it!

I would usually contribute small bug fixes in a PR but this seems like a design decision what the colour should actually be so I'll leave that to you all :)

**Expected behavior**
I should be easily able to read the labels of a form with the dark theme

**Screenshots (If applicable)**

![Screenshot from 2021-04-20 10-52-55](https://user-images.githubusercontent.com/18149242/115368153-1c485b80-a1c7-11eb-9786-f1c587625100.png)

**Environment (If applicable):**
 - OS: Ubuntu 20.04
 - Browser Firefox
 - Version 87.0

**Comment by metmarkosaric** [comment]
thanks for reporting that @emilgoldsmith! it's definitely not an intentional design decision so if you have a chance please do send a pr to fix it! all looks fine on the light theme. thanks!

**Comment by emilgoldsmith** [comment]
Hi @metmarkosaric!

Oh yes, I assumed the current color wasn’t a design decision, but what the actual correct color should be is a design decision I can’t make

If you know what the color should be I’d be happy to change that line of css if I can find it :)

**Comment by ukutaht** [comment]
Will be fixed in the app after the next deployment (probably tomorrow). Thanks for reporting!

**Comment by emilgoldsmith** [comment]
No problem! Tanks for solving it :)
