### ISSUE TITLE
API to show data on dashboard

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/analytics#95]
"As we currently use a dashboard that pulls in data via an API (or other connection methods) it would nice to be able to gave an API that can pull in details. E.g. /api/pageviews/last7days to get the last 7 days page views.

This would also be useful to make rankings of most visited posts on a blog.

Which pages get the most traffic. Ideally the API would be able to return specific page types, ie tell us the most popular product pages, ignoring home page, informational and support pages, for a specified time period."

([imported from the old roadmap](https://plausible.nolt.io/22))

**Comment by binaryfire** [comment]
Awesome to see this is on the roadmap!

**Comment by fabio-smu** [comment]
@metmarkosaric what's the reason to this issue have been removed from roadmap?

**Comment by fabio-smu** [comment]
@metmarkosaric this issue is not on roadmap anymore?

**Comment by metmarkosaric** [comment]
thanks @fabio-smu! we've basically reduced our roadmap to only show the most immediate things we're working on. there's only a couple of items outstanding on the short-term roadmap. you can see it at https://github.com/plausible/analytics/projects/1. 

after that is completed, the API and the export/import of data will be the next two big projects we will focus on. both of these we want to do and they are some of the most upvoted features. we'll update the roadmap again as we complete the current tasks and as we priortize the upcoming work. it is difficult to promise any timelines at this stage on when the API will be completed but we will keep you posted!

**Comment by alexphelps** [comment]
I'm also very interested in this, with an API to pull data for a dashboard, Plausible would be a great fit for us.

**Comment by lmiller1990** [comment]
Going to keep an eye on this issue - pretty keen. The real product, to me, is not plausible the UI, but my analytics tracked in a non-invasive way. Access to that data is the next most important thing, this would let me perform my own analysis more easily.

Loving Plausible so far. 👍

**Comment by mishushakov** [comment]
Agreeing with all the things said above
our scenario: provide analytics for websites we host for our customers

having API would allow us to add the said websites to Plausible and make it possible to fetch and display the data in our customer-facing console

**Comment by metmarkosaric** [comment]
We plan to work on the API as the next big project at the start of next year. In order to deliver the product that satisfies your needs, we would love to hear from people who want to offer Plausible Analytics to their customers, clients etc using this API.

What do you plan do to? What do you need and expect from the API? Do you have any specific requirements that we should consider when building this? 

You can share your feedback here or reach out to us on hello@plausible.io. Thanks!

**Comment by grstreten** [comment]
Great to hear that this is something actively on the horizon!

We love using the [Numerics](https://cynapse.com/numerics/) App, so an ability to integrate with this would be super slick.

Overall hopes would be at the least some historical reporting (maybe views over 7 days) and active right now.

Thanks for making such an awesome product ⚡️

**Comment by lmiller1990** [comment]
My use case for the API: I have a personal dashboard for my various socials, I want to add a small widget for my plausible data. I like to have everything in one place.
