### ISSUE TITLE
Error messages when accessing Plausible dash on WordPress

### ISSUE THREAD

**Issue by ErisFY** [plausible/analytics#950]
Hi, I'm having an issue accessing the Plausible Analytics dashboard on WordPress.

I'm using WordPress.com, if that makes any difference. I've tried accessing the Plausible dash with two different browsers, and ran into an error both times.

In Firefox, this is the error I get:

![image](https://user-images.githubusercontent.com/82986157/115640392-20838e80-a317-11eb-908b-ed7a85152b9f.png)

I tried right-clicking on "This frame -> Show only this frame" but it led me to this page:

![image](https://user-images.githubusercontent.com/82986157/115640074-6429c880-a316-11eb-8358-ea29b7b75f5d.png)

I have a bunch of add-ons installed, and thought maybe there might have been some conflict, so I switched to Chrome (zero add-ons) to check, and still couldn't access the dash, although the error was different:

![image](https://user-images.githubusercontent.com/82986157/115640150-8de2ef80-a316-11eb-8aa1-a7c2b2bab6f8.png)

I don't know at all what's causing this. Any help? 

Thank you.

**Comment by metmarkosaric** [comment]
Thanks for reporting @ErisFY! Are you using any adblocker by any chance that may be blocking calls to Plausible?

**Comment by metmarkosaric** [comment]
Version 1.2.1 has been deployed now with some fixes. Could you check now please?

**Comment by ErisFY** [comment]
> 
> 
> Thanks for reporting @ErisFY! Are you using any adblocker by any chance that may be blocking calls to Plausible?

I am using an adblocker on Firefox, but I don't have any addons on Chrome as I said, and the error repeated anyway. 


> 
> 
> Version 1.2.1 has been deployed now with some fixes. Could you check now please?

I updated the plugin, but still have the same issue.

**Comment by metmarkosaric** [comment]
that's weird. can you see the dashboard i have embedded on this page? https://markosaric.com/stats/

**Comment by ErisFY** [comment]
> 
> 
> that's weird. can you see the dashboard i have embedded on this page? https://markosaric.com/stats/

This is what I see while using Firefox:

![image](https://user-images.githubusercontent.com/82986157/115764017-5c653500-a3a5-11eb-89cc-a1c1b31bccb0.png)

![image](https://user-images.githubusercontent.com/82986157/115764048-61c27f80-a3a5-11eb-9b7d-e9a4b16580b3.png)

It does show on Chrome however. I checked again on WordPress and the dash still doesn't show on either browsers.

**Comment by metmarkosaric** [comment]
very weird! could you please let me know the link to your shared dashboard as you have it in your wordpress plugin? you can email hello@plausible.io if you don't want to post this in public

**Comment by ErisFY** [comment]
> 
> 
> very weird! could you please let me know the link to your shared dashboard as you have it in your wordpress plugin? you can email [hello@plausible.io](mailto:hello@plausible.io) if you don't want to post this in public

Sure, you mean the "shared link" under "view your stats in your wordpress dashboard" ? If that's the link, then I'll send it to the email address you gave.

**Comment by metmarkosaric** [comment]
yes, that's the one. you need to create your own shared link in your Plausible account and that's where you paste it in the plugin. without that there would be no Plausible dashboard in WordPress. see https://plausible.io/wordpress-analytics-plugin#how-to-view-your-stats-directly-in-your-wordpress-dashboard

**Comment by ErisFY** [comment]
Actually, looks like that was the issue! Thanks for your help getting there, the dashboard is showing, now.

**Comment by metmarkosaric** [comment]
ah ok thanks for the update! enjoy!
