### ISSUE TITLE
Annotations for Real-World Correlations

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/analytics#97]
"I just switched all my traffic using a redirect from es6katas.org to jskatas.org. Now I would love to see a marker (a straight vertical line) which I can give some text, to understand where possible traffic changes might have come from. I could imagine many use cases for setting such a marker, such as:

    a social media campaign
    an announcement of some sort
    a new feature deploy
    an ad campaign
    etc."

([imported from the old roadmap](https://plausible.nolt.io/24))

**Comment by chrisshennan** [comment]
This would be great. It would allow me to keep track of big changes that might influence traffic and allow others to see what worked / didn't work
